#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Prepared local finite-difference and generic patch-kernel calculus."""

from ._adjoint import (
    CheckpointedFDAdjointPlan,
    FDActionAdjointPlan,
    FDAdjointIdentityReport,
    FDCheckpointingMode,
    FDTimeAdjointResult,
)
from ._boundary import (
    AxisBoundaryPair,
    BoundaryAffineMap,
    BoundaryConditionKind,
    BoundaryRealizationKind,
    BoundaryRealizationPlan,
    HaloPlan,
)
from ._boundary_runtime import (
    BoundaryStageContext,
    BoundaryWorkspace,
    CellGhostBoundary,
    ConformingInterfaceRuntime,
    CornerPolicy,
    GhostConditionKind,
    NodalBoundaryRuntime,
)
from ._certification import (
    certify_operator_adjoint,
    certify_operator_conservation,
    certify_stencil_consistency,
    FDAdjointReport,
    FDConservationReport,
    FDConsistencyReport,
    FDEvidenceKind,
    FDStabilityReport,
)
from ._coefficients import fornberg_weights, StencilCoefficientPlan
from ._compact import (
    CompactDerivativePlan,
    CompactInterpolationPlan,
    CompactOperatorKind,
    CompactOperatorReport,
    PreparedCompactOperator,
)
from ._diagonalization import (
    diagonalize_fd_laplacian,
    FDBoundaryKind,
    FDBoundaryPair,
    FDLaplacianDiagonalization,
    FDLaplacianSolvePlan,
    FDTransformAxisReport,
    solve_fd_laplacian,
)
from ._distributed import (
    DistributedHaloSchedule,
    DistributedStencilPartition,
    HaloExchangeDescriptor,
)
from ._execution import (
    ClosureStencilKernel,
    InteriorStencilKernel,
    lower_stencil_operator,
    PreparedStencilExecutionOperator,
    StencilExecutionPlan,
    StencilExecutionReport,
)
from ._flux_differencing import (
    PreparedSBPConservationDynamics,
    SBPFluxDifferencingDiagnostics,
    SBPFluxDifferencingMethodPlan,
    SBPFluxDifferencingReport,
    TensorSBPDiscretization,
    TensorSBPPlan,
)
from ._kernel import (
    OrderedPatchKernelPlan,
    PatchExecutionKind,
    PatchKernelPlan,
    PreparedPatchKernel,
    SweepDirection,
)
from ._lifecycle import (
    FDCheckpoint,
    FDCheckpointPlan,
    read_fd_checkpoint,
    write_fd_checkpoint,
)
from ._mapped_grid import (
    evaluate_mapped_metrics,
    MappedDiffusionOperator,
    MappedMetricIdentityReport,
    MappedMetricMode,
    MappedTensorGridPlan,
    PreparedMappedTensorGrid,
)
from ._multigrid import (
    PreparedStructuredMultigrid,
    StructuredCoarsening,
    StructuredMGCompatibility,
    StructuredMGGauge,
    StructuredMultigridPlan,
    StructuredMultigridResult,
    StructuredSmootherKind,
    StructuredTensorTransferOperator,
    StructuredTransferPlan,
    StructuredTransferReport,
)
from ._operators import prepare_linear_stencil, PreparedStencilOperator
from ._plan import (
    FiniteDifferencePlan,
    periodic_finite_difference,
    PreparedFiniteDifferenceDiscretization,
)
from ._precision import FDExecutionPrecisionPolicy
from ._preflight import FDExecutionPreflightPlan, FDResourceEstimate
from ._program import (
    FDPipelineReport,
    PreparedStencilProgram,
    StencilAssignment,
    StencilProgramPlan,
)
from ._request import (
    BoundaryClosureKind,
    DerivativeRequest,
    GridRegion,
    GridRegionKind,
    StencilBias,
)
from ._sbp import (
    CompatibleSBPSecondDerivative,
    PreparedSBPOperator,
    SATBoundaryPlan,
    SATConditionKind,
    SATInterfaceFlux,
    SATInterfacePlan,
    SBPDerivativePlan,
    SBPFamily,
    SBPInteriorOrder,
)
from ._stencil import (
    BoundaryStencilSet,
    LinearStencil,
    StencilFootprint,
    StencilRowKind,
    StencilRowReport,
)


__all__ = [
    "CheckpointedFDAdjointPlan",
    "AxisBoundaryPair",
    "BoundaryAffineMap",
    "BoundaryConditionKind",
    "BoundaryClosureKind",
    "BoundaryStencilSet",
    "BoundaryRealizationKind",
    "BoundaryStageContext",
    "BoundaryWorkspace",
    "CellGhostBoundary",
    "ConformingInterfaceRuntime",
    "CornerPolicy",
    "GhostConditionKind",
    "NodalBoundaryRuntime",
    "BoundaryRealizationPlan",
    "CompactDerivativePlan",
    "CompactInterpolationPlan",
    "CompactOperatorKind",
    "CompactOperatorReport",
    "PreparedCompactOperator",
    "PreparedSBPConservationDynamics",
    "SBPFluxDifferencingDiagnostics",
    "SBPFluxDifferencingMethodPlan",
    "SBPFluxDifferencingReport",
    "TensorSBPDiscretization",
    "TensorSBPPlan",
    "ClosureStencilKernel",
    "FDActionAdjointPlan",
    "FDAdjointIdentityReport",
    "FDCheckpoint",
    "FDCheckpointingMode",
    "FDCheckpointPlan",
    "FDTimeAdjointResult",
    "DistributedHaloSchedule",
    "HaloExchangeDescriptor",
    "InteriorStencilKernel",
    "lower_stencil_operator",
    "DistributedStencilPartition",
    "DerivativeRequest",
    "certify_operator_adjoint",
    "certify_operator_conservation",
    "certify_stencil_consistency",
    "diagonalize_fd_laplacian",
    "FDBoundaryKind",
    "FDBoundaryPair",
    "FDLaplacianDiagonalization",
    "FDLaplacianSolvePlan",
    "FDTransformAxisReport",
    "evaluate_mapped_metrics",
    "MappedDiffusionOperator",
    "MappedMetricIdentityReport",
    "MappedMetricMode",
    "MappedTensorGridPlan",
    "PreparedMappedTensorGrid",
    "PreparedStructuredMultigrid",
    "StructuredCoarsening",
    "StructuredMGCompatibility",
    "StructuredMGGauge",
    "StructuredSmootherKind",
    "StructuredMultigridPlan",
    "StructuredMultigridResult",
    "StructuredTensorTransferOperator",
    "StructuredTransferPlan",
    "StructuredTransferReport",
    "solve_fd_laplacian",
    "FDAdjointReport",
    "FDConsistencyReport",
    "FDConservationReport",
    "FDEvidenceKind",
    "FDStabilityReport",
    "FDExecutionPreflightPlan",
    "FDExecutionPrecisionPolicy",
    "FDResourceEstimate",
    "FiniteDifferencePlan",
    "GridRegion",
    "GridRegionKind",
    "HaloPlan",
    "LinearStencil",
    "OrderedPatchKernelPlan",
    "PatchExecutionKind",
    "PatchKernelPlan",
    "PreparedFiniteDifferenceDiscretization",
    "PreparedPatchKernel",
    "PreparedStencilProgram",
    "FDPipelineReport",
    "PreparedStencilExecutionOperator",
    "PreparedStencilOperator",
    "CompatibleSBPSecondDerivative",
    "PreparedSBPOperator",
    "SATBoundaryPlan",
    "SATConditionKind",
    "SATInterfaceFlux",
    "SATInterfacePlan",
    "SBPDerivativePlan",
    "SBPFamily",
    "SBPInteriorOrder",
    "StencilBias",
    "periodic_finite_difference",
    "StencilCoefficientPlan",
    "StencilFootprint",
    "StencilAssignment",
    "StencilRowKind",
    "StencilRowReport",
    "StencilExecutionPlan",
    "StencilExecutionReport",
    "StencilProgramPlan",
    "read_fd_checkpoint",
    "write_fd_checkpoint",
    "SweepDirection",
    "fornberg_weights",
    "prepare_linear_stencil",
]
