#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Explicit soap films and dry foams on labeled multiregion surfaces."""

from ._air import (
    FoamAirModel,
    RegionPressureAirEvidence,
    RegionPressureAirPlan,
    RegionPressureAirRoute,
)
from ._contracts import (
    FoamDerivativeUnavailableError,
    FoamEquilibriumEvidence,
    FoamEquilibriumMethod,
    FoamEquilibriumPlan,
    FoamEquilibriumResult,
    FoamEquilibriumRoute,
    FoamEquilibriumStatus,
    FoamKKTStatus,
    FoamMaterialPlan,
    FoamWireConstraints,
)
from ._dynamics import (
    FoamDynamicsEvidence,
    FoamDynamicsPlan,
    FoamDynamicsResult,
    FoamDynamicsRoute,
    FoamDynamicsState,
    FoamDynamicsStatus,
    FoamKinematicStep,
    PreparedFoamDynamics,
)
from ._equilibrium import (
    FoamConstraintBasisEvidence,
    FoamConstraintBasisPreparationError,
    FoamConstraintBasisStatus,
    FoamEquilibriumParameters,
    FoamImplicitEquilibrium,
    FoamVolumeConstraintBasis,
    PreparedFoamEquilibrium,
)
from ._plateau_borders import (
    apply_foam_rupture_with_borders,
    PlateauBorderAdaptation,
    PlateauBorderBoundaryFlux,
    PlateauBorderEvidence,
    PlateauBorderPlan,
    PlateauBorderPreparationError,
    PlateauBorderPreparationEvidence,
    PlateauBorderPreparationStatus,
    PlateauBorderRates,
    PlateauBorderResult,
    PlateauBorderRimEvidence,
    PlateauBorderRimResult,
    PlateauBorderRimStatus,
    PlateauBorderState,
    PlateauBorderStatus,
    PlateauBorderTransportError,
    PreparedPlateauBorder,
)
from ._profiles import foam_candidate_profiles
from ._qualification import (
    catenoid_area_ratio,
    catenoid_critical_parameters,
    catenoid_stable_neck_ratio,
    foam_reference_values,
    FoamReferenceValue,
    StandardDoubleBubble,
)
from ._relaxation import (
    FoamRelaxationEvidence,
    FoamRelaxationPlan,
    FoamRelaxationResult,
    FoamRelaxationStatus,
    PreparedFoamRelaxation,
)
from ._rupture import (
    apply_foam_rupture,
    BurstProposal,
    FoamRuptureEvidence,
    FoamRupturePlan,
    FoamRuptureResult,
    FoamRuptureStatus,
)
from ._vortex_sheet_air import (
    PreparedVortexSheetAir,
    VortexSheetAirEvidence,
    VortexSheetAirPlan,
    VortexSheetAirResult,
    VortexSheetAirState,
    VortexSheetAirStatus,
    VortexSheetCorePolicy,
    VortexSheetCurvatureRelationCapacityError,
    VortexSheetCurvatureRelationEvidence,
    VortexSheetCurvatureRelationStatus,
)


__all__ = [
    "apply_foam_rupture",
    "apply_foam_rupture_with_borders",
    "BurstProposal",
    "FoamAirModel",
    "FoamConstraintBasisEvidence",
    "FoamConstraintBasisPreparationError",
    "FoamConstraintBasisStatus",
    "FoamDynamicsEvidence",
    "FoamDynamicsPlan",
    "FoamDynamicsResult",
    "FoamDynamicsRoute",
    "FoamDynamicsState",
    "FoamDynamicsStatus",
    "FoamKinematicStep",
    "FoamDerivativeUnavailableError",
    "FoamEquilibriumEvidence",
    "FoamEquilibriumMethod",
    "FoamEquilibriumParameters",
    "FoamEquilibriumPlan",
    "FoamEquilibriumResult",
    "FoamEquilibriumRoute",
    "FoamEquilibriumStatus",
    "FoamImplicitEquilibrium",
    "FoamKKTStatus",
    "FoamMaterialPlan",
    "FoamReferenceValue",
    "FoamRelaxationEvidence",
    "FoamRelaxationPlan",
    "FoamRelaxationResult",
    "FoamRelaxationStatus",
    "FoamRuptureEvidence",
    "FoamRupturePlan",
    "FoamRuptureResult",
    "FoamRuptureStatus",
    "FoamWireConstraints",
    "FoamVolumeConstraintBasis",
    "PlateauBorderAdaptation",
    "PlateauBorderBoundaryFlux",
    "PlateauBorderEvidence",
    "PlateauBorderPlan",
    "PlateauBorderPreparationError",
    "PlateauBorderPreparationEvidence",
    "PlateauBorderPreparationStatus",
    "PlateauBorderRates",
    "PlateauBorderResult",
    "PlateauBorderRimEvidence",
    "PlateauBorderRimResult",
    "PlateauBorderRimStatus",
    "PlateauBorderState",
    "PlateauBorderStatus",
    "PlateauBorderTransportError",
    "PreparedPlateauBorder",
    "PreparedFoamEquilibrium",
    "PreparedFoamRelaxation",
    "PreparedFoamDynamics",
    "PreparedVortexSheetAir",
    "RegionPressureAirEvidence",
    "RegionPressureAirPlan",
    "RegionPressureAirRoute",
    "StandardDoubleBubble",
    "catenoid_area_ratio",
    "catenoid_critical_parameters",
    "catenoid_stable_neck_ratio",
    "foam_candidate_profiles",
    "foam_reference_values",
    "VortexSheetAirEvidence",
    "VortexSheetAirPlan",
    "VortexSheetAirResult",
    "VortexSheetAirState",
    "VortexSheetAirStatus",
    "VortexSheetCorePolicy",
    "VortexSheetCurvatureRelationCapacityError",
    "VortexSheetCurvatureRelationEvidence",
    "VortexSheetCurvatureRelationStatus",
]
