#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from importlib import import_module
from typing import Any, TYPE_CHECKING

from .._partitioned_coupling_adaptive import (
    AbstractCouplingEpochTransfer,
    AdaptiveCouplingRolloutPlan,
    AdaptiveCouplingSolution,
    AdaptiveCouplingWindowPolicy,
    CallableCouplingEpochTransfer,
    coupling_composition_entries,
    coupling_exchange_transport,
    coupling_state_from_composition,
    CouplingEpochTransferResult,
    CouplingEpochTransitionPlan,
    CouplingEpochTransitionResult,
    CouplingTopologyRequest,
    IdentityCouplingEpochTransfer,
    PreparedCouplingEpoch,
    rollout_adaptive_coupling,
    transition_coupling_epoch,
)
from .._partitioned_coupling_graph import (
    CouplingGraph,
    CouplingPreparationReport,
    CouplingResourceEstimate,
    CouplingResourcePolicy,
    CouplingStagePlan,
    prepare_coupling,
    PreparedCoupling,
    refresh_coupling,
)
from .._partitioned_coupling_measurement import (
    CouplingMeasurement,
    CouplingMeasurementRepresentation,
)
from .._partitioned_coupling_runtime import advance_coupling_window
from .._partitioned_coupling_solve import (
    CouplingProblem,
    CouplingRetentionPolicy,
    CouplingRolloutPlan,
    CouplingSolution,
    solve_coupling,
)
from .._partitioned_coupling_types import (
    AbstractCouplingPolicy,
    AbstractCouplingSubsystem,
    CallableCouplingSubsystem,
    coupling_status_message,
    CouplingDifferentiationMode,
    CouplingDifferentiationPolicy,
    CouplingDirection,
    CouplingExchange,
    CouplingPort,
    CouplingProvenance,
    CouplingQuantity,
    CouplingState,
    CouplingStatus,
    CouplingSubsystemCapabilities,
    CouplingSubsystemResult,
    CouplingSweep,
    CouplingSweepKind,
    CouplingTemporalKind,
    CouplingTolerance,
    CouplingTransferRequirement,
    CouplingWindow,
    CouplingWindowDiagnostics,
    CouplingWindowErrorEstimate,
    CouplingWindowResult,
    ExplicitCouplingPolicy,
    ImplicitCouplingPolicy,
)
from .._partitioned_coupling_waveform import (
    AbstractCouplingTemporalTransfer,
    adapt_coupling_waveform_grid,
    BarycentricCouplingTemporalTransfer,
    CouplingTemporalConversion,
    CouplingTemporalConversionKind,
    CouplingWaveform,
    CouplingWaveformAdaptationEvidence,
    CouplingWaveformAdaptationPolicy,
    CouplingWaveformCapacityRequest,
    CouplingWaveformGrid,
    CouplingWaveformPlan,
    FixedGridSubcyclingSubsystem,
)
from ._acceptance import (
    certify_coupled_state,
    ComponentCertificate,
    CoupledSolution,
    solve_coupled_problem,
)
from ._components import (
    AbstractCapacityComponent,
    AbstractPreparedCapacity,
    AbstractReconstructionComponent,
    AbstractSpatialComponent,
    AbstractTraceComponent,
    ComponentBlock,
    ComponentField,
    ComponentSpace,
    ElasticityFEMBEMArguments,
    ElasticityFEMBEMComponent,
    GalerkinBoundaryComponent,
    ScalarLaplaceFEMBEMArguments,
    ScalarLaplaceFEMBEMComponent,
    VariationalCapacity,
    VariationalComponent,
)
from ._condensation import (
    CondensationEvidence,
    condense_coupled_problem,
    CondensedCoupledProblem,
    CondensedSolution,
    solve_condensed_problem,
)
from ._contributions import (
    AbstractContribution,
    AbstractContributionResidual,
    Contribution,
    ContributionEndpoint,
    ContributionSpace,
    EliminationContribution,
    LawBlock,
    LawImposition,
    LinearContribution,
    LoadContribution,
    ResidualContribution,
)
from ._execution import (
    CoupledExecutionPolicy,
    InterfaceLaneSubject,
    LaneDerivatives,
    LaneKind,
    LaneWorkset,
    LaneWorksetEstimate,
    PreparedCoupledExecution,
)
from ._host_execution import (
    AbstractHostCouplingParticipant,
    advance_host_coupling_window,
    HostCouplingSolution,
    HostCouplingWindowResult,
    HostParticipantState,
    HostRollback,
    HostWindowCommit,
    prepare_host_coupling,
    PreparedHostCoupling,
    solve_host_coupling,
)
from ._interface_quadrature import (
    FacetResampling,
    InterfaceCoverageEvidence,
    InterfaceQuadrature,
    InterfaceQuadraturePolicy,
    InterfaceSideQuadrature,
    prepare_interface_quadrature,
)
from ._interfaces import (
    EmbeddedMeaning,
    InterfaceBinding,
    InterfaceEndpoint,
    InterfaceIncidence,
    InterfaceSource,
    PairedSupportAttachment,
    SheetViewAttachment,
)
from ._laws import (
    AbstractCouplingLaw,
    AbstractInterfaceFlux,
    AbstractLawCertificate,
    BoundaryIntegralEvidence,
    BoundaryIntegralSide,
    BoundaryIntegralTransmissionLaw,
    ConservativeFluxEvidence,
    ConservativeFluxLaw,
    EliminationEvidence,
    FieldTransferEvidence,
    FieldTransferLaw,
    GapRadiation,
    IntegralPortEvidence,
    IntegralPortLaw,
    InterfaceConductance,
    InterfaceDefectReport,
    MatchingElimination,
    MortarEvidence,
    MortarImposition,
    MortarMultiplier,
    MultiplierFamily,
    NitscheEvidence,
    NitscheImposition,
    NitscheVariant,
    PortSide,
    PreparedLaw,
    ScalarTransmissionLaw,
    TransmissionImposition,
    TransmissionSide,
    VectorInterfaceResultants,
    VectorTransmissionCertificate,
    VectorTransmissionEvidence,
    VectorTransmissionLaw,
    VectorTransmissionSide,
)
from ._learned_flux import MonotoneInterfaceConductance
from ._lower_partitioned import (
    lower_partitioned_coupling,
    PartitionedCouplingDeclaration,
)
from ._method_participants import (
    AbstractMethodCouplingParticipant,
    DAECouplingParticipant,
    DAEParticipantNative,
    FixedStepCouplingParticipant,
    FixedStepParticipantEvidence,
    MethodParticipantRandomness,
    MethodParticipantState,
    MethodWindowBinding,
    SteadyResponse,
    SteadyResponseCouplingParticipant,
)
from ._observations import (
    AbstractObservationBinding,
    AbstractPreparedObservation,
    BoundaryStatistic,
    FieldBoundaryObservation,
    FieldFluxObservation,
    FieldPointObservation,
    MeasurementIdentity,
    PreparedBoundaryObservation,
    PreparedFluxObservation,
    PreparedPointObservation,
)
from ._parameters import (
    CoupledArguments,
    ParameterBinding,
    ParameterChange,
    ParameterRole,
    PreparedParameters,
    RuntimeInput,
)
from ._prepared_problem import (
    CoupledExecution,
    CoupledGauge,
    CoupledProblemPlan,
    CoupledResourcePolicy,
    prepare_coupled_problem,
    PreparedCoupledProblem,
)
from ._reduced import ComponentResidualProvider, ReducedComponent
from ._transient import (
    CoupledTransientSolution,
    prepare_coupled_transient,
    PreparedCoupledTransient,
    solve_coupled_transient,
    TransientArguments,
    TransientCertificate,
    TransientField,
    TransientScale,
)
from ._transition import (
    COUPLED_TRANSITION_CERTIFICATE_FAILURE,
    COUPLED_TRANSITION_NATIVE_FAILURE,
    COUPLED_TRANSITION_NONFINITE,
    coupled_transition_status_name,
    COUPLED_TRANSITION_SUCCESS,
    CoupledObservationPort,
    CoupledTransitionStatus,
    CoupledTransitionStep,
    prepare_coupled_transition,
    PreparedCoupledTransition,
)


_FACADE_EXPORT_MODULES: dict[str, str] = {
    "FiniteVolumeCapacity": "._finite_volume_components",
    "FiniteVolumeComponent": "._finite_volume_components",
    "MeshfreeBoundaryTrace": "._meshfree_components",
    "MeshfreeCapacity": "._meshfree_components",
    "MeshfreeComponent": "._meshfree_components",
    "MeshfreeReaction": "._meshfree_components",
    "MeshfreeTraceComponent": "._meshfree_components",
    "LangmuirAdsorptionFlux": "._surface_exchange",
    "SurfaceDeposition": "._surface_exchange",
    "SurfaceEpochRelocation": "._surface_exchange",
    "SurfaceExchangeEvidence": "._surface_exchange",
    "SurfaceExchangeLaw": "._surface_exchange",
    "MeshfreeBulkSurfaceMethod": "._surface_exchange",
    "MeshfreeBulkSurfaceEvidence": "._surface_exchange",
    "OverlapDirichletEvidence": "._overlap",
    "OverlapDirichletLaw": "._overlap",
    "OverlapFaceSide": "._overlap",
    "OverlapSchwarz": "._overlap",
    "OverlapSubdomainEvidence": "._overlap",
    "OverlapTransferEvidence": "._overlap",
    "OverlapTransferPolicy": "._overlap",
    "OverlapTransferRoute": "._overlap",
    "PreparedOverlapTransfers": "._overlap",
    "prepare_overlap_schwarz": "._overlap",
}

if TYPE_CHECKING:
    from ._finite_volume_components import (
        FiniteVolumeCapacity as FiniteVolumeCapacity,
        FiniteVolumeComponent as FiniteVolumeComponent,
    )
    from ._meshfree_components import (
        MeshfreeBoundaryTrace as MeshfreeBoundaryTrace,
        MeshfreeCapacity as MeshfreeCapacity,
        MeshfreeComponent as MeshfreeComponent,
        MeshfreeReaction as MeshfreeReaction,
        MeshfreeTraceComponent as MeshfreeTraceComponent,
    )
    from ._overlap import (
        OverlapDirichletEvidence as OverlapDirichletEvidence,
        OverlapDirichletLaw as OverlapDirichletLaw,
        OverlapFaceSide as OverlapFaceSide,
        OverlapSchwarz as OverlapSchwarz,
        OverlapSubdomainEvidence as OverlapSubdomainEvidence,
        OverlapTransferEvidence as OverlapTransferEvidence,
        OverlapTransferPolicy as OverlapTransferPolicy,
        OverlapTransferRoute as OverlapTransferRoute,
        prepare_overlap_schwarz as prepare_overlap_schwarz,
        PreparedOverlapTransfers as PreparedOverlapTransfers,
    )
    from ._surface_exchange import (
        LangmuirAdsorptionFlux as LangmuirAdsorptionFlux,
        MeshfreeBulkSurfaceEvidence as MeshfreeBulkSurfaceEvidence,
        MeshfreeBulkSurfaceMethod as MeshfreeBulkSurfaceMethod,
        SurfaceDeposition as SurfaceDeposition,
        SurfaceEpochRelocation as SurfaceEpochRelocation,
        SurfaceExchangeEvidence as SurfaceExchangeEvidence,
        SurfaceExchangeLaw as SurfaceExchangeLaw,
    )


def __getattr__(name: str) -> Any:
    module = _FACADE_EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "FiniteVolumeCapacity",
    "FiniteVolumeComponent",
    "MeshfreeBoundaryTrace",
    "MeshfreeCapacity",
    "MeshfreeComponent",
    "MeshfreeReaction",
    "MeshfreeTraceComponent",
    "LangmuirAdsorptionFlux",
    "SurfaceDeposition",
    "SurfaceEpochRelocation",
    "SurfaceExchangeEvidence",
    "SurfaceExchangeLaw",
    "MeshfreeBulkSurfaceMethod",
    "MeshfreeBulkSurfaceEvidence",
    "OverlapDirichletEvidence",
    "OverlapDirichletLaw",
    "OverlapFaceSide",
    "OverlapSchwarz",
    "OverlapSubdomainEvidence",
    "OverlapTransferEvidence",
    "OverlapTransferPolicy",
    "OverlapTransferRoute",
    "PreparedOverlapTransfers",
    "prepare_overlap_schwarz",
    "AbstractContribution",
    "AbstractContributionResidual",
    "AbstractCouplingLaw",
    "AbstractInterfaceFlux",
    "AbstractLawCertificate",
    "AbstractObservationBinding",
    "AbstractPreparedObservation",
    "AbstractCapacityComponent",
    "AbstractPreparedCapacity",
    "AbstractReconstructionComponent",
    "AbstractSpatialComponent",
    "AbstractTraceComponent",
    "BoundaryIntegralEvidence",
    "BoundaryStatistic",
    "BoundaryIntegralSide",
    "BoundaryIntegralTransmissionLaw",
    "ComponentBlock",
    "ComponentCertificate",
    "ComponentResidualProvider",
    "ComponentField",
    "ComponentSpace",
    "CondensationEvidence",
    "CondensedCoupledProblem",
    "CondensedSolution",
    "ConservativeFluxEvidence",
    "ConservativeFluxLaw",
    "Contribution",
    "ContributionEndpoint",
    "ContributionSpace",
    "CoupledArguments",
    "CoupledExecution",
    "CoupledGauge",
    "CoupledProblemPlan",
    "CoupledResourcePolicy",
    "CoupledExecutionPolicy",
    "CoupledSolution",
    "ElasticityFEMBEMArguments",
    "ElasticityFEMBEMComponent",
    "EliminationContribution",
    "EliminationEvidence",
    "FacetResampling",
    "FieldTransferEvidence",
    "FieldTransferLaw",
    "GalerkinBoundaryComponent",
    "FieldBoundaryObservation",
    "FieldFluxObservation",
    "FieldPointObservation",
    "GapRadiation",
    "IntegralPortEvidence",
    "IntegralPortLaw",
    "InterfaceConductance",
    "InterfaceCoverageEvidence",
    "InterfaceDefectReport",
    "InterfaceQuadrature",
    "InterfaceQuadraturePolicy",
    "InterfaceSideQuadrature",
    "LawBlock",
    "LawImposition",
    "LaneDerivatives",
    "LaneKind",
    "LaneWorkset",
    "LaneWorksetEstimate",
    "LinearContribution",
    "LoadContribution",
    "MatchingElimination",
    "MortarEvidence",
    "MeasurementIdentity",
    "MonotoneInterfaceConductance",
    "MortarImposition",
    "MortarMultiplier",
    "MultiplierFamily",
    "NitscheEvidence",
    "NitscheImposition",
    "NitscheVariant",
    "PortSide",
    "ParameterBinding",
    "ParameterChange",
    "ParameterRole",
    "PreparedBoundaryObservation",
    "PreparedCoupledProblem",
    "PreparedCoupledExecution",
    "PreparedLaw",
    "PreparedFluxObservation",
    "PreparedParameters",
    "PreparedPointObservation",
    "ResidualContribution",
    "ScalarLaplaceFEMBEMArguments",
    "ScalarLaplaceFEMBEMComponent",
    "ScalarTransmissionLaw",
    "ReducedComponent",
    "RuntimeInput",
    "TransmissionImposition",
    "TransmissionSide",
    "VectorInterfaceResultants",
    "VectorTransmissionCertificate",
    "VectorTransmissionEvidence",
    "VectorTransmissionLaw",
    "VectorTransmissionSide",
    "VariationalCapacity",
    "VariationalComponent",
    "CoupledTransientSolution",
    "PreparedCoupledTransient",
    "TransientArguments",
    "TransientCertificate",
    "TransientField",
    "TransientScale",
    "COUPLED_TRANSITION_CERTIFICATE_FAILURE",
    "COUPLED_TRANSITION_NATIVE_FAILURE",
    "COUPLED_TRANSITION_NONFINITE",
    "COUPLED_TRANSITION_SUCCESS",
    "CoupledObservationPort",
    "CoupledTransitionStatus",
    "CoupledTransitionStep",
    "PreparedCoupledTransition",
    "coupled_transition_status_name",
    "prepare_coupled_transition",
    "prepare_coupled_problem",
    "prepare_coupled_transient",
    "certify_coupled_state",
    "condense_coupled_problem",
    "prepare_interface_quadrature",
    "solve_coupled_problem",
    "solve_coupled_transient",
    "solve_condensed_problem",
    "AbstractCouplingEpochTransfer",
    "AbstractCouplingPolicy",
    "AbstractCouplingSubsystem",
    "AbstractCouplingTemporalTransfer",
    "AbstractHostCouplingParticipant",
    "AbstractMethodCouplingParticipant",
    "AdaptiveCouplingRolloutPlan",
    "AdaptiveCouplingSolution",
    "AdaptiveCouplingWindowPolicy",
    "BarycentricCouplingTemporalTransfer",
    "CallableCouplingEpochTransfer",
    "CallableCouplingSubsystem",
    "CouplingDifferentiationMode",
    "CouplingDifferentiationPolicy",
    "CouplingDirection",
    "CouplingEpochTransferResult",
    "CouplingEpochTransitionPlan",
    "CouplingEpochTransitionResult",
    "CouplingExchange",
    "CouplingGraph",
    "CouplingMeasurement",
    "CouplingMeasurementRepresentation",
    "CouplingPort",
    "CouplingQuantity",
    "CouplingPreparationReport",
    "CouplingProblem",
    "CouplingProvenance",
    "CouplingResourceEstimate",
    "CouplingResourcePolicy",
    "CouplingRetentionPolicy",
    "CouplingRolloutPlan",
    "CouplingSolution",
    "CouplingStagePlan",
    "CouplingState",
    "CouplingStatus",
    "CouplingSubsystemCapabilities",
    "CouplingSubsystemResult",
    "CouplingSweep",
    "CouplingSweepKind",
    "CouplingTemporalConversion",
    "CouplingTemporalConversionKind",
    "CouplingTemporalKind",
    "CouplingTolerance",
    "CouplingTopologyRequest",
    "CouplingTransferRequirement",
    "CouplingWaveform",
    "CouplingWaveformAdaptationEvidence",
    "CouplingWaveformAdaptationPolicy",
    "CouplingWaveformCapacityRequest",
    "CouplingWaveformGrid",
    "CouplingWaveformPlan",
    "CouplingWindow",
    "CouplingWindowDiagnostics",
    "CouplingWindowErrorEstimate",
    "CouplingWindowResult",
    "DAECouplingParticipant",
    "DAEParticipantNative",
    "EmbeddedMeaning",
    "ExplicitCouplingPolicy",
    "FixedGridSubcyclingSubsystem",
    "FixedStepCouplingParticipant",
    "FixedStepParticipantEvidence",
    "HostCouplingSolution",
    "HostCouplingWindowResult",
    "HostParticipantState",
    "HostRollback",
    "HostWindowCommit",
    "IdentityCouplingEpochTransfer",
    "ImplicitCouplingPolicy",
    "InterfaceBinding",
    "InterfaceEndpoint",
    "InterfaceIncidence",
    "InterfaceLaneSubject",
    "InterfaceSource",
    "MethodParticipantRandomness",
    "MethodParticipantState",
    "MethodWindowBinding",
    "PairedSupportAttachment",
    "PartitionedCouplingDeclaration",
    "PreparedCoupling",
    "PreparedCouplingEpoch",
    "PreparedHostCoupling",
    "SheetViewAttachment",
    "SteadyResponse",
    "SteadyResponseCouplingParticipant",
    "adapt_coupling_waveform_grid",
    "advance_coupling_window",
    "advance_host_coupling_window",
    "coupling_composition_entries",
    "coupling_exchange_transport",
    "coupling_state_from_composition",
    "coupling_status_message",
    "lower_partitioned_coupling",
    "prepare_coupling",
    "prepare_host_coupling",
    "refresh_coupling",
    "rollout_adaptive_coupling",
    "solve_coupling",
    "solve_host_coupling",
    "transition_coupling_epoch",
]
