#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Fixed-shape geometric, sequential, paraxial, and non-sequential optics."""

from ._dispersion_rays import (
    AbstractDispersionHamiltonian,
    AbstractSeparableDispersionHamiltonian,
    ColdPlasmaHamiltonian,
    ColdPlasmaProfile,
    ColdPlasmaRayPath,
    DispersionRayEvidence,
    DispersionRayMethod,
    DispersionRayPlan,
    DispersionRayResult,
    DispersionRayState,
    DispersionRayStatus,
    PreparedDispersionRay,
    RayFanPlan,
    RayFanResult,
)
from ._graded_index import (
    AbstractRefractiveIndexField,
    AnalyticRefractiveIndexField,
    GradedIndexRayPlan,
    RefractiveIndexHamiltonian,
    StructuredRefractiveIndexField,
    TetrahedralRefractiveIndexField,
)
from ._interface import (
    evaluate_refractive_interface,
    OpticalRayState,
    RefractiveInterfaceResult,
    RefractiveInterfaceStatus,
)
from ._nonsequential import (
    NonSequentialBranchMode,
    NonSequentialOpticsPlan,
    NonSequentialOpticsResult,
    NonSequentialOpticsStatus,
    NonSequentialSurfaceKind,
    NonSequentialSurfaceTable,
    prepare_nonsequential_optics,
    PreparedNonSequentialOptics,
    trace_nonsequential_optics,
)
from ._paraxial import (
    DifferentialRayMap,
    linearize_sequential_optics,
    ParaxialOpticsPlan,
    ParaxialOpticsResult,
    ParaxialOpticsStatus,
    PreparedParaxialOptics,
)
from ._planar import PlanarRefractiveStack, trace_planar_refractive_stack
from ._resonator import (
    analyze_paraxial_resonator,
    ParaxialResonatorEvidence,
    ParaxialResonatorMode,
    ParaxialResonatorPlan,
    ParaxialResonatorResult,
    ParaxialResonatorStatus,
    prepare_paraxial_resonator,
    PreparedParaxialResonator,
)
from ._sequential import (
    PreparedSequentialOptics,
    SequentialOpticsPlan,
    SequentialOpticsResult,
    SequentialOpticsStatus,
    SurfaceInteraction,
    SurfaceKind,
)


__all__ = [
    "AbstractDispersionHamiltonian",
    "AbstractRefractiveIndexField",
    "AbstractSeparableDispersionHamiltonian",
    "AnalyticRefractiveIndexField",
    "ColdPlasmaHamiltonian",
    "ColdPlasmaProfile",
    "ColdPlasmaRayPath",
    "DispersionRayEvidence",
    "DispersionRayMethod",
    "DispersionRayPlan",
    "DispersionRayResult",
    "DispersionRayState",
    "DispersionRayStatus",
    "DifferentialRayMap",
    "NonSequentialBranchMode",
    "NonSequentialOpticsPlan",
    "NonSequentialOpticsResult",
    "NonSequentialOpticsStatus",
    "NonSequentialSurfaceKind",
    "NonSequentialSurfaceTable",
    "GradedIndexRayPlan",
    "OpticalRayState",
    "ParaxialOpticsPlan",
    "ParaxialOpticsResult",
    "ParaxialOpticsStatus",
    "ParaxialResonatorEvidence",
    "ParaxialResonatorMode",
    "ParaxialResonatorPlan",
    "ParaxialResonatorResult",
    "ParaxialResonatorStatus",
    "PlanarRefractiveStack",
    "PreparedDispersionRay",
    "PreparedNonSequentialOptics",
    "PreparedParaxialOptics",
    "PreparedParaxialResonator",
    "PreparedSequentialOptics",
    "RefractiveIndexHamiltonian",
    "RefractiveInterfaceResult",
    "RayFanPlan",
    "RayFanResult",
    "RefractiveInterfaceStatus",
    "SequentialOpticsPlan",
    "SequentialOpticsResult",
    "SequentialOpticsStatus",
    "SurfaceInteraction",
    "SurfaceKind",
    "StructuredRefractiveIndexField",
    "TetrahedralRefractiveIndexField",
    "analyze_paraxial_resonator",
    "evaluate_refractive_interface",
    "linearize_sequential_optics",
    "prepare_nonsequential_optics",
    "prepare_paraxial_resonator",
    "trace_nonsequential_optics",
    "trace_planar_refractive_stack",
]
