#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

import hashlib
import sys
from pathlib import Path

import pytest

from phydrax._external_runtime import (
    ExternalRuntimeError,
    pin_executable,
    PinnedExecutable,
    PinnedFileOutputs,
    PinnedFileRequest,
    run_pinned_command,
)


# Deterministic provider output generated by an independent real process: a
# 3-MiB field dump plus a nested small summary.
_WRITER = (
    "import pathlib; "
    "pathlib.Path('fields').mkdir(); "
    "pathlib.Path('fields/dump.bin').write_bytes(bytes(range(256)) * 12288); "
    "pathlib.Path('summary.txt').write_bytes(b'step=42\\n')"
)
_DUMP = bytes(range(256)) * 12288
_SUMMARY = b"step=42\n"


@pytest.fixture
def python_executable() -> PinnedExecutable:
    return pin_executable(
        sys.executable, version=sys.version.split()[0], license_id="PSF-2.0"
    )


def _declared(
    destination: Path, *, dump_cap: int, summary_cap: int, total: int
) -> PinnedFileOutputs:
    return PinnedFileOutputs(
        str(destination),
        (
            PinnedFileRequest("summary.txt", summary_cap),
            PinnedFileRequest("fields/dump.bin", dump_cap),
        ),
        total,
    )


def test_file_artifacts_exceed_memory_bound_and_record_verified_digests(
    python_executable: PinnedExecutable, tmp_path: Path
) -> None:
    declared = _declared(
        tmp_path, dump_cap=len(_DUMP), summary_cap=64, total=len(_DUMP) + 64
    )
    result = run_pinned_command(
        python_executable,
        ("-c", _WRITER),
        inputs={},
        # Far below the dump size: file artifacts never pass through memory.
        max_output_bytes=4096,
        artifacts=declared,
    )

    dump = result.file_artifact("fields/dump.bin")
    summary = result.file_artifact("summary.txt")
    assert dump.size_bytes == len(_DUMP)
    assert dump.sha256 == hashlib.sha256(_DUMP).hexdigest()
    assert Path(dump.location) == tmp_path.resolve() / "fields" / "dump.bin"
    assert Path(dump.location).read_bytes() == _DUMP
    assert dump.artifact.content_digest == dump.sha256
    assert dump.artifact.status == "complete"
    assert summary.sha256 == hashlib.sha256(_SUMMARY).hexdigest()
    assert Path(summary.location).read_bytes() == _SUMMARY
    assert result.artifact.status == "complete"
    with pytest.raises(KeyError):
        result.file_artifact("undeclared.bin")


@pytest.mark.parametrize(
    ("dump_cap", "total", "reason"),
    [
        pytest.param(len(_DUMP) - 1, 2 * len(_DUMP), "byte limit", id="per-file-cap"),
        pytest.param(len(_DUMP), len(_DUMP), "maximum_total_bytes", id="total-cap"),
    ],
)
def test_file_artifact_overflow_refuses_the_whole_set(
    python_executable: PinnedExecutable,
    tmp_path: Path,
    dump_cap: int,
    total: int,
    reason: str,
) -> None:
    declared = _declared(tmp_path, dump_cap=dump_cap, summary_cap=64, total=total)
    with pytest.raises(ExternalRuntimeError, match=reason) as caught:
        run_pinned_command(
            python_executable, ("-c", _WRITER), inputs={}, artifacts=declared
        )
    failed = caught.value.result
    assert failed is not None
    assert failed.file_artifacts == ()
    assert failed.artifact.status == "failed"
    assert list(tmp_path.iterdir()) == []


def test_missing_file_artifact_is_refused_without_publication(
    python_executable: PinnedExecutable, tmp_path: Path
) -> None:
    declared = PinnedFileOutputs(
        str(tmp_path),
        (PinnedFileRequest("summary.txt", 64), PinnedFileRequest("absent.bin", 64)),
        128,
    )
    with pytest.raises(ExternalRuntimeError, match="'absent.bin' is missing"):
        run_pinned_command(
            python_executable, ("-c", _WRITER), inputs={}, artifacts=declared
        )
    assert list(tmp_path.iterdir()) == []


def test_failed_command_publishes_no_file_artifacts(
    python_executable: PinnedExecutable, tmp_path: Path
) -> None:
    declared = _declared(
        tmp_path, dump_cap=len(_DUMP), summary_cap=64, total=len(_DUMP) + 64
    )
    with pytest.raises(ExternalRuntimeError, match="status 3") as caught:
        run_pinned_command(
            python_executable,
            ("-c", _WRITER + "; raise SystemExit(3)"),
            inputs={},
            artifacts=declared,
        )
    assert caught.value.result is not None
    assert caught.value.result.file_artifacts == ()
    assert list(tmp_path.iterdir()) == []


def test_existing_destination_file_rolls_back_partial_publication(
    python_executable: PinnedExecutable, tmp_path: Path
) -> None:
    # Requests publish in canonical path order: fields/dump.bin, then summary.txt.
    (tmp_path / "summary.txt").write_bytes(b"caller-owned")
    declared = _declared(
        tmp_path, dump_cap=len(_DUMP), summary_cap=64, total=len(_DUMP) + 64
    )
    with pytest.raises(ExternalRuntimeError, match="publication failed"):
        run_pinned_command(
            python_executable, ("-c", _WRITER), inputs={}, artifacts=declared
        )
    assert (tmp_path / "summary.txt").read_bytes() == b"caller-owned"
    assert not (tmp_path / "fields" / "dump.bin").exists()


def test_file_artifact_declarations_are_validated(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="bounded relative POSIX file path"):
        PinnedFileRequest("../escape.bin", 64)
    with pytest.raises(ValueError, match="reserved"):
        PinnedFileRequest(".phydrax-stdout", 64)
    with pytest.raises(ValueError, match="positive integer"):
        PinnedFileRequest("dump.bin", 0)
    with pytest.raises(ValueError, match="unique"):
        PinnedFileOutputs(
            str(tmp_path),
            (PinnedFileRequest("a.bin", 1), PinnedFileRequest("a.bin", 2)),
            8,
        )
    regular = tmp_path / "regular.txt"
    regular.write_bytes(b"")
    with pytest.raises(ValueError, match="existing directory"):
        PinnedFileOutputs(str(regular), (PinnedFileRequest("a.bin", 1),), 8)
