#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Robot-model adaptation, kinematics, environments, and backend boundaries."""

from ._backend import (
    ObservationFreshness,
    ROBOTICS_OPERATIONS,
    RoboticsBackendProfile,
    RoboticsCapabilityNegotiation,
    RoboticsDifferentiability,
    RoboticsIndexEntry,
    RoboticsOperation,
    RoboticsOperationCapability,
    RoboticsOperationEvidence,
    RoboticsOperationRequirement,
    RoboticsOperationStatus,
    RoboticsProjection,
    RoboticsProjectionKind,
    RoboticsProjectionMap,
    RoboticsRequirementRejection,
)
from ._environment import (
    AbstractRobotEnvironmentWrapper,
    AbstractRobotTask,
    PreparedRobotEnvironment,
    RobotEnvironmentEvidence,
    RobotEnvironmentReset,
    RobotEnvironmentState,
    RobotEnvironmentTransition,
    RobotEnvironmentWrapperTransition,
    RobotTaskEvaluation,
    RobotTaskTransition,
)
from ._ik import (
    frame_pose_transform,
    FrameInverseKinematicsPlan,
    FrameInverseKinematicsResult,
    FrameOrientationTask,
    FramePoseTask,
    FramePositionTask,
    FrameTask,
    FrameTaskResidual,
    IKChartEvidence,
    IKFeasibilityEvidence,
    IKFiniteEvidence,
    InverseKinematicsStatus,
)
from ._mjx import (
    mjx_availability,
    MJX_JAX_BACKEND_CAPABILITIES,
    MJX_JAX_PROFILE,
    MJX_WARP_PROFILE,
    MJXAdapter,
    MJXState,
    MJXStepObservationRequest,
    MJXStepResult,
    prepare_mjx_adapter,
)
from ._urdf import (
    parse_urdf_file,
    parse_urdf_text,
    RobotAdaptation,
    RobotNameIDMap,
    URDFFormatEvidence,
    URDFImportError,
    URDFJointEvidence,
    URDFLinkEvidence,
)


__all__ = [
    "AbstractRobotEnvironmentWrapper",
    "AbstractRobotTask",
    "FrameInverseKinematicsPlan",
    "FrameInverseKinematicsResult",
    "FrameOrientationTask",
    "FramePoseTask",
    "FramePositionTask",
    "FrameTask",
    "FrameTaskResidual",
    "IKChartEvidence",
    "IKFeasibilityEvidence",
    "IKFiniteEvidence",
    "InverseKinematicsStatus",
    "MJXAdapter",
    "MJX_JAX_BACKEND_CAPABILITIES",
    "MJX_JAX_PROFILE",
    "MJX_WARP_PROFILE",
    "MJXState",
    "MJXStepObservationRequest",
    "MJXStepResult",
    "ObservationFreshness",
    "PreparedRobotEnvironment",
    "ROBOTICS_OPERATIONS",
    "RobotAdaptation",
    "RobotEnvironmentEvidence",
    "RobotEnvironmentReset",
    "RobotEnvironmentState",
    "RobotEnvironmentTransition",
    "RobotEnvironmentWrapperTransition",
    "RobotNameIDMap",
    "RobotTaskEvaluation",
    "RobotTaskTransition",
    "RoboticsBackendProfile",
    "RoboticsCapabilityNegotiation",
    "RoboticsDifferentiability",
    "RoboticsIndexEntry",
    "RoboticsOperation",
    "RoboticsOperationCapability",
    "RoboticsOperationEvidence",
    "RoboticsOperationRequirement",
    "RoboticsOperationStatus",
    "RoboticsProjection",
    "RoboticsProjectionKind",
    "RoboticsProjectionMap",
    "RoboticsRequirementRejection",
    "URDFFormatEvidence",
    "URDFImportError",
    "URDFJointEvidence",
    "URDFLinkEvidence",
    "frame_pose_transform",
    "mjx_availability",
    "parse_urdf_file",
    "parse_urdf_text",
    "prepare_mjx_adapter",
]
