#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Canonical linear, quadratic, and conic mathematical programs."""

from ._barrier import cone_barrier_oracle, ConeBarrierOracle
from ._cones import (
    AbstractConvexCone,
    NonnegativeCone,
    ProductCone,
    RotatedSecondOrderCone,
    SecondOrderCone,
    ZeroCone,
)
from ._conic_cuts import (
    audit_conic_cut,
    conic_cut_from_dual,
    ConicCut,
    ConicCutAudit,
    ConicCutSource,
    ConicSeparationResult,
    polyhedral_conic_rows,
    separate_conic_point,
)
from ._conic_sensitivity import (
    conic_primal_jvp,
    conic_primal_vjp,
    ConicProgramData,
    ConicSensitivityResult,
    prepare_conic_sensitivity,
    PreparedConicSensitivity,
)
from ._cvxpy import (
    CVXPYConstraintSlice,
    CVXPYProgramBinding,
    CVXPYVariableSlice,
    export_cvxpy_program,
    import_cvxpy_problem,
    refresh_cvxpy_program,
    restore_cvxpy_solution,
)
from ._exponential_cone import ExponentialCone
from ._lifecycle import (
    bind_convex_numeric,
    CanonicalProgram,
    ConvexProgramExecution,
    ConvexProgramPlan,
    ConvexProgramTemplate,
    ConvexWarmStart,
    plan_convex_program,
    prepare_convex_program,
    prepare_convex_template,
    PreparedConvexProgram,
    refresh_convex_program,
    solve_conic_program,
    solve_convex_program,
    solve_linear_program,
    solve_prepared_convex_program,
)
from ._matrix_free_conic_sensitivity import PreparedMatrixFreeConicSensitivity
from ._mixed_integer import (
    AbstractMixedIntegerMethod,
    MixedIntegerBranchingRule,
    MixedIntegerCandidate,
    MixedIntegerCandidateAudit,
    MixedIntegerCertificate,
    MixedIntegerCertification,
    MixedIntegerMethodCapabilities,
    MixedIntegerProgram,
    MixedIntegerProvenance,
    MixedIntegerResult,
    MixedIntegerSolvePolicy,
    MixedIntegerStatus,
    MixedIntegerWork,
    NativeMixedIntegerBranchAndBound,
    solve_mixed_integer_program,
)
from ._mixed_integer_audit import audit_mixed_integer_candidate
from ._mixed_integer_lifecycle import (
    bind_mixed_integer_numeric,
    MixedIntegerProgramExecution,
    MixedIntegerProgramPlan,
    MixedIntegerProgramTemplate,
    plan_mixed_integer_program,
    prepare_mixed_integer_program,
    prepare_mixed_integer_template,
    PreparedMixedIntegerProgram,
    refresh_mixed_integer_program,
    solve_prepared_mixed_integer_program,
)
from ._mixed_integer_oa import ConicOuterApproximation
from ._policy import (
    AbstractConvexProgramMethod,
    ClarabelInteriorPoint,
    ConicGeneralizedDerivativePolicy,
    ConvexDifferentiationMode,
    ConvexDifferentiationPolicy,
    ConvexSolvePolicy,
    ConvexTermination,
    DensePrimalDualQP,
    MPAXr2HPDHG,
    MPAXraPDHG,
    NativeHomogeneousConic,
)
from ._power_cone import PowerCone
from ._problem import ConicProgram, LinearProgram
from ._psd_cone import PositiveSemidefiniteCone
from ._quadratic import (
    ConvexProgramResult,
    prepare_qp_sensitivity,
    PreparedQPSensitivity,
    QuadraticProgram,
    solve_quadratic_program,
    solve_quadratic_program_primal,
)
from ._scip import SCIPMixedInteger
from ._types import (
    convex_program_status_message,
    ConvexProgramCapabilities,
    ConvexProgramCertificate,
    ConvexProgramProvenance,
    ConvexProgramStatus,
)


__all__ = [
    "AbstractConvexCone",
    "AbstractMixedIntegerMethod",
    "AbstractConvexProgramMethod",
    "CanonicalProgram",
    "ConicCut",
    "ConicCutAudit",
    "ConicCutSource",
    "ConicOuterApproximation",
    "ConicSeparationResult",
    "ConicProgram",
    "ConeBarrierOracle",
    "CVXPYConstraintSlice",
    "ConicProgramData",
    "CVXPYProgramBinding",
    "CVXPYVariableSlice",
    "ConicSensitivityResult",
    "ConvexDifferentiationMode",
    "ConicGeneralizedDerivativePolicy",
    "ConvexDifferentiationPolicy",
    "ClarabelInteriorPoint",
    "ConvexProgramCapabilities",
    "ConvexProgramCertificate",
    "ConvexProgramExecution",
    "ConvexProgramPlan",
    "ConvexProgramProvenance",
    "ConvexProgramStatus",
    "ConvexProgramTemplate",
    "ConvexSolvePolicy",
    "ConvexTermination",
    "ConvexWarmStart",
    "DensePrimalDualQP",
    "ExponentialCone",
    "MixedIntegerCandidate",
    "MixedIntegerCandidateAudit",
    "MixedIntegerCertificate",
    "MixedIntegerCertification",
    "MixedIntegerMethodCapabilities",
    "MixedIntegerBranchingRule",
    "MixedIntegerProgram",
    "MixedIntegerProgramExecution",
    "MixedIntegerProgramPlan",
    "MixedIntegerProgramTemplate",
    "MixedIntegerProvenance",
    "MixedIntegerResult",
    "MixedIntegerSolvePolicy",
    "MixedIntegerStatus",
    "MixedIntegerWork",
    "NativeMixedIntegerBranchAndBound",
    "NativeHomogeneousConic",
    "LinearProgram",
    "NonnegativeCone",
    "PositiveSemidefiniteCone",
    "PowerCone",
    "PreparedConvexProgram",
    "PreparedMixedIntegerProgram",
    "PreparedQPSensitivity",
    "PreparedMatrixFreeConicSensitivity",
    "PreparedConicSensitivity",
    "ProductCone",
    "MPAXr2HPDHG",
    "MPAXraPDHG",
    "QuadraticProgram",
    "ConvexProgramResult",
    "RotatedSecondOrderCone",
    "SecondOrderCone",
    "ZeroCone",
    "SCIPMixedInteger",
    "audit_conic_cut",
    "audit_mixed_integer_candidate",
    "bind_convex_numeric",
    "bind_mixed_integer_numeric",
    "convex_program_status_message",
    "conic_cut_from_dual",
    "cone_barrier_oracle",
    "conic_primal_jvp",
    "conic_primal_vjp",
    "export_cvxpy_program",
    "import_cvxpy_problem",
    "refresh_cvxpy_program",
    "restore_cvxpy_solution",
    "plan_mixed_integer_program",
    "polyhedral_conic_rows",
    "plan_convex_program",
    "prepare_convex_program",
    "prepare_mixed_integer_program",
    "prepare_mixed_integer_template",
    "prepare_convex_template",
    "prepare_conic_sensitivity",
    "prepare_qp_sensitivity",
    "refresh_convex_program",
    "refresh_mixed_integer_program",
    "separate_conic_point",
    "solve_convex_program",
    "solve_conic_program",
    "solve_prepared_convex_program",
    "solve_prepared_mixed_integer_program",
    "solve_linear_program",
    "solve_mixed_integer_program",
    "solve_quadratic_program",
    "solve_quadratic_program_primal",
]
