"""Finite exact-PDE trial spaces for boundary-only field fitting."""

from ..._holomorphic import (
    ComplexAffineNormalization,
    HolomorphicJet,
    HolomorphicMapCertificate,
    HolomorphicParameterCoverage,
    HolomorphicPotentialProvider,
)
from ..._holomorphic_linear import (
    HolomorphicLinearFrame,
    HolomorphicLinearFrameCertificate,
    HolomorphicMultiIndexSet,
    HolomorphicMultiJet,
    MultiIndex,
    MultivariableHolomorphicPotentialProvider,
)
from ._audit import audit_trial_space, trial_space_certificate
from ._complex_potential_2d import (
    BiharmonicPotential2D,
    HarmonicPotential2D,
    PlaneElasticityPotential2D,
    PlaneIsotropicMaterial,
)
from ._core import (
    AbstractTrefftzBasis,
    LinearTrefftzField,
    SimilarityNormalization,
    TrefftzResourceBudget,
    TrefftzResourceEvidence,
    TrialSpaceAuditReport,
    TrialSpaceCertificate,
    TrialValidityRegion,
)
from ._helmholtz import HelmholtzPlaneWaveBasis, sample_unit_directions
from ._holomorphic import HolomorphicPolynomialPotential
from ._holomorphic_composition import (
    HolomorphicBranchBundle,
    HolomorphicFactorGaugeReport,
    HolomorphicFactorizationEvidence,
    HolomorphicProductPotential,
)
from ._holomorphic_constraints import (
    ConstrainedHolomorphicPotential,
    HolomorphicAffineCoefficientMap,
    HolomorphicConstraintComponent,
    HolomorphicConstraintLiftEvidence,
    HolomorphicConstraintOperatorEvidence,
    HolomorphicConstraintOperatorPlan,
    HolomorphicConstraintProjector,
    HolomorphicJetFunctionalTerm,
    HolomorphicLinearFunctional,
    HolomorphicPointFunctional,
    HolomorphicProjectionState,
    PreparedHolomorphicConstraintOperator,
    ProjectedHolomorphicPotential,
)
from ._holomorphic_frame import HolomorphicPolynomialFrame
from ._holomorphic_physical_constraints import (
    biharmonic_normal_derivative_functional,
    biharmonic_robin_functional,
    biharmonic_value_functional,
    plane_elasticity_displacement_functional,
    plane_elasticity_stress_functional,
    plane_elasticity_traction_functional,
)
from ._holomorphic_trace import (
    DiskHolomorphicTraceLift,
    DiskHolomorphicTracePlan,
    holomorphic_period_functional,
    HolomorphicContourFunctional,
    HolomorphicTraceCertificate,
    HolomorphicTraceEvidenceKind,
)
from ._meromorphic import (
    ConstrainedMeromorphicPotential,
    DomainHolomorphicCertificate,
    MeromorphicLinearFrame,
    MeromorphicLinearFrameCertificate,
    MeromorphicMapCertificate,
    MeromorphicVariableProjectionPlan,
    PoleClearanceReport,
    PoleSet,
    TrainablePoleSet,
)
from ._monogenic import LinearMonogenicField, MonogenicPolynomialBasis
from ._pluriharmonic import PluriharmonicCertificate, PluriharmonicPotential
from ._polynomial import HarmonicPolynomialBasis, PolyharmonicAlmansiBasis


__all__ = [
    "AbstractTrefftzBasis",
    "BiharmonicPotential2D",
    "ComplexAffineNormalization",
    "ConstrainedHolomorphicPotential",
    "ConstrainedMeromorphicPotential",
    "DiskHolomorphicTraceLift",
    "DiskHolomorphicTracePlan",
    "DomainHolomorphicCertificate",
    "HarmonicPolynomialBasis",
    "HarmonicPotential2D",
    "HelmholtzPlaneWaveBasis",
    "HolomorphicAffineCoefficientMap",
    "HolomorphicBranchBundle",
    "HolomorphicConstraintComponent",
    "HolomorphicConstraintLiftEvidence",
    "HolomorphicConstraintOperatorEvidence",
    "HolomorphicConstraintOperatorPlan",
    "HolomorphicConstraintProjector",
    "HolomorphicContourFunctional",
    "HolomorphicFactorGaugeReport",
    "HolomorphicFactorizationEvidence",
    "HolomorphicJet",
    "HolomorphicJetFunctionalTerm",
    "HolomorphicLinearFrame",
    "HolomorphicLinearFrameCertificate",
    "HolomorphicLinearFunctional",
    "HolomorphicMapCertificate",
    "HolomorphicMultiIndexSet",
    "HolomorphicMultiJet",
    "HolomorphicParameterCoverage",
    "HolomorphicPointFunctional",
    "HolomorphicPolynomialFrame",
    "HolomorphicPolynomialPotential",
    "HolomorphicPotentialProvider",
    "HolomorphicProductPotential",
    "HolomorphicProjectionState",
    "HolomorphicTraceCertificate",
    "HolomorphicTraceEvidenceKind",
    "LinearMonogenicField",
    "LinearTrefftzField",
    "MeromorphicLinearFrame",
    "MeromorphicLinearFrameCertificate",
    "MeromorphicMapCertificate",
    "MeromorphicVariableProjectionPlan",
    "MonogenicPolynomialBasis",
    "MultiIndex",
    "MultivariableHolomorphicPotentialProvider",
    "PlaneElasticityPotential2D",
    "PlaneIsotropicMaterial",
    "PluriharmonicCertificate",
    "PluriharmonicPotential",
    "PoleClearanceReport",
    "PoleSet",
    "PolyharmonicAlmansiBasis",
    "PreparedHolomorphicConstraintOperator",
    "ProjectedHolomorphicPotential",
    "SimilarityNormalization",
    "TrainablePoleSet",
    "TrefftzResourceBudget",
    "TrefftzResourceEvidence",
    "TrialSpaceAuditReport",
    "TrialSpaceCertificate",
    "TrialValidityRegion",
    "audit_trial_space",
    "biharmonic_normal_derivative_functional",
    "biharmonic_robin_functional",
    "biharmonic_value_functional",
    "holomorphic_period_functional",
    "plane_elasticity_displacement_functional",
    "plane_elasticity_stress_functional",
    "plane_elasticity_traction_functional",
    "sample_unit_directions",
    "trial_space_certificate",
]
