#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

import math
from collections.abc import Mapping
from typing import Any, Literal

import equinox as eqx
import jax
import jax.numpy as jnp
from jaxtyping import Array

from ..._fingerprint import canonical_fingerprint
from ..._holomorphic import HolomorphicPotentialProvider
from ..._model import AbstractArrayModel
from ..._strict import StrictModule
from ..._trainable import NonTrainableState, partition_trainable
from ._core import TRIAL_SPACE_CERTIFICATE_KEY, TrialSpaceCertificate


def _parameter_count(value: Any, /) -> int:
    trainable, _ = partition_trainable(value)
    return sum(
        int(leaf.size)
        for leaf in jax.tree_util.tree_leaves(trainable)
        if eqx.is_inexact_array(leaf)
    )


def _physical_certificate(
    potential: HolomorphicPotentialProvider,
    /,
    *,
    equation_family: Literal["laplace", "polyharmonic", "linear-elasticity"],
    field_shape: tuple[int, ...],
    construction: str,
    equation_parameters: Mapping[str, int | float] | None = None,
    assumptions: tuple[str, ...],
    representation_id: str,
) -> TrialSpaceCertificate:
    holomorphic = potential.holomorphic_certificate()
    parameter_count = max(_parameter_count(potential), 1)
    linear = holomorphic.linear_in_parameters
    return TrialSpaceCertificate(
        equation_family=equation_family,
        ambient_dimension=2,
        field_shape=field_shape,
        construction=construction,
        equation_parameters={} if equation_parameters is None else equation_parameters,
        normalization_id=holomorphic.normalization_id,
        basis_id=representation_id,
        rank=parameter_count,
        assumptions=assumptions
        + (f"holomorphic-map-certificate:{holomorphic.certificate_id}",),
        construction_residual=0.0,
        construction_tolerance=0.0,
        coverage=holomorphic.parameter_coverage,
        linear_in_coefficients=linear,
    )


def _complex_coordinate(coordinates: Array, /) -> Array:
    values = jnp.asarray(coordinates)
    if values.shape != (2,):
        raise ValueError(
            f"Complex-potential models expect real shape (2,); got {values.shape}."
        )
    return values[0] + 1j * values[1]


class HarmonicPotential2D(AbstractArrayModel):
    """Real harmonic field generated by one holomorphic potential branch."""

    potential: Any
    branch: int = eqx.field(static=True)
    in_size: int = eqx.field(static=True)
    out_size: Literal["scalar"] = eqx.field(static=True)
    _certificate: TrialSpaceCertificate

    def __init__(self, potential: HolomorphicPotentialProvider, /, *, branch: int = 0):
        if not isinstance(potential, HolomorphicPotentialProvider):
            raise TypeError("potential must implement HolomorphicPotentialProvider.")
        certificate = potential.holomorphic_certificate()
        branch_ = int(branch)
        if (
            certificate.complex_input_size != 1
            or not 0 <= branch_ < certificate.complex_output_size
        ):
            raise ValueError("Harmonic potential requires one input and a valid branch.")
        representation_id = canonical_fingerprint(
            {
                "kind": "harmonic-holomorphic-potential-2d-v1",
                "holomorphic": certificate.certificate_id,
                "branch": branch_,
            }
        )
        self.potential = potential
        self.branch = branch_
        self.in_size = 2
        self.out_size = "scalar"
        self._certificate = _physical_certificate(
            potential,
            equation_family="laplace",
            field_shape=(),
            construction="real-part-holomorphic-potential-2d",
            assumptions=(
                "Euclidean two-dimensional Laplacian",
                "one globally holomorphic potential branch",
            ),
            representation_id=representation_id,
        )

    def __call__(self, coordinates: Array, /, *, key=None) -> Array:
        del key
        value = self.potential(_complex_coordinate(coordinates))[self.branch]
        return jnp.real(value)

    def model_metadata(self) -> Mapping[str, Any]:
        return {TRIAL_SPACE_CERTIFICATE_KEY: self._certificate}


class BiharmonicPotential2D(AbstractArrayModel):
    """Real biharmonic field generated by two holomorphic potential branches."""

    potential: Any
    phi_branch: int = eqx.field(static=True)
    psi_branch: int = eqx.field(static=True)
    in_size: int = eqx.field(static=True)
    out_size: Literal["scalar"] = eqx.field(static=True)
    _certificate: TrialSpaceCertificate

    def __init__(
        self,
        potential: HolomorphicPotentialProvider,
        /,
        *,
        phi_branch: int = 0,
        psi_branch: int = 1,
    ):
        if not isinstance(potential, HolomorphicPotentialProvider):
            raise TypeError("potential must implement HolomorphicPotentialProvider.")
        holomorphic = potential.holomorphic_certificate()
        phi = int(phi_branch)
        psi = int(psi_branch)
        if holomorphic.complex_input_size != 1:
            raise ValueError("Biharmonic potential requires one complex input.")
        if (
            phi == psi
            or min(phi, psi) < 0
            or max(phi, psi) >= holomorphic.complex_output_size
        ):
            raise ValueError("Biharmonic potential requires two distinct valid branches.")
        representation_id = canonical_fingerprint(
            {
                "kind": "goursat-holomorphic-potential-2d-v1",
                "holomorphic": holomorphic.certificate_id,
                "phi_branch": phi,
                "psi_branch": psi,
            }
        )
        self.potential = potential
        self.phi_branch = phi
        self.psi_branch = psi
        self.in_size = 2
        self.out_size = "scalar"
        self._certificate = _physical_certificate(
            potential,
            equation_family="polyharmonic",
            field_shape=(),
            construction="goursat-holomorphic-potential-2d",
            equation_parameters={"order": 2},
            assumptions=(
                "Euclidean two-dimensional biharmonic operator",
                "two globally holomorphic potential branches",
                "simply connected domain for representation completeness",
            ),
            representation_id=representation_id,
        )

    def __call__(self, coordinates: Array, /, *, key=None) -> Array:
        del key
        z = _complex_coordinate(coordinates)
        values = self.potential(z)
        return jnp.real(jnp.conj(z) * values[self.phi_branch] + values[self.psi_branch])

    def model_metadata(self) -> Mapping[str, Any]:
        return {TRIAL_SPACE_CERTIFICATE_KEY: self._certificate}


class PlaneIsotropicMaterial(StrictModule, NonTrainableState):
    """Homogeneous isotropic material under plane strain or plane stress."""

    lambda_: Array
    mu: Array
    effective_lambda: Array
    kappa: Array
    young: Array
    poisson: Array
    hypothesis: Literal["plane_strain", "plane_stress"] = eqx.field(static=True)
    material_id: str = eqx.field(static=True)

    def __init__(
        self,
        lambda_: float,
        mu: float,
        /,
        *,
        hypothesis: Literal["plane_strain", "plane_stress"] = "plane_strain",
    ):
        lambda_value = float(lambda_)
        mu_value = float(mu)
        if hypothesis not in ("plane_strain", "plane_stress"):
            raise ValueError("Unknown plane elasticity hypothesis.")
        if not math.isfinite(lambda_value) or not math.isfinite(mu_value):
            raise ValueError("Lamé parameters must be finite.")
        if mu_value <= 0.0 or 3.0 * lambda_value + 2.0 * mu_value <= 0.0:
            raise ValueError("Lamé parameters must define a stable isotropic material.")
        poisson = lambda_value / (2.0 * (lambda_value + mu_value))
        young = (
            mu_value * (3.0 * lambda_value + 2.0 * mu_value) / (lambda_value + mu_value)
        )
        effective = (
            lambda_value
            if hypothesis == "plane_strain"
            else 2.0 * lambda_value * mu_value / (lambda_value + 2.0 * mu_value)
        )
        kappa = (effective + 3.0 * mu_value) / (effective + mu_value)
        self.lambda_ = jnp.asarray(lambda_value)
        self.mu = jnp.asarray(mu_value)
        self.effective_lambda = jnp.asarray(effective)
        self.kappa = jnp.asarray(kappa)
        self.young = jnp.asarray(young)
        self.poisson = jnp.asarray(poisson)
        self.hypothesis = hypothesis
        self.material_id = canonical_fingerprint(
            {
                "kind": "plane-isotropic-material-v1",
                "lambda": lambda_value,
                "mu": mu_value,
                "hypothesis": hypothesis,
            }
        )


class PlaneElasticityPotential2D(AbstractArrayModel):
    """Kolosov-Muskhelishvili plane-elasticity state from holomorphic potentials."""

    potential: Any
    material: PlaneIsotropicMaterial
    phi_branch: int = eqx.field(static=True)
    psi_branch: int = eqx.field(static=True)
    output: Literal["mixed", "stress"] = eqx.field(static=True)
    in_size: int = eqx.field(static=True)
    out_size: int = eqx.field(static=True)
    _certificate: TrialSpaceCertificate

    def __init__(
        self,
        potential: HolomorphicPotentialProvider,
        material: PlaneIsotropicMaterial,
        /,
        *,
        phi_branch: int = 0,
        psi_branch: int = 1,
        output: Literal["mixed", "stress"] = "mixed",
    ):
        if not isinstance(potential, HolomorphicPotentialProvider):
            raise TypeError("potential must implement HolomorphicPotentialProvider.")
        if not isinstance(material, PlaneIsotropicMaterial):
            raise TypeError("material must be PlaneIsotropicMaterial.")
        if output not in ("mixed", "stress"):
            raise ValueError("Plane elasticity output must be 'mixed' or 'stress'.")
        holomorphic = potential.holomorphic_certificate()
        phi = int(phi_branch)
        psi = int(psi_branch)
        if holomorphic.maximum_derivative_order < 2:
            raise ValueError("Plane elasticity requires second holomorphic derivatives.")
        if (
            holomorphic.complex_input_size != 1
            or phi == psi
            or min(phi, psi) < 0
            or max(phi, psi) >= holomorphic.complex_output_size
        ):
            raise ValueError(
                "Plane elasticity requires two distinct valid potential branches."
            )
        output_size = 5 if output == "mixed" else 3
        representation_id = canonical_fingerprint(
            {
                "kind": "kolosov-muskhelishvili-potential-2d-v1",
                "holomorphic": holomorphic.certificate_id,
                "material": material.material_id,
                "phi_branch": phi,
                "psi_branch": psi,
                "output": output,
            }
        )
        self.potential = potential
        self.material = material
        self.phi_branch = phi
        self.psi_branch = psi
        self.output = output
        self.in_size = 2
        self.out_size = output_size
        self._certificate = _physical_certificate(
            potential,
            equation_family="linear-elasticity",
            field_shape=(output_size,),
            construction="kolosov-muskhelishvili-holomorphic-potential-2d",
            equation_parameters={"state_components": output_size},
            assumptions=(
                "homogeneous isotropic plane elasticity",
                f"material:{material.material_id}",
                "zero body force",
                "simply connected domain for representation completeness",
            ),
            representation_id=representation_id,
        )

    def __call__(self, coordinates: Array, /, *, key=None) -> Array:
        del key
        z = _complex_coordinate(coordinates)
        jet = self.potential.jet(z, 2)
        phi = jet.value[self.phi_branch]
        psi = jet.value[self.psi_branch]
        phi_z = jet.derivative(1)[self.phi_branch]
        psi_z = jet.derivative(1)[self.psi_branch]
        phi_zz = jet.derivative(2)[self.phi_branch]
        second = jnp.conj(z) * phi_zz + psi_z
        trace_half = 2.0 * jnp.real(phi_z)
        stress = jnp.stack(
            (
                trace_half - jnp.real(second),
                trace_half + jnp.real(second),
                jnp.imag(second),
            )
        )
        if self.output == "stress":
            return stress
        displacement_complex = (
            self.material.kappa * phi - z * jnp.conj(phi_z) - jnp.conj(psi)
        ) / (2.0 * self.material.mu)
        displacement = jnp.stack(
            (jnp.real(displacement_complex), jnp.imag(displacement_complex))
        )
        return jnp.concatenate((stress, displacement), axis=0)

    def model_metadata(self) -> Mapping[str, Any]:
        return {TRIAL_SPACE_CERTIFICATE_KEY: self._certificate}


__all__ = [
    "BiharmonicPotential2D",
    "HarmonicPotential2D",
    "PlaneElasticityPotential2D",
    "PlaneIsotropicMaterial",
]
