#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Literal

import equinox as eqx
import jax
import jax.numpy as jnp
from jaxtyping import Array, ArrayLike

from ..._fingerprint import canonical_fingerprint
from ..._holomorphic_linear import (
    HolomorphicMultiIndexSet,
    MultivariableHolomorphicPotentialProvider,
)
from ..._model import AbstractArrayModel
from ..._strict import StrictModule
from ..._trainable import NonTrainableState, partition_trainable
from ._core import TRIAL_SPACE_CERTIFICATE_KEY, TrialSpaceCertificate


class PluriharmonicCertificate(StrictModule, NonTrainableState):
    """Construction evidence for the real part of a holomorphic map on ℂᵐ."""

    complex_dimension: int = eqx.field(static=True)
    branch: int = eqx.field(static=True)
    holomorphic_certificate_id: str = eqx.field(static=True)
    certificate_id: str = eqx.field(static=True)

    def __init__(
        self,
        *,
        complex_dimension: int,
        branch: int,
        holomorphic_certificate_id: str,
    ):
        dimension = int(complex_dimension)
        branch_ = int(branch)
        identifier = str(holomorphic_certificate_id)
        if dimension <= 0 or branch_ < 0 or not identifier:
            raise ValueError("Pluriharmonic certificate metadata is invalid.")
        self.complex_dimension = dimension
        self.branch = branch_
        self.holomorphic_certificate_id = identifier
        self.certificate_id = canonical_fingerprint(
            {
                "kind": "pluriharmonic-certificate",
                "complex_dimension": dimension,
                "branch": branch_,
                "holomorphic_certificate_id": identifier,
            }
        )


class PluriharmonicPotential(AbstractArrayModel):
    """Real pluriharmonic field generated by one holomorphic scalar branch."""

    provider: Any
    index_set: HolomorphicMultiIndexSet
    pluriharmonic_certificate: PluriharmonicCertificate
    branch: int = eqx.field(static=True)
    complex_dimension: int = eqx.field(static=True)
    in_size: int = eqx.field(static=True)
    out_size: Literal["scalar"] = eqx.field(static=True)
    _certificate: TrialSpaceCertificate

    def __init__(
        self,
        provider: MultivariableHolomorphicPotentialProvider,
        /,
        *,
        branch: int = 0,
    ):
        if not isinstance(provider, MultivariableHolomorphicPotentialProvider):
            raise TypeError(
                "provider must implement MultivariableHolomorphicPotentialProvider."
            )
        holomorphic = provider.holomorphic_certificate()
        dimension = int(holomorphic.complex_input_size)
        branch_ = int(branch)
        if not 0 <= branch_ < int(holomorphic.complex_output_size):
            raise ValueError("Pluriharmonic branch is invalid.")
        if int(holomorphic.maximum_derivative_order) < 2:
            raise ValueError("Pluriharmonic derivatives require second-order evidence.")
        pluriharmonic = PluriharmonicCertificate(
            complex_dimension=dimension,
            branch=branch_,
            holomorphic_certificate_id=holomorphic.certificate_id,
        )
        trainable, _ = partition_trainable(provider)
        parameter_count = max(
            sum(
                int(leaf.size)
                for leaf in jax.tree_util.tree_leaves(trainable)
                if eqx.is_inexact_array(leaf)
            ),
            1,
        )
        self.provider = provider
        self.index_set = HolomorphicMultiIndexSet.total_degree(dimension, 2)
        self.pluriharmonic_certificate = pluriharmonic
        self.branch = branch_
        self.complex_dimension = dimension
        self.in_size = 2 * dimension
        self.out_size = "scalar"
        self._certificate = TrialSpaceCertificate(
            equation_family="laplace",
            ambient_dimension=2 * dimension,
            field_shape=(),
            construction="real-part-several-variable-holomorphic-potential",
            equation_parameters={"complex_dimension": dimension},
            normalization_id=holomorphic.normalization_id,
            basis_id=pluriharmonic.certificate_id,
            rank=parameter_count,
            assumptions=(
                "standard paired real/imaginary complex coordinates",
                "globally holomorphic scalar branch",
                "pluriharmonic family; not a complete harmonic family when dimension exceeds one",
                f"holomorphic-map-certificate:{holomorphic.certificate_id}",
            ),
            construction_residual=0.0,
            construction_tolerance=0.0,
            coverage=holomorphic.parameter_coverage,
            linear_in_coefficients=holomorphic.linear_in_parameters,
        )

    def _real_coordinates(self, coordinates: ArrayLike, /) -> Array:
        values = jnp.asarray(coordinates)
        if values.shape != (self.in_size,):
            raise ValueError(
                f"Pluriharmonic potential expected shape ({self.in_size},); "
                f"got {values.shape}."
            )
        return values

    def _complex_coordinates(self, coordinates: ArrayLike, /) -> Array:
        values = self._real_coordinates(coordinates)
        dimension = self.complex_dimension
        return values[:dimension] + 1j * values[dimension:]

    def _jet(self, coordinates: ArrayLike, /):
        return self.provider.multi_jet(
            self._complex_coordinates(coordinates),
            self.index_set,
        )

    def __call__(self, coordinates: ArrayLike, /, *, key=None) -> Array:
        del key
        return jnp.real(self._jet(coordinates).value[self.branch])

    def gradient(self, coordinates: ArrayLike, /) -> Array:
        jet = self._jet(coordinates)
        first = []
        for axis in range(self.complex_dimension):
            derivative = tuple(
                1 if current == axis else 0 for current in range(self.complex_dimension)
            )
            first.append(jet.derivative(derivative)[self.branch])
        values = jnp.stack(tuple(first))
        return jnp.concatenate((jnp.real(values), -jnp.imag(values)))

    def hessian(self, coordinates: ArrayLike, /) -> Array:
        jet = self._jet(coordinates)
        dimension = self.complex_dimension
        complex_hessian = jnp.zeros((dimension, dimension), dtype=jet.value.dtype)
        for first in range(dimension):
            for second in range(dimension):
                derivative = tuple(
                    int(axis == first) + int(axis == second) for axis in range(dimension)
                )
                complex_hessian = complex_hessian.at[first, second].set(
                    jet.derivative(derivative)[self.branch]
                )
        real = jnp.real(complex_hessian)
        imaginary = jnp.imag(complex_hessian)
        return jnp.block([[real, -imaginary], [-imaginary, -real]])

    def laplacian(self, coordinates: ArrayLike, /) -> Array:
        return jnp.trace(self.hessian(coordinates))

    def model_metadata(self) -> Mapping[str, Any]:
        return {TRIAL_SPACE_CERTIFICATE_KEY: self._certificate}


__all__ = [
    "PluriharmonicCertificate",
    "PluriharmonicPotential",
]
