"""Production data, normalization, checkpoint, and rollout utilities for operators."""

from ...._model import (
    OperatorArchitectureCodec,
    register_operator_architecture_codec,
)
from ...._training import (
    DelayedTargetPolicy,
    ExponentialMovingAverageTargetPolicy,
    TargetParameterSource,
    TargetParameterState,
    TrainingController,
    TrainingProgress,
)
from ._adaptation import (
    adapt_operator_context,
    BoundedResidualAdaptationPolicy,
    TestTimeAdaptationResult,
)
from ._artifact import (
    load_external_trained_operator,
    load_operator_artifact_manifest,
    load_operator_training_state,
    load_trained_operator,
    OperatorArtifactManifest,
    OperatorArtifactTrainingState,
    save_operator_artifact,
)
from ._checkpoint import (
    load_operator_training_checkpoint,
    OperatorTrainingCheckpoint,
    save_operator_training_checkpoint,
)
from ._classification_losses import (
    OperatorCaseReduction,
    OperatorClassificationNLL,
    OperatorEmptyOverlap,
    OperatorFocalClassificationLoss,
    OperatorOverlapClassReduction,
    OperatorOverlapKind,
    OperatorOverlapLoss,
    OperatorSoftClassificationLoss,
    OperatorSupportReduction,
    OperatorZeroMeasure,
)
from ._conditional_affine import (
    ChemicalConditionalAffineDriverLoss,
    ChemicalConditionalAffineTeacherForcedLoss,
)
from ._coreset import (
    compress_operator_cases,
    compress_operator_queries,
    OperatorCaseCoreset,
    OperatorCoresetMethod,
    OperatorQueryCoreset,
)
from ._dataset import (
    operator_dataset_from_arrays,
    operator_dataset_from_cases,
    OperatorDataset,
    OperatorDatasetSplit,
    OperatorSplitPolicy,
    split_operator_dataset,
)
from ._distributional import (
    DistributionReduction,
    operator_distribution_nll,
    OperatorDistributionNLL,
)
from ._dtype import (
    ComplexDTypeName,
    DTypeName,
    MatmulPrecisionName,
    OperatorDTypePolicy,
    OperatorPrecisionEvidence,
)
from ._fingerprint import operator_batch_schema, operator_dataset_fingerprint
from ._fit import (
    fit_operator,
    OperatorFitHistory,
    OperatorFitResult,
    OperatorValidationPolicy,
)
from ._flow_matching import OperatorFlowMatchingMetric
from ._linearization import linearize_operator, OperatorLinearization
from ._loader import (
    OperatorBatchEpoch,
    OperatorBatchLoader,
    OperatorEpochPlan,
    OperatorTrainingBatch,
)
from ._loss_scale import OperatorLossScalePolicy, OperatorLossScaleState
from ._losses import (
    AbstractOperatorLossTerm,
    CochainResidualInput,
    CochainResidualLoss,
    OperatorLossContext,
    OperatorLossTerm,
    ResidualOperatorRolloutLoss,
    SupervisedOperatorLoss,
    SupervisedOperatorRolloutLoss,
)
from ._normalization import (
    AffineNormalizer,
    fit_operator_normalization,
    load_operator_normalization,
    OperatorNormalizationPolicy,
    save_operator_normalization,
)
from ._physics import (
    AbstractOperatorOutputTransform,
    ConservationProjection,
    HardConstraintTransform,
    operator_hilbert_inner_product,
    operator_hilbert_norm,
    operator_hilbert_relative_error,
    operator_integral,
    operator_weak_form_loss,
    OperatorOutputPipeline,
    project_operator_conservation,
    WeakOperatorLoss,
)
from ._pod import (
    fit_operator_pod,
    fit_pod_basis,
    OperatorPODDiagnostics,
    OperatorPODFit,
)
from ._pretrained import BundledPretrainedOperator, load_pretrained_operator
from ._risk import (
    MechanicsCaseReduction,
    MechanicsCaseReductionKind,
    MechanicsCaseReductionResult,
)
from ._rollout import (
    autoregressive_operator_rollout,
    autoregressive_operator_rollout_routes,
    infer_operator_rollout_routes,
    OperatorRollout,
    OperatorRolloutControlRoute,
    OperatorRolloutPolicy,
    OperatorRolloutRoute,
)
from ._semigroup import (
    conditioned_distributional_semigroup_loss,
    conditioned_semigroup_consistency_loss,
    conditioned_sinkhorn_semigroup_loss,
    ConditionedSemigroupObjective,
    DistributionalSemigroupObjective,
    SemigroupKeyMode,
    SemigroupReduction,
    SinkhornDistributionalSemigroupObjective,
)
from ._spectral_residual import SpectralPDEResidualLoss
from ._stochastic_transition import (
    direct_operator_horizon_nll,
    marginal_operator_rollout,
    operator_jump_generator_objective,
    operator_markov_chain_nll,
    operator_weak_generator_objective,
    OperatorDriverBinding,
    OperatorDriverKind,
    OperatorDriverQuantity,
    OperatorJumpTransition,
    OperatorMarginalTransition,
    OperatorPathwiseTransition,
    OperatorProcessDistribution,
    OperatorProcessTransition,
    OperatorTransitionKind,
    OperatorTransitionReduction,
    OperatorTransitionSpec,
    pathwise_operator_rollout,
    process_operator_rollout,
    StochasticOperatorRollout,
)
from ._streaming import (
    ArrayOperatorQuerySource,
    ArrayPredictionSink,
    CallbackOperatorQuerySource,
    decode_query_chunks,
    NpyPredictionSink,
    OperatorPredictionMetadata,
    OperatorPredictionSink,
    OperatorQueryChunk,
    OperatorQuerySchema,
    OperatorQuerySource,
)
from ._target_consistency import TargetOperatorConsistencyLoss
from ._trained_operator import (
    operator_contract_fingerprint,
    operator_normalization_fingerprint,
    OperatorCompilationStrategy,
    OperatorExecutionPlan,
    OperatorPaddingPolicy,
    PreparedOperatorInput,
    TrainedOperator,
)


__all__ = [
    "OperatorArchitectureCodec",
    "register_operator_architecture_codec",
    "OperatorArtifactManifest",
    "OperatorArtifactTrainingState",
    "BoundedResidualAdaptationPolicy",
    "BundledPretrainedOperator",
    "TestTimeAdaptationResult",
    "adapt_operator_context",
    "MechanicsCaseReduction",
    "MechanicsCaseReductionKind",
    "MechanicsCaseReductionResult",
    "AffineNormalizer",
    "AbstractOperatorLossTerm",
    "CochainResidualInput",
    "ChemicalConditionalAffineDriverLoss",
    "ChemicalConditionalAffineTeacherForcedLoss",
    "CochainResidualLoss",
    "SpectralPDEResidualLoss",
    "AbstractOperatorOutputTransform",
    "ConservationProjection",
    "HardConstraintTransform",
    "operator_hilbert_inner_product",
    "operator_hilbert_norm",
    "operator_hilbert_relative_error",
    "linearize_operator",
    "OperatorLinearization",
    "operator_integral",
    "OperatorOutputPipeline",
    "operator_weak_form_loss",
    "project_operator_conservation",
    "WeakOperatorLoss",
    "compress_operator_cases",
    "compress_operator_queries",
    "ComplexDTypeName",
    "DTypeName",
    "MatmulPrecisionName",
    "fit_operator_normalization",
    "fit_operator",
    "load_pretrained_operator",
    "fit_operator_pod",
    "fit_pod_basis",
    "OperatorPODDiagnostics",
    "OperatorPODFit",
    "OperatorBatchLoader",
    "OperatorBatchEpoch",
    "OperatorDataset",
    "OperatorCaseCoreset",
    "OperatorCoresetMethod",
    "OperatorQueryCoreset",
    "OperatorDatasetSplit",
    "OperatorDTypePolicy",
    "OperatorPrecisionEvidence",
    "OperatorFitHistory",
    "OperatorFitResult",
    "OperatorFlowMatchingMetric",
    "OperatorLossContext",
    "OperatorLossTerm",
    "OperatorLossScalePolicy",
    "OperatorLossScaleState",
    "OperatorRollout",
    "OperatorRolloutPolicy",
    "OperatorRolloutControlRoute",
    "OperatorRolloutRoute",
    "TargetOperatorConsistencyLoss",
    "ResidualOperatorRolloutLoss",
    "SupervisedOperatorRolloutLoss",
    "OperatorSplitPolicy",
    "OperatorEpochPlan",
    "OperatorTrainingBatch",
    "OperatorTrainingCheckpoint",
    "autoregressive_operator_rollout",
    "autoregressive_operator_rollout_routes",
    "infer_operator_rollout_routes",
    "conditioned_distributional_semigroup_loss",
    "conditioned_semigroup_consistency_loss",
    "conditioned_sinkhorn_semigroup_loss",
    "ConditionedSemigroupObjective",
    "DistributionalSemigroupObjective",
    "SinkhornDistributionalSemigroupObjective",
    "SemigroupKeyMode",
    "SemigroupReduction",
    "direct_operator_horizon_nll",
    "marginal_operator_rollout",
    "operator_jump_generator_objective",
    "operator_markov_chain_nll",
    "operator_weak_generator_objective",
    "OperatorDriverBinding",
    "OperatorDriverKind",
    "OperatorCaseReduction",
    "OperatorClassificationNLL",
    "OperatorEmptyOverlap",
    "OperatorFocalClassificationLoss",
    "OperatorOverlapClassReduction",
    "OperatorOverlapKind",
    "OperatorOverlapLoss",
    "OperatorSoftClassificationLoss",
    "OperatorSupportReduction",
    "OperatorZeroMeasure",
    "OperatorDriverQuantity",
    "OperatorJumpTransition",
    "OperatorMarginalTransition",
    "OperatorPathwiseTransition",
    "OperatorProcessDistribution",
    "OperatorProcessTransition",
    "OperatorTransitionKind",
    "OperatorTransitionReduction",
    "OperatorTransitionSpec",
    "pathwise_operator_rollout",
    "process_operator_rollout",
    "StochasticOperatorRollout",
    "OperatorCompilationStrategy",
    "OperatorExecutionPlan",
    "OperatorPaddingPolicy",
    "PreparedOperatorInput",
    "TrainedOperator",
    "load_external_trained_operator",
    "load_operator_artifact_manifest",
    "load_operator_training_state",
    "load_trained_operator",
    "operator_contract_fingerprint",
    "operator_normalization_fingerprint",
    "save_operator_artifact",
    "load_operator_normalization",
    "load_operator_training_checkpoint",
    "OperatorNormalizationPolicy",
    "save_operator_normalization",
    "OperatorValidationPolicy",
    "operator_batch_schema",
    "operator_dataset_fingerprint",
    "operator_dataset_from_arrays",
    "operator_dataset_from_cases",
    "save_operator_training_checkpoint",
    "SupervisedOperatorLoss",
    "DistributionReduction",
    "OperatorDistributionNLL",
    "operator_distribution_nll",
    "split_operator_dataset",
    "ArrayOperatorQuerySource",
    "ArrayPredictionSink",
    "CallbackOperatorQuerySource",
    "decode_query_chunks",
    "NpyPredictionSink",
    "OperatorPredictionMetadata",
    "OperatorPredictionSink",
    "OperatorQueryChunk",
    "OperatorQuerySchema",
    "OperatorQuerySource",
    "DelayedTargetPolicy",
    "ExponentialMovingAverageTargetPolicy",
    "TargetParameterSource",
    "TargetParameterState",
    "TrainingController",
    "TrainingProgress",
]
