"""Lazy native meshing facade; capabilities load from canonical owners."""

from importlib import import_module
from typing import Any, TYPE_CHECKING


_SYMBOL_MODULES: dict[str, tuple[str, str | None]] = {
    "AbstractMeshProposer": ("._proposals", "AbstractMeshProposer"),
    "AbstractMeshingSession": ("._session", "AbstractMeshingSession"),
    "AdaptationAction": ("._decision", "AdaptationAction"),
    "AssociationPropagationError": ("._association", "AssociationPropagationError"),
    "AssociationPropagationPolicy": ("._association", "AssociationPropagationPolicy"),
    "BRepAssociationTransfer": ("._association", "BRepAssociationTransfer"),
    "BackgroundMetricControl": ("._controls", "BackgroundMetricControl"),
    "BackgroundMetricMode": ("._controls", "BackgroundMetricMode"),
    "BisectionCompatibility": ("._bisection", "BisectionCompatibility"),
    "BisectionEvidence": ("._bisection", "BisectionEvidence"),
    "BisectionHierarchy": ("._bisection", "BisectionHierarchy"),
    "BisectionUniformRefinement": ("._bisection", "BisectionUniformRefinement"),
    "BlockInterfaceControl": ("._controls", "BlockInterfaceControl"),
    "BoundaryLayerCollisionPolicy": ("._controls", "BoundaryLayerCollisionPolicy"),
    "BoundaryLayerControl": ("._controls", "BoundaryLayerControl"),
    "BoundaryLayerCornerPolicy": ("._controls", "BoundaryLayerCornerPolicy"),
    "BoundaryLayerEvidence": ("._boundary_layer", "BoundaryLayerEvidence"),
    "BoundaryLayerExtrusion": ("._layer_extrusion", "BoundaryLayerExtrusion"),
    "BoundaryLayerMesh": ("._boundary_layer", "BoundaryLayerMesh"),
    "BoundaryLayerPolicy": ("._boundary_layer", "BoundaryLayerPolicy"),
    "BoundaryLayerRoute": ("._controls", "BoundaryLayerRoute"),
    "CellFamilyPolicy": ("._contracts", "CellFamilyPolicy"),
    "CellGeometryOptimizationResult": (
        "._optimization",
        "CellGeometryOptimizationResult",
    ),
    "CellMeshAuditDisposition": ("._audit", "CellMeshAuditDisposition"),
    "CellMeshAuditPolicy": ("._audit", "CellMeshAuditPolicy"),
    "CellMeshAuditReport": ("._audit", "CellMeshAuditReport"),
    "CellMeshExportResult": ("._interop", "CellMeshExportResult"),
    "CellMeshImportResult": ("._interop", "CellMeshImportResult"),
    "CellMeshTransition": ("._lineage", "CellMeshTransition"),
    "CellMeshingResult": ("._result", "CellMeshingResult"),
    "CellMeshingTarget": ("._contracts", "CellMeshingTarget"),
    "CellQualityEvaluation": ("._quality", "CellQualityEvaluation"),
    "CellQualityReport": ("._quality", "CellQualityReport"),
    "ComposedAssociationTransfer": (
        "._association_composition",
        "ComposedAssociationTransfer",
    ),
    "ConformalCoupling": ("._coupling", "ConformalCoupling"),
    "ContactCoupling": ("._coupling", "ContactCoupling"),
    "CouplingSearchError": ("._coupling", "CouplingSearchError"),
    "CouplingSearchEvidence": ("._coupling", "CouplingSearchEvidence"),
    "CouplingSearchStatus": ("._coupling", "CouplingSearchStatus"),
    "CurvatureSizeControl": ("._sizing", "CurvatureSizeControl"),
    "CurveEnd": ("._contracts", "CurveEnd"),
    "CurveJunction": ("._contracts", "CurveJunction"),
    "CurveMeshingSpec": ("._contracts", "CurveMeshingSpec"),
    "CurvedGeometryEvidence": ("._curving", "CurvedGeometryEvidence"),
    "DecisionBudget": ("._decision", "DecisionBudget"),
    "DeviceGenerationCandidates": ("._device_generation", "DeviceGenerationCandidates"),
    "DeviceGenerationEvidence": ("._device_generation", "DeviceGenerationEvidence"),
    "DeviceGenerationLayout": ("._device_generation", "DeviceGenerationLayout"),
    "DeviceGenerationStatus": ("._device_generation", "DeviceGenerationStatus"),
    "DeviceGenerationUpdate": ("._device_generation", "DeviceGenerationUpdate"),
    "DeviceMetricEvidence": ("._device_metric", "DeviceMetricEvidence"),
    "DeviceMetricLayout": ("._device_metric", "DeviceMetricLayout"),
    "DeviceMetricReport": ("._device_metric", "DeviceMetricReport"),
    "DeviceMetricState": ("._device_metric", "DeviceMetricState"),
    "DeviceMetricUpdate": ("._device_metric", "DeviceMetricUpdate"),
    "DeviceTetraMetricEvidence": ("._device_tetra_metric", "DeviceTetraMetricEvidence"),
    "DeviceTetraMetricLayout": ("._device_tetra_metric", "DeviceTetraMetricLayout"),
    "DeviceTetraMetricReport": ("._device_tetra_metric", "DeviceTetraMetricReport"),
    "DeviceTetraMetricState": ("._device_tetra_metric", "DeviceTetraMetricState"),
    "DeviceTetraMetricUpdate": ("._device_tetra_metric", "DeviceTetraMetricUpdate"),
    "EntityLineage": ("._lineage", "EntityLineage"),
    "EntityLineageKind": ("._lineage", "EntityLineageKind"),
    "ErrorQuantity": ("._decision", "ErrorQuantity"),
    "FTetWildMeshingPlan": (".providers", "FTetWildMeshingPlan"),
    "FTetWildOptions": (".providers", "FTetWildOptions"),
    "FTetWildProvider": (".providers", "FTetWildProvider"),
    "FeatureKind": ("._controls", "FeatureKind"),
    "FiniteVolumeQualityEvaluation": ("._quality", "FiniteVolumeQualityEvaluation"),
    "FixedEpochDerivativeEvidence": ("._decision", "FixedEpochDerivativeEvidence"),
    "GeometryAssociation": ("._association", "GeometryAssociation"),
    "GeometryAssociationKind": ("._association", "GeometryAssociationKind"),
    "GeometryAssociationProvenance": ("._association", "GeometryAssociationProvenance"),
    "GeometryRealizationMeshAdaptation": (
        "._adaptation",
        "GeometryRealizationMeshAdaptation",
    ),
    "GeometrySourceEntityRole": ("._association", "GeometrySourceEntityRole"),
    "GmshHighOrderOptimization": (".providers", "GmshHighOrderOptimization"),
    "GmshMeshingPlan": (".providers", "GmshMeshingPlan"),
    "GmshOptions": (".providers", "GmshOptions"),
    "GmshProvider": (".providers", "GmshProvider"),
    "GmshRemeshingPlan": (".providers", "GmshRemeshingPlan"),
    "GmshSession": (".providers", "GmshSession"),
    "GmshSurfaceAlgorithm": (".providers", "GmshSurfaceAlgorithm"),
    "GmshVolumeAlgorithm": (".providers", "GmshVolumeAlgorithm"),
    "HessianMetricEvidence": ("._metric", "HessianMetricEvidence"),
    "HighOrderCurvingPolicy": ("._curving", "HighOrderCurvingPolicy"),
    "HighOrderCurvingResult": ("._curving", "HighOrderCurvingResult"),
    "HighOrderCurvingStatus": ("._curving", "HighOrderCurvingStatus"),
    "HoleSeed": ("._controls", "HoleSeed"),
    "ImplicitAssociationTransfer": (
        "._implicit_association_transfer",
        "ImplicitAssociationTransfer",
    ),
    "LayerSchedule": ("._controls", "LayerSchedule"),
    "LearnedMeshProposer": ("._proposals", "LearnedMeshProposer"),
    "LevelSetEvidence": ("._level_set", "LevelSetEvidence"),
    "LevelSetMeshAdaptation": ("._level_set", "LevelSetMeshAdaptation"),
    "LocalMetricEvidence": ("._local_metric", "LocalMetricEvidence"),
    "ManifoldProvider": (".providers", "ManifoldProvider"),
    "MappedReferenceAssociationTransfer": (
        "._association",
        "MappedReferenceAssociationTransfer",
    ),
    "MarkedMeshAdaptation": ("._adaptation", "MarkedMeshAdaptation"),
    "MeasuredAdaptationCost": ("._decision", "MeasuredAdaptationCost"),
    "MeshAdaptationPolicy": ("._adaptation", "MeshAdaptationPolicy"),
    "MeshAdaptationResult": ("._adaptation", "MeshAdaptationResult"),
    "MeshAdaptationRoute": ("._adaptation", "MeshAdaptationRoute"),
    "MeshAdaptationStatus": ("._adaptation", "MeshAdaptationStatus"),
    "MeshAssembly": ("._assembly", "MeshAssembly"),
    "MeshAttribute": ("._organization", "MeshAttribute"),
    "MeshAttributeRole": ("._organization", "MeshAttributeRole"),
    "MeshCarrier": ("._assembly", "MeshCarrier"),
    "MeshCarrierKind": ("._assembly", "MeshCarrierKind"),
    "MeshCertificationCheck": ("._certification", "MeshCertificationCheck"),
    "MeshCertificationInputs": ("._certification_inputs", "MeshCertificationInputs"),
    "MeshCertificationOutcome": ("._certification", "MeshCertificationOutcome"),
    "MeshCertificationPreparedEvidence": (
        "._certification",
        "MeshCertificationPreparedEvidence",
    ),
    "MeshCertificationReport": ("._certification", "MeshCertificationReport"),
    "MeshCertificationRoute": ("._certification", "MeshCertificationRoute"),
    "MeshCertificationSchedule": ("._certification", "MeshCertificationSchedule"),
    "MeshCoordinateProposal": ("._proposals", "MeshCoordinateProposal"),
    "MeshCoupling": ("._coupling", "MeshCoupling"),
    "MeshCouplingKind": ("._coupling", "MeshCouplingKind"),
    "MeshDistribution": ("._distribution", "MeshDistribution"),
    "MeshDistributionTransition": ("._distribution", "MeshDistributionTransition"),
    "MeshFileCarrier": (".._mesh_file_profiles", "MeshCarrier"),
    "MeshFileProfile": (".._mesh_file_profiles", "MeshFileProfile"),
    "MeshInterfaceAttachment": ("._interface_binding", "MeshInterfaceAttachment"),
    "MeshInteropPolicy": ("._interop", "MeshInteropPolicy"),
    "MeshLabel": ("._organization", "MeshLabel"),
    "MeshLineage": ("._lineage", "MeshLineage"),
    "MeshMarkingProposal": ("._proposals", "MeshMarkingProposal"),
    "MeshMetricField": ("._metric", "MeshMetricField"),
    "MeshMetricProposal": ("._proposals", "MeshMetricProposal"),
    "MeshMetricSamples": ("._metric", "MeshMetricSamples"),
    "MeshMotionAdvance": ("._motion", "MeshMotionAdvance"),
    "MeshMotionAssessment": ("._motion", "MeshMotionAssessment"),
    "MeshMotionDecision": ("._motion", "MeshMotionDecision"),
    "MeshMotionMonitor": ("._motion", "MeshMotionMonitor"),
    "MeshMotionMonitorPolicy": ("._motion", "MeshMotionMonitorPolicy"),
    "MeshOptimizationResult": ("._optimization", "MeshOptimizationResult"),
    "MeshOptimizationStatus": ("._optimization", "MeshOptimizationStatus"),
    "MeshPart": ("._assembly", "MeshPart"),
    "MeshPartitionEvidence": ("._distribution", "MeshPartitionEvidence"),
    "MeshPartitionKind": ("._distribution", "MeshPartitionKind"),
    "MeshPartitionPolicy": ("._distribution", "MeshPartitionPolicy"),
    "MeshPatch": ("._organization", "MeshPatch"),
    "MeshProposal": ("._proposals", "MeshProposal"),
    "MeshProposalFeatures": ("._proposals", "MeshProposalFeatures"),
    "MeshProposalProjection": ("._proposals", "MeshProposalProjection"),
    "MeshProposalSafetyPolicy": ("._proposals", "MeshProposalSafetyPolicy"),
    "MeshProposalTransaction": ("._proposals", "MeshProposalTransaction"),
    "MeshQualityObjective": ("._optimization", "MeshQualityObjective"),
    "MeshQualityTarget": ("._contracts", "MeshQualityTarget"),
    "MeshSizeProposal": ("._proposals", "MeshSizeProposal"),
    "MeshTransitionKind": ("._lineage", "MeshTransitionKind"),
    "MeshUntanglingEvidence": ("._optimization", "MeshUntanglingEvidence"),
    "MeshUntanglingPolicy": ("._optimization", "MeshUntanglingPolicy"),
    "MeshZone": ("._organization", "MeshZone"),
    "MeshZoneRole": ("._organization", "MeshZoneRole"),
    "MeshingCapability": ("._contracts", "MeshingCapability"),
    "MeshingComplianceReport": ("._result", "MeshingComplianceReport"),
    "MeshingDerivativeMode": ("._contracts", "MeshingDerivativeMode"),
    "MeshingDiagnostic": ("._trace", "MeshingDiagnostic"),
    "MeshingDiagnosticSeverity": ("._trace", "MeshingDiagnosticSeverity"),
    "MeshingEntityKind": ("._scope", "MeshingEntityKind"),
    "MeshingEvidenceBinding": ("._trace", "MeshingEvidenceBinding"),
    "MeshingExecutionMode": ("._contracts", "MeshingExecutionMode"),
    "MeshingExecutionPolicy": ("._session", "MeshingExecutionPolicy"),
    "MeshingFailure": ("._contracts", "MeshingFailure"),
    "MeshingFailureCategory": ("._contracts", "MeshingFailureCategory"),
    "MeshingFailureEvidence": ("._contracts", "MeshingFailureEvidence"),
    "MeshingLimits": ("._contracts", "MeshingLimits"),
    "MeshingOperation": ("._contracts", "MeshingOperation"),
    "MeshingProviderInfo": ("._contracts", "MeshingProviderInfo"),
    "MeshingRuntimeInfo": ("._result", "MeshingRuntimeInfo"),
    "MeshingScope": ("._scope", "MeshingScope"),
    "MeshingSourceDescriptor": ("._contracts", "MeshingSourceDescriptor"),
    "MeshingSourceKind": ("._contracts", "MeshingSourceKind"),
    "MeshingStageKind": ("._trace", "MeshingStageKind"),
    "MeshingStageReport": ("._trace", "MeshingStageReport"),
    "MeshingStageStatus": ("._trace", "MeshingStageStatus"),
    "MeshingTrace": ("._trace", "MeshingTrace"),
    "MetisPartitionError": ("._metis", "MetisPartitionError"),
    "MetisUnavailableError": ("._metis", "MetisUnavailableError"),
    "MetricCombinationEvidence": ("._metric", "MetricCombinationEvidence"),
    "MetricCombinationResult": ("._metric", "MetricCombinationResult"),
    "MetricComplexityStatus": ("._metric", "MetricComplexityStatus"),
    "MetricGradationError": ("._metric", "MetricGradationError"),
    "MetricGradationEvidence": ("._metric", "MetricGradationEvidence"),
    "MetricGradationKind": ("._metric", "MetricGradationKind"),
    "MetricGradationPolicy": ("._metric", "MetricGradationPolicy"),
    "MetricGradationStatus": ("._metric", "MetricGradationStatus"),
    "MetricMeshAdaptation": ("._adaptation", "MetricMeshAdaptation"),
    "MetricNormalizationEvidence": ("._metric", "MetricNormalizationEvidence"),
    "MetricNormalizationPolicy": ("._metric", "MetricNormalizationPolicy"),
    "MixedAdaptationHierarchy": ("._mixed_adaptation", "MixedAdaptationHierarchy"),
    "MixedLayerColumns": ("._mixed_adaptation", "MixedLayerColumns"),
    "MmgAdaptationPlan": (".providers", "MmgAdaptationPlan"),
    "MmgAdaptationResult": (".providers", "MmgAdaptationResult"),
    "MmgFieldTransfer": (".providers", "MmgFieldTransfer"),
    "MmgLagrangianMode": (".providers", "MmgLagrangianMode"),
    "MmgLagrangianMotion": (".providers", "MmgLagrangianMotion"),
    "MmgLevelSet": (".providers", "MmgLevelSet"),
    "MmgOptions": (".providers", "MmgOptions"),
    "MmgProvider": (".providers", "MmgProvider"),
    "MmgReference": (".providers", "MmgReference"),
    "MmgReferenceRetention": (".providers", "MmgReferenceRetention"),
    "MmgSessionEvidence": (".providers", "MmgSessionEvidence"),
    "MultiblockConstruction": ("._multiblock", "MultiblockConstruction"),
    "NativeCurveSchedule": (".providers", "NativeCurveSchedule"),
    "NativeCurveSource": (".providers", "NativeCurveSource"),
    "NativeHexGridRoute": ("._hex_generation", "NativeHexGridRoute"),
    "NativeHexGridSchedule": ("._hex_generation", "NativeHexGridSchedule"),
    "NativeImplicitSource": (".providers", "NativeImplicitSource"),
    "NativeLayerCoreSource": (".providers", "NativeLayerCoreSource"),
    "NativeMappedHexSource": (".providers", "NativeMappedHexSource"),
    "NativeMeshingOptions": (".providers", "NativeMeshingOptions"),
    "NativeMeshingPhase": ("._measurements", "NativeMeshingPhase"),
    "NativeMeshingPhaseMeasurement": ("._measurements", "NativeMeshingPhaseMeasurement"),
    "NativeMeshingPhaseRecorder": ("._measurements", "NativeMeshingPhaseRecorder"),
    "NativeMeshingPlan": (".providers", "NativeMeshingPlan"),
    "NativeMeshingProvider": (".providers", "NativeMeshingProvider"),
    "NativeMeshingRoute": (".providers", "NativeMeshingRoute"),
    "NativeMeshingSource": (".providers", "NativeMeshingSource"),
    "NativePeriodicSource": (".providers", "NativePeriodicSource"),
    "NativePlanarSource": (".providers", "NativePlanarSource"),
    "NativePlcSource": (".providers", "NativePlcSource"),
    "NativePolyhedralSchedule": (".providers", "NativePolyhedralSchedule"),
    "NativePolyhedralSource": (".providers", "NativePolyhedralSource"),
    "NativeStructuredSchedule": (".providers", "NativeStructuredSchedule"),
    "NativeStructuredSource": (".providers", "NativeStructuredSource"),
    "NativeSurfaceEnvelopeSource": (".providers", "NativeSurfaceEnvelopeSource"),
    "NativeSurfaceSchedule": (".providers", "NativeSurfaceSchedule"),
    "NativeSurfaceSource": (".providers", "NativeSurfaceSource"),
    "NativeSweepSource": (".providers", "NativeSweepSource"),
    "NativeVolumeSchedule": ("._volume_generation", "NativeVolumeSchedule"),
    "OmegaHAdaptationEvidence": (".providers", "OmegaHAdaptationEvidence"),
    "OmegaHAdaptationResult": (".providers", "OmegaHAdaptationResult"),
    "OmegaHClassification": (".providers", "OmegaHClassification"),
    "OmegaHField": (".providers", "OmegaHField"),
    "OmegaHFieldEvidence": (".providers", "OmegaHFieldEvidence"),
    "OmegaHFieldTransfer": (".providers", "OmegaHFieldTransfer"),
    "OmegaHOptions": (".providers", "OmegaHOptions"),
    "OmegaHPartition": (".providers", "OmegaHPartition"),
    "OmegaHProvider": (".providers", "OmegaHProvider"),
    "OmegaHTransferredField": (".providers", "OmegaHTransferredField"),
    "OpenVDBLevelSetRebuild": (".providers", "OpenVDBLevelSetRebuild"),
    "OpenVDBMeshingSpec": (".providers", "OpenVDBMeshingSpec"),
    "OpenVDBProvider": (".providers", "OpenVDBProvider"),
    "OrientedPointCloud": (".providers", "OrientedPointCloud"),
    "OversetCellStatus": ("._overset", "OversetCellStatus"),
    "OversetConnectivity": ("._overset", "OversetConnectivity"),
    "OversetConnectivityError": ("._overset", "OversetConnectivityError"),
    "OversetCoupling": ("._coupling", "OversetCoupling"),
    "OversetDonorPacket": ("._overset", "OversetDonorPacket"),
    "OversetPartBlanking": ("._overset", "OversetPartBlanking"),
    "OversetPartSpec": ("._overset", "OversetPartSpec"),
    "OversetPolicy": ("._overset", "OversetPolicy"),
    "OversetReceptorEvidence": ("._overset", "OversetReceptorEvidence"),
    "OversetRegistration": ("._overset", "OversetRegistration"),
    "OversetVertexStatus": ("._overset", "OversetVertexStatus"),
    "PartitionedAdaptiveSimplex": ("._device_adaptation", "PartitionedAdaptiveSimplex"),
    "PatchControl": ("._controls", "PatchControl"),
    "PeriodicAssociationTransfer": (
        ".providers._native_periodic",
        "PeriodicAssociationTransfer",
    ),
    "PeriodicConstraint": ("._controls", "PeriodicConstraint"),
    "PeriodicCoupling": ("._coupling", "PeriodicCoupling"),
    "PeriodicMeshConstruction": ("._periodic", "PeriodicMeshConstruction"),
    "PeriodicPointOrbits": ("._periodic", "PeriodicPointOrbits"),
    "PeriodicQuotientEvidence": ("._periodic", "PeriodicQuotientEvidence"),
    "PeriodicRefinement": ("._periodic", "PeriodicRefinement"),
    "PhysicalErrorEvidence": ("._decision", "PhysicalErrorEvidence"),
    "PiecewiseLinearComplex": ("._volume_generation", "PiecewiseLinearComplex"),
    "PlanarBandControl": ("._planar_bands", "PlanarBandControl"),
    "PlanarBandPlan": ("._planar_bands", "PlanarBandPlan"),
    "PlanarBandResult": ("._planar_bands", "PlanarBandResult"),
    "PoissonBoundaryCondition": (".providers", "PoissonBoundaryCondition"),
    "PoissonProvider": (".providers", "PoissonProvider"),
    "PoissonReconstructionSpec": (".providers", "PoissonReconstructionSpec"),
    "PolyhedralAdaptationOperation": (
        "._polyhedral_adaptation",
        "PolyhedralAdaptationOperation",
    ),
    "PolyhedralMeshAdaptation": ("._polyhedral_adaptation", "PolyhedralMeshAdaptation"),
    "PreparedAdaptiveSimplex": ("._device_adaptation", "PreparedAdaptiveSimplex"),
    "PreparedDeviceGeneration": ("._device_generation", "PreparedDeviceGeneration"),
    "PreparedDeviceMetricAdaptation": (
        "._device_metric",
        "PreparedDeviceMetricAdaptation",
    ),
    "PreparedDistributedSurfaceGeneration": (
        "._distributed_generation",
        "PreparedDistributedSurfaceGeneration",
    ),
    "PreparedMeshAdaptation": ("._adaptation", "PreparedMeshAdaptation"),
    "PreparedOversetFieldTransfer": ("._overset", "PreparedOversetFieldTransfer"),
    "PreparedOversetMotion": ("._overset", "PreparedOversetMotion"),
    "ProtectedFeature": ("._controls", "ProtectedFeature"),
    "ProviderSupportReport": ("._contracts", "ProviderSupportReport"),
    "ProximitySizeControl": ("._sizing", "ProximitySizeControl"),
    "RegionBoundaryEvidence": ("._organization", "RegionBoundaryEvidence"),
    "RegionControl": ("._controls", "RegionControl"),
    "RegionMeshingEvidence": ("._organization", "RegionMeshingEvidence"),
    "RegionRole": ("._organization", "RegionRole"),
    "RegionSeed": ("._controls", "RegionSeed"),
    "RelocationMeshAdaptation": ("._adaptation", "RelocationMeshAdaptation"),
    "ResolvedSizeField": ("._sizing", "ResolvedSizeField"),
    "RouteFeasibility": ("._decision", "RouteFeasibility"),
    "ScopeResolutionReport": ("._scope", "ScopeResolutionReport"),
    "SizeCombinationPolicy": ("._sizing", "SizeCombinationPolicy"),
    "SizeCompliancePolicy": ("._sizing", "SizeCompliancePolicy"),
    "SizeControl": ("._sizing", "SizeControl"),
    "SizeControlStrength": ("._sizing", "SizeControlStrength"),
    "SizeFieldDomain": ("._sizing", "SizeFieldDomain"),
    "SizeResolutionReport": ("._sizing", "SizeResolutionReport"),
    "SolverAwareCandidate": ("._decision", "SolverAwareCandidate"),
    "SolverAwareDecision": ("._decision", "SolverAwareDecision"),
    "SourceProximityGapEvidence": ("._sizing", "SourceProximityGapEvidence"),
    "StructuredConstruction": ("._structured", "StructuredConstruction"),
    "SurfaceMeshingSpec": ("._contracts", "SurfaceMeshingSpec"),
    "SurfaceReconstructionControl": ("._controls", "SurfaceReconstructionControl"),
    "SurfaceRemeshingSpec": ("._contracts", "SurfaceRemeshingSpec"),
    "SweepConstruction": ("._sweep", "SweepConstruction"),
    "SweepControl": ("._sweep", "SweepControl"),
    "SweepMapKind": ("._sweep", "SweepMapKind"),
    "TargetMatrixOptimizationPlan": ("._optimization", "TargetMatrixOptimizationPlan"),
    "TiogaAssemblyResult": (".providers", "TiogaAssemblyResult"),
    "TiogaDonorEvidence": (".providers", "TiogaDonorEvidence"),
    "TiogaOptions": (".providers", "TiogaOptions"),
    "TiogaPartBlanking": (".providers", "TiogaPartBlanking"),
    "TiogaProvider": (".providers", "TiogaProvider"),
    "TiogaRegistration": (".providers", "TiogaRegistration"),
    "TransfiniteBlock": ("._structured", "TransfiniteBlock"),
    "TransfiniteCurveControl": ("._controls", "TransfiniteCurveControl"),
    "TransfiniteSurfaceControl": ("._controls", "TransfiniteSurfaceControl"),
    "UniformSizeControl": ("._sizing", "UniformSizeControl"),
    "VertexInterpolationStencil": ("._lineage", "VertexInterpolationStencil"),
    "VolumeFillStrategy": ("._contracts", "VolumeFillStrategy"),
    "VolumeMeshingSpec": ("._contracts", "VolumeMeshingSpec"),
    "VoroCrustOptions": (".providers", "VoroCrustOptions"),
    "VoroCrustProvider": (".providers", "VoroCrustProvider"),
    "acceptance_stage_report": ("._certification", "acceptance_stage_report"),
    "adapt_device_metric": ("._device_metric", "adapt_device_metric"),
    "adapt_device_tetra_metric": ("._device_tetra_metric", "adapt_device_tetra_metric"),
    "advance_mesh_motion": ("._motion", "advance_mesh_motion"),
    "assemble_independent_blocks": ("._multiblock", "assemble_independent_blocks"),
    "associate_mesh_entities": ("._association", "associate_mesh_entities"),
    "associate_mesh_vertices": ("._association", "associate_mesh_vertices"),
    "audit_cell_mesh": ("._audit", "audit_cell_mesh"),
    "canonicalize_cell_mesh": ("._canonical", "canonicalize_cell_mesh"),
    "certify_cell_mesh": ("._canonical", "certify_cell_mesh"),
    "certify_meshing_acceptance": ("._certification", "certify_meshing_acceptance"),
    "combine_mesh_metrics": ("._metric", "combine_mesh_metrics"),
    "commit_adaptive_simplex": ("._device_adaptation", "commit_adaptive_simplex"),
    "commit_device_metric_adaptation": (
        "._device_metric",
        "commit_device_metric_adaptation",
    ),
    "commit_partitioned_adaptive_simplex": (
        "._device_adaptation",
        "commit_partitioned_adaptive_simplex",
    ),
    "curve_cell_mesh": ("._curving", "curve_cell_mesh"),
    "declared_plc_domain": ("._volume_generation", "declared_plc_domain"),
    "evaluate_cell_quality": ("._quality", "evaluate_cell_quality"),
    "evaluate_device_generation_candidates": (
        "._device_generation",
        "evaluate_device_generation_candidates",
    ),
    "evaluate_finite_volume_quality": ("._quality", "evaluate_finite_volume_quality"),
    "execute_device_generation_round": (
        "._device_generation",
        "execute_device_generation_round",
    ),
    "execute_mesh_adaptation": ("._adaptation", "execute_mesh_adaptation"),
    "export_cell_mesh": ("._interop", "export_cell_mesh"),
    "export_mesh_array_artifact": ("._interop", "export_mesh_array_artifact"),
    "generate_structured_block": ("._structured", "generate_structured_block"),
    "generate_sweep": ("._sweep", "generate_sweep"),
    "glue_structured_blocks": ("._multiblock", "glue_structured_blocks"),
    "grade_mesh_metric": ("._metric", "grade_mesh_metric"),
    "import_cell_mesh": ("._interop", "import_cell_mesh"),
    "interpolate_mesh_metric": ("._metric", "interpolate_mesh_metric"),
    "lp_metric_from_hessian": ("._metric", "lp_metric_from_hessian"),
    "mesh_file_profiles": (".._mesh_file_profiles", "mesh_file_profiles"),
    "mesh_proposal_scope": ("._proposals", "mesh_proposal_scope"),
    "metric_edge_lengths": ("._metric", "metric_edge_lengths"),
    "metric_simplex_quality": ("._metric", "metric_simplex_quality"),
    "normalize_mesh_metric": ("._metric", "normalize_mesh_metric"),
    "optimize_cell_geometry_coordinates": (
        "._optimization",
        "optimize_cell_geometry_coordinates",
    ),
    "optimize_cell_mesh": ("._optimization", "optimize_cell_mesh"),
    "partition_adaptive_simplex": ("._device_adaptation", "partition_adaptive_simplex"),
    "periodic_cell_from_constraints": ("._periodic", "periodic_cell_from_constraints"),
    "periodic_delaunay_mesh": ("._periodic", "periodic_delaunay_mesh"),
    "prepare_adaptive_simplex": ("._device_adaptation", "prepare_adaptive_simplex"),
    "prepare_boundary_layer_extrusion": (
        "._layer_extrusion",
        "prepare_boundary_layer_extrusion",
    ),
    "prepare_boundary_layers": ("._boundary_layer", "prepare_boundary_layers"),
    "prepare_device_generation": ("._device_generation", "prepare_device_generation"),
    "prepare_device_metric_adaptation": (
        "._device_metric",
        "prepare_device_metric_adaptation",
    ),
    "prepare_device_tetra_metric": (
        "._device_tetra_metric",
        "prepare_device_tetra_metric",
    ),
    "prepare_distributed_surface_generation": (
        "._distributed_generation",
        "prepare_distributed_surface_generation",
    ),
    "prepare_distribution_transition": (
        "._distribution",
        "prepare_distribution_transition",
    ),
    "prepare_mesh_adaptation": ("._adaptation", "prepare_mesh_adaptation"),
    "prepare_mesh_distribution": ("._distribution", "prepare_mesh_distribution"),
    "prepare_mesh_proposal": ("._proposals", "prepare_mesh_proposal"),
    "prepare_native_layer_association_transfer": (
        "._layer_core_association",
        "prepare_native_layer_association_transfer",
    ),
    "prepare_overset_connectivity": ("._overset", "prepare_overset_connectivity"),
    "prepare_overset_conservative_remap": (
        "._overset",
        "prepare_overset_conservative_remap",
    ),
    "prepare_overset_conservative_state_transport": (
        "._overset",
        "prepare_overset_conservative_state_transport",
    ),
    "prepare_overset_field_transfer": ("._overset", "prepare_overset_field_transfer"),
    "prepare_overset_motion_rebind": ("._overset", "prepare_overset_motion_rebind"),
    "prepare_planar_bands": ("._planar_bands", "prepare_planar_bands"),
    "project_hp_lineage": ("._adaptation", "project_hp_lineage"),
    "project_mesh_proposal": ("._proposals", "project_mesh_proposal"),
    "propagate_association": ("._association", "propagate_association"),
    "providers": (".providers", None),
    "publish_periodic_simplices": ("._periodic", "publish_periodic_simplices"),
    "read_mesh_array_artifact": ("._interop", "read_mesh_array_artifact"),
    "rederive_association": ("._association", "rederive_association"),
    "refine_periodic_mesh": ("._periodic", "refine_periodic_mesh"),
    "resolve_mesh_file_profile": (".._mesh_file_profiles", "resolve_mesh_file_profile"),
    "resolve_mesh_scope": ("._scope", "resolve_mesh_scope"),
    "resolve_size_controls": ("._sizing", "resolve_size_controls"),
    "size_field_metric": ("._sizing", "size_field_metric"),
    "summarize_cell_quality": ("._quality", "summarize_cell_quality"),
    "transition_interface_attachment": (
        "._interface_binding",
        "transition_interface_attachment",
    ),
    "validate_mesh_labels": ("._organization", "validate_mesh_labels"),
    "validate_mesh_zones": ("._organization", "validate_mesh_zones"),
    "verify_curved_geometry": ("._curving", "verify_curved_geometry"),
}


if TYPE_CHECKING:
    from .._mesh_file_profiles import (
        mesh_file_profiles,
        MeshCarrier as MeshFileCarrier,
        MeshFileProfile,
        resolve_mesh_file_profile,
    )
    from . import providers
    from ._adaptation import (
        execute_mesh_adaptation,
        GeometryRealizationMeshAdaptation,
        MarkedMeshAdaptation,
        MeshAdaptationPolicy,
        MeshAdaptationResult,
        MeshAdaptationRoute,
        MeshAdaptationStatus,
        MetricMeshAdaptation,
        prepare_mesh_adaptation,
        PreparedMeshAdaptation,
        project_hp_lineage,
        RelocationMeshAdaptation,
    )
    from ._assembly import (
        MeshAssembly,
        MeshCarrier,
        MeshCarrierKind,
        MeshPart,
    )
    from ._association import (
        associate_mesh_entities,
        associate_mesh_vertices,
        AssociationPropagationError,
        AssociationPropagationPolicy,
        BRepAssociationTransfer,
        GeometryAssociation,
        GeometryAssociationKind,
        GeometryAssociationProvenance,
        GeometrySourceEntityRole,
        MappedReferenceAssociationTransfer,
        propagate_association,
        rederive_association,
    )
    from ._association_composition import (
        ComposedAssociationTransfer,
    )
    from ._audit import (
        audit_cell_mesh,
        CellMeshAuditDisposition,
        CellMeshAuditPolicy,
        CellMeshAuditReport,
    )
    from ._bisection import (
        BisectionCompatibility,
        BisectionEvidence,
        BisectionHierarchy,
        BisectionUniformRefinement,
    )
    from ._boundary_layer import (
        BoundaryLayerEvidence,
        BoundaryLayerMesh,
        BoundaryLayerPolicy,
        prepare_boundary_layers,
    )
    from ._canonical import (
        canonicalize_cell_mesh,
        certify_cell_mesh,
    )
    from ._certification import (
        acceptance_stage_report,
        certify_meshing_acceptance,
        MeshCertificationCheck,
        MeshCertificationOutcome,
        MeshCertificationPreparedEvidence,
        MeshCertificationReport,
        MeshCertificationRoute,
        MeshCertificationSchedule,
    )
    from ._certification_inputs import (
        MeshCertificationInputs,
    )
    from ._contracts import (
        CellFamilyPolicy,
        CellMeshingTarget,
        CurveEnd,
        CurveJunction,
        CurveMeshingSpec,
        MeshingCapability,
        MeshingDerivativeMode,
        MeshingExecutionMode,
        MeshingFailure,
        MeshingFailureCategory,
        MeshingFailureEvidence,
        MeshingLimits,
        MeshingOperation,
        MeshingProviderInfo,
        MeshingSourceDescriptor,
        MeshingSourceKind,
        MeshQualityTarget,
        ProviderSupportReport,
        SurfaceMeshingSpec,
        SurfaceRemeshingSpec,
        VolumeFillStrategy,
        VolumeMeshingSpec,
    )
    from ._controls import (
        BackgroundMetricControl,
        BackgroundMetricMode,
        BlockInterfaceControl,
        BoundaryLayerCollisionPolicy,
        BoundaryLayerControl,
        BoundaryLayerCornerPolicy,
        BoundaryLayerRoute,
        FeatureKind,
        HoleSeed,
        LayerSchedule,
        PatchControl,
        PeriodicConstraint,
        ProtectedFeature,
        RegionControl,
        RegionSeed,
        SurfaceReconstructionControl,
        TransfiniteCurveControl,
        TransfiniteSurfaceControl,
    )
    from ._coupling import (
        ConformalCoupling,
        ContactCoupling,
        CouplingSearchError,
        CouplingSearchEvidence,
        CouplingSearchStatus,
        MeshCoupling,
        MeshCouplingKind,
        OversetCoupling,
        PeriodicCoupling,
    )
    from ._curving import (
        curve_cell_mesh,
        CurvedGeometryEvidence,
        HighOrderCurvingPolicy,
        HighOrderCurvingResult,
        HighOrderCurvingStatus,
        verify_curved_geometry,
    )
    from ._decision import (
        AdaptationAction,
        DecisionBudget,
        ErrorQuantity,
        FixedEpochDerivativeEvidence,
        MeasuredAdaptationCost,
        PhysicalErrorEvidence,
        RouteFeasibility,
        SolverAwareCandidate,
        SolverAwareDecision,
    )
    from ._device_adaptation import (
        commit_adaptive_simplex,
        commit_partitioned_adaptive_simplex,
        partition_adaptive_simplex,
        PartitionedAdaptiveSimplex,
        prepare_adaptive_simplex,
        PreparedAdaptiveSimplex,
    )
    from ._device_generation import (
        DeviceGenerationCandidates,
        DeviceGenerationEvidence,
        DeviceGenerationLayout,
        DeviceGenerationStatus,
        DeviceGenerationUpdate,
        evaluate_device_generation_candidates,
        execute_device_generation_round,
        prepare_device_generation,
        PreparedDeviceGeneration,
    )
    from ._device_metric import (
        adapt_device_metric,
        commit_device_metric_adaptation,
        DeviceMetricEvidence,
        DeviceMetricLayout,
        DeviceMetricReport,
        DeviceMetricState,
        DeviceMetricUpdate,
        prepare_device_metric_adaptation,
        PreparedDeviceMetricAdaptation,
    )
    from ._device_tetra_metric import (
        adapt_device_tetra_metric,
        DeviceTetraMetricEvidence,
        DeviceTetraMetricLayout,
        DeviceTetraMetricReport,
        DeviceTetraMetricState,
        DeviceTetraMetricUpdate,
        prepare_device_tetra_metric,
    )
    from ._distributed_generation import (
        prepare_distributed_surface_generation,
        PreparedDistributedSurfaceGeneration,
    )
    from ._distribution import (
        MeshDistribution,
        MeshDistributionTransition,
        MeshPartitionEvidence,
        MeshPartitionKind,
        MeshPartitionPolicy,
        prepare_distribution_transition,
        prepare_mesh_distribution,
    )
    from ._hex_generation import (
        NativeHexGridRoute,
        NativeHexGridSchedule,
    )
    from ._implicit_association_transfer import (
        ImplicitAssociationTransfer,
    )
    from ._interface_binding import (
        MeshInterfaceAttachment,
        transition_interface_attachment,
    )
    from ._interop import (
        CellMeshExportResult,
        CellMeshImportResult,
        export_cell_mesh,
        export_mesh_array_artifact,
        import_cell_mesh,
        MeshInteropPolicy,
        read_mesh_array_artifact,
    )
    from ._layer_core_association import (
        prepare_native_layer_association_transfer,
    )
    from ._layer_extrusion import (
        BoundaryLayerExtrusion,
        prepare_boundary_layer_extrusion,
    )
    from ._level_set import (
        LevelSetEvidence,
        LevelSetMeshAdaptation,
    )
    from ._lineage import (
        CellMeshTransition,
        EntityLineage,
        EntityLineageKind,
        MeshLineage,
        MeshTransitionKind,
        VertexInterpolationStencil,
    )
    from ._local_metric import (
        LocalMetricEvidence,
    )
    from ._measurements import (
        NativeMeshingPhase,
        NativeMeshingPhaseMeasurement,
        NativeMeshingPhaseRecorder,
    )
    from ._metis import (
        MetisPartitionError,
        MetisUnavailableError,
    )
    from ._metric import (
        combine_mesh_metrics,
        grade_mesh_metric,
        HessianMetricEvidence,
        interpolate_mesh_metric,
        lp_metric_from_hessian,
        MeshMetricField,
        MeshMetricSamples,
        metric_edge_lengths,
        metric_simplex_quality,
        MetricCombinationEvidence,
        MetricCombinationResult,
        MetricComplexityStatus,
        MetricGradationError,
        MetricGradationEvidence,
        MetricGradationKind,
        MetricGradationPolicy,
        MetricGradationStatus,
        MetricNormalizationEvidence,
        MetricNormalizationPolicy,
        normalize_mesh_metric,
    )
    from ._mixed_adaptation import (
        MixedAdaptationHierarchy,
        MixedLayerColumns,
    )
    from ._motion import (
        advance_mesh_motion,
        MeshMotionAdvance,
        MeshMotionAssessment,
        MeshMotionDecision,
        MeshMotionMonitor,
        MeshMotionMonitorPolicy,
    )
    from ._multiblock import (
        assemble_independent_blocks,
        glue_structured_blocks,
        MultiblockConstruction,
    )
    from ._optimization import (
        CellGeometryOptimizationResult,
        MeshOptimizationResult,
        MeshOptimizationStatus,
        MeshQualityObjective,
        MeshUntanglingEvidence,
        MeshUntanglingPolicy,
        optimize_cell_geometry_coordinates,
        optimize_cell_mesh,
        TargetMatrixOptimizationPlan,
    )
    from ._organization import (
        MeshAttribute,
        MeshAttributeRole,
        MeshLabel,
        MeshPatch,
        MeshZone,
        MeshZoneRole,
        RegionBoundaryEvidence,
        RegionMeshingEvidence,
        RegionRole,
        validate_mesh_labels,
        validate_mesh_zones,
    )
    from ._overset import (
        OversetCellStatus,
        OversetConnectivity,
        OversetConnectivityError,
        OversetDonorPacket,
        OversetPartBlanking,
        OversetPartSpec,
        OversetPolicy,
        OversetReceptorEvidence,
        OversetRegistration,
        OversetVertexStatus,
        prepare_overset_connectivity,
        prepare_overset_conservative_remap,
        prepare_overset_conservative_state_transport,
        prepare_overset_field_transfer,
        prepare_overset_motion_rebind,
        PreparedOversetFieldTransfer,
        PreparedOversetMotion,
    )
    from ._periodic import (
        periodic_cell_from_constraints,
        periodic_delaunay_mesh,
        PeriodicMeshConstruction,
        PeriodicPointOrbits,
        PeriodicQuotientEvidence,
        PeriodicRefinement,
        publish_periodic_simplices,
        refine_periodic_mesh,
    )
    from ._planar_bands import (
        PlanarBandControl,
        PlanarBandPlan,
        PlanarBandResult,
        prepare_planar_bands,
    )
    from ._polyhedral_adaptation import (
        PolyhedralAdaptationOperation,
        PolyhedralMeshAdaptation,
    )
    from ._proposals import (
        AbstractMeshProposer,
        LearnedMeshProposer,
        mesh_proposal_scope,
        MeshCoordinateProposal,
        MeshMarkingProposal,
        MeshMetricProposal,
        MeshProposal,
        MeshProposalFeatures,
        MeshProposalProjection,
        MeshProposalSafetyPolicy,
        MeshProposalTransaction,
        MeshSizeProposal,
        prepare_mesh_proposal,
        project_mesh_proposal,
    )
    from ._quality import (
        CellQualityEvaluation,
        CellQualityReport,
        evaluate_cell_quality,
        evaluate_finite_volume_quality,
        FiniteVolumeQualityEvaluation,
        summarize_cell_quality,
    )
    from ._result import (
        CellMeshingResult,
        MeshingComplianceReport,
        MeshingRuntimeInfo,
    )
    from ._scope import (
        MeshingEntityKind,
        MeshingScope,
        resolve_mesh_scope,
        ScopeResolutionReport,
    )
    from ._session import (
        AbstractMeshingSession,
        MeshingExecutionPolicy,
    )
    from ._sizing import (
        CurvatureSizeControl,
        ProximitySizeControl,
        resolve_size_controls,
        ResolvedSizeField,
        size_field_metric,
        SizeCombinationPolicy,
        SizeCompliancePolicy,
        SizeControl,
        SizeControlStrength,
        SizeFieldDomain,
        SizeResolutionReport,
        SourceProximityGapEvidence,
        UniformSizeControl,
    )
    from ._structured import (
        generate_structured_block,
        StructuredConstruction,
        TransfiniteBlock,
    )
    from ._sweep import (
        generate_sweep,
        SweepConstruction,
        SweepControl,
        SweepMapKind,
    )
    from ._trace import (
        MeshingDiagnostic,
        MeshingDiagnosticSeverity,
        MeshingEvidenceBinding,
        MeshingStageKind,
        MeshingStageReport,
        MeshingStageStatus,
        MeshingTrace,
    )
    from ._volume_generation import (
        declared_plc_domain,
        NativeVolumeSchedule,
        PiecewiseLinearComplex,
    )
    from .providers import (
        FTetWildMeshingPlan,
        FTetWildOptions,
        FTetWildProvider,
        GmshHighOrderOptimization,
        GmshMeshingPlan,
        GmshOptions,
        GmshProvider,
        GmshRemeshingPlan,
        GmshSession,
        GmshSurfaceAlgorithm,
        GmshVolumeAlgorithm,
        ManifoldProvider,
        MmgAdaptationPlan,
        MmgAdaptationResult,
        MmgFieldTransfer,
        MmgLagrangianMode,
        MmgLagrangianMotion,
        MmgLevelSet,
        MmgOptions,
        MmgProvider,
        MmgReference,
        MmgReferenceRetention,
        MmgSessionEvidence,
        NativeCurveSchedule,
        NativeCurveSource,
        NativeImplicitSource,
        NativeLayerCoreSource,
        NativeMappedHexSource,
        NativeMeshingOptions,
        NativeMeshingPlan,
        NativeMeshingProvider,
        NativeMeshingRoute,
        NativeMeshingSource,
        NativePeriodicSource,
        NativePlanarSource,
        NativePlcSource,
        NativePolyhedralSchedule,
        NativePolyhedralSource,
        NativeStructuredSchedule,
        NativeStructuredSource,
        NativeSurfaceEnvelopeSource,
        NativeSurfaceSchedule,
        NativeSurfaceSource,
        NativeSweepSource,
        OmegaHAdaptationEvidence,
        OmegaHAdaptationResult,
        OmegaHClassification,
        OmegaHField,
        OmegaHFieldEvidence,
        OmegaHFieldTransfer,
        OmegaHOptions,
        OmegaHPartition,
        OmegaHProvider,
        OmegaHTransferredField,
        OpenVDBLevelSetRebuild,
        OpenVDBMeshingSpec,
        OpenVDBProvider,
        OrientedPointCloud,
        PoissonBoundaryCondition,
        PoissonProvider,
        PoissonReconstructionSpec,
        TiogaAssemblyResult,
        TiogaDonorEvidence,
        TiogaOptions,
        TiogaPartBlanking,
        TiogaProvider,
        TiogaRegistration,
        VoroCrustOptions,
        VoroCrustProvider,
    )
    from .providers._native_periodic import (
        PeriodicAssociationTransfer,
    )


def __getattr__(name: str) -> Any:
    owner = _SYMBOL_MODULES.get(name)
    if owner is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, symbol = owner
    module = import_module(module_name, __package__)
    value = module if symbol is None else getattr(module, symbol)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "AbstractMeshProposer",
    "AbstractMeshingSession",
    "AdaptationAction",
    "AssociationPropagationError",
    "AssociationPropagationPolicy",
    "BRepAssociationTransfer",
    "ComposedAssociationTransfer",
    "ImplicitAssociationTransfer",
    "MappedReferenceAssociationTransfer",
    "BackgroundMetricControl",
    "BackgroundMetricMode",
    "BisectionCompatibility",
    "BisectionEvidence",
    "BisectionHierarchy",
    "BisectionUniformRefinement",
    "BlockInterfaceControl",
    "BoundaryLayerCollisionPolicy",
    "BoundaryLayerControl",
    "BoundaryLayerCornerPolicy",
    "BoundaryLayerEvidence",
    "BoundaryLayerExtrusion",
    "BoundaryLayerMesh",
    "BoundaryLayerPolicy",
    "BoundaryLayerRoute",
    "CellFamilyPolicy",
    "CellGeometryOptimizationResult",
    "CellMeshAuditDisposition",
    "CellMeshAuditPolicy",
    "CellMeshAuditReport",
    "CellMeshExportResult",
    "CellMeshImportResult",
    "CellMeshTransition",
    "CellMeshingResult",
    "CellMeshingTarget",
    "CellQualityEvaluation",
    "CellQualityReport",
    "ConformalCoupling",
    "ContactCoupling",
    "CouplingSearchError",
    "CouplingSearchEvidence",
    "CouplingSearchStatus",
    "CurvatureSizeControl",
    "CurveEnd",
    "CurveJunction",
    "CurveMeshingSpec",
    "CurvedGeometryEvidence",
    "DecisionBudget",
    "DeviceGenerationCandidates",
    "DeviceGenerationEvidence",
    "DeviceGenerationLayout",
    "DeviceGenerationStatus",
    "DeviceGenerationUpdate",
    "DeviceMetricEvidence",
    "DeviceMetricLayout",
    "DeviceMetricReport",
    "DeviceMetricState",
    "DeviceMetricUpdate",
    "DeviceTetraMetricEvidence",
    "DeviceTetraMetricLayout",
    "DeviceTetraMetricReport",
    "DeviceTetraMetricState",
    "DeviceTetraMetricUpdate",
    "EntityLineage",
    "EntityLineageKind",
    "ErrorQuantity",
    "FTetWildMeshingPlan",
    "FTetWildOptions",
    "FTetWildProvider",
    "FeatureKind",
    "FiniteVolumeQualityEvaluation",
    "FixedEpochDerivativeEvidence",
    "GeometryAssociation",
    "GeometryAssociationKind",
    "GeometryAssociationProvenance",
    "GeometrySourceEntityRole",
    "GeometryRealizationMeshAdaptation",
    "GmshHighOrderOptimization",
    "GmshMeshingPlan",
    "GmshOptions",
    "GmshProvider",
    "GmshRemeshingPlan",
    "GmshSession",
    "GmshSurfaceAlgorithm",
    "GmshVolumeAlgorithm",
    "HessianMetricEvidence",
    "HighOrderCurvingPolicy",
    "HighOrderCurvingResult",
    "HighOrderCurvingStatus",
    "HoleSeed",
    "LayerSchedule",
    "LearnedMeshProposer",
    "LevelSetEvidence",
    "LevelSetMeshAdaptation",
    "LocalMetricEvidence",
    "ManifoldProvider",
    "MeasuredAdaptationCost",
    "MarkedMeshAdaptation",
    "MeshAdaptationPolicy",
    "MeshAdaptationResult",
    "MeshAdaptationRoute",
    "MeshAdaptationStatus",
    "MeshAssembly",
    "MeshAttribute",
    "MeshAttributeRole",
    "MeshCarrier",
    "MeshCarrierKind",
    "MeshCertificationCheck",
    "MeshCertificationInputs",
    "MeshCertificationOutcome",
    "MeshCertificationPreparedEvidence",
    "MeshCertificationReport",
    "MeshCertificationRoute",
    "MeshCertificationSchedule",
    "MeshCoordinateProposal",
    "MeshCoupling",
    "MeshCouplingKind",
    "MeshDistribution",
    "MeshDistributionTransition",
    "MeshFileCarrier",
    "MeshFileProfile",
    "MeshInterfaceAttachment",
    "MeshInteropPolicy",
    "MeshLabel",
    "MeshLineage",
    "MeshMarkingProposal",
    "MeshMetricField",
    "MeshMetricProposal",
    "MeshMetricSamples",
    "MeshMotionAdvance",
    "MeshMotionAssessment",
    "MeshMotionDecision",
    "MeshMotionMonitor",
    "MeshMotionMonitorPolicy",
    "MeshOptimizationResult",
    "MeshOptimizationStatus",
    "MeshPart",
    "MeshPartitionEvidence",
    "MeshPartitionKind",
    "MeshPartitionPolicy",
    "MeshPatch",
    "MeshQualityTarget",
    "MeshProposal",
    "MeshProposalFeatures",
    "MeshProposalProjection",
    "MeshProposalSafetyPolicy",
    "MeshProposalTransaction",
    "MeshQualityObjective",
    "MeshSizeProposal",
    "MeshTransitionKind",
    "MeshUntanglingEvidence",
    "MeshUntanglingPolicy",
    "MeshZone",
    "MeshZoneRole",
    "MeshingCapability",
    "MeshingComplianceReport",
    "MeshingDerivativeMode",
    "MeshingDiagnostic",
    "MeshingDiagnosticSeverity",
    "MeshingEntityKind",
    "MeshingEvidenceBinding",
    "MeshingExecutionMode",
    "MeshingExecutionPolicy",
    "MeshingFailure",
    "MeshingFailureCategory",
    "MeshingFailureEvidence",
    "MeshingLimits",
    "MeshingOperation",
    "MeshingProviderInfo",
    "MeshingRuntimeInfo",
    "MeshingScope",
    "MeshingSourceDescriptor",
    "MeshingSourceKind",
    "MeshingStageKind",
    "MeshingStageReport",
    "MeshingStageStatus",
    "MeshingTrace",
    "MetisPartitionError",
    "MetisUnavailableError",
    "MetricCombinationEvidence",
    "MetricCombinationResult",
    "MetricComplexityStatus",
    "MetricGradationError",
    "MetricGradationEvidence",
    "MetricGradationKind",
    "MetricGradationPolicy",
    "MetricGradationStatus",
    "MetricMeshAdaptation",
    "MetricNormalizationEvidence",
    "MetricNormalizationPolicy",
    "MixedAdaptationHierarchy",
    "MixedLayerColumns",
    "MmgAdaptationPlan",
    "MmgAdaptationResult",
    "MmgFieldTransfer",
    "MmgLagrangianMode",
    "MmgLagrangianMotion",
    "MmgLevelSet",
    "MmgOptions",
    "MmgProvider",
    "MmgReference",
    "MmgReferenceRetention",
    "MmgSessionEvidence",
    "MultiblockConstruction",
    "NativeCurveSchedule",
    "NativeCurveSource",
    "NativeImplicitSource",
    "NativeLayerCoreSource",
    "NativeHexGridRoute",
    "NativeHexGridSchedule",
    "NativeMappedHexSource",
    "NativeMeshingOptions",
    "NativeMeshingPhase",
    "NativeMeshingPhaseMeasurement",
    "NativeMeshingPhaseRecorder",
    "NativeMeshingPlan",
    "NativeMeshingProvider",
    "NativeMeshingRoute",
    "NativeMeshingSource",
    "NativePeriodicSource",
    "NativePlanarSource",
    "NativePlcSource",
    "NativePolyhedralSchedule",
    "NativePolyhedralSource",
    "NativeStructuredSchedule",
    "NativeStructuredSource",
    "NativeSurfaceEnvelopeSource",
    "NativeSurfaceSchedule",
    "NativeSurfaceSource",
    "NativeSweepSource",
    "NativeVolumeSchedule",
    "OmegaHAdaptationEvidence",
    "OmegaHAdaptationResult",
    "OmegaHClassification",
    "OmegaHField",
    "OmegaHFieldEvidence",
    "OmegaHFieldTransfer",
    "OmegaHOptions",
    "OmegaHPartition",
    "OmegaHProvider",
    "OmegaHTransferredField",
    "OpenVDBLevelSetRebuild",
    "OpenVDBMeshingSpec",
    "OpenVDBProvider",
    "OrientedPointCloud",
    "OversetCoupling",
    "OversetCellStatus",
    "OversetConnectivity",
    "OversetConnectivityError",
    "OversetDonorPacket",
    "OversetPartBlanking",
    "OversetPartSpec",
    "OversetPolicy",
    "OversetReceptorEvidence",
    "OversetRegistration",
    "OversetVertexStatus",
    "PiecewiseLinearComplex",
    "PhysicalErrorEvidence",
    "PartitionedAdaptiveSimplex",
    "PatchControl",
    "PeriodicAssociationTransfer",
    "PeriodicConstraint",
    "PeriodicCoupling",
    "PeriodicMeshConstruction",
    "PeriodicPointOrbits",
    "PeriodicQuotientEvidence",
    "PeriodicRefinement",
    "periodic_cell_from_constraints",
    "periodic_delaunay_mesh",
    "publish_periodic_simplices",
    "refine_periodic_mesh",
    "PlanarBandControl",
    "PlanarBandPlan",
    "PlanarBandResult",
    "PoissonBoundaryCondition",
    "PoissonProvider",
    "PoissonReconstructionSpec",
    "PolyhedralAdaptationOperation",
    "PolyhedralMeshAdaptation",
    "PreparedAdaptiveSimplex",
    "PreparedDeviceGeneration",
    "PreparedDistributedSurfaceGeneration",
    "PreparedDeviceMetricAdaptation",
    "PreparedMeshAdaptation",
    "PreparedOversetFieldTransfer",
    "PreparedOversetMotion",
    "ProtectedFeature",
    "ProviderSupportReport",
    "ProximitySizeControl",
    "SourceProximityGapEvidence",
    "RegionControl",
    "RegionBoundaryEvidence",
    "RegionMeshingEvidence",
    "RegionRole",
    "RegionSeed",
    "RelocationMeshAdaptation",
    "ResolvedSizeField",
    "RouteFeasibility",
    "ScopeResolutionReport",
    "SizeCombinationPolicy",
    "SizeCompliancePolicy",
    "SizeControl",
    "SizeControlStrength",
    "SizeFieldDomain",
    "SizeResolutionReport",
    "SolverAwareCandidate",
    "SolverAwareDecision",
    "StructuredConstruction",
    "SurfaceMeshingSpec",
    "SurfaceReconstructionControl",
    "SurfaceRemeshingSpec",
    "SweepConstruction",
    "SweepControl",
    "SweepMapKind",
    "TargetMatrixOptimizationPlan",
    "TiogaAssemblyResult",
    "TiogaDonorEvidence",
    "TiogaOptions",
    "TiogaPartBlanking",
    "TiogaProvider",
    "TiogaRegistration",
    "TransfiniteBlock",
    "TransfiniteCurveControl",
    "TransfiniteSurfaceControl",
    "UniformSizeControl",
    "VertexInterpolationStencil",
    "VolumeFillStrategy",
    "VolumeMeshingSpec",
    "VoroCrustOptions",
    "VoroCrustProvider",
    "acceptance_stage_report",
    "assemble_independent_blocks",
    "adapt_device_metric",
    "adapt_device_tetra_metric",
    "advance_mesh_motion",
    "associate_mesh_entities",
    "associate_mesh_vertices",
    "audit_cell_mesh",
    "canonicalize_cell_mesh",
    "certify_cell_mesh",
    "certify_meshing_acceptance",
    "combine_mesh_metrics",
    "commit_adaptive_simplex",
    "commit_device_metric_adaptation",
    "commit_partitioned_adaptive_simplex",
    "curve_cell_mesh",
    "declared_plc_domain",
    "evaluate_cell_quality",
    "evaluate_device_generation_candidates",
    "evaluate_finite_volume_quality",
    "execute_device_generation_round",
    "execute_mesh_adaptation",
    "export_cell_mesh",
    "export_mesh_array_artifact",
    "generate_structured_block",
    "generate_sweep",
    "glue_structured_blocks",
    "grade_mesh_metric",
    "import_cell_mesh",
    "interpolate_mesh_metric",
    "lp_metric_from_hessian",
    "mesh_file_profiles",
    "mesh_proposal_scope",
    "metric_edge_lengths",
    "metric_simplex_quality",
    "normalize_mesh_metric",
    "optimize_cell_geometry_coordinates",
    "optimize_cell_mesh",
    "partition_adaptive_simplex",
    "prepare_adaptive_simplex",
    "prepare_boundary_layer_extrusion",
    "prepare_boundary_layers",
    "prepare_device_generation",
    "prepare_distributed_surface_generation",
    "prepare_device_metric_adaptation",
    "prepare_device_tetra_metric",
    "prepare_distribution_transition",
    "prepare_mesh_adaptation",
    "prepare_native_layer_association_transfer",
    "prepare_mesh_distribution",
    "prepare_mesh_proposal",
    "prepare_planar_bands",
    "prepare_overset_connectivity",
    "prepare_overset_conservative_remap",
    "prepare_overset_conservative_state_transport",
    "prepare_overset_field_transfer",
    "prepare_overset_motion_rebind",
    "project_hp_lineage",
    "project_mesh_proposal",
    "propagate_association",
    "providers",
    "read_mesh_array_artifact",
    "rederive_association",
    "resolve_mesh_file_profile",
    "resolve_mesh_scope",
    "resolve_size_controls",
    "size_field_metric",
    "summarize_cell_quality",
    "transition_interface_attachment",
    "validate_mesh_labels",
    "validate_mesh_zones",
    "verify_curved_geometry",
]
