#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from .._functional_update_kernel import (
    FunctionalUpdateEvidence,
    FunctionalUpdateKernel,
    FunctionalUpdateState,
)
from ._adaptive import (
    AdaptiveRefinementPlan,
    AdaptiveTopologyEvidence,
    AdaptiveTopologyTransaction,
    coarsen_axis_partition,
    prepare_adaptive_topology_transaction,
    refine_axis_partition,
    TrainableAxisPartition,
    TrainablePartitionEvidence,
)
from ._asynchronous import (
    AsynchronousSchwarzPlan,
    AsynchronousSchwarzResult,
    AsynchronousSchwarzState,
    solve_asynchronous_schwarz,
)
from ._checkpoint import (
    load_functional_decomposition_checkpoint,
    save_functional_decomposition_checkpoint,
)
from ._constraints import (
    AugmentedInterfacePlan,
    AugmentedInterfaceResult,
    solve_augmented_interface,
)
from ._curvature import (
    DecompositionKFACResult,
    dense_local_curvature_step,
    LocalCurvaturePlan,
    LocalCurvatureResult,
    matrix_free_gauss_newton_step,
    MatrixFreeGaussNewtonPlan,
    MatrixFreeGaussNewtonResult,
    solve_decomposition_kfac,
    solve_local_kfac,
    solve_overlap_kfac,
)
from ._export import (
    DecompositionDeploymentArtifact,
    FixedPatchParticipant,
    FunctionalPatchParticipant,
    HybridFunctionalDecomposition,
    load_decomposition_artifact,
    save_decomposition_artifact,
)
from ._multilevel import (
    FunctionalCoarseCorrection,
    FunctionalCyclePlan,
    FunctionalCycleResult,
    FunctionalHierarchyPlan,
    FunctionalHierarchyResult,
    train_functional_cycles,
    train_functional_hierarchy,
)
from ._prepare import (
    FunctionalDecompositionPlan,
    prepare_functional_decomposition,
    PreparedFunctionalDecomposition,
)
from ._problem import (
    FunctionalDecompositionProblem,
    GlobalScope,
    localize_residual_penalty,
    PairScope,
    PatchScope,
    ScopedFunctionalTerm,
)
from ._schwarz import (
    aitken_relax_trace_state,
    AitkenTracePlan,
    AitkenTraceState,
    capture_generalized_trace_state,
    capture_schwarz_trace_state,
    DiscreteOperatorTracePenalty,
    DiscreteTracePenalty,
    SchwarzTraceQuantity,
    SchwarzTraceState,
    TraceExchangeState,
)
from ._sharding import (
    DecompositionShardingEvidence,
    distributed_pou_collective,
    distributed_schwarz_exchange,
    DistributedCollectiveEvidence,
    DistributedCollectiveResult,
    FunctionalDecompositionShardingPlan,
    place_local_field_family,
    place_schwarz_trace_state,
    ShardedLocalFieldFamily,
)
from ._solve import (
    FunctionalDecompositionEvidence,
    FunctionalDecompositionIterationMetrics,
    FunctionalDecompositionResult,
    FunctionalDecompositionState,
    solve_functional_decomposition,
)
from ._strategy import (
    BlockDecompositionTraining,
    JointDecompositionTraining,
    SchwarzDecompositionTraining,
)


__all__ = [
    "AdaptiveRefinementPlan",
    "AitkenTracePlan",
    "AsynchronousSchwarzPlan",
    "AsynchronousSchwarzResult",
    "AsynchronousSchwarzState",
    "AitkenTraceState",
    "aitken_relax_trace_state",
    "capture_generalized_trace_state",
    "AdaptiveTopologyEvidence",
    "AdaptiveTopologyTransaction",
    "TrainableAxisPartition",
    "TrainablePartitionEvidence",
    "AugmentedInterfacePlan",
    "DecompositionShardingEvidence",
    "DecompositionDeploymentArtifact",
    "DistributedCollectiveEvidence",
    "DistributedCollectiveResult",
    "DecompositionKFACResult",
    "AugmentedInterfaceResult",
    "BlockDecompositionTraining",
    "FixedPatchParticipant",
    "DiscreteTracePenalty",
    "DiscreteOperatorTracePenalty",
    "FunctionalCoarseCorrection",
    "FunctionalDecompositionEvidence",
    "FunctionalDecompositionIterationMetrics",
    "FunctionalDecompositionPlan",
    "FunctionalDecompositionProblem",
    "FunctionalDecompositionShardingPlan",
    "FunctionalDecompositionResult",
    "FunctionalCyclePlan",
    "FunctionalCycleResult",
    "FunctionalDecompositionState",
    "FunctionalHierarchyPlan",
    "FunctionalHierarchyResult",
    "FunctionalUpdateEvidence",
    "FunctionalPatchParticipant",
    "FunctionalUpdateKernel",
    "LocalCurvaturePlan",
    "LocalCurvatureResult",
    "MatrixFreeGaussNewtonPlan",
    "MatrixFreeGaussNewtonResult",
    "FunctionalUpdateState",
    "GlobalScope",
    "HybridFunctionalDecomposition",
    "JointDecompositionTraining",
    "PairScope",
    "PatchScope",
    "PreparedFunctionalDecomposition",
    "ShardedLocalFieldFamily",
    "SchwarzDecompositionTraining",
    "SchwarzTraceState",
    "SchwarzTraceQuantity",
    "ScopedFunctionalTerm",
    "TraceExchangeState",
    "capture_schwarz_trace_state",
    "localize_residual_penalty",
    "load_functional_decomposition_checkpoint",
    "prepare_functional_decomposition",
    "save_functional_decomposition_checkpoint",
    "prepare_adaptive_topology_transaction",
    "distributed_pou_collective",
    "distributed_schwarz_exchange",
    "refine_axis_partition",
    "place_local_field_family",
    "coarsen_axis_partition",
    "place_schwarz_trace_state",
    "solve_functional_decomposition",
    "solve_augmented_interface",
    "load_decomposition_artifact",
    "solve_asynchronous_schwarz",
    "save_decomposition_artifact",
    "dense_local_curvature_step",
    "solve_decomposition_kfac",
    "solve_local_kfac",
    "solve_overlap_kfac",
    "matrix_free_gauss_newton_step",
    "train_functional_cycles",
    "train_functional_hierarchy",
]
