#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Composable spaces, operators, decompositions, and linear numerical runtime."""

from . import krylov
from ._costs import LinearCostEstimate
from ._factorizations import (
    FactorizationCapabilities,
    FactorizationKind,
    FactorizationPolicy,
    factorize,
    PreparedFactorization,
    refresh_factorization,
)
from ._linearizations import (
    LinearizationPolicy,
    prepare_linearization,
    PreparedLinearization,
    RematerializationPolicy,
)
from ._materialization import MaterializationPolicy, materialize
from ._matrix_functions import (
    matrix_exponential_action,
    matrix_function_action,
    matrix_phi1_action,
    MatrixFunctionKind,
    MatrixFunctionMethod,
    MatrixFunctionPolicy,
    MatrixFunctionResult,
    SpectralMatrixRepresentation,
)
from ._operator_pairing import OperatorPairing
from ._operators import (
    AbstractLinearOperator,
    adjoint,
    AdjointLinearOperator,
    BlockLinearOperator,
    ComposedLinearOperator,
    DenseLinearOperator,
    DiagonalLinearOperator,
    FunctionLinearOperator,
    IdentityLinearOperator,
    JacobianLinearOperator,
    ScaledLinearOperator,
    SumLinearOperator,
    transpose,
    TransposeLinearOperator,
)
from ._pairings import AbstractPairing, DiagonalPairing, EuclideanPairing
from ._plans import LinearBackend, LinearSolvePlan, plan
from ._policies import (
    AbstractLinearMethod,
    AutoLinearMethod,
    BiCGStab,
    ConjugateGradient,
    DenseCholesky,
    DenseLU,
    DenseQR,
    DenseSVD,
    DifferentiationMode,
    DifferentiationPolicy,
    FailureMode,
    FailurePolicy,
    FGMRES,
    GeneralizedLSMR,
    GMRES,
    HostSparseLU,
    LinearSolvePolicy,
    LSMR,
    MINRES,
    PCG,
    RankPolicy,
    SolveResourcePolicy,
    SparseDirect,
    StructuredDirect,
    TolerancePolicy,
)
from ._preconditioners import (
    AbstractPreconditioner,
    BlockDiagonalPreconditioner,
    DiagonalPreconditioner,
    IdentityPreconditioner,
    IncompleteFactorizationPreconditioner,
    LowRankWoodburyPreconditioner,
    MultigridPreconditioner,
    OperatorPreconditioner,
)
from ._prepared import PreparedLinearSolve
from ._problems import (
    AbstractLinearProblem,
    LeastSquaresProblem,
    LinearProblemKind,
    LinearSystem,
    MinimumNormProblem,
)
from ._properties import (
    LinearCapabilityError,
    OperatorCapabilities,
    OperatorProperties,
    PropertyEvidence,
)
from ._recycling import prepare_recycling_subspace, RecyclingSubspace
from ._results import (
    linear_status_message,
    LinearSolveDiagnostics,
    LinearSolveProvenance,
    LinearSolveResult,
    LinearSolveStatus,
)
from ._runtime import (
    prepare,
    refresh,
    solve,
    solve_adjoint,
    solve_many,
    solve_transpose,
)
from ._saddle import (
    saddle_point_operator,
    saddle_point_schur_complement,
    saddle_point_system,
)
from ._space_extensions import CoordaxSpace, TensorProductSpace
from ._spaces import (
    AbstractVectorSpace,
    ArraySpace,
    BlockSpace,
    DualSpace,
    PyTreeSpace,
    RHSLayout,
)
from ._spectral import (
    estimate_condition_number,
    estimate_diagonal,
    estimate_inverse_diagonal,
    estimate_numerical_range,
    estimate_operator_norm,
    estimate_spectral_bounds,
    estimate_spectral_radius,
    NumericalRangeEstimate,
    SpectralBoundsEstimate,
    SpectralEstimate,
    stochastic_log_determinant,
    stochastic_trace,
    StochasticEstimate,
)
from ._structured_operators import (
    BandedLinearOperator,
    BlockDiagonalLinearOperator,
    DiagonalPlusLowRankLinearOperator,
    KroneckerLinearOperator,
    KroneckerSumLinearOperator,
    LowRankLinearOperator,
    PermutationLinearOperator,
    SchurComplementLinearOperator,
    StackedLinearOperator,
    SymmetricLowRankLinearOperator,
    TriangularLinearOperator,
    TridiagonalLinearOperator,
)
from ._subspaces import LinearSubspace, NullspacePolicy


__all__ = [
    "AbstractLinearMethod",
    "AbstractLinearOperator",
    "AbstractLinearProblem",
    "AbstractPairing",
    "AbstractPreconditioner",
    "AbstractVectorSpace",
    "AdjointLinearOperator",
    "ArraySpace",
    "AutoLinearMethod",
    "BandedLinearOperator",
    "BiCGStab",
    "BlockDiagonalLinearOperator",
    "BlockDiagonalPreconditioner",
    "BlockLinearOperator",
    "BlockSpace",
    "ComposedLinearOperator",
    "ConjugateGradient",
    "CoordaxSpace",
    "DenseCholesky",
    "DenseLU",
    "DenseLinearOperator",
    "DenseQR",
    "DenseSVD",
    "DiagonalLinearOperator",
    "DiagonalPlusLowRankLinearOperator",
    "DiagonalPreconditioner",
    "DiagonalPairing",
    "DifferentiationMode",
    "DifferentiationPolicy",
    "DualSpace",
    "EuclideanPairing",
    "FGMRES",
    "FactorizationCapabilities",
    "FactorizationKind",
    "FactorizationPolicy",
    "FailureMode",
    "FailurePolicy",
    "FunctionLinearOperator",
    "GeneralizedLSMR",
    "GMRES",
    "HostSparseLU",
    "IdentityLinearOperator",
    "IdentityPreconditioner",
    "IncompleteFactorizationPreconditioner",
    "JacobianLinearOperator",
    "KroneckerLinearOperator",
    "KroneckerSumLinearOperator",
    "LSMR",
    "LeastSquaresProblem",
    "LinearBackend",
    "LinearCapabilityError",
    "LinearCostEstimate",
    "LinearProblemKind",
    "LinearSolveDiagnostics",
    "LinearSolvePlan",
    "LinearSolvePolicy",
    "LinearSolveProvenance",
    "LinearSolveResult",
    "LinearSolveStatus",
    "LinearSubspace",
    "LinearSystem",
    "LinearizationPolicy",
    "LowRankLinearOperator",
    "LowRankWoodburyPreconditioner",
    "MINRES",
    "MaterializationPolicy",
    "MatrixFunctionKind",
    "MatrixFunctionMethod",
    "MatrixFunctionPolicy",
    "MatrixFunctionResult",
    "MinimumNormProblem",
    "MultigridPreconditioner",
    "NullspacePolicy",
    "NumericalRangeEstimate",
    "OperatorCapabilities",
    "OperatorPairing",
    "OperatorPreconditioner",
    "OperatorProperties",
    "PCG",
    "PermutationLinearOperator",
    "PreparedFactorization",
    "PreparedLinearSolve",
    "PreparedLinearization",
    "PropertyEvidence",
    "RecyclingSubspace",
    "PyTreeSpace",
    "RHSLayout",
    "RankPolicy",
    "RematerializationPolicy",
    "ScaledLinearOperator",
    "SchurComplementLinearOperator",
    "SolveResourcePolicy",
    "SparseDirect",
    "SpectralBoundsEstimate",
    "SpectralEstimate",
    "SpectralMatrixRepresentation",
    "StackedLinearOperator",
    "StochasticEstimate",
    "StructuredDirect",
    "SumLinearOperator",
    "SymmetricLowRankLinearOperator",
    "TensorProductSpace",
    "TolerancePolicy",
    "TransposeLinearOperator",
    "TriangularLinearOperator",
    "TridiagonalLinearOperator",
    "adjoint",
    "estimate_condition_number",
    "estimate_diagonal",
    "estimate_inverse_diagonal",
    "estimate_numerical_range",
    "estimate_operator_norm",
    "estimate_spectral_bounds",
    "estimate_spectral_radius",
    "factorize",
    "krylov",
    "linear_status_message",
    "materialize",
    "matrix_exponential_action",
    "matrix_function_action",
    "matrix_phi1_action",
    "plan",
    "prepare",
    "prepare_linearization",
    "prepare_recycling_subspace",
    "refresh",
    "refresh_factorization",
    "saddle_point_operator",
    "saddle_point_schur_complement",
    "saddle_point_system",
    "solve",
    "solve_adjoint",
    "solve_many",
    "solve_transpose",
    "stochastic_log_determinant",
    "stochastic_trace",
    "transpose",
]
