# Copyright © 2026 PHYDRA, Inc. All rights reserved.
"""Pairing-aware exact and key-bound randomized singular subspaces."""

from .._singular_subspaces import (
    covariance_action,
    covariance_factor,
    projector_action,
    SingularSubspaceResponse,
)
from .._svd import plan_svd, prepare_svd, refresh_svd, svd
from .._svd_contracts import (
    DenseSVD,
    DenseSVDState,
    PreparedSVDSolve,
    RandomizedSVD,
    RandomizedSVDState,
    require_exact_svd_rank,
    SVDApproximationPolicy,
    SVDCertificateKind,
    SVDCostEstimate,
    SVDDifferentiationMode,
    SVDLeadingEvidence,
    SVDProblem,
    SVDRangeEvidence,
    SVDRankEvidence,
    SVDResourcePolicy,
    SVDSolveDiagnostics,
    SVDSolvePlan,
    SVDSolvePolicy,
    SVDSolveProvenance,
    SVDSolveResult,
    SVDSolveStatus,
    SVDTarget,
    SVDTolerancePolicy,
)


__all__ = [
    "DenseSVD",
    "DenseSVDState",
    "PreparedSVDSolve",
    "RandomizedSVD",
    "RandomizedSVDState",
    "SVDApproximationPolicy",
    "SVDCertificateKind",
    "SVDCostEstimate",
    "SVDDifferentiationMode",
    "SVDLeadingEvidence",
    "SVDProblem",
    "SVDRankEvidence",
    "SVDRangeEvidence",
    "SVDResourcePolicy",
    "SVDSolveDiagnostics",
    "SVDSolvePlan",
    "SVDSolvePolicy",
    "SVDSolveProvenance",
    "SVDSolveResult",
    "SVDSolveStatus",
    "SVDTarget",
    "SVDTolerancePolicy",
    "SingularSubspaceResponse",
    "covariance_action",
    "covariance_factor",
    "plan_svd",
    "prepare_svd",
    "projector_action",
    "refresh_svd",
    "require_exact_svd_rank",
    "svd",
]
