#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#
# ruff: noqa: I001

# Ensure JAX uses 64-bit floats by default for numerical robustness.
from importlib import import_module
from types import ModuleType
from typing import TYPE_CHECKING

import jax


jax.config.update("jax_enable_x64", True)

# Launcher-provided rank settings must be consumed before any device-owning module
# is imported. Local imports remain unchanged and preserve the package's deliberate
# dependency order.
from ._execution_bootstrap import RuntimeBootstrap, initialize_from_environment


if RuntimeBootstrap.from_environment() is not None:
    initialize_from_environment()

# Bootstrap the dependency-ordered numerical core that owns cross-package
# protocols. Domain-specific public surfaces remain lazy below.
from . import logging as logging
from . import ein as ein
from . import discretization

_PUBLIC_SUBMODULES = frozenset(
    (
        "acoustics",
        "algebraic",
        "applications",
        "artifacts",
        "atomistic",
        "axes",
        "backends",
        "bubble_dynamics",
        "causal",
        "chemo_mechanics",
        "chemistry",
        "circuit",
        "closure_data",
        "combinatorial",
        "conditions",
        "continuation",
        "control",
        "coresets",
        "correlation",
        "data_utils",
        "diagnostics",
        "discretization",
        "domain",
        "durability",
        "dynamics",
        "ein",
        "electrochemistry",
        "electrohydrodynamics",
        "electromagnetics",
        "enforcement",
        "equations",
        "events",
        "execution",
        "export",
        "exterior",
        "fidelity",
        "finance",
        "frequency",
        "geometry",
        "graph",
        "imaging",
        "integration",
        "interchange",
        "interfacial_transport",
        "kernels",
        "lifecycle",
        "linalg",
        "logging",
        "manufacturing",
        "materials",
        "measurement",
        "membranes",
        "meshing",
        "metrix",
        "ml",
        "nn",
        "nonlinear",
        "nuclear",
        "observation",
        "operators",
        "optics",
        "optim",
        "optomechanics",
        "particle_physics",
        "pgm",
        "phoresis",
        "population_balance",
        "precision",
        "privacy",
        "process_systems",
        "qualification",
        "rendering",
        "rheology",
        "rom",
        "sampling",
        "sensing",
        "series",
        "service",
        "signal",
        "smart_materials",
        "solver",
        "sparse",
        "spatial_sampling",
        "special",
        "statistical_dynamics",
        "stochastic",
        "structural_dynamics",
        "surface_chemistry",
        "system_modeling",
        "tensor_decomposition",
        "tensor_network",
        "tensor_train",
        "terms",
        "thermal_systems",
        "threshold_dynamics",
        "topology",
        "transport",
        "tribology",
        "typing",
        "units",
        "uq",
        "variational",
        "velocimetry",
        "weighting",
    )
)


if TYPE_CHECKING:
    from . import (
        acoustics,
        algebraic,
        applications,
        artifacts,
        atomistic,
        axes,
        backends,
        bubble_dynamics,
        causal,
        chemo_mechanics,
        chemistry,
        circuit,
        closure_data,
        combinatorial,
        conditions,
        continuation,
        control,
        coresets,
        correlation,
        data_utils,
        diagnostics,
        discretization,
        domain,
        durability,
        dynamics,
        ein,
        electrochemistry,
        electrohydrodynamics,
        electromagnetics,
        enforcement,
        equations,
        events,
        execution,
        export,
        exterior,
        fidelity,
        finance,
        frequency,
        geometry,
        graph,
        imaging,
        integration,
        interchange,
        interfacial_transport,
        kernels,
        lifecycle,
        linalg,
        logging,
        manufacturing,
        materials,
        measurement,
        membranes,
        meshing,
        metrix,
        ml,
        nn,
        nonlinear,
        nuclear,
        observation,
        operators,
        optics,
        optim,
        optomechanics,
        particle_physics,
        pgm,
        phoresis,
        population_balance,
        precision,
        privacy,
        process_systems,
        qualification,
        rendering,
        rheology,
        rom,
        sampling,
        sensing,
        series,
        service,
        signal,
        smart_materials,
        solver,
        sparse,
        spatial_sampling,
        special,
        statistical_dynamics,
        stochastic,
        structural_dynamics,
        surface_chemistry,
        system_modeling,
        tensor_decomposition,
        tensor_network,
        tensor_train,
        terms,
        thermal_systems,
        threshold_dynamics,
        topology,
        transport,
        tribology,
        typing,
        units,
        uq,
        variational,
        velocimetry,
        weighting,
    )


def __getattr__(name: str) -> ModuleType:
    if name not in _PUBLIC_SUBMODULES:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{name}")
    globals()[name] = module
    return module


def __dir__() -> list[str]:
    return sorted(set(globals()) | _PUBLIC_SUBMODULES)


from ._array_archive import (
    ArrayArchiveCorruptionError,
    ArrayArchiveError,
    ArrayArchiveLimits,
)
from ._admissibility import (
    AdmissibilityHeader,
    AdmissibilityReason,
    AdmissibilityTransitionRequest,
    combine_admissibility,
    reason_bits_where,
)
from ._array_tree import ArrayLeafSchema, ArrayPyTreeSchema
from ._differentiation import (
    AbstractConstructionCertificate,
    admit_regularity,
    authority_admits,
    branch_policy_contract,
    BranchDifferentiationPolicy,
    CapabilityEvidenceKind,
    CapabilityRequirement,
    ComponentAuthority,
    DERIVATIVE_SUPPORTED,
    DERIVATIVE_UNSUPPORTED,
    DerivativeAdmission,
    DerivativeContract,
    DerivativeRegularity,
    DerivativeRoute,
    DerivativeSurface,
    DifferentiationRequest,
    gradient_level_at_least,
    GradientLevel,
    is_owned_surface,
    ObjectiveKind,
    OwnerDerivativeCapability,
    RegularityPieces,
    RegularityPolicy,
    resolve_gradient_level,
    SurfaceDerivative,
    weakest_level,
)
from ._fingerprint import array_tree_fingerprint
from ._execution_resources import ExecutionResourceEvidence
from ._identity import (
    ArtifactBindingIdentity,
    callable_payload,
    ExecutableSignature,
    NumericRevision,
    SemanticProvenance,
    strict_module_payload,
)
from ._model import (
    AbstractArrayModel,
    AbstractComponentSlot,
    admit_randomness,
    artifact_value,
    artifact_value_id,
    bind_component,
    CertificateRecord,
    ComponentBinding,
    ComponentContract,
    ComponentPrecisionContract,
    ComponentSlotContract,
    ExecutionCapabilities,
    ExecutionTier,
    FrozenRealization,
    ModelExecutionContract,
    ModelPorts,
    operator_architecture_codec,
    operator_architecture_codec_for,
    OperatorArchitectureCodec,
    PortBindingEvidence,
    PortMapping,
    PortProvider,
    PortVariance,
    RandomnessContract,
    RandomnessMode,
    register_artifact_value,
    register_operator_architecture_codec,
    resolve_port_mapping,
    supports_derivative,
    ValuePort,
)
from ._strict import StrictModule
from ._trainable import (
    ArrayRole,
    combine_parameters,
    ExplicitFreeze,
    fixed_field,
    LaneLayout,
    model_state_field,
    NonTrainableState,
    parameter_field,
    ParameterOwner,
    partition_parameters,
    require_parameter_roles,
    resolve_array_roles,
    RoleResolution,
)
from ._physical import (
    DimensionalScaleContract,
    ElectromagneticScaleContract,
    LengthCoordinateKind,
    RelativityScaleContract,
    SpatialCoordinateContract,
)
from ._lorentz import (
    boost_event,
    boost_fields,
    boost_matrix,
    boost_proper_velocity,
    boost_wavevector,
    FourMomentum,
    LorentzFrame,
    LorentzSpectralTransform,
    lower_four_vector,
    MINKOWSKI_METRIC,
    minkowski_dot,
    SpectralEmissionCompleteness,
    transform_spectral_energy,
)


# Explicit re-exports for star import
__all__ = [
    "FourMomentum",
    "LorentzFrame",
    "LorentzSpectralTransform",
    "MINKOWSKI_METRIC",
    "SpectralEmissionCompleteness",
    "boost_event",
    "boost_fields",
    "boost_matrix",
    "boost_proper_velocity",
    "boost_wavevector",
    "lower_four_vector",
    "minkowski_dot",
    "transform_spectral_energy",
    "AbstractArrayModel",
    "AbstractComponentSlot",
    "AbstractConstructionCertificate",
    "AdmissibilityHeader",
    "AdmissibilityReason",
    "AdmissibilityTransitionRequest",
    "ArrayArchiveCorruptionError",
    "ArrayArchiveError",
    "ArrayArchiveLimits",
    "ArrayLeafSchema",
    "ArrayPyTreeSchema",
    "ArrayRole",
    "ArtifactBindingIdentity",
    "BranchDifferentiationPolicy",
    "CapabilityEvidenceKind",
    "CapabilityRequirement",
    "CertificateRecord",
    "ComponentAuthority",
    "ComponentBinding",
    "ComponentContract",
    "ComponentPrecisionContract",
    "ComponentSlotContract",
    "DERIVATIVE_SUPPORTED",
    "DERIVATIVE_UNSUPPORTED",
    "DerivativeAdmission",
    "DerivativeContract",
    "DerivativeRegularity",
    "DerivativeRoute",
    "DerivativeSurface",
    "DifferentiationRequest",
    "DimensionalScaleContract",
    "ElectromagneticScaleContract",
    "ExecutableSignature",
    "ExecutionCapabilities",
    "ExecutionResourceEvidence",
    "ExecutionTier",
    "ExplicitFreeze",
    "FrozenRealization",
    "GradientLevel",
    "LaneLayout",
    "LengthCoordinateKind",
    "ModelExecutionContract",
    "ModelPorts",
    "NonTrainableState",
    "NumericRevision",
    "ObjectiveKind",
    "OperatorArchitectureCodec",
    "OwnerDerivativeCapability",
    "ParameterOwner",
    "PortBindingEvidence",
    "PortMapping",
    "PortProvider",
    "PortVariance",
    "RandomnessContract",
    "RandomnessMode",
    "RegularityPieces",
    "RegularityPolicy",
    "RelativityScaleContract",
    "RoleResolution",
    "SemanticProvenance",
    "SpatialCoordinateContract",
    "StrictModule",
    "SurfaceDerivative",
    "ValuePort",
    "acoustics",
    "admit_randomness",
    "admit_regularity",
    "algebraic",
    "applications",
    "array_tree_fingerprint",
    "artifact_value",
    "artifact_value_id",
    "artifacts",
    "atomistic",
    "authority_admits",
    "axes",
    "backends",
    "bubble_dynamics",
    "bind_component",
    "branch_policy_contract",
    "callable_payload",
    "causal",
    "chemistry",
    "chemo_mechanics",
    "circuit",
    "closure_data",
    "combinatorial",
    "combine_admissibility",
    "combine_parameters",
    "conditions",
    "continuation",
    "control",
    "coresets",
    "correlation",
    "data_utils",
    "diagnostics",
    "discretization",
    "domain",
    "durability",
    "dynamics",
    "ein",
    "electrochemistry",
    "electrohydrodynamics",
    "electromagnetics",
    "enforcement",
    "equations",
    "events",
    "execution",
    "export",
    "exterior",
    "fidelity",
    "finance",
    "fixed_field",
    "frequency",
    "geometry",
    "gradient_level_at_least",
    "graph",
    "imaging",
    "integration",
    "interchange",
    "interfacial_transport",
    "is_owned_surface",
    "kernels",
    "lifecycle",
    "linalg",
    "logging",
    "manufacturing",
    "materials",
    "measurement",
    "membranes",
    "meshing",
    "metrix",
    "ml",
    "model_state_field",
    "nn",
    "nonlinear",
    "nuclear",
    "observation",
    "operator_architecture_codec",
    "operator_architecture_codec_for",
    "operators",
    "optics",
    "optim",
    "optomechanics",
    "parameter_field",
    "particle_physics",
    "partition_parameters",
    "pgm",
    "phoresis",
    "population_balance",
    "precision",
    "privacy",
    "process_systems",
    "qualification",
    "reason_bits_where",
    "register_artifact_value",
    "register_operator_architecture_codec",
    "rendering",
    "require_parameter_roles",
    "resolve_array_roles",
    "resolve_gradient_level",
    "resolve_port_mapping",
    "rheology",
    "rom",
    "sampling",
    "sensing",
    "series",
    "service",
    "signal",
    "smart_materials",
    "solver",
    "sparse",
    "spatial_sampling",
    "special",
    "statistical_dynamics",
    "stochastic",
    "strict_module_payload",
    "structural_dynamics",
    "supports_derivative",
    "surface_chemistry",
    "system_modeling",
    "tensor_decomposition",
    "tensor_network",
    "tensor_train",
    "terms",
    "threshold_dynamics",
    "thermal_systems",
    "topology",
    "transport",
    "tribology",
    "typing",
    "units",
    "uq",
    "variational",
    "velocimetry",
    "weakest_level",
    "weighting",
]
