#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#
# ruff: noqa: I001

# Ensure JAX uses 64-bit floats by default for numerical robustness.
import jax


jax.config.update("jax_enable_x64", True)

# Launcher-provided rank settings must be consumed before any device-owning module
# is imported. Local imports remain unchanged and preserve the package's deliberate
# dependency order.
from ._execution_bootstrap import RuntimeBootstrap, initialize_from_environment


if RuntimeBootstrap.from_environment() is not None:
    initialize_from_environment()

from . import logging as logging

from . import ein as ein

from . import (
    acoustics,
    algebraic,
    axes,
    backends,
    combinatorial,
    conditions,
    continuation,
    control,
    coresets,
    data_utils,
    correlation,
    series,
    discretization,
    diagnostics,
    topology,
    domain,
    dynamics,
    durability,
    enforcement,
    electrochemistry,
    electrohydrodynamics,
    electromagnetics,
    variational,
    equations,
    export,
    fidelity,
    execution,
    geometry,
    frequency,
    graph,
    interchange,
    imaging,
    meshing,
    integration,
    lifecycle,
    interfacial_transport,
    kernels,
    linalg,
    metrix,
    ml,
    measurement,
    signal,
    nn,
    manufacturing,
    materials,
    membranes,
    nonlinear,
    operators,
    optim,
    pgm,
    precision,
    privacy,
    particle_physics,
    qualification,
    rendering,
    optomechanics,
    phoresis,
    population_balance,
    process_systems,
    sensing,
    rom,
    service,
    rheology,
    spatial_sampling,
    sampling,
    solver,
    sparse,
    special,
    stochastic,
    tensor_network,
    tensor_decomposition,
    tensor_train,
    structural_dynamics,
    surface_chemistry,
    system_modeling,
    thermal_systems,
    tribology,
    smart_materials,
    chemo_mechanics,
    terms,
    transport,
    uq,
    units,
    circuit,
    optics,
    velocimetry,
    weighting,
)
from . import artifacts, events, observation
from . import causal
from ._array_archive import ArrayArchiveLimits
from ._admissibility import (
    AdmissibilityHeader,
    AdmissibilityReason,
    AdmissibilityTransitionRequest,
    combine_admissibility,
    reason_bits_where,
)
from ._array_tree import ArrayLeafSchema, ArrayPyTreeSchema
from ._differentiation import (
    AbstractConstructionCertificate,
    admit_regularity,
    authority_admits,
    branch_policy_contract,
    BranchDifferentiationPolicy,
    CapabilityEvidenceKind,
    CapabilityRequirement,
    ComponentAuthority,
    DERIVATIVE_SUPPORTED,
    DERIVATIVE_UNSUPPORTED,
    DerivativeAdmission,
    DerivativeContract,
    DerivativeRegularity,
    DerivativeRoute,
    DerivativeSurface,
    DifferentiationRequest,
    gradient_level_at_least,
    GradientLevel,
    is_owned_surface,
    ObjectiveKind,
    RegularityPieces,
    RegularityPolicy,
    resolve_gradient_level,
    SurfaceDerivative,
    weakest_level,
)
from ._fingerprint import array_tree_fingerprint
from ._execution_resources import ExecutionResourceEvidence
from ._identity import (
    ArtifactBindingIdentity,
    callable_payload,
    ExecutableSignature,
    NumericRevision,
    SemanticProvenance,
    strict_module_payload,
)
from ._model import (
    AbstractArrayModel,
    AbstractComponentSlot,
    admit_randomness,
    artifact_value,
    artifact_value_id,
    bind_component,
    CertificateRecord,
    ComponentBinding,
    ComponentContract,
    ComponentPrecisionContract,
    ComponentSlotContract,
    ExecutionCapabilities,
    ExecutionTier,
    FrozenRealization,
    ModelExecutionContract,
    ModelPorts,
    operator_architecture_codec,
    operator_architecture_codec_for,
    OperatorArchitectureCodec,
    PortBindingEvidence,
    PortMapping,
    PortProvider,
    PortVariance,
    RandomnessContract,
    RandomnessMode,
    register_artifact_value,
    register_operator_architecture_codec,
    resolve_port_mapping,
    supports_derivative,
    ValuePort,
)
from ._strict import StrictModule
from ._trainable import (
    ArrayRole,
    combine_parameters,
    ExplicitFreeze,
    fixed_field,
    LaneLayout,
    model_state_field,
    NonTrainableState,
    parameter_field,
    ParameterOwner,
    partition_parameters,
    require_parameter_roles,
    resolve_array_roles,
    RoleResolution,
)
from ._physical import (
    DimensionalScaleContract,
    LengthCoordinateKind,
    RelativityScaleContract,
    SpatialCoordinateContract,
)

from . import atomistic, chemistry, nuclear

# Closure-data and statistical-dynamics packages depend on loaded numerical substrates.
from . import closure_data, statistical_dynamics

# Finance composes the loaded numerical, stochastic, and qualification substrates.
from . import finance

# Applications depend on public equation/solver substrates and load last.
from . import applications

# Cosmology interchange depends on application products and therefore loads after apps.
from .interchange import cosmology as _cosmology_interchange  # noqa: F401


# Explicit re-exports for star import
__all__ = [
    "AbstractArrayModel",
    "AbstractComponentSlot",
    "AbstractConstructionCertificate",
    "AdmissibilityHeader",
    "AdmissibilityReason",
    "AdmissibilityTransitionRequest",
    "ArrayArchiveLimits",
    "ArrayLeafSchema",
    "ArrayPyTreeSchema",
    "ArrayRole",
    "ArtifactBindingIdentity",
    "BranchDifferentiationPolicy",
    "CapabilityEvidenceKind",
    "CapabilityRequirement",
    "CertificateRecord",
    "ComponentAuthority",
    "ComponentBinding",
    "ComponentContract",
    "ComponentPrecisionContract",
    "ComponentSlotContract",
    "DERIVATIVE_SUPPORTED",
    "DERIVATIVE_UNSUPPORTED",
    "DerivativeAdmission",
    "DerivativeContract",
    "DerivativeRegularity",
    "DerivativeRoute",
    "DerivativeSurface",
    "DifferentiationRequest",
    "DimensionalScaleContract",
    "ExecutableSignature",
    "ExecutionCapabilities",
    "ExecutionResourceEvidence",
    "ExecutionTier",
    "ExplicitFreeze",
    "FrozenRealization",
    "GradientLevel",
    "LaneLayout",
    "LengthCoordinateKind",
    "ModelExecutionContract",
    "ModelPorts",
    "NonTrainableState",
    "NumericRevision",
    "ObjectiveKind",
    "OperatorArchitectureCodec",
    "ParameterOwner",
    "PortBindingEvidence",
    "PortMapping",
    "PortProvider",
    "PortVariance",
    "RandomnessContract",
    "RandomnessMode",
    "RegularityPieces",
    "RegularityPolicy",
    "RelativityScaleContract",
    "RoleResolution",
    "SemanticProvenance",
    "SpatialCoordinateContract",
    "StrictModule",
    "SurfaceDerivative",
    "ValuePort",
    "acoustics",
    "admit_randomness",
    "admit_regularity",
    "algebraic",
    "applications",
    "array_tree_fingerprint",
    "artifact_value",
    "artifact_value_id",
    "artifacts",
    "atomistic",
    "authority_admits",
    "axes",
    "backends",
    "bind_component",
    "branch_policy_contract",
    "callable_payload",
    "causal",
    "chemistry",
    "chemo_mechanics",
    "circuit",
    "closure_data",
    "combinatorial",
    "combine_admissibility",
    "combine_parameters",
    "conditions",
    "continuation",
    "control",
    "coresets",
    "correlation",
    "data_utils",
    "diagnostics",
    "discretization",
    "domain",
    "durability",
    "dynamics",
    "ein",
    "electrochemistry",
    "electrohydrodynamics",
    "electromagnetics",
    "enforcement",
    "equations",
    "events",
    "execution",
    "export",
    "fidelity",
    "finance",
    "fixed_field",
    "frequency",
    "geometry",
    "gradient_level_at_least",
    "graph",
    "imaging",
    "integration",
    "interchange",
    "interfacial_transport",
    "is_owned_surface",
    "kernels",
    "lifecycle",
    "linalg",
    "logging",
    "manufacturing",
    "materials",
    "measurement",
    "membranes",
    "meshing",
    "metrix",
    "ml",
    "model_state_field",
    "nn",
    "nonlinear",
    "nuclear",
    "observation",
    "operator_architecture_codec",
    "operator_architecture_codec_for",
    "operators",
    "optics",
    "optim",
    "optomechanics",
    "parameter_field",
    "particle_physics",
    "partition_parameters",
    "pgm",
    "phoresis",
    "population_balance",
    "precision",
    "privacy",
    "process_systems",
    "qualification",
    "reason_bits_where",
    "register_artifact_value",
    "register_operator_architecture_codec",
    "rendering",
    "require_parameter_roles",
    "resolve_array_roles",
    "resolve_gradient_level",
    "resolve_port_mapping",
    "rheology",
    "rom",
    "sampling",
    "sensing",
    "series",
    "service",
    "signal",
    "smart_materials",
    "solver",
    "sparse",
    "spatial_sampling",
    "special",
    "statistical_dynamics",
    "stochastic",
    "strict_module_payload",
    "structural_dynamics",
    "supports_derivative",
    "surface_chemistry",
    "system_modeling",
    "tensor_decomposition",
    "tensor_network",
    "tensor_train",
    "terms",
    "thermal_systems",
    "topology",
    "transport",
    "tribology",
    "units",
    "uq",
    "variational",
    "velocimetry",
    "weakest_level",
    "weighting",
]
