#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#
# ruff: noqa: F822, I001

"""Execution bootstrap, planning, worksets, observation, and checkpoints."""

from importlib import import_module
from typing import Any

from ._execution_bootstrap import (
    initialize,
    initialize_from_environment,
    runtime_info,
    RuntimeBootstrap,
    RuntimeInfo,
)


_SYMBOL_MODULES = {
    "AbstractIterationObserver": "._iteration",
    "AbstractIterationStopRule": "._iteration",
    "CallableIterationHostControl": "._iteration",
    "BoundedThreadTaskExecutor": "._execution_tasks",
    "CallableIterationObserver": "._iteration",
    "CallableIterationSink": "._iteration",
    "CallableIterationStopRule": "._iteration",
    "CancellationMode": "._execution_control",
    "CancellationToken": "._execution_control",
    "AxisBinding": "._execution_plan",
    "DeterminismScope": "._execution_resources",
    "DeviceResource": "._execution_resources",
    "DistributedIndexEpochPlan": "._data_plane",
    "DistributedObservationPolicy": "._execution_control",
    "DistributionMode": "._execution_resources",
    "ExecutionAdmissionError": "._execution_plan",
    "ExecutionCandidate": "._execution_plan",
    "ExecutionGroup": "._execution_runtime",
    "ExecutionGroupSpec": "._execution_resources",
    "ExecutionPlan": "._execution_plan",
    "ExecutionPolicy": "._execution_resources",
    "ExecutionRequirements": "._execution_plan",
    "ExecutionCancelledError": "._execution_control",
    "ExecutionFailureContext": "._execution_control",
    "FutureTaskHandle": "._execution_tasks",
    "ExecutionRuntime": "._execution_runtime",
    "ExecutionWorksetCheckpoint": "._execution_workset",
    "ExecutionWorksetEvaluation": "._execution_workset",
    "ExecutionWorksetEvidence": "._execution_workset",
    "ExecutionWorksetPlan": "._execution_workset",
    "FailureScope": "._execution_control",
    "HostTaskExecutor": "._execution_tasks",
    "global_weighted_mean": "._execution_array",
    "HostIterationEvent": "._iteration",
    "ImmediateTaskHandle": "._execution_tasks",
    "InlineTaskExecutor": "._execution_tasks",
    "IterationCapabilities": "._iteration",
    "IterationChildPlan": "._iteration",
    "IterationCoordinates": "._iteration",
    "IterationCountObserver": "._iteration",
    "IterationCounts": "._iteration",
    "IterationDecision": "._iteration",
    "IterationEvidence": "._iteration",
    "IterationGranularity": "._iteration",
    "IterationHostControl": "._iteration",
    "IterationMomentObserver": "._iteration",
    "IterationMoments": "._iteration",
    "IterationPhase": "._iteration",
    "IterationPlan": "._iteration",
    "LocalProcessLaunchError": "._execution_launch",
    "LocalProcessLaunchPlan": "._execution_launch",
    "LocalProcessResult": "._execution_launch",
    "IterationRecord": "._iteration",
    "IterationScope": "._iteration",
    "IterationSession": "._iteration",
    "IterationSessionState": "._iteration",
    "IterationSink": "._iteration",
    "IterationTrace": "._iteration",
    "IterationTraceObserver": "._iteration",
    "HostObservation": "._execution_control",
    "LogicalAxis": "._execution_plan",
    "LogicalAxisKind": "._execution_plan",
    "PlacementKind": "._execution_plan",
    "ObservationScope": "._execution_control",
    "PoolExecutionSignature": "._execution_pool",
    "PreparedExecutionWorksets": "._execution_workset",
    "ProcessLocalBatch": "._data_plane",
    "replicate_tree": "._execution_array",
    "shard_array_axis": "._execution_array",
    "shard_tree_axis": "._execution_array",
    "ProviderBinding": "._execution_plan",
    "RecoveryPolicy": "._execution_resources",
    "RankEnvironment": "._execution_launch",
    "ResourceInventory": "._execution_resources",
    "ResourceRequest": "._execution_resources",
    "TrainingIterationKind": "._training",
    "SpawnedProcessTaskExecutor": "._execution_tasks",
    "TaskHandle": "._execution_tasks",
    "TrainingIterationMetrics": "._training",
    "evaluate_execution_worksets_serial": "._execution_workset",
    "evaluate_execution_worksets_grouped": "._execution_workset",
    "evaluate_execution_worksets_vmap": "._execution_workset",
    "restore_execution_workset_checkpoint": "._execution_workset",
    "global_boolean_consensus": "._execution_control",
    "materialize_observation": "._execution_control",
    "launch_local_processes": "._execution_launch",
    "ValuePlacement": "._execution_plan",
    "bind_execution_group": "._execution_runtime",
    "discover_resource_inventory": "._execution_runtime",
    "make_global_array_from_process_local_data": "._data_plane",
    "partition_execution_group_specs": "._execution_runtime",
    "resolve_execution_plan": "._execution_plan",
    "root_execution_group_spec": "._execution_runtime",
}


def __getattr__(name: str) -> Any:
    module_name = _SYMBOL_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __package__)
    value = module.__dict__[name]
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | _SYMBOL_MODULES.keys())


__all__ = (
    "AbstractIterationObserver",
    "AbstractIterationStopRule",
    "BoundedThreadTaskExecutor",
    "CallableIterationHostControl",
    "CancellationMode",
    "CancellationToken",
    "CallableIterationObserver",
    "CallableIterationSink",
    "CallableIterationStopRule",
    "AxisBinding",
    "DeterminismScope",
    "DeviceResource",
    "DistributedIndexEpochPlan",
    "DistributedObservationPolicy",
    "DistributionMode",
    "ExecutionAdmissionError",
    "ExecutionCandidate",
    "ExecutionGroup",
    "ExecutionGroupSpec",
    "ExecutionPlan",
    "ExecutionPolicy",
    "ExecutionRequirements",
    "ExecutionRuntime",
    "ExecutionCancelledError",
    "ExecutionFailureContext",
    "FutureTaskHandle",
    "ExecutionWorksetCheckpoint",
    "FailureScope",
    "HostTaskExecutor",
    "global_weighted_mean",
    "ImmediateTaskHandle",
    "InlineTaskExecutor",
    "ExecutionWorksetEvaluation",
    "ExecutionWorksetEvidence",
    "ExecutionWorksetPlan",
    "HostIterationEvent",
    "IterationCapabilities",
    "IterationChildPlan",
    "IterationCoordinates",
    "IterationCountObserver",
    "IterationCounts",
    "IterationDecision",
    "IterationEvidence",
    "IterationGranularity",
    "IterationHostControl",
    "IterationMomentObserver",
    "IterationMoments",
    "LocalProcessLaunchError",
    "LocalProcessLaunchPlan",
    "LocalProcessResult",
    "IterationPhase",
    "IterationPlan",
    "IterationRecord",
    "IterationScope",
    "IterationSession",
    "IterationSessionState",
    "IterationSink",
    "HostObservation",
    "IterationTrace",
    "IterationTraceObserver",
    "LogicalAxis",
    "LogicalAxisKind",
    "ObservationScope",
    "PlacementKind",
    "PoolExecutionSignature",
    "replicate_tree",
    "shard_array_axis",
    "shard_tree_axis",
    "PreparedExecutionWorksets",
    "ProcessLocalBatch",
    "RankEnvironment",
    "ProviderBinding",
    "RecoveryPolicy",
    "ResourceInventory",
    "ResourceRequest",
    "RuntimeBootstrap",
    "RuntimeInfo",
    "TrainingIterationKind",
    "TrainingIterationMetrics",
    "evaluate_execution_worksets_serial",
    "evaluate_execution_worksets_vmap",
    "initialize",
    "initialize_from_environment",
    "SpawnedProcessTaskExecutor",
    "TaskHandle",
    "restore_execution_workset_checkpoint",
    "runtime_info",
    "ValuePlacement",
    "bind_execution_group",
    "evaluate_execution_worksets_grouped",
    "discover_resource_inventory",
    "make_global_array_from_process_local_data",
    "global_boolean_consensus",
    "materialize_observation",
    "partition_execution_group_specs",
    "launch_local_processes",
    "resolve_execution_plan",
    "root_execution_group_spec",
)
