#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Deterministic execution worksets, iteration observation, and checkpoints."""

from ._execution_pool import PoolExecutionSignature
from ._execution_workset import (
    evaluate_execution_worksets_serial,
    evaluate_execution_worksets_vmap,
    ExecutionWorksetCheckpoint,
    ExecutionWorksetEvaluation,
    ExecutionWorksetEvidence,
    ExecutionWorksetPlan,
    PreparedExecutionWorksets,
    restore_execution_workset_checkpoint,
)
from ._iteration import (
    AbstractIterationObserver,
    AbstractIterationStopRule,
    CallableIterationHostControl,
    CallableIterationObserver,
    CallableIterationSink,
    CallableIterationStopRule,
    HostIterationEvent,
    IterationCapabilities,
    IterationChildPlan,
    IterationCoordinates,
    IterationCountObserver,
    IterationCounts,
    IterationDecision,
    IterationEvidence,
    IterationGranularity,
    IterationHostControl,
    IterationMomentObserver,
    IterationMoments,
    IterationPhase,
    IterationPlan,
    IterationRecord,
    IterationScope,
    IterationSession,
    IterationSessionState,
    IterationSink,
    IterationTrace,
    IterationTraceObserver,
)
from ._training import TrainingIterationKind, TrainingIterationMetrics


__all__ = [
    "AbstractIterationObserver",
    "AbstractIterationStopRule",
    "CallableIterationHostControl",
    "CallableIterationObserver",
    "CallableIterationSink",
    "CallableIterationStopRule",
    "ExecutionWorksetCheckpoint",
    "ExecutionWorksetEvaluation",
    "ExecutionWorksetEvidence",
    "ExecutionWorksetPlan",
    "HostIterationEvent",
    "IterationCapabilities",
    "IterationChildPlan",
    "IterationCoordinates",
    "IterationCountObserver",
    "IterationCounts",
    "IterationDecision",
    "IterationEvidence",
    "IterationGranularity",
    "IterationHostControl",
    "IterationMomentObserver",
    "IterationMoments",
    "IterationPhase",
    "IterationPlan",
    "IterationRecord",
    "IterationScope",
    "IterationSession",
    "IterationSessionState",
    "IterationSink",
    "IterationTrace",
    "IterationTraceObserver",
    "TrainingIterationKind",
    "TrainingIterationMetrics",
    "PoolExecutionSignature",
    "PreparedExecutionWorksets",
    "evaluate_execution_worksets_serial",
    "evaluate_execution_worksets_vmap",
    "restore_execution_workset_checkpoint",
]
