#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Stochastic-feedback control problems, solvers, and evidence."""

from ._belief_lqg import (
    BeliefFeedbackPolicy,
    CentralizedLQGProblem,
    CentralizedLQGResult,
    CentralizedLQGStatus,
    finite_horizon_centralized_lqg,
)
from ._evaluation import (
    compare_feedback_policies,
    ControlledPathBatch,
    ControlledTransitionProblem,
    evaluate_feedback_policy,
    FeedbackPolicyEvaluation,
    FeedbackPolicyEvaluationStatus,
    MonteCarloEvidence,
    PairedPolicyComparison,
    PreparedControlledNoise,
    rollout_feedback,
)
from ._fitted_bellman import (
    bridge_fitted_bellman_to_bsde,
    evaluate_fitted_bellman,
    fit_frozen_policy_bellman,
    FittedBellmanBSDEBridge,
    FittedBellmanPlan,
    FittedBellmanPrepared,
    FittedBellmanProblem,
    FittedBellmanResult,
    FittedBellmanStatus,
    FROZEN_POLICY_FITTED_BELLMAN,
    prepare_fitted_bellman,
)
from ._hjb import (
    BoundedUniformGrid1D,
    DiscreteHJBEvidence,
    DiscreteHJBProblem,
    DiscreteHJBRefinementResult,
    DiscreteHJBResult,
    DiscreteHJBStatus,
    refine_discrete_hjb_reference,
    solve_discrete_hjb_reference,
)
from ._lqg import (
    finite_horizon_lqg_state_feedback,
    FiniteHorizonLQGStateFeedbackResult,
    LQGStateFeedbackStatus,
)
from ._mean_field_control import (
    evaluate_mean_field_control_planner,
    MEAN_FIELD_CONTROL_PLANNER_STATIONARITY,
    MeanFieldControlProblem,
    MeanFieldControlResult,
    MeanFieldControlStatus,
    MeanFieldExternality,
    MeanFieldExternalityMode,
    MINIMUM_MEAN_FIELD_CONTROL_EFFECTIVE_SAMPLE_SIZE,
)
from ._multiplicative_lq import (
    finite_horizon_multiplicative_lq_state_feedback,
    FiniteHorizonMultiplicativeLQStateFeedbackDiagnostics,
    FiniteHorizonMultiplicativeLQStateFeedbackResult,
    MultiplicativeLQStateFeedbackStatus,
)
from ._smp import (
    evaluate_stochastic_maximum_principle,
    SMPAdjointPredictor,
    SMPCausalInformationEvidence,
    SMPMartingaleIntegrandPredictor,
    SMPPathClusterEvidence,
    StochasticMaximumPrincipleProblem,
    StochasticMaximumPrincipleResult,
    StochasticMaximumPrincipleStatus,
)


__all__ = [
    "BeliefFeedbackPolicy",
    "BoundedUniformGrid1D",
    "CentralizedLQGProblem",
    "CentralizedLQGResult",
    "CentralizedLQGStatus",
    "ControlledPathBatch",
    "ControlledTransitionProblem",
    "DiscreteHJBEvidence",
    "DiscreteHJBProblem",
    "DiscreteHJBRefinementResult",
    "DiscreteHJBResult",
    "DiscreteHJBStatus",
    "FROZEN_POLICY_FITTED_BELLMAN",
    "FeedbackPolicyEvaluation",
    "FeedbackPolicyEvaluationStatus",
    "FiniteHorizonLQGStateFeedbackResult",
    "FiniteHorizonMultiplicativeLQStateFeedbackDiagnostics",
    "FiniteHorizonMultiplicativeLQStateFeedbackResult",
    "FittedBellmanBSDEBridge",
    "FittedBellmanPlan",
    "FittedBellmanPrepared",
    "FittedBellmanProblem",
    "FittedBellmanResult",
    "FittedBellmanStatus",
    "LQGStateFeedbackStatus",
    "MEAN_FIELD_CONTROL_PLANNER_STATIONARITY",
    "MINIMUM_MEAN_FIELD_CONTROL_EFFECTIVE_SAMPLE_SIZE",
    "MeanFieldControlProblem",
    "MeanFieldControlResult",
    "MeanFieldControlStatus",
    "MeanFieldExternality",
    "MeanFieldExternalityMode",
    "MonteCarloEvidence",
    "MultiplicativeLQStateFeedbackStatus",
    "PairedPolicyComparison",
    "PreparedControlledNoise",
    "SMPAdjointPredictor",
    "SMPCausalInformationEvidence",
    "SMPMartingaleIntegrandPredictor",
    "SMPPathClusterEvidence",
    "StochasticMaximumPrincipleProblem",
    "StochasticMaximumPrincipleResult",
    "StochasticMaximumPrincipleStatus",
    "bridge_fitted_bellman_to_bsde",
    "compare_feedback_policies",
    "evaluate_feedback_policy",
    "evaluate_fitted_bellman",
    "evaluate_mean_field_control_planner",
    "evaluate_stochastic_maximum_principle",
    "finite_horizon_centralized_lqg",
    "finite_horizon_lqg_state_feedback",
    "finite_horizon_multiplicative_lq_state_feedback",
    "fit_frozen_policy_bellman",
    "prepare_fitted_bellman",
    "refine_discrete_hjb_reference",
    "rollout_feedback",
    "solve_discrete_hjb_reference",
]
