#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from typing import Any, Literal

import jax.numpy as jnp

from ..._strict import StrictModule
from ...domain._function import DomainFunction
from .._composition import pullback
from ..differential._domain_ops import dt, grad
from ..linalg._ops import einsum
from ._lagrangian import _require_factor


_ADEngine = Literal["auto", "reverse", "forward", "jvp"]


class _VectorValueCallable(StrictModule):
    function: DomainFunction

    def __init__(self, function: DomainFunction):
        self.function = function

    def __call__(self, *args: Any, key=None, **kwargs: Any):
        return jnp.atleast_1d(self.function.func(*args, key=key, **kwargs))


class _StackPairCallable(StrictModule):
    first: DomainFunction
    second: DomainFunction
    first_positions: tuple[int, ...]
    second_positions: tuple[int, ...]

    def __init__(
        self,
        first: DomainFunction,
        second: DomainFunction,
        first_positions: tuple[int, ...],
        second_positions: tuple[int, ...],
    ):
        self.first = first
        self.second = second
        self.first_positions = first_positions
        self.second_positions = second_positions

    def __call__(self, *args: Any, key=None, **kwargs: Any):
        first_args = tuple(args[position] for position in self.first_positions)
        second_args = tuple(args[position] for position in self.second_positions)
        first_value = jnp.atleast_1d(
            self.first.func(*first_args, key=key, **kwargs)
        )
        second_value = jnp.atleast_1d(
            self.second.func(*second_args, key=key, **kwargs)
        )
        return jnp.concatenate((first_value, second_value), axis=-1)


def _compatible_domain(a: DomainFunction, b: DomainFunction, /):
    if a.domain.labels != b.domain.labels:
        return a.domain.join(b.domain)
    for label in a.domain.labels:
        if (
            a.domain.factor(label).var_dim
            != b.domain.factor(label).var_dim
        ):
            raise ValueError(
                f"Incompatible domain factors for shared label {label!r}."
            )
    return a.domain


def _as_vector(function: DomainFunction, /) -> DomainFunction:
    return DomainFunction(
        domain=function.domain,
        deps=function.deps,
        func=_VectorValueCallable(function),
        metadata=function.metadata,
    )


def _stack_pair(first: DomainFunction, second: DomainFunction, /) -> DomainFunction:
    domain = _compatible_domain(first, second)
    first_ = first.promote(domain)
    second_ = second.promote(domain)
    deps = tuple(
        label
        for label in domain.labels
        if label in first_.deps or label in second_.deps
    )
    positions = {label: index for index, label in enumerate(deps)}
    return DomainFunction(
        domain=domain,
        deps=deps,
        func=_StackPairCallable(
            first_,
            second_,
            tuple(positions[label] for label in first_.deps),
            tuple(positions[label] for label in second_.deps),
        ),
        metadata={},
    )


def _canonical_gradients(
    function: DomainFunction,
    /,
    *,
    configuration_var: str,
    momentum_var: str,
    mode: Literal["reverse", "forward"],
    ad_engine: _ADEngine,
) -> tuple[DomainFunction, DomainFunction]:
    configuration_factor = _require_factor(
        function, configuration_var, role="Configuration"
    )
    momentum_factor = _require_factor(function, momentum_var, role="Momentum")
    if configuration_factor.var_dim != momentum_factor.var_dim:
        raise ValueError(
            "Canonical phase-space dimensions must match; "
            f"{configuration_var!r} has dimension {configuration_factor.var_dim} and "
            f"{momentum_var!r} has dimension {momentum_factor.var_dim}."
        )
    d_configuration = grad(
        function,
        var=configuration_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    d_momentum = grad(
        function,
        var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    return d_configuration, d_momentum


def canonical_hamiltonian_vector_field(
    hamiltonian: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    momentum_var: str = "p",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical Hamiltonian vector field generated by a scalar Hamiltonian.

    The returned field has the last-axis layout ``[dq/dt, dp/dt]`` and equals

    $$
    X_H = \begin{bmatrix}\nabla_p H \\ -\nabla_q H\end{bmatrix}.
    $$
    """
    d_configuration, d_momentum = _canonical_gradients(
        hamiltonian,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    return _stack_pair(d_momentum, -d_configuration)


def poisson_bracket(
    f: DomainFunction,
    g: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    momentum_var: str = "p",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical Poisson bracket of two scalar phase-space functions.

    $$
    \{F,G\}=\nabla_qF\cdot\nabla_pG-\nabla_pF\cdot\nabla_qG.
    $$
    """
    f_q, f_p = _canonical_gradients(
        f,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    g_q, g_p = _canonical_gradients(
        g,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    return einsum("...i,...i->...", _as_vector(f_q), _as_vector(g_p)) - einsum(
        "...i,...i->...", _as_vector(f_p), _as_vector(g_q)
    )


def canonical_hamiltonian_residual(
    configuration: DomainFunction,
    momentum: DomainFunction,
    hamiltonian: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    momentum_var: str = "p",
    time_var: str = "t",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical Hamilton-equation residual along a phase trajectory.

    The returned field stacks

    $$
    r_q=\dot q-\nabla_pH,\qquad r_p=\dot p+\nabla_qH.
    $$
    """
    if time_var not in configuration.deps or time_var not in momentum.deps:
        raise ValueError(
            f"Configuration and momentum trajectories must depend on {time_var!r}."
        )
    target_domain = _compatible_domain(configuration, momentum)
    configuration_ = configuration.promote(target_domain)
    momentum_ = momentum.promote(target_domain)

    d_configuration, d_momentum = _canonical_gradients(
        hamiltonian,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    substitutions = {
        configuration_var: configuration_,
        momentum_var: momentum_,
    }
    d_configuration_path = pullback(
        d_configuration,
        substitutions,
        domain=target_domain,
    )
    d_momentum_path = pullback(
        d_momentum,
        substitutions,
        domain=target_domain,
    )
    configuration_residual = (
        dt(
            configuration_,
            var=time_var,
            mode=mode,
            ad_engine=ad_engine,
        )
        - d_momentum_path
    )
    momentum_residual = (
        dt(
            momentum_,
            var=time_var,
            mode=mode,
            ad_engine=ad_engine,
        )
        + d_configuration_path
    )
    return _stack_pair(configuration_residual, momentum_residual)


def hamilton_jacobi_residual(
    action: DomainFunction,
    hamiltonian: DomainFunction,
    /,
    *,
    position_var: str = "x",
    momentum_var: str = "p",
    time_var: str = "t",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Hamilton–Jacobi residual $\partial_tS+H(x,\nabla_xS,t)$."""
    if time_var not in action.deps:
        raise ValueError(f"Action must depend on time_var {time_var!r}.")
    action_position_factor = _require_factor(action, position_var, role="Position")
    hamiltonian_position_factor = _require_factor(
        hamiltonian, position_var, role="Hamiltonian position"
    )
    hamiltonian_momentum_factor = _require_factor(
        hamiltonian, momentum_var, role="Hamiltonian momentum"
    )
    if action_position_factor.var_dim != hamiltonian_position_factor.var_dim:
        raise ValueError("Action and Hamiltonian position dimensions are incompatible.")
    if hamiltonian_position_factor.var_dim != hamiltonian_momentum_factor.var_dim:
        raise ValueError("Hamiltonian position and momentum dimensions must match.")

    momentum = grad(
        action,
        var=position_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    hamiltonian_path = pullback(
        hamiltonian,
        {momentum_var: momentum},
        domain=action.domain,
    )
    return dt(
        action,
        var=time_var,
        mode=mode,
        ad_engine=ad_engine,
    ) + hamiltonian_path


__all__ = [
    "canonical_hamiltonian_residual",
    "canonical_hamiltonian_vector_field",
    "hamilton_jacobi_residual",
    "poisson_bracket",
]
