#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from typing import Any, Literal

import jax.numpy as jnp

import phydrax.ein as ein
from phydrax.domain import DomainFunction

from ..._strict import StrictModule
from ...metrix import (
    PoissonStructure,
    symplectic_to_poisson,
    SymplecticForm,
)
from .._composition import pullback
from ..differential._domain_ops import dt, grad
from ..linalg._ops import einsum
from ._lagrangian import _require_factor


_ADEngine = Literal["auto", "reverse", "forward", "jvp"]


class _VectorValueCallable(StrictModule):
    function: DomainFunction

    def __init__(self, function: DomainFunction):
        self.function = function

    def __call__(self, *args: Any, key=None, **kwargs: Any):
        return jnp.atleast_1d(self.function.func(*args, key=key, **kwargs))


class _StackPairCallable(StrictModule):
    first: DomainFunction
    second: DomainFunction
    first_positions: tuple[int, ...]
    second_positions: tuple[int, ...]

    def __init__(
        self,
        first: DomainFunction,
        second: DomainFunction,
        first_positions: tuple[int, ...],
        second_positions: tuple[int, ...],
    ):
        self.first = first
        self.second = second
        self.first_positions = first_positions
        self.second_positions = second_positions

    def __call__(self, *args: Any, key=None, **kwargs: Any):
        first_args = tuple(args[position] for position in self.first_positions)
        second_args = tuple(args[position] for position in self.second_positions)
        first_value = jnp.atleast_1d(self.first.func(*first_args, key=key, **kwargs))
        second_value = jnp.atleast_1d(self.second.func(*second_args, key=key, **kwargs))
        return jnp.concatenate((first_value, second_value), axis=-1)


def _compatible_domain(a: DomainFunction, b: DomainFunction, /):
    if a.domain.labels != b.domain.labels:
        return a.domain.join(b.domain)
    for label in a.domain.labels:
        if not a.domain.coordinate(label).compatible(b.domain.coordinate(label)):
            raise ValueError(f"Incompatible domain factors for shared label {label!r}.")
    return a.domain


def _as_vector(function: DomainFunction, /) -> DomainFunction:
    return DomainFunction(
        domain=function.domain,
        deps=function.deps,
        func=_VectorValueCallable(function),
        metadata=function.metadata,
    )


def _stack_pair(first: DomainFunction, second: DomainFunction, /) -> DomainFunction:
    domain = _compatible_domain(first, second)
    first_ = first.promote(domain)
    second_ = second.promote(domain)
    deps = tuple(
        label for label in domain.labels if label in first_.deps or label in second_.deps
    )
    positions = {label: index for index, label in enumerate(deps)}
    return DomainFunction(
        domain=domain,
        deps=deps,
        func=_StackPairCallable(
            first_,
            second_,
            tuple(positions[label] for label in first_.deps),
            tuple(positions[label] for label in second_.deps),
        ),
        metadata={},
    )


def _canonical_gradients(
    function: DomainFunction,
    /,
    *,
    configuration_var: str,
    momentum_var: str,
    mode: Literal["reverse", "forward"],
    ad_engine: _ADEngine,
) -> tuple[DomainFunction, DomainFunction]:
    _require_factor(function, configuration_var, role="Configuration")
    _require_factor(function, momentum_var, role="Momentum")
    configuration_dimension = function.domain.coordinate(configuration_var).event_size
    momentum_dimension = function.domain.coordinate(momentum_var).event_size
    if configuration_dimension != momentum_dimension:
        raise ValueError(
            "Canonical phase-space dimensions must match; "
            f"{configuration_var!r} has dimension {configuration_dimension} and "
            f"{momentum_var!r} has dimension {momentum_dimension}."
        )
    d_configuration = grad(
        function,
        var=configuration_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    d_momentum = grad(
        function,
        var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    return d_configuration, d_momentum


def canonical_hamiltonian_vector_field(
    hamiltonian: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    momentum_var: str = "p",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical Hamiltonian vector field generated by a scalar Hamiltonian.

    The returned field has the last-axis layout ``[dq/dt, dp/dt]`` and equals

    $$
    X_H = \begin{bmatrix}\nabla_p H \\ -\nabla_q H\end{bmatrix}.
    $$
    """
    d_configuration, d_momentum = _canonical_gradients(
        hamiltonian,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    return _stack_pair(d_momentum, -d_configuration)


def canonical_poisson_bracket(
    f: DomainFunction,
    g: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    momentum_var: str = "p",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical Poisson bracket of two scalar phase-space functions.

    $$
    \{F,G\}=\nabla_qF\cdot\nabla_pG-\nabla_pF\cdot\nabla_qG.
    $$
    """
    f_q, f_p = _canonical_gradients(
        f,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    g_q, g_p = _canonical_gradients(
        g,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    return einsum("...i,...i->...", _as_vector(f_q), _as_vector(g_p)) - einsum(
        "...i,...i->...", _as_vector(f_p), _as_vector(g_q)
    )


class _PoissonBracketCallable(StrictModule):
    left_derivatives: tuple[DomainFunction, ...]
    right_derivatives: tuple[DomainFunction, ...]
    poisson: PoissonStructure
    left_positions: tuple[tuple[int, ...], ...]
    right_positions: tuple[tuple[int, ...], ...]
    coordinate_positions: tuple[int, ...]

    def __init__(
        self,
        left_derivatives: tuple[DomainFunction, ...],
        right_derivatives: tuple[DomainFunction, ...],
        poisson: PoissonStructure,
        deps: tuple[str, ...],
        variables: tuple[str, ...],
        /,
    ):
        positions = {label: index for index, label in enumerate(deps)}
        self.left_derivatives = left_derivatives
        self.right_derivatives = right_derivatives
        self.poisson = poisson
        self.left_positions = tuple(
            tuple(positions[label] for label in derivative.deps)
            for derivative in left_derivatives
        )
        self.right_positions = tuple(
            tuple(positions[label] for label in derivative.deps)
            for derivative in right_derivatives
        )
        self.coordinate_positions = tuple(positions[label] for label in variables)

    def __call__(self, *args: Any, key=None, **kwargs: Any):
        left = jnp.concatenate(
            tuple(
                jnp.atleast_1d(
                    derivative.func(
                        *[args[position] for position in positions],
                        key=key,
                        **kwargs,
                    )
                )
                for derivative, positions in zip(
                    self.left_derivatives, self.left_positions, strict=True
                )
            ),
            axis=-1,
        )
        right = jnp.concatenate(
            tuple(
                jnp.atleast_1d(
                    derivative.func(
                        *[args[position] for position in positions],
                        key=key,
                        **kwargs,
                    )
                )
                for derivative, positions in zip(
                    self.right_derivatives, self.right_positions, strict=True
                )
            ),
            axis=-1,
        )
        coordinates = jnp.concatenate(
            tuple(
                jnp.atleast_1d(args[position]) for position in self.coordinate_positions
            ),
            axis=-1,
        )
        return ein.contract(
            "...i,...ij,...j->...",
            left,
            self.poisson(coordinates),
            right,
        )


class _PoissonHamiltonianCallable(StrictModule):
    derivatives: tuple[DomainFunction, ...]
    poisson: PoissonStructure
    derivative_positions: tuple[tuple[int, ...], ...]
    coordinate_positions: tuple[int, ...]

    def __init__(
        self,
        derivatives: tuple[DomainFunction, ...],
        poisson: PoissonStructure,
        deps: tuple[str, ...],
        variables: tuple[str, ...],
        /,
    ):
        positions = {label: index for index, label in enumerate(deps)}
        self.derivatives = derivatives
        self.poisson = poisson
        self.derivative_positions = tuple(
            tuple(positions[label] for label in derivative.deps)
            for derivative in derivatives
        )
        self.coordinate_positions = tuple(positions[label] for label in variables)

    def __call__(self, *args: Any, key=None, **kwargs: Any):
        differential = jnp.concatenate(
            tuple(
                jnp.atleast_1d(
                    derivative.func(
                        *[args[position] for position in positions],
                        key=key,
                        **kwargs,
                    )
                )
                for derivative, positions in zip(
                    self.derivatives, self.derivative_positions, strict=True
                )
            ),
            axis=-1,
        )
        coordinates = jnp.concatenate(
            tuple(
                jnp.atleast_1d(args[position]) for position in self.coordinate_positions
            ),
            axis=-1,
        )
        return ein.contract(
            "...ij,...j->...i",
            self.poisson(coordinates),
            differential,
        )


def _poisson_contract(
    function: DomainFunction,
    structure: PoissonStructure | SymplecticForm,
    variables: tuple[str, ...],
    /,
) -> tuple[PoissonStructure, int]:
    if not variables or len(set(variables)) != len(variables):
        raise ValueError("variables must be a nonempty tuple of unique domain labels.")
    poisson = (
        symplectic_to_poisson(structure)
        if isinstance(structure, SymplecticForm)
        else structure
    )
    if not isinstance(poisson, PoissonStructure):
        raise TypeError("structure must be a PoissonStructure or SymplecticForm.")
    dimension = 0
    for variable in variables:
        _require_factor(function, variable, role="Poisson phase")
        dimension += function.domain.coordinate(variable).event_size
    if dimension != poisson.chart.dimension:
        raise ValueError(
            f"Poisson chart dimension {poisson.chart.dimension} does not match "
            f"combined phase-variable dimension {dimension}."
        )
    return poisson, dimension


def poisson_bracket(
    left: DomainFunction,
    right: DomainFunction,
    structure: PoissonStructure | SymplecticForm,
    /,
    *,
    variables: tuple[str, ...],
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    """Poisson bracket on one or more labeled phase-space variables."""
    domain = _compatible_domain(left, right)
    left_function = left.promote(domain)
    right_function = right.promote(domain)
    poisson, _ = _poisson_contract(left_function, structure, variables)
    _poisson_contract(right_function, poisson, variables)
    left_derivatives = tuple(
        grad(left_function, var=variable, mode=mode, ad_engine=ad_engine)
        for variable in variables
    )
    right_derivatives = tuple(
        grad(right_function, var=variable, mode=mode, ad_engine=ad_engine)
        for variable in variables
    )
    deps = tuple(
        label
        for label in domain.labels
        if label in variables
        or any(label in derivative.deps for derivative in left_derivatives)
        or any(label in derivative.deps for derivative in right_derivatives)
    )
    return DomainFunction(
        domain=domain,
        deps=deps,
        func=_PoissonBracketCallable(
            left_derivatives,
            right_derivatives,
            poisson,
            deps,
            variables,
        ),
        metadata={},
    )


def hamiltonian_vector_field(
    hamiltonian: DomainFunction,
    structure: PoissonStructure | SymplecticForm,
    /,
    *,
    variables: tuple[str, ...],
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    """Hamiltonian vector field for a declared Poisson or symplectic structure."""
    poisson, _ = _poisson_contract(hamiltonian, structure, variables)
    derivatives = tuple(
        grad(hamiltonian, var=variable, mode=mode, ad_engine=ad_engine)
        for variable in variables
    )
    deps = tuple(
        label
        for label in hamiltonian.domain.labels
        if label in variables
        or any(label in derivative.deps for derivative in derivatives)
    )
    return DomainFunction(
        domain=hamiltonian.domain,
        deps=deps,
        func=_PoissonHamiltonianCallable(
            derivatives,
            poisson,
            deps,
            variables,
        ),
        metadata=hamiltonian.metadata,
    )


def canonical_hamiltonian_residual(
    configuration: DomainFunction,
    momentum: DomainFunction,
    hamiltonian: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    momentum_var: str = "p",
    time_var: str = "t",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical Hamilton-equation residual along a phase trajectory.

    The returned field stacks

    $$
    r_q=\dot q-\nabla_pH,\qquad r_p=\dot p+\nabla_qH.
    $$
    """
    if time_var not in configuration.deps or time_var not in momentum.deps:
        raise ValueError(
            f"Configuration and momentum trajectories must depend on {time_var!r}."
        )
    target_domain = _compatible_domain(configuration, momentum)
    configuration_ = configuration.promote(target_domain)
    momentum_ = momentum.promote(target_domain)

    d_configuration, d_momentum = _canonical_gradients(
        hamiltonian,
        configuration_var=configuration_var,
        momentum_var=momentum_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    substitutions = {
        configuration_var: configuration_,
        momentum_var: momentum_,
    }
    d_configuration_path = pullback(
        d_configuration,
        substitutions,
        domain=target_domain,
    )
    d_momentum_path = pullback(
        d_momentum,
        substitutions,
        domain=target_domain,
    )
    configuration_residual = (
        dt(
            configuration_,
            var=time_var,
            mode=mode,
            ad_engine=ad_engine,
        )
        - d_momentum_path
    )
    momentum_residual = (
        dt(
            momentum_,
            var=time_var,
            mode=mode,
            ad_engine=ad_engine,
        )
        + d_configuration_path
    )
    return _stack_pair(configuration_residual, momentum_residual)


def hamilton_jacobi_residual(
    action: DomainFunction,
    hamiltonian: DomainFunction,
    /,
    *,
    position_var: str = "x",
    momentum_var: str = "p",
    time_var: str = "t",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Hamilton–Jacobi residual $\partial_tS+H(x,\nabla_xS,t)$."""
    if time_var not in action.deps:
        raise ValueError(f"Action must depend on time_var {time_var!r}.")
    _require_factor(action, position_var, role="Position")
    _require_factor(hamiltonian, position_var, role="Hamiltonian position")
    _require_factor(hamiltonian, momentum_var, role="Hamiltonian momentum")
    action_position_dimension = action.domain.coordinate(position_var).event_size
    hamiltonian_position_dimension = hamiltonian.domain.coordinate(
        position_var
    ).event_size
    hamiltonian_momentum_dimension = hamiltonian.domain.coordinate(
        momentum_var
    ).event_size
    if action_position_dimension != hamiltonian_position_dimension:
        raise ValueError("Action and Hamiltonian position dimensions are incompatible.")
    if hamiltonian_position_dimension != hamiltonian_momentum_dimension:
        raise ValueError("Hamiltonian position and momentum dimensions must match.")

    momentum = grad(
        action,
        var=position_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    hamiltonian_path = pullback(
        hamiltonian,
        {momentum_var: momentum},
        domain=action.domain,
    )
    return (
        dt(
            action,
            var=time_var,
            mode=mode,
            ad_engine=ad_engine,
        )
        + hamiltonian_path
    )


__all__ = [
    "canonical_hamiltonian_residual",
    "canonical_hamiltonian_vector_field",
    "canonical_poisson_bracket",
    "hamiltonian_vector_field",
    "hamilton_jacobi_residual",
    "poisson_bracket",
]
