#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from typing import Literal

from jaxtyping import ArrayLike

from phydrax.domain import DomainFunction

from .._composition import pullback
from ..differential._domain_ops import dt, grad


_ADEngine = Literal["auto", "reverse", "forward", "jvp"]


def _require_factor(function: DomainFunction, label: str, /, *, role: str):
    if label not in function.domain.labels:
        raise ValueError(
            f"{role} label {label!r} is absent from domain {function.domain.labels!r}."
        )
    return function.domain.factor(label)


def canonical_momentum(
    lagrangian: DomainFunction,
    /,
    *,
    velocity_var: str = "v",
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Canonical momentum generated by a Lagrangian.

    For a scalar Lagrangian $\mathcal L(q,v,t)$ this constructs

    $$
    p(q,v,t)=\frac{\partial\mathcal L}{\partial v}.
    $$

    `lagrangian` is a `DomainFunction` on a tangent-state domain. It may be an
    analytic function or a trainable model.
    """
    _require_factor(lagrangian, velocity_var, role="Velocity")
    return grad(
        lagrangian,
        var=velocity_var,
        mode=mode,
        ad_engine=ad_engine,
    )


def euler_lagrange(
    trajectory: DomainFunction,
    lagrangian: DomainFunction,
    /,
    *,
    configuration_var: str = "q",
    velocity_var: str = "v",
    time_var: str = "t",
    generalized_force: DomainFunction | ArrayLike | None = None,
    mode: Literal["reverse", "forward"] = "reverse",
    ad_engine: _ADEngine = "auto",
) -> DomainFunction:
    r"""Euler–Lagrange residual along a trajectory.

    Given a trajectory $q(t)$ and scalar tangent-state Lagrangian
    $\mathcal L(q,v,t)$, this constructs

    $$
    \mathcal E_q(\mathcal L)
    = \frac{d}{dt}\frac{\partial\mathcal L}{\partial v}
      - \frac{\partial\mathcal L}{\partial q} - Q.
    $$

    `generalized_force` supplies $Q$ and defaults to zero. The state-space
    derivatives of the Lagrangian are pulled back along
    $(q(t),v(t))=(q(t),\dot q(t))$ before the total time derivative is taken.
    """
    if time_var not in trajectory.deps:
        raise ValueError(
            f"Trajectory must depend on time_var {time_var!r}; got deps={trajectory.deps!r}."
        )

    _require_factor(lagrangian, configuration_var, role="Configuration")
    _require_factor(lagrangian, velocity_var, role="Velocity")
    configuration_dimension = lagrangian.domain.coordinate(configuration_var).event_size
    velocity_dimension = lagrangian.domain.coordinate(velocity_var).event_size
    if configuration_dimension != velocity_dimension:
        raise ValueError(
            "Euler–Lagrange canonical dimensions must match; "
            f"{configuration_var!r} has dimension {configuration_dimension} and "
            f"{velocity_var!r} has dimension {velocity_dimension}."
        )

    velocity = dt(
        trajectory,
        var=time_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    momentum_state = canonical_momentum(
        lagrangian,
        velocity_var=velocity_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    configuration_gradient_state = grad(
        lagrangian,
        var=configuration_var,
        mode=mode,
        ad_engine=ad_engine,
    )
    substitutions = {
        configuration_var: trajectory,
        velocity_var: velocity,
    }
    momentum_path = pullback(
        momentum_state,
        substitutions,
        domain=trajectory.domain,
    )
    configuration_gradient_path = pullback(
        configuration_gradient_state,
        substitutions,
        domain=trajectory.domain,
    )

    residual = (
        dt(
            momentum_path,
            var=time_var,
            mode=mode,
            ad_engine=ad_engine,
        )
        - configuration_gradient_path
    )
    if generalized_force is None:
        return residual
    if isinstance(generalized_force, DomainFunction):
        force = generalized_force
    else:
        force = DomainFunction(
            domain=trajectory.domain,
            deps=(),
            func=generalized_force,
            metadata={},
        )
    return residual - force


__all__ = [
    "canonical_momentum",
    "euler_lagrange",
]
