#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Trajectory preprocessing and dynamical-system identification."""

from ._adapters import (
    trajectory_data_from_control,
    trajectory_data_from_differential_solution,
    trajectory_data_from_evolution,
    trajectory_data_from_fixed_step,
    trajectory_data_from_stochastic,
)
from ._differentiation import (
    bspline_derivative,
    DerivativeEstimate,
    finite_difference_derivative,
    FiniteDifferenceEndpoint,
    local_polynomial_derivative,
)
from ._dmd import (
    DMDDiagnostics,
    DMDMode,
    DMDRankPolicy,
    DMDResult,
    EDMDDiagnostics,
    EDMDResult,
    fit_dmd,
    fit_edmd,
)
from ._features import (
    AbstractFeatureLibrary,
    ConcatenatedFeatureLibrary,
    CustomFeatureLibrary,
    FeatureEvaluation,
    FourierFeatureLibrary,
    PolynomialFeatureLibrary,
    TensorProductFeatureLibrary,
)
from ._implicit import (
    AbstractImplicitFeatureLibrary,
    fit_implicit_sindy,
    ImplicitFeatureLibrary,
    ImplicitSINDyCandidate,
    ImplicitSINDyProblem,
    ImplicitSINDyResult,
    PolynomialImplicitFeatureLibrary,
)
from ._markov_state import (
    fit_markov_state_model,
    MarkovStateDiagnostics,
    MarkovStateModel,
)
from ._neural import (
    DiscreteModelFitHistory,
    DiscreteModelFitResult,
    DiscreteModelRolloutPolicy,
    DiscreteModelValidationPolicy,
    fit_discrete_model,
    ReferenceBranchDiscreteModelObjective,
    ResidualDiscreteModelObjective,
    SupervisedDiscreteModelObjective,
    TargetDiscreteModelObjective,
)
from ._pde import (
    AbstractPDEDerivative,
    AbstractPDEFeatureLibrary,
    FiniteDifferencePDEDerivative,
    fit_pde_find,
    PDEDerivative,
    PDEDerivativeEvaluation,
    PDEFeatureLibrary,
    PDEIdentificationProblem,
    PDEIdentificationResult,
    PDELibraryTerm,
    PolynomialPDELibrary,
    StructuredPDEData,
)
from ._preprocessing import delay_embed
from ._selection import (
    EnsembleSINDyResult,
    fit_ensemble_sindy,
    select_sindy_model,
    SelectionCriterion,
    SINDySelectionPolicy,
    SINDySelectionResult,
)
from ._sindy import fit_sindy, SINDyResult
from ._sindy_design import (
    AbstractSINDyFormulation,
    build_sindy_design,
    DiscreteSINDyFormulation,
    IntegralSINDyFormulation,
    SINDyDesign,
    SINDyDesignDiagnostics,
    SINDyFormulationKind,
    SINDyProblem,
    StrongSINDyFormulation,
    WeakSINDyFormulation,
    WindowBoundary,
    WindowQuadrature,
)
from ._sparse_regression import (
    AbstractSparseRegression,
    SequentialThresholdedLeastSquares,
    SparseRegressionHistory,
    SparseRegressionResult,
    ThresholdSpace,
)
from ._sr3 import SR3Diagnostics, SR3Penalty, SR3Regression
from ._status import (
    IDENTIFICATION_INFEASIBLE,
    IDENTIFICATION_INSUFFICIENT_SAMPLES,
    IDENTIFICATION_NONFINITE,
    IDENTIFICATION_NOT_CONVERGED,
    IDENTIFICATION_RANK_DEFICIENT,
    IDENTIFICATION_SUCCESS,
)
from ._stochastic_transition import (
    LearnedMarginalTransition,
    LearnedPathwiseTransition,
)
from ._structured import (
    CoefficientIndex,
    CoefficientStructure,
    LinearCoefficientConstraint,
    named_coefficient_constraint,
    shared_feature_groups,
    StructuredRegressionDiagnostics,
    StructuredSequentialThresholdedLeastSquares,
)
from ._symmetry import (
    LinearTransformedFeatureLibrary,
    SymmetryAveragedFeatureLibrary,
)
from ._variational_kinetics import (
    fit_tica,
    fit_vac,
    fit_vamp,
    LaggedKineticEvidence,
    LaggedPairWeighting,
    VACDiagnostics,
    VACResult,
    VAMPDiagnostics,
    VAMPModel,
    VAMPResult,
)
from ._variational_training import (
    fit_variational_kinetic_model,
    ModelFeatureLibrary,
    VariationalCoordinateModel,
    VariationalKineticFitHistory,
    VariationalKineticFitResult,
    VariationalKineticTrainingPolicy,
)


__all__ = [
    "AbstractImplicitFeatureLibrary",
    "AbstractPDEDerivative",
    "AbstractPDEFeatureLibrary",
    "AbstractSINDyFormulation",
    "AbstractSparseRegression",
    "AbstractFeatureLibrary",
    "CoefficientIndex",
    "CoefficientStructure",
    "ConcatenatedFeatureLibrary",
    "CustomFeatureLibrary",
    "DMDDiagnostics",
    "DMDMode",
    "DMDRankPolicy",
    "DMDResult",
    "DiscreteSINDyFormulation",
    "DiscreteModelFitHistory",
    "DiscreteModelFitResult",
    "DiscreteModelRolloutPolicy",
    "DiscreteModelValidationPolicy",
    "DerivativeEstimate",
    "EnsembleSINDyResult",
    "FiniteDifferencePDEDerivative",
    "FiniteDifferenceEndpoint",
    "EDMDDiagnostics",
    "IntegralSINDyFormulation",
    "EDMDResult",
    "FeatureEvaluation",
    "ImplicitFeatureLibrary",
    "ImplicitSINDyCandidate",
    "ImplicitSINDyProblem",
    "ImplicitSINDyResult",
    "FourierFeatureLibrary",
    "IDENTIFICATION_INFEASIBLE",
    "IDENTIFICATION_INSUFFICIENT_SAMPLES",
    "IDENTIFICATION_NONFINITE",
    "IDENTIFICATION_NOT_CONVERGED",
    "IDENTIFICATION_RANK_DEFICIENT",
    "LaggedKineticEvidence",
    "LaggedPairWeighting",
    "IDENTIFICATION_SUCCESS",
    "LinearCoefficientConstraint",
    "LinearTransformedFeatureLibrary",
    "PDEDerivative",
    "PDEDerivativeEvaluation",
    "PDEFeatureLibrary",
    "PDEIdentificationProblem",
    "PDEIdentificationResult",
    "PDELibraryTerm",
    "MarkovStateDiagnostics",
    "MarkovStateModel",
    "PolynomialImplicitFeatureLibrary",
    "ModelFeatureLibrary",
    "LearnedMarginalTransition",
    "LearnedPathwiseTransition",
    "ReferenceBranchDiscreteModelObjective",
    "ResidualDiscreteModelObjective",
    "PolynomialPDELibrary",
    "PolynomialFeatureLibrary",
    "TensorProductFeatureLibrary",
    "SequentialThresholdedLeastSquares",
    "SINDyDesign",
    "SINDyDesignDiagnostics",
    "SINDyFormulationKind",
    "SINDyProblem",
    "StrongSINDyFormulation",
    "SR3Diagnostics",
    "SR3Penalty",
    "SR3Regression",
    "SelectionCriterion",
    "SINDySelectionPolicy",
    "SINDySelectionResult",
    "StructuredPDEData",
    "StructuredRegressionDiagnostics",
    "StructuredSequentialThresholdedLeastSquares",
    "SymmetryAveragedFeatureLibrary",
    "SupervisedDiscreteModelObjective",
    "TargetDiscreteModelObjective",
    "WeakSINDyFormulation",
    "VACDiagnostics",
    "VACResult",
    "VAMPDiagnostics",
    "VAMPModel",
    "VariationalCoordinateModel",
    "VariationalKineticFitHistory",
    "VariationalKineticFitResult",
    "VariationalKineticTrainingPolicy",
    "VAMPResult",
    "WindowBoundary",
    "WindowQuadrature",
    "SINDyResult",
    "SparseRegressionHistory",
    "SparseRegressionResult",
    "ThresholdSpace",
    "bspline_derivative",
    "delay_embed",
    "finite_difference_derivative",
    "build_sindy_design",
    "fit_implicit_sindy",
    "fit_discrete_model",
    "fit_pde_find",
    "fit_markov_state_model",
    "fit_dmd",
    "fit_edmd",
    "fit_sindy",
    "fit_tica",
    "fit_vac",
    "fit_vamp",
    "local_polynomial_derivative",
    "fit_variational_kinetic_model",
    "trajectory_data_from_control",
    "trajectory_data_from_differential_solution",
    "trajectory_data_from_fixed_step",
    "fit_ensemble_sindy",
    "select_sindy_model",
    "named_coefficient_constraint",
    "shared_feature_groups",
    "trajectory_data_from_evolution",
    "trajectory_data_from_stochastic",
]
