#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

IDENTIFICATION_SUCCESS = 0
IDENTIFICATION_NONFINITE = 1
IDENTIFICATION_RANK_DEFICIENT = 2
IDENTIFICATION_INSUFFICIENT_SAMPLES = 3
IDENTIFICATION_NOT_CONVERGED = 4
IDENTIFICATION_INFEASIBLE = 5


__all__ = [
    "IDENTIFICATION_INFEASIBLE",
    "IDENTIFICATION_INSUFFICIENT_SAMPLES",
    "IDENTIFICATION_NONFINITE",
    "IDENTIFICATION_NOT_CONVERGED",
    "IDENTIFICATION_RANK_DEFICIENT",
    "IDENTIFICATION_SUCCESS",
]
