#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Classical, quantum, electrothermal and evidence-bounded semiconductor models."""

from . import quantum
from ._analysis import (
    semiconductor_sensitivity,
    semiconductor_small_signal,
    semiconductor_transient,
    SemiconductorLinearEvidence,
    SemiconductorSensitivityResult,
    SemiconductorSmallSignalResult,
    SemiconductorTransientResult,
)
from ._calibration import (
    archive_semiconductor_calibration,
    archive_semiconductor_forward_evaluation,
    calibrate_semiconductor,
    evaluate_semiconductor_forward,
    prepare_semiconductor_calibration,
    PreparedSemiconductorCalibration,
    qualify_semiconductor_calibration,
    semiconductor_identifiability,
    SemiconductorCalibrationCampaign,
    SemiconductorCalibrationCriteria,
    SemiconductorCalibrationDomain,
    SemiconductorCalibrationQualification,
    SemiconductorCalibrationResult,
    SemiconductorForwardEvaluation,
    SemiconductorForwardResult,
    SemiconductorForwardUnresolved,
    SemiconductorIdentifiability,
    SemiconductorMeasurementCase,
    SemiconductorParameterBinding,
    SemiconductorPredictiveCheck,
)
from ._circuit import (
    semiconductor_circuit_operating_point,
    semiconductor_circuit_transient,
    SemiconductorCircuitLaw,
)
from ._continuum import (
    PreparedSemiconductorDevice,
    SemiconductorEvidence,
    SemiconductorOperatingPoint,
    SemiconductorSweepResult,
)
from ._coupled import MaterialInterface, ThermalPort, TrapBinding, TunnelingChannel
from ._device import DevicePlan, GateContact, MaterialBinding, OhmicContact
from ._examples import bipolar_transistor, mos_capacitor, pn_junction
from ._high_field import (
    HighFieldDrivingForce,
    ImpactIonizationEvaluation,
    LocalImpactIonization,
    LocalVelocitySaturation,
    SaturationEvaluation,
)
from ._interfaces import (
    interface_electrostatics,
    InterfaceElectrostaticState,
    InterfaceExchange,
    ThermionicInterface,
)
from ._kinetics import (
    DynamicTrap,
    NonlocalTunnelingEvaluation,
    NonlocalTunnelingPath,
    TrapExchangeEvaluation,
    TrapStepEvaluation,
    TrapStorage,
    WKBBarrierPath,
    WKBTransmissionEvaluation,
)
from ._materials import (
    ConstantMobility,
    DielectricMaterial,
    DopingDependentMobility,
    SemiconductorMaterial,
    srh_recombination,
)
from ._quantities import (
    BOLTZMANN_CONSTANT_SI,
    ELEMENTARY_CHARGE_SI,
    HERTZ_UNIT,
    MOBILITY_UNIT,
    NUMBER_FLUX_UNIT,
    PER_CUBIC_METER,
    PERMITTIVITY_UNIT,
    RECOMBINATION_UNIT,
    SemiconductorQuantitySpec,
    SQUARE_METER,
    VACUUM_PERMITTIVITY_SI,
    WATT_UNIT,
)
from ._state import SemiconductorStateLayout
from ._support import TransportSupport
from ._thermal import (
    CarrierEnergyFluxEvaluation,
    CarrierEnergyRelaxation,
    CarrierEnergyTransport,
    CarrierRelaxationEvaluation,
    ConstantLatticeHeatCapacity,
    LatticeEnergyEvaluation,
    ThermalBoundaryExchange,
    ThermalConductance,
    ThermalExchangeEvaluation,
)
from ._thermodynamics import BandThermodynamics, IncompleteIonization
from ._transfer import (
    semiconductor_adaptation_indicators,
    semiconductor_reprepare,
    SemiconductorAdaptationIndicators,
    SemiconductorTransferEvidence,
    SemiconductorTransferResult,
)


__all__ = [
    "BOLTZMANN_CONSTANT_SI",
    "BandThermodynamics",
    "CarrierEnergyFluxEvaluation",
    "CarrierEnergyRelaxation",
    "CarrierEnergyTransport",
    "CarrierRelaxationEvaluation",
    "ConstantLatticeHeatCapacity",
    "ConstantMobility",
    "DevicePlan",
    "DielectricMaterial",
    "DopingDependentMobility",
    "DynamicTrap",
    "ELEMENTARY_CHARGE_SI",
    "GateContact",
    "HERTZ_UNIT",
    "HighFieldDrivingForce",
    "ImpactIonizationEvaluation",
    "IncompleteIonization",
    "InterfaceElectrostaticState",
    "InterfaceExchange",
    "LatticeEnergyEvaluation",
    "LocalImpactIonization",
    "LocalVelocitySaturation",
    "MOBILITY_UNIT",
    "MaterialBinding",
    "MaterialInterface",
    "NUMBER_FLUX_UNIT",
    "NonlocalTunnelingEvaluation",
    "NonlocalTunnelingPath",
    "OhmicContact",
    "PERMITTIVITY_UNIT",
    "PER_CUBIC_METER",
    "PreparedSemiconductorCalibration",
    "PreparedSemiconductorDevice",
    "RECOMBINATION_UNIT",
    "SQUARE_METER",
    "SaturationEvaluation",
    "SemiconductorAdaptationIndicators",
    "SemiconductorCalibrationCampaign",
    "SemiconductorCalibrationCriteria",
    "SemiconductorCalibrationDomain",
    "SemiconductorCalibrationQualification",
    "SemiconductorCalibrationResult",
    "SemiconductorCircuitLaw",
    "SemiconductorEvidence",
    "SemiconductorForwardEvaluation",
    "SemiconductorForwardResult",
    "SemiconductorForwardUnresolved",
    "SemiconductorIdentifiability",
    "SemiconductorLinearEvidence",
    "SemiconductorMaterial",
    "SemiconductorMeasurementCase",
    "SemiconductorOperatingPoint",
    "SemiconductorParameterBinding",
    "SemiconductorPredictiveCheck",
    "SemiconductorQuantitySpec",
    "SemiconductorSensitivityResult",
    "SemiconductorSmallSignalResult",
    "SemiconductorStateLayout",
    "SemiconductorSweepResult",
    "SemiconductorTransferEvidence",
    "SemiconductorTransferResult",
    "SemiconductorTransientResult",
    "ThermalBoundaryExchange",
    "ThermalConductance",
    "ThermalExchangeEvaluation",
    "ThermalPort",
    "ThermionicInterface",
    "TransportSupport",
    "TrapBinding",
    "TrapExchangeEvaluation",
    "TrapStepEvaluation",
    "TrapStorage",
    "TunnelingChannel",
    "VACUUM_PERMITTIVITY_SI",
    "WKBBarrierPath",
    "WATT_UNIT",
    "WKBTransmissionEvaluation",
    "archive_semiconductor_calibration",
    "archive_semiconductor_forward_evaluation",
    "bipolar_transistor",
    "calibrate_semiconductor",
    "evaluate_semiconductor_forward",
    "interface_electrostatics",
    "mos_capacitor",
    "pn_junction",
    "prepare_semiconductor_calibration",
    "qualify_semiconductor_calibration",
    "quantum",
    "semiconductor_adaptation_indicators",
    "semiconductor_circuit_operating_point",
    "semiconductor_circuit_transient",
    "semiconductor_identifiability",
    "semiconductor_reprepare",
    "semiconductor_sensitivity",
    "semiconductor_small_signal",
    "semiconductor_transient",
    "srh_recombination",
]
