#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from abc import abstractmethod
from collections.abc import Callable
from math import prod
from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
import jax.random as jr
import numpy as np
from jaxtyping import Array, ArrayLike, Key, PyTree

from .._strict import AbstractAttribute, StrictModule
from ..stochastic._state_space import state_space_key, StateSpaceProblem
from ._particle import (
    bootstrap_particle_filter,
    normalize_log_weights,
    PARTICLE_FILTER_NONFINITE,
    PARTICLE_FILTER_SUCCESS,
    PARTICLE_FILTER_TRANSITION_FAILURE,
    PARTICLE_FILTER_WEIGHT_DEGENERACY,
    resample_indices,
    ResamplingMethod,
)


class ConditionalParticleFilterResult(StrictModule):
    """Conditional bootstrap-filter history retaining one complete reference path."""

    initial_particles: Array
    particles: Array
    log_weights: Array
    ancestor_indices: Array
    transition_valid: Array
    incremental_log_likelihood: Array
    cumulative_log_likelihood: Array
    step_valid: Array
    valid: Array
    status: Array
    reference_path: Array
    root_key: Array
    problem: StateSpaceProblem
    state_shape: tuple[int, ...] = eqx.field(static=True)
    case_shape: tuple[int, ...] = eqx.field(static=True)
    case_axes: tuple[str, ...] = eqx.field(static=True)
    case_ids: tuple[str, ...] = eqx.field(static=True)
    num_particles: int = eqx.field(static=True)
    conditioned_particle: int = eqx.field(static=True)
    ancestor_sampling: bool = eqx.field(static=True)
    resampling_method: ResamplingMethod = eqx.field(static=True)

    @property
    def successful(self) -> Array:
        return jnp.all(self.valid | ~self.step_valid, axis=-1)


class ParticleGibbsResult(StrictModule):
    """Latent-path draws generated by conditional SMC or PGAS transitions."""

    paths: Array
    log_likelihood_estimates: Array
    moved: Array
    final_path: Array
    problem: StateSpaceProblem
    num_particles: int = eqx.field(static=True)
    num_samples: int = eqx.field(static=True)
    num_warmup: int = eqx.field(static=True)
    thinning: int = eqx.field(static=True)
    ancestor_sampling: bool = eqx.field(static=True)

    @property
    def movement_rate(self) -> Array:
        return jnp.mean(self.moved.astype(float))


class AbstractParameterProposal(StrictModule):
    """Normalized parameter-space proposal used by particle MCMC."""

    proposal_id: AbstractAttribute[str]

    @abstractmethod
    def sample(self, key: Key[Array, ""], current: PyTree[Any], /) -> PyTree[Array]:
        raise NotImplementedError

    @abstractmethod
    def log_prob(self, proposed: PyTree[Any], current: PyTree[Any], /) -> Array:
        raise NotImplementedError


class GaussianRandomWalkProposal(AbstractParameterProposal):
    """Isotropic Gaussian random walk over every inexact parameter leaf."""

    scale: float = eqx.field(static=True)
    proposal_id: str = eqx.field(static=True)

    def __init__(self, scale: float, /, *, proposal_id: str = "gaussian-random-walk"):
        value = float(scale)
        if not np.isfinite(value) or value <= 0.0:
            raise ValueError("scale must be finite and positive.")
        if not isinstance(proposal_id, str) or not proposal_id:
            raise ValueError("proposal_id must be a non-empty string.")
        self.scale = value
        self.proposal_id = proposal_id

    def sample(self, key, current, /) -> PyTree[Array]:
        leaves, structure = jax.tree_util.tree_flatten(current)
        if not leaves or any(not eqx.is_inexact_array(leaf) for leaf in leaves):
            raise TypeError("Parameters must be a non-empty PyTree of inexact arrays.")
        keys = jr.split(key, len(leaves))
        return structure.unflatten(
            jnp.asarray(leaf)
            + self.scale * jr.normal(leaf_key, leaf.shape, dtype=jnp.asarray(leaf).dtype)
            for leaf, leaf_key in zip(leaves, keys, strict=True)
        )

    def log_prob(self, proposed, current, /) -> Array:
        proposed_leaves, proposed_structure = jax.tree_util.tree_flatten(proposed)
        current_leaves, current_structure = jax.tree_util.tree_flatten(current)
        if proposed_structure != current_structure:
            raise ValueError("Proposed and current parameter structures must agree.")
        dimension = sum(int(leaf.size) for leaf in current_leaves)
        squared = sum(
            (
                jnp.sum(
                    (
                        (jnp.asarray(proposed_leaf) - jnp.asarray(current_leaf))
                        / self.scale
                    )
                    ** 2
                )
                for proposed_leaf, current_leaf in zip(
                    proposed_leaves, current_leaves, strict=True
                )
            ),
            jnp.zeros(()),
        )
        return -0.5 * (squared + dimension * jnp.log(2.0 * jnp.pi * self.scale**2))


class CallableParameterProposal(AbstractParameterProposal):
    """Normalized user-defined parameter proposal."""

    sample_fn: Callable[[Array, PyTree[Any]], PyTree[Any]] = eqx.field(static=True)
    log_prob_fn: Callable[[PyTree[Any], PyTree[Any]], ArrayLike] = eqx.field(static=True)
    proposal_id: str = eqx.field(static=True)

    def __init__(
        self,
        sample: Callable[[Array, PyTree[Any]], PyTree[Any]],
        log_prob: Callable[[PyTree[Any], PyTree[Any]], ArrayLike],
        /,
        *,
        proposal_id: str,
    ):
        if not callable(sample) or not callable(log_prob):
            raise TypeError("sample and log_prob must be callable.")
        if not isinstance(proposal_id, str) or not proposal_id:
            raise ValueError("proposal_id must be a non-empty string.")
        self.sample_fn = sample
        self.log_prob_fn = log_prob
        self.proposal_id = proposal_id

    def sample(self, key, current, /) -> PyTree[Array]:
        proposed = self.sample_fn(key, current)
        if jax.tree_util.tree_structure(proposed) != jax.tree_util.tree_structure(
            current
        ):
            raise ValueError("Parameter proposal must preserve PyTree structure.")
        return jax.tree_util.tree_map(jnp.asarray, proposed)

    def log_prob(self, proposed, current, /) -> Array:
        return jnp.asarray(self.log_prob_fn(proposed, current), dtype=float).reshape(())


class ParticleMarginalMetropolisHastingsResult(StrictModule):
    """Pseudo-marginal parameter chain driven by unbiased particle likelihoods."""

    samples: PyTree[Array]
    log_likelihoods: Array
    log_priors: Array
    log_posteriors: Array
    accepted: Array
    final_parameters: PyTree[Array]
    initial_parameters: PyTree[Array]
    proposal_id: str = eqx.field(static=True)
    num_particles: int = eqx.field(static=True)
    num_samples: int = eqx.field(static=True)
    num_warmup: int = eqx.field(static=True)
    thinning: int = eqx.field(static=True)
    filter_evaluations: int = eqx.field(static=True)

    @property
    def acceptance_rate(self) -> Array:
        return jnp.mean(self.accepted.astype(float))


def _particle_configuration(
    num_particles: int,
    method: ResamplingMethod,
) -> tuple[int, ResamplingMethod]:
    count = int(num_particles)
    if count < 2:
        raise ValueError("Conditional SMC requires at least two particles.")
    if method not in ("systematic", "stratified", "multinomial", "residual"):
        raise ValueError("Unknown resampling_method.")
    return count, method


def _reference_path(problem: StateSpaceProblem, path: ArrayLike, /) -> Array:
    array = jnp.asarray(path)
    expected = (
        problem.observations.case_shape
        + (problem.observations.num_steps + 1,)
        + problem.model.state_shape
    )
    if array.shape != expected:
        raise ValueError(f"reference_path must have shape {expected}; got {array.shape}.")
    if bool(jnp.any(~jnp.isfinite(array))):
        raise ValueError("reference_path must be finite.")
    if problem.model.prior.has_log_density:
        step_axis = len(problem.observations.case_shape)
        initial = jnp.take(array, 0, axis=step_axis)
        if bool(jnp.any(~jnp.isfinite(problem.model.prior.log_prob(initial)))):
            raise ValueError("reference_path initial state lies outside prior support.")
    return array


def conditional_particle_filter(
    key: Key[Array, ""],
    problem: StateSpaceProblem,
    reference_path: ArrayLike,
    /,
    *,
    num_particles: int,
    ancestor_sampling: bool = False,
    resampling_method: ResamplingMethod = "systematic",
    raise_on_failure: bool = False,
) -> ConditionalParticleFilterResult:
    """Run conditional bootstrap SMC, optionally with ancestor sampling (PGAS)."""
    if not isinstance(problem, StateSpaceProblem):
        raise TypeError("problem must be a StateSpaceProblem.")
    count, method = _particle_configuration(num_particles, resampling_method)
    use_ancestor_sampling = bool(ancestor_sampling)
    if use_ancestor_sampling and not problem.model.transition.has_log_density:
        raise ValueError(
            "Ancestor sampling requires a transition with a normalized log density."
        )
    reference = _reference_path(problem, reference_path)
    sequence = problem.observations
    case_shape = sequence.case_shape
    case_count = prod(case_shape) if case_shape else 1
    num_steps = sequence.num_steps
    state_shape = problem.model.state_shape
    flat_reference = reference.reshape((case_count, num_steps + 1) + state_shape)
    initial_cases = []
    initial_valid = []
    for case_index, case_id in enumerate(sequence.case_ids):
        particles = [flat_reference[case_index, 0]]
        validity = [jnp.asarray(True)]
        for particle_index in range(1, count):
            prior_key = state_space_key(
                key, "conditional-smc-prior", case_id, 0, member=particle_index
            )
            complete = problem.model.prior.sample(prior_key)
            draw = (
                complete
                if not case_shape
                else complete.reshape((case_count,) + state_shape)[case_index]
            )
            particles.append(draw)
            validity.append(jnp.all(jnp.isfinite(draw)))
        initial_cases.append(jnp.stack(particles))
        initial_valid.append(jnp.all(jnp.stack(validity)))
    initial_particles = jnp.stack(initial_cases)
    particles = initial_particles
    log_weights = jnp.full((case_count, count), -jnp.log(float(count)), dtype=float)
    times = problem.initial_time.reshape((case_count,))
    cumulative = jnp.zeros((case_count,), dtype=float)
    alive = jnp.stack(initial_valid)
    final_status = jnp.where(
        alive, PARTICLE_FILTER_SUCCESS, PARTICLE_FILTER_NONFINITE
    ).astype(jnp.int32)

    particle_history: list[Array] = []
    weight_history: list[Array] = []
    ancestor_history: list[Array] = []
    transition_valid_history: list[Array] = []
    increment_history: list[Array] = []
    cumulative_history: list[Array] = []
    valid_history: list[Array] = []
    status_history: list[Array] = []
    flat_times = sequence.times.reshape((case_count, num_steps))
    flat_active = sequence.step_valid.reshape((case_count, num_steps))
    flat_values = sequence.values.reshape(
        (case_count, num_steps) + problem.model.observation_shape
    )
    flat_masks = sequence.observation_mask.reshape(
        (case_count, num_steps) + problem.model.observation_shape
    )
    identity = jnp.arange(count, dtype=jnp.int32)

    for step in range(num_steps):
        step_particles = []
        step_weights = []
        step_ancestors = []
        step_transition_valid = []
        step_increments = []
        step_cumulative = []
        step_validity = []
        step_status = []
        for case_index, case_id in enumerate(sequence.case_ids):
            active = bool(flat_active[case_index, step])
            if not active or not bool(alive[case_index]):
                step_particles.append(particles[case_index])
                step_weights.append(log_weights[case_index])
                step_ancestors.append(identity)
                step_transition_valid.append(
                    jnp.full((count,), alive[case_index], dtype=bool)
                )
                step_increments.append(jnp.asarray(0.0))
                step_cumulative.append(cumulative[case_index])
                step_validity.append(alive[case_index])
                step_status.append(final_status[case_index])
                continue

            start = times[case_index]
            end = flat_times[case_index, step]
            value = flat_values[case_index, step]
            mask = flat_masks[case_index, step]
            resampling_key = state_space_key(
                key, "conditional-smc-resampling", case_id, step
            )
            ancestors = resample_indices(
                resampling_key, log_weights[case_index], method=method
            )
            if use_ancestor_sampling:
                reference_next = flat_reference[case_index, step + 1]
                backward_log_weights = log_weights[case_index] + jnp.stack(
                    [
                        problem.model.transition.log_prob(
                            reference_next,
                            particles[case_index, particle_index],
                            start,
                            end,
                        )
                        for particle_index in range(count)
                    ]
                )
                normalized_backward, _, backward_valid = normalize_log_weights(
                    backward_log_weights
                )
                if not bool(backward_valid):
                    raise FloatingPointError(
                        "Reference transition has no valid ancestor support."
                    )
                ancestor_key = state_space_key(
                    key, "conditional-smc-ancestor", case_id, step
                )
                conditioned_ancestor = jr.categorical(
                    ancestor_key, normalized_backward
                ).astype(jnp.int32)
            else:
                conditioned_ancestor = jnp.asarray(0, dtype=jnp.int32)
            ancestors = ancestors.at[0].set(conditioned_ancestor)
            parents = particles[case_index, ancestors]
            proposed = [flat_reference[case_index, step + 1]]
            proposal_valid = [jnp.asarray(True)]
            if problem.model.transition.has_log_density:
                reference_log_prob = problem.model.transition.log_prob(
                    proposed[0], parents[0], start, end
                )
                proposal_valid[0] = jnp.isfinite(reference_log_prob)
            for particle_index in range(1, count):
                transition_key = state_space_key(
                    key,
                    "conditional-smc-transition",
                    case_id,
                    step,
                    member=particle_index,
                )
                sample = problem.model.transition.sample(
                    transition_key, parents[particle_index], start, end
                )
                valid = jnp.all(sample.valid) & jnp.all(sample.status == 0)
                proposed.append(jnp.where(valid, sample.values, parents[particle_index]))
                proposal_valid.append(valid)
            proposed = jnp.stack(proposed)
            proposal_valid = jnp.stack(proposal_valid)
            observation_log_weights = jnp.stack(
                [
                    problem.model.observation.log_prob(
                        value, proposed[particle_index], end, mask
                    )
                    for particle_index in range(count)
                ]
            )
            proposal_valid = proposal_valid & ~jnp.isnan(observation_log_weights)
            candidates = jnp.where(proposal_valid, observation_log_weights, -jnp.inf)
            posterior_weights, _, weights_valid = normalize_log_weights(candidates)
            log_increment = jax.scipy.special.logsumexp(candidates) - jnp.log(
                float(count)
            )
            accepted = bool(
                jnp.any(proposal_valid) & weights_valid & jnp.isfinite(log_increment)
            )
            if accepted:
                output_particles = proposed
                output_weights = posterior_weights
                status = PARTICLE_FILTER_SUCCESS
            else:
                output_particles = particles[case_index]
                output_weights = log_weights[case_index]
                ancestors = identity
                status = (
                    PARTICLE_FILTER_TRANSITION_FAILURE
                    if not bool(jnp.any(proposal_valid))
                    else PARTICLE_FILTER_WEIGHT_DEGENERACY
                )
            next_cumulative = cumulative[case_index] + jnp.where(
                accepted, log_increment, 0.0
            )
            step_particles.append(output_particles)
            step_weights.append(output_weights)
            step_ancestors.append(ancestors)
            step_transition_valid.append(proposal_valid)
            step_increments.append(jnp.where(accepted, log_increment, 0.0))
            step_cumulative.append(next_cumulative)
            step_validity.append(jnp.asarray(accepted))
            step_status.append(jnp.asarray(status, dtype=jnp.int32))

        particles = jnp.stack(step_particles)
        log_weights = jnp.stack(step_weights)
        cumulative = jnp.stack(step_cumulative)
        step_valid_array = jnp.stack(step_validity)
        alive = alive & step_valid_array
        final_status = jnp.stack(step_status)
        times = jnp.where(flat_active[:, step], flat_times[:, step], times)
        particle_history.append(particles)
        weight_history.append(log_weights)
        ancestor_history.append(jnp.stack(step_ancestors))
        transition_valid_history.append(jnp.stack(step_transition_valid))
        increment_history.append(jnp.stack(step_increments))
        cumulative_history.append(cumulative)
        valid_history.append(step_valid_array)
        status_history.append(final_status)

    def restore(history: list[Array], trailing_shape: tuple[int, ...]) -> Array:
        return jnp.stack(history, axis=1).reshape(
            case_shape + (num_steps,) + trailing_shape
        )

    result = ConditionalParticleFilterResult(
        initial_particles=initial_particles.reshape(case_shape + (count,) + state_shape),
        particles=restore(particle_history, (count,) + state_shape),
        log_weights=restore(weight_history, (count,)),
        ancestor_indices=restore(ancestor_history, (count,)),
        transition_valid=restore(transition_valid_history, (count,)),
        incremental_log_likelihood=restore(increment_history, ()),
        cumulative_log_likelihood=restore(cumulative_history, ()),
        step_valid=sequence.step_valid,
        valid=restore(valid_history, ()),
        status=restore(status_history, ()),
        reference_path=reference,
        root_key=jnp.asarray(key),
        problem=problem,
        state_shape=state_shape,
        case_shape=case_shape,
        case_axes=sequence.case_axes,
        case_ids=sequence.case_ids,
        num_particles=count,
        conditioned_particle=0,
        ancestor_sampling=use_ancestor_sampling,
        resampling_method=method,
    )
    if raise_on_failure and not bool(jnp.all(result.successful)):
        raise RuntimeError("Conditional SMC failed for at least one physical case.")
    return result


def sample_conditional_particle_path(
    key: Key[Array, ""],
    result: ConditionalParticleFilterResult,
    /,
) -> Array:
    """Draw one complete initial-to-terminal path from a conditional SMC history."""
    if not isinstance(result, ConditionalParticleFilterResult):
        raise TypeError("result must be a ConditionalParticleFilterResult.")
    if not bool(jnp.all(result.successful)):
        raise ValueError("Cannot sample a path from a failed conditional SMC run.")
    case_shape = result.case_shape
    case_count = prod(case_shape) if case_shape else 1
    num_steps = result.problem.observations.num_steps
    count = result.num_particles
    state_shape = result.state_shape
    particles = result.particles.reshape((case_count, num_steps, count) + state_shape)
    initial = result.initial_particles.reshape((case_count, count) + state_shape)
    weights = result.log_weights.reshape((case_count, num_steps, count))
    ancestors = result.ancestor_indices.reshape((case_count, num_steps, count))
    paths = []
    for case_index, case_id in enumerate(result.case_ids):
        terminal_key = state_space_key(
            key, "conditional-smc-terminal", case_id, num_steps
        )
        particle_index = int(jr.categorical(terminal_key, weights[case_index, -1]))
        states = [particles[case_index, -1, particle_index]]
        for step in range(num_steps - 1, 0, -1):
            particle_index = int(ancestors[case_index, step, particle_index])
            states.append(particles[case_index, step - 1, particle_index])
        particle_index = int(ancestors[case_index, 0, particle_index])
        states.append(initial[case_index, particle_index])
        paths.append(jnp.stack(states[::-1]))
    return jnp.stack(paths).reshape(case_shape + (num_steps + 1,) + state_shape)


def particle_gibbs(
    key: Key[Array, ""],
    problem: StateSpaceProblem,
    initial_path: ArrayLike,
    /,
    *,
    num_particles: int,
    num_samples: int,
    num_warmup: int = 0,
    thinning: int = 1,
    ancestor_sampling: bool = True,
    resampling_method: ResamplingMethod = "systematic",
) -> ParticleGibbsResult:
    """Sample latent trajectories with conditional SMC or PGAS transitions."""
    samples_count = int(num_samples)
    warmup_count = int(num_warmup)
    thin = int(thinning)
    if samples_count < 1:
        raise ValueError("num_samples must be positive.")
    if warmup_count < 0:
        raise ValueError("num_warmup must be nonnegative.")
    if thin < 1:
        raise ValueError("thinning must be positive.")
    reference = _reference_path(problem, initial_path)
    total_steps = warmup_count + samples_count * thin
    paths = []
    likelihoods = []
    moved = []
    for iteration in range(total_steps):
        filter_key = jr.fold_in(jr.fold_in(key, 0), iteration)
        draw_key = jr.fold_in(jr.fold_in(key, 1), iteration)
        filtered = conditional_particle_filter(
            filter_key,
            problem,
            reference,
            num_particles=num_particles,
            ancestor_sampling=ancestor_sampling,
            resampling_method=resampling_method,
            raise_on_failure=True,
        )
        proposed_path = sample_conditional_particle_path(draw_key, filtered)
        changed = jnp.any(proposed_path != reference)
        reference = proposed_path
        retain = iteration >= warmup_count and (
            (iteration - warmup_count + 1) % thin == 0
        )
        if retain:
            paths.append(reference)
            likelihoods.append(jnp.sum(filtered.cumulative_log_likelihood[..., -1]))
            moved.append(changed)
    return ParticleGibbsResult(
        paths=jnp.stack(paths),
        log_likelihood_estimates=jnp.stack(likelihoods),
        moved=jnp.stack(moved),
        final_path=reference,
        problem=problem,
        num_particles=int(num_particles),
        num_samples=samples_count,
        num_warmup=warmup_count,
        thinning=thin,
        ancestor_sampling=bool(ancestor_sampling),
    )


def _particle_log_likelihood(
    key: Array,
    problem: StateSpaceProblem,
    /,
    *,
    num_particles: int,
    resampling_method: ResamplingMethod,
) -> Array:
    filtered = bootstrap_particle_filter(
        key,
        problem,
        num_particles=num_particles,
        resampling_method=resampling_method,
        resampling_policy="always",
    )
    per_case = jnp.where(
        filtered.successful,
        filtered.final_state.log_likelihood,
        -jnp.inf,
    )
    return jnp.sum(per_case).reshape(())


def particle_marginal_metropolis_hastings(
    key: Key[Array, ""],
    initial_parameters: PyTree[Any],
    problem: Callable[[PyTree[Any]], StateSpaceProblem],
    log_prior: Callable[[PyTree[Any]], ArrayLike],
    proposal: AbstractParameterProposal,
    /,
    *,
    num_particles: int,
    num_samples: int,
    num_warmup: int = 0,
    thinning: int = 1,
    resampling_method: ResamplingMethod = "systematic",
) -> ParticleMarginalMetropolisHastingsResult:
    """Run pseudo-marginal Metropolis-Hastings with a particle likelihood."""
    if not callable(problem) or not callable(log_prior):
        raise TypeError("problem and log_prior must be callable.")
    if not isinstance(proposal, AbstractParameterProposal):
        raise TypeError("proposal must implement AbstractParameterProposal.")
    count = int(num_particles)
    samples_count = int(num_samples)
    warmup_count = int(num_warmup)
    thin = int(thinning)
    if count < 1:
        raise ValueError("num_particles must be positive.")
    if samples_count < 1:
        raise ValueError("num_samples must be positive.")
    if warmup_count < 0:
        raise ValueError("num_warmup must be nonnegative.")
    if thin < 1:
        raise ValueError("thinning must be positive.")
    if resampling_method not in (
        "systematic",
        "stratified",
        "multinomial",
        "residual",
    ):
        raise ValueError("Unknown resampling_method.")
    current = jax.tree_util.tree_map(jnp.asarray, initial_parameters)
    if not jax.tree_util.tree_leaves(current):
        raise ValueError("initial_parameters must be non-empty.")
    current_prior = jnp.asarray(log_prior(current), dtype=float).reshape(())
    initial_problem = problem(current)
    if not isinstance(initial_problem, StateSpaceProblem):
        raise TypeError("problem(parameters) must return a StateSpaceProblem.")
    current_likelihood = _particle_log_likelihood(
        jr.fold_in(jr.fold_in(key, 2), 0),
        initial_problem,
        num_particles=count,
        resampling_method=resampling_method,
    )
    filter_evaluations = 1
    if not bool(jnp.isfinite(current_prior + current_likelihood)):
        raise FloatingPointError(
            "Initial parameters must have finite prior and particle likelihood."
        )

    total_steps = warmup_count + samples_count * thin
    sample_trees = []
    likelihoods = []
    priors = []
    posteriors = []
    accepted_history = []
    for iteration in range(total_steps):
        proposal_key = jr.fold_in(jr.fold_in(key, 3), iteration)
        candidate = proposal.sample(proposal_key, current)
        candidate_prior = jnp.asarray(log_prior(candidate), dtype=float).reshape(())
        candidate_likelihood = jnp.asarray(-jnp.inf)
        if bool(jnp.isfinite(candidate_prior)):
            candidate_problem = problem(candidate)
            if not isinstance(candidate_problem, StateSpaceProblem):
                raise TypeError("problem(parameters) must return a StateSpaceProblem.")
            filter_key = jr.fold_in(jr.fold_in(key, 4), iteration)
            candidate_likelihood = _particle_log_likelihood(
                filter_key,
                candidate_problem,
                num_particles=count,
                resampling_method=resampling_method,
            )
            filter_evaluations += 1
        forward = proposal.log_prob(candidate, current)
        reverse = proposal.log_prob(current, candidate)
        log_acceptance = (
            candidate_prior
            + candidate_likelihood
            + reverse
            - current_prior
            - current_likelihood
            - forward
        )
        acceptance_key = jr.fold_in(jr.fold_in(key, 5), iteration)
        accepted = bool(
            jnp.log(jr.uniform(acceptance_key)) < jnp.minimum(log_acceptance, 0.0)
        )
        if accepted:
            current = candidate
            current_prior = candidate_prior
            current_likelihood = candidate_likelihood
        retain = iteration >= warmup_count and (
            (iteration - warmup_count + 1) % thin == 0
        )
        if retain:
            sample_trees.append(current)
            likelihoods.append(current_likelihood)
            priors.append(current_prior)
            posteriors.append(current_prior + current_likelihood)
            accepted_history.append(jnp.asarray(accepted))
    samples = jax.tree_util.tree_map(lambda *values: jnp.stack(values), *sample_trees)
    return ParticleMarginalMetropolisHastingsResult(
        samples=samples,
        log_likelihoods=jnp.stack(likelihoods),
        log_priors=jnp.stack(priors),
        log_posteriors=jnp.stack(posteriors),
        accepted=jnp.stack(accepted_history),
        final_parameters=current,
        initial_parameters=jax.tree_util.tree_map(jnp.asarray, initial_parameters),
        proposal_id=proposal.proposal_id,
        num_particles=count,
        num_samples=samples_count,
        num_warmup=warmup_count,
        thinning=thin,
        filter_evaluations=filter_evaluations,
    )


__all__ = [
    "AbstractParameterProposal",
    "CallableParameterProposal",
    "conditional_particle_filter",
    "ConditionalParticleFilterResult",
    "GaussianRandomWalkProposal",
    "particle_gibbs",
    "ParticleGibbsResult",
    "particle_marginal_metropolis_hastings",
    "ParticleMarginalMetropolisHastingsResult",
    "sample_conditional_particle_path",
]
