#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""
# Solver

Solvers aggregate numerical terms and attached model losses for training or
evaluation. `FunctionalSolver` consumes one ordered `terms` collection.

Hard `EnforcementSpec` declarations may also compile boundary, initial, and
interior requirements into an `EnforcementProgram` that transforms fields before
term evaluation.

!!! example
    ```python
    import jax.random as jr
    import phydrax as phx

    geom = phx.domain.Interval1d(0.0, 1.0)

    @geom.Function("x")
    def u(x):
        return 1.0

    component = geom.component()
    condition = phx.conditions.Residual("u", component, lambda field: field)
    source = phx.integration.per_step(
        phx.integration.mean_over(component),
        phx.domain.PointSampling(
            32,
            layout=phx.domain.SampleLayout((("x",),)),
        ),
    )
    term = phx.terms.ResidualPenalty(condition, source)

    solver = phx.solver.FunctionalSolver(
        functions={"u": u},
        terms=(term,),
    )

    loss = solver.loss(key=jr.key(0))
    print(loss)
    ```
"""

from ._bdf_method import BDFMethod
from ._calabi_yau import (
    CalabiYauMetricProblem,
    CalabiYauMetricResult,
    CalabiYauSolvePolicy,
    solve_calabi_yau_metric,
)
from ._calabi_yau_archive import CalabiYauMetricArtifact, freeze_calabi_yau_result
from ._calabi_yau_campaigns import (
    CalabiYauCampaign,
    cp1_calibration,
    prepare_elliptic_curve,
    prepare_fermat_calabi_yau,
    prepare_fermat_quintic,
    prepare_quartic_k3,
)
from ._collocation import (
    assemble_stochastic_collocation,
    COLLOCATION_NONFINITE,
    COLLOCATION_SOLVER_FAILURE,
    COLLOCATION_SUCCESS,
    CollocationAxisRule,
    evaluate_stochastic_collocation,
    materialize_stochastic_collocation,
    run_stochastic_collocation,
    StochasticCollocationDesign,
    StochasticCollocationDiagnostics,
    StochasticCollocationNode,
    StochasticCollocationNodeEvaluation,
    StochasticCollocationPlan,
    StochasticCollocationResult,
)
from ._compatible_systems import (
    CompatibleElasticityDynamics,
    CompatibleElasticityState,
    CompatibleIdealMHDInductionDynamics,
    CompatibleIdealMHDState,
    CompatibleIncompressibleProjection,
    CompatibleMaxwellDynamics,
    CompatibleMaxwellState,
    CompatiblePoroelasticDynamics,
    CompatiblePoroelasticState,
    CompatibleThermoelasticDynamics,
    CompatibleThermoelasticState,
    CompatibleVariableDensityProjection,
    IncompressibleProjectionResult,
)
from ._convergence import (
    coupled_strong_error,
    NoiseTruncationLevel,
    NoiseTruncationStudy,
    SPDEConvergenceLevel,
    SPDEConvergenceMetric,
    SPDEConvergenceStudy,
    SPDEErrorBudget,
    SPDERefinementAxis,
    weak_observable_estimate,
    WeakObservableEstimate,
)
from ._coupled import (
    CoupledCost,
    CoupledHierarchyResult,
    CoupledLevelResult,
    CoupledLevelSolver,
    CoupledObservable,
    CoupledValidity,
    solve_coupled_hierarchy,
)
from ._dae_initialization import (
    DAEInitializationMode,
    DAEInitializationResult,
    DAEInitializationSpec,
    DAEInitializationStatus,
)
from ._deep_bsde import DeepBSDEResult, solve_deep_bsde
from ._deep_picard import (
    DeepPicardDiagnostics,
    DeepPicardInitialSource,
    DeepPicardResult,
    PicardSourceContext,
    solve_deep_picard,
    StructuredPicardSource,
    StructuredSourceBuilder,
)
from ._deep_splitting import (
    DeepSplittingDiagnostics,
    DeepSplittingInterpolation,
    DeepSplittingResult,
    DeepSplittingSamplingMode,
    DeepSplittingSolution,
    solve_deep_splitting,
)
from ._delay import (
    ConstantDelay,
    DelayDifferentialProblem,
    DelayHistory,
    DelayHistoryDerivative,
    DelayHistoryWindow,
    DelayTerm,
    DelayValues,
    DelayVectorField,
    DelayWienerTerm,
    DerivativeDelay,
    DistributedDelay,
    DistributedDelayKernel,
    EndpointNeutralFunctional,
    FunctionalDelay,
    HistoryFunctional,
    NeutralDelayProblem,
    NeutralFunctional,
    NeutralRecoveryGuess,
    PointDelay,
    StateDependentDelay,
    StateDependentLag,
)
from ._delay_adjoint import CheckpointedDelayAdjoint, SegmentedDelayAdjoint
from ._delay_segmented import (
    DelaySegmentArchive,
    DelaySegmentContinuation,
    fixed_delay_history_capacity,
    SegmentedDelayResult,
    solve_diffrax_delay_segmented,
)
from ._differential import (
    DifferentialInterpretation,
    DifferentialProblem,
    DifferentialSolution,
    DifferentialVectorField,
    NoiseStructure,
    WienerTerm,
)
from ._differential_algebraic import (
    DAEAdaptivePolicy,
    DAEAttemptHistory,
    DAEAttemptStatus,
    DAEContinuation,
    DAEFailureMode,
    DAERegularityEvidence,
    DAERegularityFailureMode,
    DAERegularityMode,
    DAERegularityPolicy,
    DAERegularityStatus,
    DAEReplayEvidence,
    DAEReplayMode,
    DAEReplayPolicy,
    DAESolvePlan,
    DAESolvePolicy,
    DAEStatus,
    DAEStepHistory,
    DAETemporalReusePolicy,
    DAETerminationStatus,
    DifferentialAlgebraicProblem,
    DifferentialAlgebraicSolution,
    discretized_dae_problem,
    initialize_dae,
    plan_dae,
    prepare_dae,
    PreparedDAESolve,
    solve_dae,
)
from ._diffrax_backend import solve_diffrax, solve_diffrax_ensemble
from ._diffrax_cde import ControlledDifferentialSolution, solve_diffrax_cde
from ._diffrax_delay_backend import solve_diffrax_delay
from ._driving_path import (
    AbstractDifferentiableDrivingPath,
    CallableDrivingPath,
    CausalBackwardHermiteDrivingPath,
    DrivingPathFitDiagnostics,
    FixedBSplineDrivingPath,
    OfflineCubicDrivingPath,
    PiecewiseLinearDrivingPath,
)
from ._dynamics_evolution import DiffraxEvolution
from ._fbsde import (
    CoupledFBSDEProblem,
    CoupledFBSDEResult,
    solve_coupled_fbsde_explicit,
)
from ._fermionic_gaussian import (
    damped_fermionic_mode,
    FermionicGaussianProblem,
    FermionicGaussianSolution,
    open_kitaev_chain,
    solve_fermionic_gaussian,
)
from ._finite_volume import (
    DirectionalSplitFiniteVolumePlan,
    FiniteVolumeStepResult,
    SplittingKind,
    UnsplitFiniteVolumeSSPRK3Plan,
)
from ._finite_volume_case import (
    FiniteVolumeCaseSpec,
    FiniteVolumeExecutionSpec,
    FiniteVolumePrecisionPolicy,
    PrecisionDType,
)
from ._finite_volume_case_loader import (
    load_finite_volume_case,
    PreparedFiniteVolumeCase,
)
from ._finite_volume_checkpoint import (
    FiniteVolumeCheckpoint,
    FiniteVolumeCheckpointPlan,
    read_finite_volume_checkpoint,
    write_finite_volume_checkpoint,
)
from ._finite_volume_output import FiniteVolumeOutputPlan
from ._finite_volume_rollout import (
    FiniteVolumeGradientReport,
    FiniteVolumeRematerializationPolicy,
    FiniteVolumeRetentionPolicy,
    FiniteVolumeRolloutPlan,
    FiniteVolumeRolloutResult,
)
from ._finite_volume_runtime import (
    FiniteVolumeAdvanceResult,
    FiniteVolumeRunStatus,
    FiniteVolumeRuntimeState,
    FiniteVolumeStepPolicy,
    PreparedFiniteVolumeRuntime,
)
from ._fock_continuation import (
    FockContinuationPolicy,
    FockContinuationResult,
    FockContinuationStage,
    solve_fock_continuation,
)
from ._fractional_memory import (
    CaputoFractionalProblem,
    FractionalVectorField,
    solve_caputo_fractional,
)
from ._functional_differential import (
    FunctionalCollocationPlan,
    FunctionalDifferentialBoundaryProblem,
    FunctionalDifferentialContext,
    FunctionalDifferentialSolution,
    solve_functional_differential,
)
from ._functional_solver import FunctionalSolver
from ._gaussian_lindblad import (
    damped_thermal_oscillator,
    GaussianLindbladProblem,
    GaussianLindbladSolution,
    solve_gaussian_lindblad,
)
from ._generalized_alpha import (
    GeneralizedAlphaMethod,
    GeneralizedAlphaSolution,
    solve_generalized_alpha,
)
from ._geometric import (
    AbstractGeometricSolver,
    commutator_free_midpoint_tableau,
    CommutatorFreeSolver,
    CommutatorFreeTableau,
    GeometricEuler,
    GeometricLocalInterpolation,
    RKMK,
    SeparableHamiltonianVectorField,
    solver_state_geometry,
    SRKMK,
    StormerVerlet,
)
from ._heom import (
    drude_lorentz_qubit_heom,
    HEOMHierarchy,
    HEOMProblem,
    HEOMSolution,
    solve_heom,
    thermal_drude_lorentz_qubit_heom,
)
from ._heom_implicit import (
    HEOMImplicitEvidence,
    HEOMImplicitResult,
    solve_heom_backward_euler,
)
from ._heom_production import (
    HEOMContinuationResult,
    HEOMContinuationStage,
    solve_heom_continuation,
)
from ._heom_scaled import ScaledHEOMTopology
from ._implicit_runge_kutta import (
    GaussLegendreInterpolation,
    GaussLegendreIRK,
    solve_implicit_runge_kutta,
)
from ._jump import (
    finite_state_generator,
    FiniteStateGenerator,
    GeneratorBoundaryPolicy,
    JumpAlgorithm,
    JumpDifferentialProblem,
    JumpDifferentialSolution,
    JumpSolution,
    solve_direct_ssa,
    solve_jump_differential,
    solve_next_reaction,
)
from ._jump_delay import (
    DelayJumpMap,
    JumpDelayBackendResult,
    JumpDelayProblem,
    solve_jump_delay,
)
from ._levy import (
    LevySDEProblem,
    LevySDEScheme,
    LevySDESolution,
    LevySDESolverDiagnostics,
    LevySDEVectorField,
    LevySmallJumpApproximation,
    solve_levy_sde,
)
from ._lindblad import (
    amplitude_damping_problem,
    dephasing_problem,
    LindbladProblem,
    LindbladSolution,
    solve_lindblad,
)
from ._markov_cubature import (
    MarkovCubatureDiagnostics,
    MarkovCubatureMethod,
    MarkovCubaturePlan,
    MarkovCubatureSolution,
    MarkovCubatureStatus,
    PolynomialRecombination,
    solve_markov_cubature,
)
from ._memory import (
    ConvolutionKernel,
    ConvolutionVolterraProblem,
    MemoryEquationSolution,
    solve_convolution_volterra,
    solve_stochastic_volterra,
    StochasticVolterraProblem,
    VolterraFreeTerm,
    VolterraKernel,
    VolterraVectorField,
)
from ._memory_kernel import (
    DynamicalMapPhysicality,
    exponential_memory_qubit_problem,
    MemoryKernelMasterEquation,
    OpenSystemHistorySolution,
    QuantumMemoryKernel,
    solve_memory_kernel,
    solve_time_local_open_system,
    TimeLocalOpenSystemProblem,
)
from ._mps_quantum_jump import (
    LocalMPSJump,
    MPSQuantumJumpProblem,
    MPSQuantumTrajectoryResult,
    solve_mps_quantum_jump,
)
from ._multirate import (
    multirate_amr_subcycling_plan,
    MultiratePartitionedRK,
    PartitionedDifferentialProblem,
    solve_multirate,
)
from ._neural_cde import (
    neural_cde_loss,
    NeuralCDETrainingData,
    NeuralCDETrainingState,
    NeuralCDEVectorField,
    train_neural_cde,
)
from ._neural_quantum_jump import (
    NeuralJumpProjectionProblem,
    NeuralJumpProjectionResult,
    NeuralNoJumpTDVPProblem,
    NeuralNoJumpTDVPResult,
    solve_neural_jump_projection,
    solve_neural_no_jump_tdvp,
)
from ._nonmarkov_campaign import (
    lorentzian_qubit_comparison,
    NonMarkovianComparisonResult,
    spin_boson_dephasing_comparison,
    SpinBosonComparisonResult,
)
from ._particles import (
    InteractingParticleProblem,
    InteractingParticleSolution,
    ParticleVectorField,
    solve_interacting_particles,
)
from ._probabilistic_ode import (
    PROBABILISTIC_ODE_NONFINITE,
    probabilistic_ode_status_name,
    PROBABILISTIC_ODE_STEP_LIMIT_REACHED,
    PROBABILISTIC_ODE_STIFF,
    PROBABILISTIC_ODE_SUCCESS,
    ProbabilisticODECalibration,
    ProbabilisticODECovarianceOutput,
    ProbabilisticODEFactorization,
    ProbabilisticODEMethod,
    ProbabilisticODESolution,
    ProbabilisticODEStatus,
    ProbabilisticODEUpdate,
    solve_probabilistic_ode,
)
from ._process_tomography import (
    CausalProcessTomographyProblem,
    CausalProcessTomographyResult,
    fit_causal_process_initial_state,
    ProcessTomographyExperiment,
)
from ._pseudomode import (
    jaynes_cummings_pseudomode_problem,
    PseudomodeEmbeddingProblem,
    PseudomodeSolution,
    solve_pseudomode,
)
from ._purified_lindblad import (
    apply_local_kraus_channel,
    LocalKrausChannel,
    PurificationTruncationEvidence,
    PurifiedLindbladProblem,
    PurifiedLindbladResult,
    solve_purified_lindblad,
)
from ._purified_tebd import (
    apply_lpdo_two_site_unitary,
    LPDOBondEvidence,
    PurifiedStrangProblem,
    PurifiedStrangResult,
    solve_purified_strang,
)
from ._quantum_jump import (
    amplitude_damping_trajectory_problem,
    QuantumJumpProblem,
    QuantumTrajectoryEnsemble,
    solve_quantum_jump_ensemble,
    StateVectorOperator,
)
from ._quantum_jump_event import (
    EventDrivenQuantumJumpResult,
    QuantumJumpEventTable,
    solve_event_driven_quantum_jump,
)
from ._quantum_propagation import (
    solve_unitary_propagator,
    UnitaryGroupKind,
    UnitaryPropagatorProblem,
    UnitaryPropagatorSolution,
)
from ._quantum_tomography import (
    freeze_quantum_tomography,
    QuantumTomographyArtifact,
    QuantumTomographyPolicy,
    QuantumTomographyProblem,
    QuantumTomographyResult,
    solve_quantum_tomography,
)
from ._quantum_tomography_campaigns import tetrahedral_qubit_tomography
from ._quantum_trajectory_contract import (
    QuantumTrajectoryCheckpoint,
    QuantumTrajectoryEventTable,
    QuantumTrajectoryPlan,
    QuantumTrajectoryStatus,
)
from ._reflected_bsde import (
    predict_reflected_path_dependent_control,
    predict_reflected_path_dependent_value,
    reflected_path_dependent_bsde_diagnostics,
    ReflectedPathDependentBSDEDiagnostics,
    ReflectedPathDependentBSDEResult,
    solve_reflected_path_dependent_bsde,
)
from ._regression_bsde import (
    AbstractBSDERegressionBasis,
    BSDERegressionScheme,
    CallableBSDERegressionBasis,
    least_squares_bsde_diagnostics,
    LeastSquaresBSDEDiagnostics,
    LeastSquaresBSDEResult,
    PolynomialBSDERegressionBasis,
    predict_bsde_least_squares_control,
    predict_bsde_least_squares_value,
    solve_bsde_least_squares,
)
from ._rosenbrock import (
    RosenbrockAdaptivePolicy,
    RosenbrockWMethod,
    solve_rosenbrock,
    solve_rosenbrock_adaptive,
)
from ._rough import (
    AbstractRoughSolver,
    Davie,
    RoughDifferentialProblem,
    RoughDifferentialSolution,
    RoughDrift,
    RoughEuler,
    RoughVectorFields,
    solve_rough_differential,
)
from ._rough_delay import (
    RoughDelayDifferentialProblem,
    RoughDelayDrift,
    RoughDelayVectorFields,
    solve_rough_delay,
)
from ._rough_lift import lift_rough_vector_fields, LiftedRoughVectorFields
from ._rough_logode import LinearLogODE, LogODE
from ._semilinear import (
    exact_modal_stochastic_convolution,
    SemilinearFallback,
    SemilinearSPDEScheme,
    solve_semilinear_spde,
)
from ._semilinear_drift import SemilinearDrift
from ._spde import (
    SemidiscreteSPDE,
    semidiscretize_reaction_diffusion,
    semidiscretize_semilinear_spde,
    semidiscretize_spde,
)
from ._split_differential import (
    split_differential_problem,
    SplitDifferentialProblem,
)
from ._ssp_runge_kutta import SSPRK33, ssprk33_step, SSPRK54, ssprk54_step
from ._state_partition import StatePartition
from ._stencil_evolution import (
    PreparedSplitFieldPML,
    PreparedStaggeredAcoustics,
    SplitFieldPMLPlan,
    StaggeredAcousticPlan,
    StaggeredAcousticState,
)
from ._symplectic import (
    integrate_stormer_verlet,
    SeparableHamiltonianResult,
    stormer_verlet_step,
)
from ._temporal_method import (
    NoiseRequirement,
    TemporalEquationForm,
    TemporalMethodCapabilities,
    TemporalMethodClass,
    TemporalSolveEvidence,
)
from ._theta import ThetaMethod
from ._variational_monte_carlo import (
    evaluate_variational_monte_carlo,
    read_variational_monte_carlo_checkpoint,
    solve_variational_monte_carlo,
    VariationalMonteCarloEstimate,
    VariationalMonteCarloPolicy,
    VariationalMonteCarloProblem,
    VariationalMonteCarloResult,
    VariationalMonteCarloState,
    VMC_IMAGINARY_ENERGY,
    VMC_INVALID_SAMPLES,
    VMC_LINEAR_FAILURE,
    VMC_NONFINITE,
    vmc_status_name,
    VMC_SUCCESS,
    VMCStatus,
    write_variational_monte_carlo_checkpoint,
)
from ._variational_tdvp import (
    solve_variational_tdvp,
    TDVPMode,
    VariationalTDVPPolicy,
    VariationalTDVPResult,
)
from ._xxz_open import boundary_driven_xxz_problem


__all__ = [
    "CalabiYauCampaign",
    "CalabiYauMetricArtifact",
    "CalabiYauMetricProblem",
    "CalabiYauMetricResult",
    "CalabiYauSolvePolicy",
    "LindbladProblem",
    "LindbladSolution",
    "QuantumTomographyArtifact",
    "QuantumTomographyPolicy",
    "QuantumTomographyProblem",
    "QuantumTomographyResult",
    "amplitude_damping_problem",
    "cp1_calibration",
    "dephasing_problem",
    "freeze_calabi_yau_result",
    "freeze_quantum_tomography",
    "prepare_elliptic_curve",
    "prepare_fermat_calabi_yau",
    "prepare_fermat_quintic",
    "prepare_quartic_k3",
    "solve_calabi_yau_metric",
    "solve_lindblad",
    "solve_quantum_tomography",
    "tetrahedral_qubit_tomography",
    "DynamicalMapPhysicality",
    "GaussianLindbladProblem",
    "GaussianLindbladSolution",
    "HEOMHierarchy",
    "HEOMProblem",
    "HEOMSolution",
    "MemoryKernelMasterEquation",
    "OpenSystemHistorySolution",
    "PseudomodeEmbeddingProblem",
    "PseudomodeSolution",
    "QuantumJumpProblem",
    "QuantumMemoryKernel",
    "QuantumTrajectoryEnsemble",
    "StateVectorOperator",
    "TimeLocalOpenSystemProblem",
    "amplitude_damping_trajectory_problem",
    "damped_thermal_oscillator",
    "drude_lorentz_qubit_heom",
    "exponential_memory_qubit_problem",
    "jaynes_cummings_pseudomode_problem",
    "solve_gaussian_lindblad",
    "solve_heom",
    "solve_memory_kernel",
    "solve_pseudomode",
    "solve_quantum_jump_ensemble",
    "solve_time_local_open_system",
    "thermal_drude_lorentz_qubit_heom",
    "EventDrivenQuantumJumpResult",
    "FermionicGaussianProblem",
    "FermionicGaussianSolution",
    "FockContinuationPolicy",
    "FockContinuationResult",
    "FockContinuationStage",
    "HEOMContinuationResult",
    "HEOMContinuationStage",
    "LocalKrausChannel",
    "LocalMPSJump",
    "MPSQuantumJumpProblem",
    "MPSQuantumTrajectoryResult",
    "NeuralJumpProjectionProblem",
    "NeuralJumpProjectionResult",
    "NonMarkovianComparisonResult",
    "PurificationTruncationEvidence",
    "PurifiedLindbladProblem",
    "PurifiedLindbladResult",
    "QuantumJumpEventTable",
    "apply_local_kraus_channel",
    "damped_fermionic_mode",
    "lorentzian_qubit_comparison",
    "solve_event_driven_quantum_jump",
    "solve_fermionic_gaussian",
    "solve_fock_continuation",
    "solve_heom_continuation",
    "solve_mps_quantum_jump",
    "solve_neural_jump_projection",
    "solve_purified_lindblad",
    "SeparableHamiltonianResult",
    "integrate_stormer_verlet",
    "stormer_verlet_step",
    "UnitaryGroupKind",
    "UnitaryPropagatorProblem",
    "UnitaryPropagatorSolution",
    "solve_unitary_propagator",
    "AbstractDifferentiableDrivingPath",
    "AbstractGeometricSolver",
    "AbstractBSDERegressionBasis",
    "assemble_stochastic_collocation",
    "COLLOCATION_NONFINITE",
    "COLLOCATION_SOLVER_FAILURE",
    "COLLOCATION_SUCCESS",
    "CollocationAxisRule",
    "CoupledCost",
    "CoupledHierarchyResult",
    "CoupledLevelResult",
    "CoupledLevelSolver",
    "CoupledObservable",
    "CoupledValidity",
    "CoupledFBSDEProblem",
    "CoupledFBSDEResult",
    "BSDERegressionScheme",
    "CommutatorFreeSolver",
    "CommutatorFreeTableau",
    "commutator_free_midpoint_tableau",
    "DeepBSDEResult",
    "DeepPicardDiagnostics",
    "DeepPicardInitialSource",
    "DeepPicardResult",
    "DeepSplittingDiagnostics",
    "DeepSplittingInterpolation",
    "DeepSplittingResult",
    "DeepSplittingSamplingMode",
    "DeepSplittingSolution",
    "PicardSourceContext",
    "CallableBSDERegressionBasis",
    "CallableDrivingPath",
    "CausalBackwardHermiteDrivingPath",
    "ControlledDifferentialSolution",
    "ConstantDelay",
    "CompatibleElasticityDynamics",
    "CompatibleElasticityState",
    "CompatibleIdealMHDInductionDynamics",
    "CompatibleIdealMHDState",
    "CompatibleIncompressibleProjection",
    "CompatibleMaxwellDynamics",
    "CompatibleMaxwellState",
    "CompatiblePoroelasticDynamics",
    "CompatiblePoroelasticState",
    "CompatibleThermoelasticDynamics",
    "CompatibleThermoelasticState",
    "CompatibleVariableDensityProjection",
    "CheckpointedDelayAdjoint",
    "SegmentedDelayAdjoint",
    "DelayDifferentialProblem",
    "DelaySegmentArchive",
    "DelaySegmentContinuation",
    "DelayHistoryDerivative",
    "DelayHistoryWindow",
    "DelayTerm",
    "DelayValues",
    "DelayWienerTerm",
    "DerivativeDelay",
    "DistributedDelay",
    "DistributedDelayKernel",
    "DrivingPathFitDiagnostics",
    "FunctionalDelay",
    "HistoryFunctional",
    "EndpointNeutralFunctional",
    "NeutralDelayProblem",
    "NeutralFunctional",
    "NeutralRecoveryGuess",
    "DelayHistory",
    "DelayVectorField",
    "PointDelay",
    "StateDependentDelay",
    "StateDependentLag",
    "SegmentedDelayResult",
    "BDFMethod",
    "DifferentialInterpretation",
    "DifferentialProblem",
    "DifferentialSolution",
    "DAEAdaptivePolicy",
    "DAEAttemptHistory",
    "DAEAttemptStatus",
    "DAEContinuation",
    "DAEFailureMode",
    "DAERegularityEvidence",
    "DAERegularityFailureMode",
    "DAERegularityMode",
    "DAERegularityPolicy",
    "DAERegularityStatus",
    "DAEReplayEvidence",
    "DAEReplayMode",
    "DAEReplayPolicy",
    "DAESolvePlan",
    "DAESolvePolicy",
    "DAEStatus",
    "DAEStepHistory",
    "DAETemporalReusePolicy",
    "DAETerminationStatus",
    "DAEInitializationMode",
    "DAEInitializationResult",
    "DAEInitializationSpec",
    "DAEInitializationStatus",
    "DifferentialAlgebraicProblem",
    "DifferentialAlgebraicSolution",
    "discretized_dae_problem",
    "initialize_dae",
    "plan_dae",
    "prepare_dae",
    "PreparedDAESolve",
    "MarkovCubatureDiagnostics",
    "MarkovCubatureMethod",
    "MarkovCubaturePlan",
    "MarkovCubatureSolution",
    "MarkovCubatureStatus",
    "PolynomialRecombination",
    "solve_markov_cubature",
    "solve_dae",
    "DiffraxEvolution",
    "DifferentialVectorField",
    "FixedBSplineDrivingPath",
    "FunctionalCollocationPlan",
    "FunctionalDifferentialBoundaryProblem",
    "FunctionalDifferentialContext",
    "FunctionalDifferentialSolution",
    "DelayJumpMap",
    "evaluate_stochastic_collocation",
    "GeometricEuler",
    "GeometricLocalInterpolation",
    "GaussLegendreInterpolation",
    "GaussLegendreIRK",
    "GeneralizedAlphaMethod",
    "GeneralizedAlphaSolution",
    "NoiseStructure",
    "finite_state_generator",
    "FiniteStateGenerator",
    "GeneratorBoundaryPolicy",
    "JumpAlgorithm",
    "JumpDelayBackendResult",
    "JumpDelayProblem",
    "JumpDifferentialProblem",
    "JumpDifferentialSolution",
    "JumpSolution",
    "InteractingParticleProblem",
    "InteractingParticleSolution",
    "LevySDEProblem",
    "LevySDEScheme",
    "LevySDESolution",
    "IncompressibleProjectionResult",
    "LevySDESolverDiagnostics",
    "LevySDEVectorField",
    "LevySmallJumpApproximation",
    "PROBABILISTIC_ODE_NONFINITE",
    "PROBABILISTIC_ODE_STEP_LIMIT_REACHED",
    "PROBABILISTIC_ODE_STIFF",
    "PROBABILISTIC_ODE_SUCCESS",
    "probabilistic_ode_status_name",
    "ProbabilisticODECalibration",
    "ProbabilisticODECovarianceOutput",
    "ProbabilisticODEFactorization",
    "ProbabilisticODEMethod",
    "LocalImplicitSourcePlan",
    "ProbabilisticODESolution",
    "ProbabilisticODEStatus",
    "ProbabilisticODEUpdate",
    "IdentityStateTransfer",
    "CaputoFractionalProblem",
    "ConvolutionKernel",
    "ConvolutionVolterraProblem",
    "FractionalVectorField",
    "MemoryEquationSolution",
    "NoiseTruncationLevel",
    "NoiseTruncationStudy",
    "materialize_stochastic_collocation",
    "least_squares_bsde_diagnostics",
    "LeastSquaresBSDEDiagnostics",
    "RKMK",
    "SeparableHamiltonianVectorField",
    "SRKMK",
    "StormerVerlet",
    "solver_state_geometry",
    "LeastSquaresBSDEResult",
    "ParticleVectorField",
    "NeuralCDETrainingData",
    "NeuralCDETrainingState",
    "NeuralCDEVectorField",
    "neural_cde_loss",
    "OfflineCubicDrivingPath",
    "PiecewiseLinearDrivingPath",
    "AbstractRoughSolver",
    "Davie",
    "LiftedRoughVectorFields",
    "lift_rough_vector_fields",
    "LinearLogODE",
    "LogODE",
    "RoughDifferentialProblem",
    "RoughDelayDifferentialProblem",
    "RoughDelayDrift",
    "RoughDelayVectorFields",
    "RoughEuler",
    "RoughDifferentialSolution",
    "RoughDrift",
    "RoughVectorFields",
    "multirate_amr_subcycling_plan",
    "MultiratePartitionedRK",
    "NoiseRequirement",
    "PartitionedDifferentialProblem",
    "RosenbrockAdaptivePolicy",
    "RosenbrockWMethod",
    "SemidiscreteSPDE",
    "SemilinearDrift",
    "SemilinearFallback",
    "SemilinearSPDEScheme",
    "SPDEConvergenceLevel",
    "PreparedSplitFieldPML",
    "PreparedStaggeredAcoustics",
    "SPDEConvergenceMetric",
    "SPDEConvergenceStudy",
    "SPDEErrorBudget",
    "SPDERefinementAxis",
    "PolynomialBSDERegressionBasis",
    "predict_bsde_least_squares_control",
    "predict_bsde_least_squares_value",
    "predict_reflected_path_dependent_control",
    "predict_reflected_path_dependent_value",
    "reflected_path_dependent_bsde_diagnostics",
    "ReflectedPathDependentBSDEDiagnostics",
    "ReflectedPathDependentBSDEResult",
    "run_stochastic_collocation",
    "StochasticCollocationDesign",
    "StochasticCollocationDiagnostics",
    "StochasticCollocationNode",
    "StochasticCollocationNodeEvaluation",
    "StochasticCollocationPlan",
    "StochasticCollocationResult",
    "StochasticVolterraProblem",
    "WeakObservableEstimate",
    "WienerTerm",
    "SplitDifferentialProblem",
    "SSPRK33",
    "SSPRK54",
    "StatePartition",
    "TemporalEquationForm",
    "TemporalMethodCapabilities",
    "TemporalMethodClass",
    "TemporalSolveEvidence",
    "ThetaMethod",
    "VolterraFreeTerm",
    "VolterraKernel",
    "VolterraVectorField",
    "semidiscretize_reaction_diffusion",
    "coupled_strong_error",
    "exact_modal_stochastic_convolution",
    "semidiscretize_spde",
    "semidiscretize_semilinear_spde",
    "solve_caputo_fractional",
    "solve_convolution_volterra",
    "solve_diffrax",
    "split_differential_problem",
    "solve_diffrax_cde",
    "fixed_delay_history_capacity",
    "solve_diffrax_delay",
    "solve_diffrax_delay_segmented",
    "solve_diffrax_ensemble",
    "solve_generalized_alpha",
    "solve_implicit_runge_kutta",
    "solve_multirate",
    "solve_rosenbrock",
    "solve_rosenbrock_adaptive",
    "SplitFieldPMLPlan",
    "StaggeredAcousticPlan",
    "StaggeredAcousticState",
    "StrangSplitPlan",
    "DirectionalSplitFiniteVolumePlan",
    "FiniteVolumeStepResult",
    "SplittingKind",
    "UnsplitFiniteVolumeSSPRK3Plan",
    "FiniteVolumeAdvanceResult",
    "FiniteVolumeRunStatus",
    "FiniteVolumeRuntimeState",
    "FiniteVolumeStepPolicy",
    "PreparedFiniteVolumeRuntime",
    "FiniteVolumeCaseSpec",
    "FiniteVolumeExecutionSpec",
    "FiniteVolumePrecisionPolicy",
    "PrecisionDType",
    "load_finite_volume_case",
    "PreparedFiniteVolumeCase",
    "FiniteVolumeCheckpoint",
    "FiniteVolumeCheckpointPlan",
    "read_finite_volume_checkpoint",
    "write_finite_volume_checkpoint",
    "FiniteVolumeOutputPlan",
    "FiniteVolumeGradientReport",
    "FiniteVolumeRematerializationPolicy",
    "FiniteVolumeRetentionPolicy",
    "FiniteVolumeRolloutPlan",
    "FiniteVolumeRolloutResult",
    "solve_direct_ssa",
    "solve_jump_differential",
    "solve_next_reaction",
    "solve_jump_delay",
    "solve_functional_differential",
    "solve_levy_sde",
    "solve_coupled_hierarchy",
    "solve_coupled_fbsde_explicit",
    "solve_interacting_particles",
    "solve_rough_differential",
    "solve_probabilistic_ode",
    "solve_rough_delay",
    "solve_deep_picard",
    "solve_deep_bsde",
    "solve_deep_splitting",
    "StructuredPicardSource",
    "StructuredSourceBuilder",
    "solve_semilinear_spde",
    "ssprk33_step",
    "ssprk54_step",
    "solve_stochastic_volterra",
    "solve_bsde_least_squares",
    "solve_reflected_path_dependent_bsde",
    "weak_observable_estimate",
    "FunctionalSolver",
    "solve_variational_tdvp",
    "TDVPMode",
    "VariationalTDVPPolicy",
    "VariationalTDVPResult",
    "evaluate_variational_monte_carlo",
    "read_variational_monte_carlo_checkpoint",
    "solve_variational_monte_carlo",
    "write_variational_monte_carlo_checkpoint",
    "VariationalMonteCarloEstimate",
    "VariationalMonteCarloPolicy",
    "VariationalMonteCarloProblem",
    "VariationalMonteCarloResult",
    "VariationalMonteCarloState",
    "VMC_IMAGINARY_ENERGY",
    "VMC_INVALID_SAMPLES",
    "VMC_LINEAR_FAILURE",
    "VMC_NONFINITE",
    "VMC_SUCCESS",
    "VMCStatus",
    "vmc_status_name",
    "train_neural_cde",
    "CausalProcessTomographyProblem",
    "CausalProcessTomographyResult",
    "HEOMImplicitEvidence",
    "HEOMImplicitResult",
    "LPDOBondEvidence",
    "NeuralNoJumpTDVPProblem",
    "NeuralNoJumpTDVPResult",
    "ProcessTomographyExperiment",
    "PurifiedStrangProblem",
    "PurifiedStrangResult",
    "QuantumTrajectoryCheckpoint",
    "QuantumTrajectoryEventTable",
    "QuantumTrajectoryPlan",
    "QuantumTrajectoryStatus",
    "ScaledHEOMTopology",
    "SpinBosonComparisonResult",
    "apply_lpdo_two_site_unitary",
    "boundary_driven_xxz_problem",
    "fit_causal_process_initial_state",
    "open_kitaev_chain",
    "solve_heom_backward_euler",
    "solve_neural_no_jump_tdvp",
    "solve_purified_strang",
    "spin_boson_dephasing_comparison",
]
