#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from . import continuous, dynamic
from ._barycenters import (
    BarycenterDiagnostics,
    BarycenterProblemProvenance,
    BarycenterProvenance,
    BarycenterResult,
    fixed_support_barycenter_problem,
    FixedSupportBarycenterProblem,
    FreeSupportBarycenter,
    FreeSupportBarycenterDiagnostics,
    FreeSupportBarycenterProvenance,
    FreeSupportBarycenterResult,
    require_barycenter_converged,
    SinkhornBarycenter,
)
from ._costs import (
    AbstractGroundCost,
    IntrinsicSquaredDistanceCost,
    PeriodicSquaredEuclideanCost,
    PrecomputedCost,
    SquaredEuclideanCost,
    WeightedSquaredEuclideanCost,
)
from ._divergence import sinkhorn_divergence, SinkhornDivergenceResult
from ._fast_order import fast_soft_rank, fast_soft_sort
from ._problem import (
    discrete_problem,
    DiscreteTransportProblem,
    TransportProblemProvenance,
)
from ._references import (
    prepare_sinkhorn_reference,
    PreparedSinkhornReference,
    sinkhorn_divergence_against,
)
from ._results import (
    AbstractBalancedTransportPlan,
    AbstractBalancedTransportSolver,
    require_converged,
    SinkhornDiagnostics,
    SinkhornResult,
    TransportProvenance,
)
from ._scalable import (
    GaussianPositiveFeatures,
    KernelApproximationStatus,
    PositiveFeatureSinkhorn,
    PositiveFeatureSinkhornResult,
    PositiveKernelApproximationDiagnostics,
    PositiveKernelFactors,
)
from ._semidiscrete import (
    semidiscrete_problem,
    SemidiscreteIntegrationDiagnostics,
    SemidiscreteProblemProvenance,
    SemidiscreteQuantizationDiagnostics,
    SemidiscreteQuantizationResult,
    SemidiscreteQuantizer,
    SemidiscreteSinkhorn,
    SemidiscreteTransportDiagnostics,
    SemidiscreteTransportProblem,
    SemidiscreteTransportProvenance,
    SemidiscreteTransportResult,
)
from ._sinkhorn import Sinkhorn
from ._sliced import sliced_wasserstein_distance, SlicedWassersteinResult
from ._soft import (
    soft_order_transport,
    soft_quantile,
    soft_quantile_normalize,
    soft_quantize,
    soft_rank,
    soft_sort,
    soft_sort_by,
    soft_topk_mask,
    soft_topk_values,
)
from ._status import status_message, TransportStatus
from ._unbalanced_divergence import (
    unbalanced_sinkhorn_divergence,
    UnbalancedSinkhornDivergenceResult,
)
from ._unbalanced_problem import unbalanced_problem, UnbalancedTransportProblem
from ._unbalanced_references import (
    prepare_unbalanced_sinkhorn_reference,
    PreparedUnbalancedSinkhornReference,
    unbalanced_sinkhorn_divergence_against,
)
from ._unbalanced_results import (
    require_unbalanced_converged,
    UnbalancedSinkhornDiagnostics,
    UnbalancedSinkhornResult,
)
from ._unbalanced_sinkhorn import UnbalancedSinkhorn
from ._univariate import wasserstein_distance_1d
from .continuous import (
    AbstractEndpointInterpolant,
    ContinuousFlowDensityResult,
    ContinuousFlowLaw,
    ContinuousTransport,
    ContinuousTransportSample,
    EndpointCouplingSample,
    EndpointInterpolantEvaluation,
    estimate_continuous_flow_log_prob,
    independent_endpoint_coupling,
    LinearEndpointInterpolant,
    transport_plan_endpoint_coupling,
)
from .dynamic import (
    bridge_path_law_diagnostics,
    bridge_path_log_prob,
    BridgeInferenceAdapter,
    BridgePathLawDiagnostics,
    BridgePathSample,
    BridgeProblemProvenance,
    BridgeProvenance,
    ControlledTransitionKernel,
    FiniteBridgeTarget,
    reference_path_log_prob,
    require_converged_bridge,
    sample_bridge,
    sample_bridge_paths,
    sample_bridge_state_indices,
    SchrodingerBridgeDiagnostics,
    SchrodingerBridgeProblem,
    SchrodingerBridgeResult,
    SchrodingerBridgeSolver,
    solve_schrodinger_bridge,
    TerminalDistributionControlAdapter,
)


__all__ = [
    "AbstractBalancedTransportPlan",
    "AbstractBalancedTransportSolver",
    "AbstractGroundCost",
    "AbstractEndpointInterpolant",
    "BarycenterDiagnostics",
    "BarycenterProblemProvenance",
    "BarycenterProvenance",
    "BarycenterResult",
    "BridgeInferenceAdapter",
    "BridgePathLawDiagnostics",
    "BridgePathSample",
    "BridgeProblemProvenance",
    "BridgeProvenance",
    "ControlledTransitionKernel",
    "ContinuousFlowDensityResult",
    "ContinuousFlowLaw",
    "ContinuousTransport",
    "ContinuousTransportSample",
    "EndpointCouplingSample",
    "EndpointInterpolantEvaluation",
    "DiscreteTransportProblem",
    "FixedSupportBarycenterProblem",
    "FreeSupportBarycenter",
    "FreeSupportBarycenterDiagnostics",
    "FreeSupportBarycenterProvenance",
    "FreeSupportBarycenterResult",
    "FiniteBridgeTarget",
    "GaussianPositiveFeatures",
    "KernelApproximationStatus",
    "IntrinsicSquaredDistanceCost",
    "PeriodicSquaredEuclideanCost",
    "PrecomputedCost",
    "PreparedSinkhornReference",
    "PreparedUnbalancedSinkhornReference",
    "PositiveFeatureSinkhorn",
    "PositiveFeatureSinkhornResult",
    "LinearEndpointInterpolant",
    "PositiveKernelApproximationDiagnostics",
    "PositiveKernelFactors",
    "SemidiscreteIntegrationDiagnostics",
    "SemidiscreteProblemProvenance",
    "SemidiscreteQuantizationDiagnostics",
    "SemidiscreteQuantizationResult",
    "SemidiscreteQuantizer",
    "SemidiscreteSinkhorn",
    "SemidiscreteTransportDiagnostics",
    "SemidiscreteTransportProblem",
    "SemidiscreteTransportProvenance",
    "SemidiscreteTransportResult",
    "SchrodingerBridgeDiagnostics",
    "SchrodingerBridgeProblem",
    "SchrodingerBridgeResult",
    "SchrodingerBridgeSolver",
    "SinkhornBarycenter",
    "Sinkhorn",
    "SinkhornDiagnostics",
    "SinkhornDivergenceResult",
    "SlicedWassersteinResult",
    "SinkhornResult",
    "SquaredEuclideanCost",
    "TransportProblemProvenance",
    "TransportProvenance",
    "TransportStatus",
    "UnbalancedSinkhorn",
    "UnbalancedSinkhornDiagnostics",
    "UnbalancedSinkhornDivergenceResult",
    "UnbalancedSinkhornResult",
    "UnbalancedTransportProblem",
    "WeightedSquaredEuclideanCost",
    "TerminalDistributionControlAdapter",
    "fixed_support_barycenter_problem",
    "bridge_path_law_diagnostics",
    "estimate_continuous_flow_log_prob",
    "bridge_path_log_prob",
    "discrete_problem",
    "continuous",
    "dynamic",
    "fast_soft_rank",
    "independent_endpoint_coupling",
    "fast_soft_sort",
    "semidiscrete_problem",
    "sliced_wasserstein_distance",
    "soft_order_transport",
    "soft_quantile",
    "soft_quantile_normalize",
    "soft_quantize",
    "soft_rank",
    "soft_sort",
    "soft_sort_by",
    "soft_topk_mask",
    "soft_topk_values",
    "prepare_sinkhorn_reference",
    "prepare_unbalanced_sinkhorn_reference",
    "require_converged",
    "require_barycenter_converged",
    "require_unbalanced_converged",
    "reference_path_log_prob",
    "require_converged_bridge",
    "sinkhorn_divergence",
    "sinkhorn_divergence_against",
    "sample_bridge",
    "sample_bridge_paths",
    "sample_bridge_state_indices",
    "solve_schrodinger_bridge",
    "unbalanced_problem",
    "unbalanced_sinkhorn_divergence",
    "unbalanced_sinkhorn_divergence_against",
    "transport_plan_endpoint_coupling",
    "status_message",
    "wasserstein_distance_1d",
]
