from __future__ import annotations

from phydrax.units._dimension import (
    AMOUNT,
    ANGLE,
    CAPACITANCE,
    CHARGE,
    CONCENTRATION,
    CONDUCTANCE,
    CURRENT,
    DIMENSIONLESS,
    ENERGY,
    LENGTH,
    MASS,
    PRESSURE,
    RESISTANCE,
    TEMPERATURE,
    TIME,
    VOLTAGE,
    VOLUME,
)
from phydrax.units._unit import derived_unit, UnitDefinition


SI_REFERENCE_SYSTEM_ID = "si"

ONE = UnitDefinition("1", DIMENSIONLESS, SI_REFERENCE_SYSTEM_ID)

METER = UnitDefinition("m", LENGTH, SI_REFERENCE_SYSTEM_ID)
KILOMETER = UnitDefinition("km", LENGTH, SI_REFERENCE_SYSTEM_ID, 1000)
CENTIMETER = UnitDefinition("cm", LENGTH, SI_REFERENCE_SYSTEM_ID, "0.01")
BOHR = UnitDefinition("bohr", LENGTH, SI_REFERENCE_SYSTEM_ID, "5.29177210903e-11")
MILLIMETER = UnitDefinition("mm", LENGTH, SI_REFERENCE_SYSTEM_ID, "0.001")
MICROMETER = UnitDefinition("um", LENGTH, SI_REFERENCE_SYSTEM_ID, "0.000001")
ANGSTROM = UnitDefinition("angstrom", LENGTH, SI_REFERENCE_SYSTEM_ID, "1e-10")
MEGAPARSEC = UnitDefinition(
    "Mpc", LENGTH, SI_REFERENCE_SYSTEM_ID, "3.0856775814913673e22"
)

KILOGRAM = UnitDefinition("kg", MASS, SI_REFERENCE_SYSTEM_ID)
MILLIGRAM = UnitDefinition("mg", MASS, SI_REFERENCE_SYSTEM_ID, "1e-6")
DALTON = UnitDefinition("dalton", MASS, SI_REFERENCE_SYSTEM_ID, "1.66053906660e-27")
SOLAR_MASS = UnitDefinition("solar_mass", MASS, SI_REFERENCE_SYSTEM_ID, "1.98847e30")

SECOND = UnitDefinition("s", TIME, SI_REFERENCE_SYSTEM_ID)
MILLISECOND = UnitDefinition("ms", TIME, SI_REFERENCE_SYSTEM_ID, "0.001")
PICOSECOND = UnitDefinition("ps", TIME, SI_REFERENCE_SYSTEM_ID, "1e-12")
FEMTOSECOND = UnitDefinition("fs", TIME, SI_REFERENCE_SYSTEM_ID, "1e-15")
GIGAYEAR = UnitDefinition("Gyr", TIME, SI_REFERENCE_SYSTEM_ID, "3.15576e16")

COULOMB = UnitDefinition("C", CHARGE, SI_REFERENCE_SYSTEM_ID)
ELEMENTARY_CHARGE = UnitDefinition("e", CHARGE, SI_REFERENCE_SYSTEM_ID, "1.602176634e-19")
KELVIN = UnitDefinition("K", TEMPERATURE, SI_REFERENCE_SYSTEM_ID)
MOLE = UnitDefinition("mol", AMOUNT, SI_REFERENCE_SYSTEM_ID)
RADIAN = UnitDefinition("rad", ANGLE, SI_REFERENCE_SYSTEM_ID)
DEGREE = UnitDefinition("deg", ANGLE, SI_REFERENCE_SYSTEM_ID, "0.017453292519943295")

JOULE = UnitDefinition("J", ENERGY, SI_REFERENCE_SYSTEM_ID)
ELECTRONVOLT = UnitDefinition("eV", ENERGY, SI_REFERENCE_SYSTEM_ID, "1.602176634e-19")
HARTREE = UnitDefinition("hartree", ENERGY, SI_REFERENCE_SYSTEM_ID, "4.3597447222071e-18")
KILOJOULE = UnitDefinition("kJ", ENERGY, SI_REFERENCE_SYSTEM_ID, 1000)
KILOCALORIE = UnitDefinition("kcal", ENERGY, SI_REFERENCE_SYSTEM_ID, 4184)

AMPERE = UnitDefinition("A", CURRENT, SI_REFERENCE_SYSTEM_ID)
MICROAMPERE = UnitDefinition("uA", CURRENT, SI_REFERENCE_SYSTEM_ID, "1e-6")
NANOAMPERE = UnitDefinition("nA", CURRENT, SI_REFERENCE_SYSTEM_ID, "1e-9")

VOLT = UnitDefinition("V", VOLTAGE, SI_REFERENCE_SYSTEM_ID)
MILLIVOLT = UnitDefinition("mV", VOLTAGE, SI_REFERENCE_SYSTEM_ID, "0.001")

SIEMENS = UnitDefinition("S", CONDUCTANCE, SI_REFERENCE_SYSTEM_ID)
MILLISIEMENS = UnitDefinition("mS", CONDUCTANCE, SI_REFERENCE_SYSTEM_ID, "0.001")
MICROSIEMENS = UnitDefinition("uS", CONDUCTANCE, SI_REFERENCE_SYSTEM_ID, "1e-6")

OHM = UnitDefinition("ohm", RESISTANCE, SI_REFERENCE_SYSTEM_ID)
MEGOHM = UnitDefinition("Mohm", RESISTANCE, SI_REFERENCE_SYSTEM_ID, "1e6")

FARAD = UnitDefinition("F", CAPACITANCE, SI_REFERENCE_SYSTEM_ID)
MICROFARAD = UnitDefinition("uF", CAPACITANCE, SI_REFERENCE_SYSTEM_ID, "1e-6")
NANOFARAD = UnitDefinition("nF", CAPACITANCE, SI_REFERENCE_SYSTEM_ID, "1e-9")

PASCAL = UnitDefinition("Pa", PRESSURE, SI_REFERENCE_SYSTEM_ID)
KILOPASCAL = UnitDefinition("kPa", PRESSURE, SI_REFERENCE_SYSTEM_ID, 1000)
MILLIMETER_MERCURY = UnitDefinition(
    "mmHg", PRESSURE, SI_REFERENCE_SYSTEM_ID, "133.322387415"
)

CUBIC_METER = UnitDefinition("m3", VOLUME, SI_REFERENCE_SYSTEM_ID)
LITER = UnitDefinition("L", VOLUME, SI_REFERENCE_SYSTEM_ID, "0.001")
MILLILITER = UnitDefinition("mL", VOLUME, SI_REFERENCE_SYSTEM_ID, "1e-6")
MICROLITER = UnitDefinition("uL", VOLUME, SI_REFERENCE_SYSTEM_ID, "1e-9")
PICOLITER = UnitDefinition("pL", VOLUME, SI_REFERENCE_SYSTEM_ID, "1e-15")

MOLE_PER_CUBIC_METER = UnitDefinition("mol/m3", CONCENTRATION, SI_REFERENCE_SYSTEM_ID)
MILLIMOLAR = UnitDefinition("mM", CONCENTRATION, SI_REFERENCE_SYSTEM_ID)

KILOJOULE_PER_MOLE = derived_unit("kJ/mol", ((KILOJOULE, 1), (MOLE, -1)))
KILOCALORIE_PER_MOLE = derived_unit("kcal/mol", ((KILOCALORIE, 1), (MOLE, -1)))

OHM_CENTIMETER = derived_unit("ohm*cm", ((OHM, 1), (CENTIMETER, 1)))
MICROFARAD_PER_SQUARE_CENTIMETER = derived_unit(
    "uF/cm2", ((MICROFARAD, 1), (CENTIMETER, -2))
)
MILLISIEMENS_PER_SQUARE_CENTIMETER = derived_unit(
    "mS/cm2", ((MILLISIEMENS, 1), (CENTIMETER, -2))
)
MICROAMPERE_PER_SQUARE_CENTIMETER = derived_unit(
    "uA/cm2", ((MICROAMPERE, 1), (CENTIMETER, -2))
)
