# Copyright © 2026 PHYDRA, Inc. All rights reserved.
"""Physical bindings and host boundaries shared by geophysical applications."""

from ._archive import read_geophysical_archive, write_geophysical_archive
from ._binding import GeophysicalFieldBinding
from ._coupling import (
    BoussinesqOceanCouplingSubsystem,
    coupling_surface_field,
    geophysical_coupling_quantity,
    HydrostaticOceanCouplingSubsystem,
    read_geophysical_coupling_checkpoint,
    SlabReservoir,
    SlabReservoirState,
    write_geophysical_coupling_checkpoint,
)
from ._data import (
    DEFAULT_GEOPHYSICAL_DATA_LIMITS,
    from_cf_dataset,
    GeophysicalData,
    read_cf,
    to_cf_dataset,
    write_cf,
)
from ._ensembles import (
    geophysical_analysis_increments,
    GeophysicalAnalysisIncrement,
    GeophysicalAnalysisInventory,
    GeophysicalEnsembleAxis,
    GeophysicalEnsembleLineage,
    prepare_geophysical_assimilation,
)
from ._flux_closure import (
    admit_column_flux,
    column_flux_datasets,
    column_flux_quantities,
    column_flux_space,
    column_flux_tasks,
    ColumnFluxAdmission,
    ColumnFluxBinding,
    ColumnFluxTarget,
    conditional_column_flux_target,
    ConservativeColumnTransfer,
    deploy_column_flux,
)
from ._inference import (
    column_gradient_audit,
    column_local_information,
    ColumnCalibrationProblem,
    ColumnCalibrationResult,
    ColumnDesignCandidate,
    ColumnDesignResult,
    ColumnExperiment,
    ColumnIntervention,
    ColumnLocalInformation,
    ColumnObservationBinding,
    ColumnObservationData,
    ColumnParameterSpace,
    ColumnPrediction,
    design_column_intervention,
    load_column_inference,
    save_column_inference,
    score_column_holdout,
)
from ._learning import (
    admit_column_closure,
    column_closure_dataset,
    ColumnClosureAdmission,
    ColumnClosureBinding,
    deploy_column_closure,
    GeophysicalForcingSchedule,
    GeophysicalForecastContinuation,
    GeophysicalForecastProduct,
    GeophysicalForecastRequest,
    GeophysicalLearningExperiment,
    NativeGeophysicalForecast,
)
from ._metrics import (
    fit_geophysical_climatology,
    geophysical_extreme_reliability,
    geophysical_forecast_metrics,
    geophysical_spectral_rmse,
    GeophysicalClimatology,
    GeophysicalExtremeReliability,
    GeophysicalFieldMetrics,
    GeophysicalForecastMetrics,
)
from ._observations import (
    GeophysicalObservationOperator,
    GeophysicalObservationPolicy,
    prepare_geophysical_observations,
    prepare_tensor_observation_operator,
    PreparedGeophysicalObservations,
)
from ._quantities import GeophysicalQuantity
from ._time import GeophysicalTimeSpec, TemporalSupport
from ._vertical import HybridPressureCoordinate


__all__ = [
    "GeophysicalFieldBinding",
    "GeophysicalQuantity",
    "GeophysicalTimeSpec",
    "TemporalSupport",
    "HybridPressureCoordinate",
    "read_geophysical_archive",
    "write_geophysical_archive",
    "BoussinesqOceanCouplingSubsystem",
    "HydrostaticOceanCouplingSubsystem",
    "SlabReservoir",
    "SlabReservoirState",
    "coupling_surface_field",
    "geophysical_coupling_quantity",
    "read_geophysical_coupling_checkpoint",
    "write_geophysical_coupling_checkpoint",
    "DEFAULT_GEOPHYSICAL_DATA_LIMITS",
    "GeophysicalData",
    "from_cf_dataset",
    "read_cf",
    "to_cf_dataset",
    "write_cf",
    "GeophysicalAnalysisIncrement",
    "GeophysicalAnalysisInventory",
    "GeophysicalEnsembleAxis",
    "GeophysicalEnsembleLineage",
    "geophysical_analysis_increments",
    "prepare_geophysical_assimilation",
    "ColumnClosureAdmission",
    "ColumnClosureBinding",
    "GeophysicalForcingSchedule",
    "GeophysicalForecastContinuation",
    "GeophysicalForecastProduct",
    "GeophysicalForecastRequest",
    "GeophysicalLearningExperiment",
    "NativeGeophysicalForecast",
    "admit_column_closure",
    "column_closure_dataset",
    "deploy_column_closure",
    "GeophysicalClimatology",
    "GeophysicalExtremeReliability",
    "GeophysicalFieldMetrics",
    "GeophysicalForecastMetrics",
    "fit_geophysical_climatology",
    "geophysical_extreme_reliability",
    "geophysical_forecast_metrics",
    "geophysical_spectral_rmse",
    "GeophysicalObservationOperator",
    "GeophysicalObservationPolicy",
    "PreparedGeophysicalObservations",
    "prepare_geophysical_observations",
    "prepare_tensor_observation_operator",
    "ColumnFluxAdmission",
    "ColumnFluxBinding",
    "ColumnFluxTarget",
    "ConservativeColumnTransfer",
    "admit_column_flux",
    "column_flux_datasets",
    "column_flux_quantities",
    "column_flux_space",
    "column_flux_tasks",
    "conditional_column_flux_target",
    "deploy_column_flux",
    "ColumnParameterSpace",
    "ColumnIntervention",
    "ColumnObservationBinding",
    "ColumnExperiment",
    "ColumnPrediction",
    "ColumnObservationData",
    "ColumnLocalInformation",
    "ColumnCalibrationProblem",
    "ColumnCalibrationResult",
    "ColumnDesignCandidate",
    "ColumnDesignResult",
    "column_local_information",
    "column_gradient_audit",
    "design_column_intervention",
    "score_column_holdout",
    "save_column_inference",
    "load_column_inference",
]
