#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Global tensor spectral spaces, operators, and pseudospectral methods."""

from ..._spectral._spherical import (
    SphericalExecution,
    SphericalHarmonicPlan,
    SphericalSampling,
)
from ._basis import (
    AbstractSpectralBasisPlan,
    ChebyshevBasisPlan,
    CosineBasisPlan,
    FourierBasisPlan,
    LegendreBasisPlan,
    PreparedSpectralAxis,
    SineBasisPlan,
    SpectralBasisFamily,
    SpectralBoundaryKind,
    SpectralModeLayout,
)
from ._channel import (
    ChannelMeanConstraint,
    ChannelMeanConstraintKind,
    ChannelStokesDiagnostics,
    ChannelStokesPlan,
    ChannelStokesPreparationReport,
    ChannelStokesRoute,
    ChannelStokesSolveResult,
    PreparedChannelStokesSolver,
)
from ._conservation import (
    PreparedSpectralConservationDynamics,
    PreparedSpectralConservationMethod,
    PreparedSpectralSplitForm,
    SpectralConservationDiagnostics,
    SpectralConservationMethodPlan,
    SpectralEntropyDiagnostics,
    SpectralSplitFormPlan,
    SpectralSplitFormReport,
)
from ._constraints import (
    BoundaryLiftPlan,
    ConstrainedBasisPlan,
    PreparedBoundaryLift,
    SpectralBoundaryConditionPlan,
    SpectralTraceConstraint,
    SpectralTraceTerm,
)
from ._coordinates import HermitianSpectralCoordinates
from ._dealias import (
    AbstractDealiasingPlan,
    DealiasingKind,
    DealiasingReport,
    ModalFilterPlan,
    NoDealiasingPlan,
    PaddingDealiasingPlan,
    PolynomialClosureDealiasingPlan,
    PreparedDealiasingPlan,
)
from ._diagnostics import (
    ModalDecayReport,
    PreparedSpectralModalDiagnostics,
    SpectralModalDiagnosticsPlan,
)
from ._distributed import (
    DistributedSpectralExecutionPlan,
    DistributedSpectralPreparationReport,
    SpectralExecutionResult,
    SpectralGlobalDiagnostics,
    SpectralLayout,
    SpectralMeshTopology,
    SpectralResourceError,
    SpectralResourceReport,
    SpectralTranspose,
)
from ._eigen_verification import (
    compare_spectral_eigen_resolutions,
    SpectralEigenResolutionPolicy,
    SpectralEigenResolutionReport,
)
from ._fourier_shells import (
    DCPolicy,
    FinalEdgePolicy,
    FourierShellStatisticResult,
    ModeTransferCorrection,
    NyquistPolicy,
    PeriodicFourierField,
    PeriodicFourierShellPlan,
)
from ._galerkin import PreparedSpectralGalerkin, SpectralGalerkinMethodPlan
from ._incompressible import (
    IncompressibleSpectralDiagnostics,
    PeriodicLerayProjector,
)
from ._lattice import (
    BrillouinZonePlan,
    HarmonicTruncationKind,
    LatticeHarmonicDiscretization,
    LatticeHarmonicLayout,
    LatticeHarmonicPlan,
    PreparedBrillouinZone,
)
from ._method import (
    PreparedPseudospectralMethod,
    PseudospectralMethodPlan,
    SpectralDifferentiabilityPolicy,
    SpectralResidualDiagnostics,
)
from ._modal_discovery import (
    discover_modal_support,
    estimate_spectral_regularity,
    MissingModeRecoveryPolicy,
    MissingModeRecoveryProblem,
    MissingModeRecoveryResult,
    ModalSupportDiscoveryPlan,
    PreparedModalSupport,
    recover_missing_modes,
    SpectralRegularityEstimate,
)
from ._operators import (
    PreparedSpectralOperator,
    spectral_derivative_operator,
    spectral_hilbert_operator,
    spectral_laplacian_operator,
)
from ._precision import SpectralPrecisionPolicy
from ._rational import (
    RationalChebyshevHalfLineBasisPlan,
    RationalChebyshevLineBasisPlan,
)
from ._space import TensorSpectralDiscretization, TensorSpectralPlan
from ._spherical import (
    spherical_laplacian_operator,
    SphericalSpectralDiscretization,
    SphericalSpectralPlan,
)
from ._spherical_algebra import (
    PreparedSphericalClebschGordan,
    PreparedSphericalRotation,
    SphericalClebschGordanPlan,
    SphericalClebschGordanReport,
    SphericalRotationPlan,
)
from ._spherical_layout import SphericalModeLayout
from ._spherical_operators import (
    PreparedSphericalSpinOperator,
    spherical_coordinate_derivative,
    SphericalCoordinate,
    SphericalCoordinateDerivativeResult,
    SphericalDerivativeRepresentation,
    SphericalSpinOperatorKind,
    SphericalSpinOperatorPlan,
)
from ._spherical_sampling import (
    HealpixOrdering,
    PreparedSphericalSampleOperator,
    SphericalSampleFitResult,
    SphericalSamplePlan,
    SphericalSampleReport,
)
from ._symmetry import (
    project_tensor_spectral_symmetries,
    TensorSpectralSymmetry,
)
from ._tau import GeneralizedTauPlan, PreparedTauSystem, TauSolveResult
from ._transfer import (
    prepare_spectral_modal_transfer,
    PreparedSpectralModalTransfer,
    SpectralModalTransferPlan,
    SpectralModalTransferReport,
    SpectralModalTransferResult,
)


__all__ = [
    "AbstractDealiasingPlan",
    "AbstractSpectralBasisPlan",
    "BoundaryLiftPlan",
    "ChebyshevBasisPlan",
    "ConstrainedBasisPlan",
    "CosineBasisPlan",
    "ChannelMeanConstraint",
    "ChannelMeanConstraintKind",
    "ChannelStokesDiagnostics",
    "ChannelStokesPlan",
    "ChannelStokesPreparationReport",
    "ChannelStokesRoute",
    "ChannelStokesSolveResult",
    "DCPolicy",
    "FinalEdgePolicy",
    "FourierShellStatisticResult",
    "DealiasingKind",
    "discover_modal_support",
    "estimate_spectral_regularity",
    "BrillouinZonePlan",
    "DealiasingReport",
    "FourierBasisPlan",
    "HermitianSpectralCoordinates",
    "IncompressibleSpectralDiagnostics",
    "GeneralizedTauPlan",
    "HarmonicTruncationKind",
    "LegendreBasisPlan",
    "LatticeHarmonicDiscretization",
    "LatticeHarmonicLayout",
    "LatticeHarmonicPlan",
    "HealpixOrdering",
    "ModalFilterPlan",
    "ModalDecayReport",
    "ModeTransferCorrection",
    "MissingModeRecoveryPolicy",
    "MissingModeRecoveryProblem",
    "MissingModeRecoveryResult",
    "ModalSupportDiscoveryPlan",
    "NyquistPolicy",
    "NoDealiasingPlan",
    "PaddingDealiasingPlan",
    "PolynomialClosureDealiasingPlan",
    "PeriodicLerayProjector",
    "PreparedBoundaryLift",
    "PreparedDealiasingPlan",
    "PreparedPseudospectralMethod",
    "PreparedSpectralModalDiagnostics",
    "PreparedSphericalClebschGordan",
    "PreparedSphericalRotation",
    "PreparedSphericalSampleOperator",
    "PreparedSphericalSpinOperator",
    "PreparedSpectralSplitForm",
    "PreparedSpectralModalTransfer",
    "PreparedSpectralAxis",
    "PreparedSpectralConservationDynamics",
    "PreparedSpectralConservationMethod",
    "PreparedChannelStokesSolver",
    "PreparedSpectralGalerkin",
    "PreparedSpectralOperator",
    "PreparedBrillouinZone",
    "PreparedModalSupport",
    "PeriodicFourierField",
    "PeriodicFourierShellPlan",
    "PreparedTauSystem",
    "TensorSpectralSymmetry",
    "PseudospectralMethodPlan",
    "SineBasisPlan",
    "SphericalClebschGordanPlan",
    "SphericalClebschGordanReport",
    "SphericalCoordinate",
    "SphericalCoordinateDerivativeResult",
    "SphericalDerivativeRepresentation",
    "SphericalExecution",
    "SphericalHarmonicPlan",
    "SphericalModeLayout",
    "SphericalSampling",
    "SphericalSpectralDiscretization",
    "SphericalSpectralPlan",
    "SphericalRotationPlan",
    "SphericalSampleFitResult",
    "SphericalSamplePlan",
    "SphericalSampleReport",
    "SphericalSpinOperatorKind",
    "SphericalSpinOperatorPlan",
    "RationalChebyshevHalfLineBasisPlan",
    "RationalChebyshevLineBasisPlan",
    "SpectralBasisFamily",
    "SpectralBoundaryConditionPlan",
    "SpectralBoundaryKind",
    "SpectralConservationDiagnostics",
    "SpectralConservationMethodPlan",
    "SpectralDifferentiabilityPolicy",
    "SpectralEntropyDiagnostics",
    "SpectralSplitFormPlan",
    "SpectralSplitFormReport",
    "SpectralGalerkinMethodPlan",
    "SpectralModeLayout",
    "SpectralEigenResolutionPolicy",
    "SpectralEigenResolutionReport",
    "SpectralModalDiagnosticsPlan",
    "SpectralModalTransferPlan",
    "SpectralModalTransferResult",
    "SpectralModalTransferReport",
    "recover_missing_modes",
    "SpectralRegularityEstimate",
    "SpectralPrecisionPolicy",
    "SpectralTraceConstraint",
    "SpectralTraceTerm",
    "project_tensor_spectral_symmetries",
    "compare_spectral_eigen_resolutions",
    "prepare_spectral_modal_transfer",
    "SpectralResidualDiagnostics",
    "TauSolveResult",
    "TensorSpectralDiscretization",
    "TensorSpectralPlan",
    "spectral_derivative_operator",
    "spectral_hilbert_operator",
    "spectral_laplacian_operator",
    "spherical_laplacian_operator",
    "spherical_coordinate_derivative",
    "DistributedSpectralExecutionPlan",
    "DistributedSpectralPreparationReport",
    "SpectralExecutionResult",
    "SpectralGlobalDiagnostics",
    "SpectralLayout",
    "SpectralMeshTopology",
    "SpectralResourceError",
    "SpectralResourceReport",
    "SpectralTranspose",
]
