#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from ._cache import (
    CachedContactSearchPlan,
    ContactSearchCacheState,
    ContactSearchCacheUpdate,
)
from ._ccd import (
    CCDStatus,
    CertifiedAABBCCDPlan,
    collision_free_step_limit,
    ContactSafetyEvidence,
    InclusionCCDPlan,
)
from ._compiled_search import (
    CompiledCandidateBatch,
    CompiledContactSearchEvidence,
    CompiledContactSearchPlan,
    CompiledContactSearchResult,
)
from ._distance import (
    contact_tangent_basis,
    ContactDistanceEvaluation,
    edge_edge_distance,
    edge_edge_mollifier,
    edge_edge_mollifier_threshold,
    EdgeEdgeFeature,
    point_edge_distance,
    point_point_distance,
    point_triangle_distance,
    PointEdgeFeature,
    PointTriangleFeature,
)
from ._distributed import (
    DistributedContactEpoch,
    DistributedContactPartitionPlan,
    partition_contact_epoch,
)
from ._geometric_filter import (
    certify_closed_oriented_surface,
    ClosedSurfaceCertificate,
    filter_geometric_contacts,
    GeometricContactFilterEvidence,
    GeometricContactFilterPlan,
    GeometricContactFilterResult,
)
from ._guarantee import (
    ContactCapability,
    ContactGuaranteeEvidence,
    ContactGuaranteeLevel,
)
from ._halo import (
    ContactHaloExchangeEvidence,
    ContactHaloExchangePlan,
    ContactHaloPayload,
    ContactHaloReduction,
    pack_contact_halo,
    reduce_contact_halo,
)
from ._implicit_geometry import (
    AbstractImplicitContactGeometry,
    FunctionImplicitContactGeometry,
    ImplicitContactEvaluation,
    PlaneContactGeometry,
    SphereContactGeometry,
)
from ._interface import (
    assemble_contact_interface_traction,
    ContactInterfaceKinematics,
    ContactInterfacePlan,
    ContactInterfaceResidual,
    evaluate_contact_interface,
)
from ._inversion import (
    InversionStatus,
    InversionStepEvidence,
    simplex_inversion_step_limit,
    SimplexInversionStepPlan,
)
from ._kinematics import (
    ContactKinematicsBatch,
    ContactKinematicsEpoch,
    ContactKinematicsEvidence,
    evaluate_contact_kinematics,
    evaluate_contact_kinematics_batch,
)
from ._participant import (
    AbstractContactParticipant,
    ContactParticipantScene,
    FunctionContactParticipant,
    LinearContactParticipant,
    ParticipantDualityEvidence,
    ParticipantTrajectoryBounds,
)
from ._patch_builder import (
    build_triangle_mortar_interface,
    ContactPatchBuildEvidence,
    ContactPatchBuildResult,
)
from ._precision import ContactPrecisionPolicy
from ._pressure_patch import (
    extract_hydroelastic_pressure_patch,
    HydroelasticPatchEvidence,
    HydroelasticPatchExtraction,
    HydroelasticPressureFieldPlan,
    HydroelasticPressurePatch,
)
from ._proxy import (
    ContactProxyEvidence,
    ContactProxyPlan,
    ContactProxyTransfer,
    PreparedContactProxy,
)
from ._search import (
    ContactCandidateEpoch,
    ContactSearchLimits,
    ContactSearchStatus,
    DenseContactSearchPlan,
    SweepAndPruneContactSearchPlan,
)
from ._stencils import (
    canonical_contact_route_keys,
    ContactStencilBatch,
    ContactStencilEvaluation,
    ContactStencilKind,
    evaluate_contact_stencils,
)
from ._surface import (
    CollisionMapEvidence,
    CollisionSurfacePlan,
    ContactPairPolicy,
    prepare_cell_mesh_collision_surface,
    PreparedCollisionScene,
    PreparedCollisionSurface,
    selection_collision_operator,
    static_collision_operator,
)
from ._trajectory import (
    AbstractContactTrajectory,
    ContactTrajectoryEvaluation,
    CubicHermiteContactTrajectory,
    LinearContactTrajectory,
    RigidSweepContactTrajectory,
)


__all__ = [
    "AbstractContactParticipant",
    "AbstractContactTrajectory",
    "AbstractImplicitContactGeometry",
    "CCDStatus",
    "CachedContactSearchPlan",
    "CertifiedAABBCCDPlan",
    "CollisionMapEvidence",
    "ClosedSurfaceCertificate",
    "CompiledCandidateBatch",
    "CompiledContactSearchEvidence",
    "CompiledContactSearchPlan",
    "CompiledContactSearchResult",
    "ContactHaloExchangeEvidence",
    "ContactHaloExchangePlan",
    "ContactHaloPayload",
    "ContactHaloReduction",
    "ContactPatchBuildEvidence",
    "ContactPatchBuildResult",
    "GeometricContactFilterEvidence",
    "GeometricContactFilterPlan",
    "GeometricContactFilterResult",
    "HydroelasticPatchEvidence",
    "HydroelasticPatchExtraction",
    "HydroelasticPressureFieldPlan",
    "HydroelasticPressurePatch",
    "build_triangle_mortar_interface",
    "certify_closed_oriented_surface",
    "extract_hydroelastic_pressure_patch",
    "filter_geometric_contacts",
    "pack_contact_halo",
    "reduce_contact_halo",
    "CollisionSurfacePlan",
    "ContactCandidateEpoch",
    "ContactCapability",
    "ContactDistanceEvaluation",
    "ContactGuaranteeEvidence",
    "ContactGuaranteeLevel",
    "ContactInterfaceKinematics",
    "ContactInterfacePlan",
    "ContactInterfaceResidual",
    "ContactKinematicsBatch",
    "ContactKinematicsEpoch",
    "ContactKinematicsEvidence",
    "ContactPairPolicy",
    "ContactParticipantScene",
    "ContactPrecisionPolicy",
    "ContactProxyEvidence",
    "ContactProxyPlan",
    "ContactProxyTransfer",
    "ContactSafetyEvidence",
    "ContactSearchCacheState",
    "ContactSearchCacheUpdate",
    "ContactSearchLimits",
    "ContactSearchStatus",
    "ContactStencilBatch",
    "ContactStencilEvaluation",
    "ContactStencilKind",
    "ContactTrajectoryEvaluation",
    "CubicHermiteContactTrajectory",
    "DenseContactSearchPlan",
    "DistributedContactEpoch",
    "DistributedContactPartitionPlan",
    "EdgeEdgeFeature",
    "FunctionContactParticipant",
    "FunctionImplicitContactGeometry",
    "ImplicitContactEvaluation",
    "InclusionCCDPlan",
    "InversionStatus",
    "InversionStepEvidence",
    "LinearContactParticipant",
    "LinearContactTrajectory",
    "ParticipantDualityEvidence",
    "ParticipantTrajectoryBounds",
    "PlaneContactGeometry",
    "PointEdgeFeature",
    "PointTriangleFeature",
    "PreparedCollisionScene",
    "PreparedCollisionSurface",
    "PreparedContactProxy",
    "RigidSweepContactTrajectory",
    "SimplexInversionStepPlan",
    "SphereContactGeometry",
    "SweepAndPruneContactSearchPlan",
    "assemble_contact_interface_traction",
    "canonical_contact_route_keys",
    "collision_free_step_limit",
    "contact_tangent_basis",
    "edge_edge_distance",
    "edge_edge_mollifier",
    "edge_edge_mollifier_threshold",
    "evaluate_contact_interface",
    "evaluate_contact_kinematics",
    "evaluate_contact_kinematics_batch",
    "evaluate_contact_stencils",
    "partition_contact_epoch",
    "point_edge_distance",
    "point_point_distance",
    "point_triangle_distance",
    "prepare_cell_mesh_collision_surface",
    "selection_collision_operator",
    "simplex_inversion_step_limit",
    "static_collision_operator",
]
