#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""MACE symmetric contraction with preserved W and a fixed U-to-polynomial map.

For output block ``L`` and correlation order ``nu`` the source contraction is

    B[c, M] = sum_k W_nu[species, k, c] sum_{i_1..i_nu} U_nu[M, i_1..i_nu, k]
              x[c, i_1] ... x[c, i_nu].

Only the symmetric part of ``U_nu`` contributes, so each basis is stored as its
exact projection ``P_nu[t, M, k]`` onto canonical commutative monomials ``t``.
That fixed projection is a nontrainable sparse route map; the original ``W_nu``
remain the trainable parameters. Monomials are formed once by a shared
prefix-sharing product graph, never as dense ``dim**nu`` runtime arrays.

Native bases are generated by sparse iterated real coupling of input blocks;
imported bases are the provider's exact ``U`` tensors, transformed to the native
component basis by explicit orthogonal block maps. Merged coefficients
``C = P W`` are a frozen realization bound to the numeric revision of ``W``; they
are fixed data and never become independent trainable parameters.
"""

from __future__ import annotations

import functools
import itertools
import math
from collections import defaultdict
from collections.abc import Callable, Sequence
from typing import final, Literal, NamedTuple, TypeAlias

import equinox as eqx
import jax
import jax.numpy as jnp
import jax.random as jr
import numpy as np
from jax import Array
from jax.typing import ArrayLike, DTypeLike

import phydrax.ein as ein

from ..._fingerprint import array_tree_fingerprint, canonical_fingerprint
from ..._identity import NumericRevision, SemanticProvenance
from ..._model import register_artifact_value
from ..._polynomial import ProductGraphPlan, project_tuple_coefficients
from ..._strict import StrictModule
from ..._trainable import NonTrainableState, ParameterOwner
from ..._validation import canonical_identifier, positive_finite_float, positive_integer
from ...linalg import ArraySpace, DenseLinearOperator, FailurePolicy, RankPolicy
from ...linalg.svd import (
    DenseSVD,
    require_exact_svd_rank,
    svd,
    SVDProblem,
    SVDSolvePolicy,
    SVDSolveStatus,
)
from ...sparse import EdgeRelation, linear_apply
from ...typing import (
    as_array,
    as_host_array,
    Dim,
    Float,
    HostFloat64,
    Inexact,
    Integer,
    parse,
    PRNGKey,
    Scope,
)
from ..operator.representations._irreps import (
    o3_irrep_action,
    o3_real_coupling,
    O3IrrepBlock,
    O3IrrepLayout,
)
from ._fixed_binding import require_identical, require_realized


SymmetricBasisOrigin: TypeAlias = Literal["native-coupling", "imported-source"]

# Relative singular-value cutoff separating exactly dependent coupling families
# (rounding-level singular values) from independent ones (order-one values).
_COUPLING_RANK_RELATIVE_CUTOFF = 1.0e-10
_DEFAULT_MAXIMUM_TERMS = 1 << 16
_DEFAULT_MAXIMUM_NODES = 1 << 16
_DEFAULT_EQUIVARIANCE_TOLERANCE = 1.0e-9
# Fixed improper test transformation for basis equivariance evidence.
_EVIDENCE_ANGLES = (0.3141592653589793, 1.2345678901234567, -0.7071067811865476)
# Native-origin evidence: a restored native basis must be orthonormal and span
# the regenerated coupling span to the rank cutoff. The span is gauge-free; the
# individual singular vectors of degenerate couplings are not, so they are not
# regenerated and compared.
_NATIVE_SPAN_TOLERANCE = 1.0e-10
# Owner dense-entry budget of native basis generation and restored-basis
# replay. Generation charges its exact projection and intermediate coupling
# families before allocating them; replay charges ``terms * components * paths``
# stored routes before re-projecting them densely, instead of trusting recorded
# sizes.
_MAXIMUM_REPLAY_ENTRIES = 1 << 24


class SymmetricStateDim(Dim):
    """Packed per-channel input irrep components."""


class SymmetricTermDim(Dim):
    """Canonical monomials of one fixed basis projection."""


class SymmetricComponentDim(Dim):
    """Components ``2L + 1`` of one output irrep block."""


class SymmetricPathDim(Dim):
    """Independent coupling paths of one basis."""


class SymmetricRouteDim(Dim):
    """Nonzero routes of one fixed term-to-(component, path) projection."""


class SymmetricChannelDim(Dim):
    """Feature channels contracted independently."""


class SymmetricNodeDim(Dim):
    """Nodes (atoms) evaluated by one contraction."""


type _NodeKernel = Callable[[Array, Array], Array]


class StaleSymmetricContractionBinding(ValueError):
    """A merged contraction was bound to different source weights."""


def _rotation(angles: tuple[float, float, float], /) -> np.ndarray:
    alpha, beta, gamma = angles

    def axis_rotation(angle: float, first: int, second: int) -> np.ndarray:
        matrix = np.eye(3, dtype=np.float64)
        cosine, sine = math.cos(angle), math.sin(angle)
        matrix[first, first] = cosine
        matrix[second, second] = cosine
        matrix[first, second] = -sine
        matrix[second, first] = sine
        return matrix

    return (
        axis_rotation(alpha, 0, 1)
        @ axis_rotation(beta, 1, 2)
        @ axis_rotation(gamma, 0, 1)
    )


def _validate_channel_layout(layout: O3IrrepLayout, name: str, /) -> None:
    if not isinstance(layout, O3IrrepLayout):
        raise TypeError(f"{name} must be an O3IrrepLayout.")
    if any(block.multiplicity != 1 for block in layout.blocks):
        raise ValueError(
            f"{name} is a per-channel layout: every block must have multiplicity one; "
            "channels are a separate axis."
        )


def _readmitted_layout(layout: O3IrrepLayout, name: str, /) -> O3IrrepLayout:
    """Re-admit a restored layout through its constructors and identity."""
    if not isinstance(layout, O3IrrepLayout):
        raise TypeError(f"{name} must be an O3IrrepLayout.")
    readmitted = O3IrrepLayout(
        tuple(
            O3IrrepBlock(
                block.name, block.degree, block.parity, multiplicity=block.multiplicity
            )
            for block in layout.blocks
        )
    )
    require_identical(layout, readmitted, name, ValueError)
    _validate_channel_layout(readmitted, name)
    return readmitted


def _independent_families(families: np.ndarray, expected: int, /) -> np.ndarray:
    """Return an orthonormal basis of the span of equivariant coupling families.

    ``families`` has shape ``(n, 2l+1, terms)``; each row is one intertwiner. The
    numerical rank is decided by the native SVD rank evidence and must equal the
    ``expected`` symmetric-power multiplicity; the basis rows are the retained
    right singular vectors with a deterministic sign convention.
    """
    # Couplings that vanish identically (for example antisymmetric couplings of
    # one block with itself) are exact zeros, not numerical rank decisions.
    nonzero = families[np.any(families != 0.0, axis=(1, 2))]
    count = nonzero.shape[0]
    if expected == 0:
        # Independent families are order one (orthonormal predecessors times
        # component-normalized couplings); a mathematically empty irrep leaves
        # only rounding residue, which a relative cutoff alone would promote
        # to a spurious path.
        if count and float(np.max(np.abs(nonzero))) > _COUPLING_RANK_RELATIVE_CUTOFF:
            raise ValueError(
                "Native coupling families span an irrep absent from the symmetric power."
            )
        return nonzero[:0]
    if count == 0:
        raise ValueError(
            f"Native coupling families have rank 0; the symmetric power has {expected}."
        )
    width = families.shape[1] * families.shape[2]
    matrix = nonzero.reshape((count, width))
    operator = DenseLinearOperator(
        jnp.asarray(matrix),
        source=ArraySpace((width,), dtype=jnp.float64),
        target=ArraySpace((count,), dtype=jnp.float64),
    )
    policy = SVDSolvePolicy(
        DenseSVD(),
        count=min(count, width),
        rank=RankPolicy(relative_cutoff=_COUPLING_RANK_RELATIVE_CUTOFF),
        failure=FailurePolicy("status"),
    )
    result = svd(SVDProblem(operator), policy=policy)
    status = int(np.asarray(result.primal_status))
    if status not in (SVDSolveStatus.SUCCESS, SVDSolveStatus.RANK_DEFICIENT):
        raise ValueError(f"Coupling-basis SVD failed with status {status}.")
    # Host preparation boundary: the certified deterministic global rank.
    lower = int(np.asarray(require_exact_svd_rank(result)))
    if lower != expected:
        raise ValueError(
            f"Native coupling families have rank {lower}; the symmetric power has "
            f"{expected}."
        )
    rows = np.asarray(result.right_coordinates, dtype=np.float64)[:, :lower].T
    pivots = np.argmax(np.abs(rows), axis=1)
    signs = np.sign(rows[np.arange(lower), pivots])
    return (rows * signs[:, None]).reshape((lower, families.shape[1], families.shape[2]))


def _symmetric_power_multiplicities(
    blocks: tuple[tuple[int, int, int], ...], correlation: int, /
) -> tuple[dict[tuple[int, int], int], ...]:
    """Multiplicities of O(3) irreps ``(l, p)`` in ``Sym^d V`` for ``d = 0..nu``.

    Character oracle independent of the coupling generation: under a rotation
    by ``theta`` about one axis, component ``m`` of a block of parity ``p``
    has weight ``q**m``, and the inversion composed with that rotation adds the
    sign ``p``. The graded characters of the symmetric algebra are then
    ``prod_v (1 - t s_v q**m_v)**-1`` with ``s_v = 1`` (rotation) or
    ``s_v = p_v`` (inverted rotation). In the inversion eigenspace ``P`` the
    weight multiplicities are ``(n_rot + P n_inv) / 2``, and the SO(3)
    multiplicity of degree ``l`` is the weight multiplicity at ``l`` minus
    that at ``l + 1``. Arithmetic is exact over integers.
    """
    span = correlation * max(degree for degree, _, _ in blocks)
    width = 2 * span + 1
    sectors: list[list[list[int]]] = []
    for inverted in (False, True):
        weights: defaultdict[tuple[int, int], int] = defaultdict(int)
        for degree, parity, _ in blocks:
            for m in range(-degree, degree + 1):
                weights[(m, parity if inverted else 1)] += 1
        series = [[0] * width for _ in range(correlation + 1)]
        series[0][span] = 1
        for (m, sign), count in sorted(weights.items()):
            # Multiply by (1 - t s q**m)**-count = sum_j C(count+j-1, j) (t s q**m)**j.
            previous = series
            series = [[0] * width for _ in range(correlation + 1)]
            for degree in range(correlation + 1):
                for power in range(degree + 1):
                    factor = math.comb(count + power - 1, power) * sign**power
                    shift = power * m
                    for index, value in enumerate(previous[degree - power]):
                        if value:
                            series[degree][index + shift] += factor * value
        sectors.append(series)
    rotation, inversion = sectors

    def lowest(series: list[int], degree: int, /) -> int:
        above = series[span + degree + 1] if degree < span else 0
        return series[span + degree] - above

    return tuple(
        {
            (degree, parity): (
                lowest(rotation[order], degree)
                + parity * lowest(inversion[order], degree)
            )
            // 2
            for degree in range(span + 1)
            for parity in (1, -1)
        }
        for order in range(correlation + 1)
    )


class _NativeCouplingResources(NamedTuple):
    """Exact sizes of one native generation, resolved before any allocation."""

    paths: int
    projection_entries: int
    # ``(stage, dense entries)`` of the multiplication tables and of the live
    # coupling families (or largest gathered contraction) of each degree.
    intermediate_entries: tuple[tuple[str, int], ...]


def _native_coupling_resources(
    blocks: tuple[tuple[int, int, int], ...],
    size: int,
    output_degree: int,
    output_parity: int,
    correlation: int,
    /,
) -> _NativeCouplingResources:
    """Replay the `_native_coupling_span` schedule on sizes only.

    Group ranks after each SVD are the exact symmetric-power multiplicities of
    `_symmetric_power_multiplicities`: iterated coupling of a complete degree-d
    intertwiner basis with every input block spans every degree-(d+1)
    intertwiner (Euler's identity), and the reachability filter only drops
    degrees that cannot couple to the output. Generation certifies every SVD
    rank against the same multiplicities, so these sizes are exact.
    """
    multiplicities = _symmetric_power_multiplicities(blocks, correlation)
    largest = max(degree for degree, _, _ in blocks)

    def reachable(degree: int, value: int, /) -> bool:
        return abs(value - output_degree) <= (correlation - degree) * largest

    term_counts = [
        math.comb(size + degree - 1, degree) for degree in range(correlation + 1)
    ]
    stages = [
        (
            "monomial multiplication tables",
            sum(term_counts[degree] * size for degree in range(1, correlation)),
        )
    ]
    rows: defaultdict[tuple[int, int], int] = defaultdict(int)
    for degree, parity, _ in blocks:
        if reachable(1, degree):
            rows[(degree, parity)] += 1
    stages.append(
        (
            "degree-1 coupling families",
            sum(count * (2 * degree + 1) * size for (degree, _), count in rows.items()),
        )
    )
    ranks = {key: multiplicities[1][key] for key in rows}
    for degree in range(1, correlation):
        following: defaultdict[tuple[int, int], int] = defaultdict(int)
        gathered = 0
        for (left, left_parity), rank in ranks.items():
            for right, right_parity, _ in blocks:
                for coupled in range(abs(left - right), left + right + 1):
                    if not reachable(degree + 1, coupled):
                        continue
                    gathered = max(
                        gathered,
                        rank * (2 * coupled + 1) * term_counts[degree] * (2 * right + 1),
                    )
                    following[(coupled, left_parity * right_parity)] += rank
        families = sum(
            count * (2 * coupled + 1) * term_counts[degree + 1]
            for (coupled, _), count in following.items()
        )
        stages.append((f"degree-{degree + 1} coupling families", max(families, gathered)))
        ranks = {key: multiplicities[degree + 1].get(key, 0) for key in following}
    paths = ranks.get((output_degree, output_parity), 0)
    return _NativeCouplingResources(
        paths=paths,
        projection_entries=term_counts[correlation] * (2 * output_degree + 1) * paths,
        intermediate_entries=tuple(stages),
    )


def _native_coupling_basis(
    layout: O3IrrepLayout,
    output: O3IrrepBlock,
    correlation: int,
    maximum_terms: int,
    /,
) -> tuple[tuple[tuple[int, ...], ...], np.ndarray]:
    """Generate ``P[t, M, k]`` by sparse iterated coupling over monomial indices.

    The projection is a pure function of the block signature and is generated
    once per process; the returned array is read-only. Its exact path count and
    every dense intermediate are charged against the owner budget before the
    generation allocates anything.
    """
    size = layout.packed_size
    term_count = math.comb(size + correlation - 1, correlation)
    if term_count > maximum_terms:
        raise ValueError(
            f"Correlation-{correlation} basis needs {term_count} monomials, "
            f"exceeding maximum_terms={maximum_terms}."
        )
    blocks_: list[tuple[int, int, int]] = []
    offset = 0
    for block in layout.blocks:
        blocks_.append((block.degree, block.parity, offset))
        offset += block.size
    blocks = tuple(blocks_)
    resources = _native_coupling_resources(
        blocks, size, output.degree, output.parity, correlation
    )
    if resources.paths == 0:
        raise ValueError(
            f"No equivariant correlation-{correlation} coupling maps the input layout "
            f"to block {output.name!r}."
        )
    if resources.projection_entries > _MAXIMUM_REPLAY_ENTRIES:
        raise ValueError(
            f"Correlation-{correlation} native basis for block {output.name!r} needs "
            f"{resources.projection_entries} projection entries ({term_count} terms x "
            f"{2 * output.degree + 1} components x {resources.paths} paths), "
            f"exceeding the dense-entry budget {_MAXIMUM_REPLAY_ENTRIES}."
        )
    for stage, entries in resources.intermediate_entries:
        if entries > _MAXIMUM_REPLAY_ENTRIES:
            raise ValueError(
                f"Correlation-{correlation} native basis for block {output.name!r} "
                f"needs {entries} dense entries for its {stage}, exceeding the "
                f"dense-entry budget {_MAXIMUM_REPLAY_ENTRIES}."
            )
    terms, projection = _native_coupling_span(
        blocks, size, output.degree, output.parity, correlation
    )
    if projection is None:
        raise ValueError(
            f"Native correlation-{correlation} coupling for block {output.name!r} "
            f"disagrees with the symmetric-power dimension {resources.paths}."
        )
    return terms, projection


@functools.lru_cache(maxsize=64)
def _native_coupling_span(
    blocks: tuple[tuple[int, int, int], ...],
    size: int,
    output_degree: int,
    output_parity: int,
    correlation: int,
    /,
) -> tuple[tuple[tuple[int, ...], ...], np.ndarray | None]:
    largest = max(degree for degree, _, _ in blocks)
    multiplicities = _symmetric_power_multiplicities(blocks, correlation)
    terms = [
        tuple(itertools.combinations_with_replacement(range(size), degree))
        for degree in range(correlation + 1)
    ]
    positions = [
        {term: position for position, term in enumerate(level)} for level in terms
    ]
    multiplication = [
        np.asarray(
            [
                [
                    positions[degree + 1][tuple(sorted((*term, variable)))]
                    for variable in range(size)
                ]
                for term in terms[degree]
            ],
            dtype=np.int64,
        ).reshape((len(terms[degree]), size))
        for degree in range(1, correlation)
    ]

    def reachable(degree: int, value: int, /) -> bool:
        return abs(value - output_degree) <= (correlation - degree) * largest

    groups: dict[tuple[int, int], np.ndarray]
    first: defaultdict[tuple[int, int], list[np.ndarray]] = defaultdict(list)
    for degree, parity, offset in blocks:
        if not reachable(1, degree):
            continue
        family = np.zeros((1, 2 * degree + 1, size), dtype=np.float64)
        family[0, np.arange(2 * degree + 1), offset + np.arange(2 * degree + 1)] = 1.0
        first[(degree, parity)].append(family)
    groups = {
        key: _independent_families(np.concatenate(values, axis=0), multiplicities[1][key])
        for key, values in sorted(first.items())
    }
    for degree in range(1, correlation):
        following: defaultdict[tuple[int, int], list[np.ndarray]] = defaultdict(list)
        targets_by_block = multiplication[degree - 1]
        for (left, left_parity), families in groups.items():
            for right, right_parity, offset in blocks:
                targets = targets_by_block[:, offset : offset + 2 * right + 1]
                for coupled in range(abs(left - right), left + right + 1):
                    if not reachable(degree + 1, coupled):
                        continue
                    coefficients = o3_real_coupling(left, right, coupled).dense()
                    gathered = ein.contract("oij,nit->notj", coefficients, families)
                    product = np.zeros(
                        (families.shape[0], 2 * coupled + 1, len(terms[degree + 1])),
                        dtype=np.float64,
                    )
                    # Accumulate over (term, variable) targets with the term
                    # axis leading: distinct pairs can reach one monomial.
                    np.add.at(
                        np.moveaxis(product, 2, 0),
                        targets,
                        np.moveaxis(gathered, (2, 3), (0, 1)),
                    )
                    following[(coupled, left_parity * right_parity)].append(product)
        groups = {
            key: _independent_families(
                np.concatenate(values, axis=0), multiplicities[degree + 1].get(key, 0)
            )
            for key, values in sorted(following.items())
        }
    final_families = groups.get((output_degree, output_parity))
    if final_families is None or final_families.shape[0] == 0:
        return terms[correlation], None
    projection = np.ascontiguousarray(np.transpose(final_families, (2, 1, 0)))
    projection.setflags(write=False)
    return terms[correlation], projection


def _transform_source_tensor(
    tensor: np.ndarray,
    input_transform: np.ndarray,
    output_transform: np.ndarray,
    correlation: int,
    /,
) -> np.ndarray:
    """Return ``U'`` with inputs leading: ``(D,)*nu + (2L+1, K)`` in the native basis.

    ``x_native = T_in x_source`` and ``y_native = T_out y_source`` with orthogonal
    maps, so every input axis contracts with ``T_in`` (``x_source = T_in^T
    x_native``) and the output axis with ``T_out``.
    """
    letters = "abcdefghijklmnopqrstuvwxyz"
    if correlation + 4 > len(letters):
        raise ValueError("Correlation order exceeds the transform contraction alphabet.")
    value = ein.contract("om,m...->o...", output_transform, tensor)
    for axis in range(correlation):
        source = letters[: correlation + 2]
        target = source[: axis + 1] + "Z" + source[axis + 2 :]
        value = ein.contract(
            f"Z{source[axis + 1]},{source}->{target}", input_transform, value
        )
    return np.moveaxis(value, 0, correlation)


def _block_diagonal(layout: O3IrrepLayout, /) -> np.ndarray:
    allowed = np.zeros((layout.packed_size, layout.packed_size), dtype=np.bool_)
    for block in layout.blocks:
        start = layout.offset(block.name)
        stop = start + block.size
        allowed[start:stop, start:stop] = True
    return allowed


def _orthogonal_transform(
    value: ArrayLike, size: int, name: str, /, *, allowed: np.ndarray | None = None
) -> np.ndarray:
    matrix = as_host_array(value, HostFloat64[SymmetricStateDim, SymmetricStateDim], name)
    if matrix.shape != (size, size):
        raise ValueError(f"{name} must have shape {(size, size)}.")
    if not np.all(np.isfinite(matrix)):
        raise ValueError(f"{name} must be finite.")
    if not np.allclose(matrix @ matrix.T, np.eye(size), rtol=0.0, atol=1.0e-12):
        raise ValueError(f"{name} must be orthogonal.")
    if allowed is not None and np.any(matrix[~allowed] != 0.0):
        raise ValueError(f"{name} must not mix distinct irrep blocks.")
    return matrix


@final
class SymmetricContractionBasis(StrictModule, NonTrainableState):
    """Fixed projection ``P[t, M, k]`` of one generalized coupling basis.

    ``relation`` routes canonical degree-``correlation`` monomials ``terms`` to
    flattened ``(component, path)`` targets with fixed ``coefficients``. The
    basis records its origin, explicit source identity, the equivariance gate it
    was admitted under and the residual measured at preparation under a fixed
    improper transformation. `validate` re-admits a restored basis.
    """

    __strict_contract__ = True

    relation: EdgeRelation
    coefficients: Float[SymmetricRouteDim]
    terms: tuple[tuple[int, ...], ...] = eqx.field(static=True)
    correlation: int = eqx.field(static=True)
    input_size: int = eqx.field(static=True)
    output_degree: int = eqx.field(static=True)
    output_parity: int = eqx.field(static=True)
    path_count: int = eqx.field(static=True)
    origin: SymmetricBasisOrigin = eqx.field(static=True)
    source_id: str = eqx.field(static=True)
    input_layout_id: str = eqx.field(static=True)
    equivariance_tolerance: float = eqx.field(static=True)
    equivariance_residual: float = eqx.field(static=True)
    basis_id: str = eqx.field(static=True)

    def __init__(
        self,
        terms: Sequence[Sequence[int]],
        projection: ArrayLike,
        input_layout: O3IrrepLayout,
        output_block: O3IrrepBlock,
        correlation: int,
        /,
        *,
        origin: SymmetricBasisOrigin,
        source_id: str,
        equivariance_tolerance: float = _DEFAULT_EQUIVARIANCE_TOLERANCE,
    ) -> None:
        _validate_channel_layout(input_layout, "input_layout")
        if not isinstance(output_block, O3IrrepBlock):
            raise TypeError("output_block must be an O3IrrepBlock.")
        if output_block.multiplicity != 1:
            raise ValueError("output_block must have multiplicity one.")
        order = positive_integer(correlation, "correlation")
        tolerance = positive_finite_float(
            equivariance_tolerance, "equivariance_tolerance"
        )
        identifier = canonical_identifier(source_id, "source_id")
        origin_ = parse(origin, SymmetricBasisOrigin, "origin")
        canonical = tuple(tuple(sorted(int(index) for index in term)) for term in terms)
        size = input_layout.packed_size
        if any(
            len(term) != order or any(index < 0 or index >= size for index in term)
            for term in canonical
        ):
            raise ValueError(
                f"Every term must be a degree-{order} monomial over {size} components."
            )
        if len(set(canonical)) != len(canonical) or list(canonical) != sorted(canonical):
            raise ValueError(
                "terms must be distinct and in canonical lexicographic order."
            )
        components = 2 * output_block.degree + 1
        values = as_host_array(
            projection,
            HostFloat64[SymmetricTermDim, SymmetricComponentDim, SymmetricPathDim],
            "projection",
        )
        if values.ndim != 3 or values.shape[:2] != (len(canonical), components):
            raise ValueError(
                f"projection must have shape (terms, {components}, paths); got {values.shape}."
            )
        if values.shape[2] == 0 or not np.all(np.isfinite(values)):
            raise ValueError("projection must be finite with at least one path.")
        # The routes store nonzero entries only, so the content identity uses
        # the same zero: signed zeros are canonicalized to +0.0.
        values = np.where(values == 0.0, 0.0, values)
        residual = _equivariance_residual(canonical, values, input_layout, output_block)
        if not residual <= tolerance:
            raise ValueError(
                f"Symmetric basis is not equivariant in the declared native basis "
                f"(residual {residual:.3e} > {tolerance:.3e}); check the source "
                "basis transform."
            )
        term_index, component, path = np.nonzero(values)
        paths = values.shape[2]
        self.relation = EdgeRelation(
            term_index.astype(np.int32),
            (component * paths + path).astype(np.int32),
            source_size=len(canonical),
            target_size=components * paths,
        )
        self.coefficients = jnp.asarray(values[term_index, component, path])
        self.terms = canonical
        self.correlation = order
        self.input_size = size
        self.output_degree = output_block.degree
        self.output_parity = output_block.parity
        self.path_count = paths
        self.origin = origin_
        self.source_id = identifier
        self.input_layout_id = input_layout.layout_id
        self.equivariance_tolerance = tolerance
        self.equivariance_residual = residual
        self.basis_id = canonical_fingerprint(
            {
                "kind": "symmetric-contraction-basis",
                "origin": origin_,
                "source_id": identifier,
                "input_layout": input_layout.layout_id,
                "output_degree": output_block.degree,
                "output_parity": output_block.parity,
                "correlation": order,
                "terms": [list(term) for term in canonical],
                "projection": array_tree_fingerprint(values),
                "equivariance_tolerance": tolerance,
            }
        )

    @classmethod
    def native(
        cls,
        input_layout: O3IrrepLayout,
        output_block: O3IrrepBlock,
        correlation: int,
        /,
        *,
        maximum_terms: int = _DEFAULT_MAXIMUM_TERMS,
    ) -> SymmetricContractionBasis:
        """Generate an orthonormal native basis by sparse iterated real coupling."""
        _validate_channel_layout(input_layout, "input_layout")
        order = positive_integer(correlation, "correlation")
        maximum = positive_integer(maximum_terms, "maximum_terms")
        terms, projection = _native_coupling_basis(
            input_layout, output_block, order, maximum
        )
        return cls(
            terms,
            projection,
            input_layout,
            output_block,
            order,
            origin="native-coupling",
            source_id="native-real-coupling",
        )

    @classmethod
    def from_source_tensor(
        cls,
        tensor: ArrayLike,
        input_layout: O3IrrepLayout,
        output_block: O3IrrepBlock,
        correlation: int,
        /,
        *,
        source_id: str,
        input_transform: ArrayLike,
        output_transform: ArrayLike,
        maximum_entries: int,
        equivariance_tolerance: float = _DEFAULT_EQUIVARIANCE_TOLERANCE,
    ) -> SymmetricContractionBasis:
        """Bind a provider ``U`` of shape ``(2L+1, D, ..., D, K)`` exactly.

        The tensor size is charged against ``maximum_entries`` before any host
        conversion. ``input_transform`` maps source to native packed components
        (block diagonal, orthogonal); ``output_transform`` maps source to native
        output components.
        """
        _validate_channel_layout(input_layout, "input_layout")
        order = positive_integer(correlation, "correlation")
        maximum = positive_integer(maximum_entries, "maximum_entries")
        size = input_layout.packed_size
        components = 2 * output_block.degree + 1
        shape = tuple(np.shape(tensor))
        if len(shape) != order + 2 or shape[:-1] != (components, *(size,) * order):
            raise ValueError(
                f"Source U must have shape ({components}, {size} x{order}, paths); "
                f"got {shape}."
            )
        entries = math.prod(shape)
        if entries > maximum:
            raise ValueError(
                f"Source U has {entries} entries, exceeding maximum_entries={maximum}."
            )
        original = np.asarray(tensor)
        if not (
            np.issubdtype(original.dtype, np.floating)
            or np.issubdtype(original.dtype, np.integer)
        ):
            raise TypeError(
                f"Source U must have a real numeric dtype; got {original.dtype}."
            )
        source = original.astype(np.float64, copy=False)
        if not np.all(np.isfinite(source)):
            raise ValueError("Source U must be finite.")
        inputs = _orthogonal_transform(
            input_transform,
            size,
            "input_transform",
            allowed=_block_diagonal(input_layout),
        )
        outputs = _orthogonal_transform(output_transform, components, "output_transform")
        native = _transform_source_tensor(source, inputs, outputs, order)
        terms, projection = project_tuple_coefficients(
            native, size, order, maximum_entries=maximum
        )
        return cls(
            terms,
            projection,
            input_layout,
            output_block,
            order,
            origin="imported-source",
            source_id=source_id,
            equivariance_tolerance=equivariance_tolerance,
        )

    @property
    def component_count(self) -> int:
        return 2 * self.output_degree + 1

    def dense_projection(self) -> Array:
        """Materialize the fixed ``(terms, components, paths)`` projection."""
        flat = jnp.zeros(
            (len(self.terms), self.relation.target_size), self.coefficients.dtype
        )
        flat = flat.at[self.relation.source_indices, self.relation.target_indices].add(
            self.coefficients
        )
        return flat.reshape((len(self.terms), self.component_count, self.path_count))

    def path_features(self, monomials: Array, /) -> Array:
        """Map ``(terms, *lanes)`` monomials to ``(components, paths, *lanes)``."""
        routed = linear_apply(
            self.relation, self.coefficients.astype(monomials.dtype), monomials
        )
        return routed.reshape(
            (self.component_count, self.path_count, *monomials.shape[1:])
        )

    def validate(
        self, input_layout: O3IrrepLayout, output_block: O3IrrepBlock, /
    ) -> None:
        """Re-admit this (possibly restored) basis for one declared layout and block.

        This is a host boundary over concrete arrays. The stored routes and
        coefficients are re-projected densely and passed through the
        constructor again: finiteness, the recorded equivariance gate, the
        canonical route layout and the content-derived ``basis_id`` are
        recomputed, never trusted. A native basis must additionally be an
        orthonormal basis of the regenerated native coupling span; an imported
        basis is authoritative source data and is not regenerated.
        """
        _validate_channel_layout(input_layout, "input_layout")
        if not isinstance(output_block, O3IrrepBlock):
            raise TypeError("output_block must be an O3IrrepBlock.")
        if (
            self.input_layout_id != input_layout.layout_id
            or self.input_size != input_layout.packed_size
            or (self.output_degree, self.output_parity)
            != (output_block.degree, output_block.parity)
        ):
            raise ValueError("Symmetric basis does not match its declared layouts.")
        projection = self._host_projection()
        expected = SymmetricContractionBasis(
            self.terms,
            projection,
            input_layout,
            output_block,
            self.correlation,
            origin=self.origin,
            source_id=self.source_id,
            equivariance_tolerance=self.equivariance_tolerance,
        )
        require_identical(
            (self.relation, self.coefficients),
            (expected.relation, expected.coefficients),
            "Symmetric basis routes",
            ValueError,
        )
        if (
            self.terms,
            self.correlation,
            self.path_count,
            self.equivariance_tolerance,
            self.basis_id,
        ) != (
            expected.terms,
            expected.correlation,
            expected.path_count,
            expected.equivariance_tolerance,
            expected.basis_id,
        ):
            raise ValueError("Symmetric basis does not match its recorded identity.")
        recorded = self.equivariance_residual
        if not (
            isinstance(recorded, float) and 0.0 <= recorded <= self.equivariance_tolerance
        ):
            raise ValueError("Symmetric basis equivariance evidence is invalid.")
        if expected.origin == "native-coupling":
            _require_native_span(
                projection,
                expected.terms,
                input_layout,
                output_block,
                expected.correlation,
            )

    def _host_projection(self) -> np.ndarray:
        """Dense float64 projection of the stored routes, after bounds checks."""
        coefficients = np.asarray(jax.device_get(self.coefficients))
        sources = np.asarray(jax.device_get(self.relation.source_indices))
        targets = np.asarray(jax.device_get(self.relation.target_indices))
        term_count = len(self.terms)
        components = self.component_count
        paths = self.path_count
        if (
            not np.issubdtype(coefficients.dtype, np.floating)
            or coefficients.ndim != 1
            or sources.shape != coefficients.shape
            or targets.shape != coefficients.shape
            or not np.issubdtype(sources.dtype, np.integer)
            or not np.issubdtype(targets.dtype, np.integer)
            or type(paths) is not int
            or paths <= 0
            or self.relation.source_size != term_count
            or self.relation.target_size != components * paths
        ):
            raise ValueError("Symmetric basis routes do not match its declared shape.")
        if term_count * components * paths > _MAXIMUM_REPLAY_ENTRIES:
            raise ValueError(
                f"Symmetric basis replay needs {term_count * components * paths} "
                f"projection entries, exceeding {_MAXIMUM_REPLAY_ENTRIES}."
            )
        if not np.all(np.isfinite(coefficients)):
            raise ValueError("Symmetric basis coefficients must be finite.")
        if np.any((sources < 0) | (sources >= term_count)) or np.any(
            (targets < 0) | (targets >= self.relation.target_size)
        ):
            raise ValueError("Symmetric basis routes leave the declared projection.")
        flat = np.zeros((term_count, self.relation.target_size), dtype=np.float64)
        np.add.at(flat, (sources, targets), coefficients.astype(np.float64))
        return flat.reshape((term_count, components, paths))


def _require_native_span(
    projection: np.ndarray,
    terms: tuple[tuple[int, ...], ...],
    layout: O3IrrepLayout,
    output: O3IrrepBlock,
    correlation: int,
    /,
) -> None:
    """Refuse a native basis that is not an orthonormal native coupling span."""
    native_terms, native = _native_coupling_basis(
        layout, output, correlation, max(len(terms), 1)
    )
    if tuple(native_terms) != terms or native.shape != projection.shape:
        raise ValueError(
            "Native symmetric basis does not match the native coupling terms."
        )
    paths = projection.shape[2]
    stored = np.transpose(projection, (2, 1, 0)).reshape((paths, -1))
    reference = np.transpose(native, (2, 1, 0)).reshape((paths, -1))
    orthonormality = float(np.max(np.abs(stored @ stored.T - np.eye(paths))))
    outside = float(np.max(np.abs(stored - (stored @ reference.T) @ reference)))
    if not (
        orthonormality <= _NATIVE_SPAN_TOLERANCE and outside <= _NATIVE_SPAN_TOLERANCE
    ):
        raise ValueError(
            "Native symmetric basis is not an orthonormal basis of the native "
            "coupling span."
        )


def _equivariance_residual(
    terms: tuple[tuple[int, ...], ...],
    projection: np.ndarray,
    layout: O3IrrepLayout,
    output: O3IrrepBlock,
    /,
) -> float:
    """Relative residual of ``P(D x) - D_out P(x)`` at fixed host sample points."""
    orthogonal = -_rotation(_EVIDENCE_ANGLES)
    action_in = np.asarray(layout.representation_matrix(orthogonal), dtype=np.float64)
    action_out = np.asarray(
        o3_irrep_action(orthogonal, output.degree, output.parity), dtype=np.float64
    )
    samples = np.random.default_rng(20261003).normal(size=(4, layout.packed_size))
    indices = np.asarray(terms, dtype=np.int64).reshape((len(terms), -1))

    def evaluate(points: np.ndarray, /) -> np.ndarray:
        monomials = np.prod(points[:, indices], axis=-1)
        return ein.contract("st,tmk->smk", monomials, projection)

    rotated = evaluate(samples @ action_in.T)
    expected = ein.contract("om,smk->sok", action_out, evaluate(samples))
    scale = max(float(np.max(np.abs(expected))), 1.0)
    return float(np.max(np.abs(rotated - expected)) / scale)


@final
class SymmetricContractionPlan(StrictModule, NonTrainableState):
    """Static symmetric-contraction architecture with one shared product graph."""

    input_layout: O3IrrepLayout
    output_layout: O3IrrepLayout
    bases: tuple[tuple[SymmetricContractionBasis, ...], ...]
    product_graph: ProductGraphPlan
    term_maps: tuple[tuple[Array, ...], ...]
    correlation: int = eqx.field(static=True)
    species_count: int = eqx.field(static=True)
    channel_count: int = eqx.field(static=True)
    plan_id: str = eqx.field(static=True)

    def __init__(
        self,
        input_layout: O3IrrepLayout,
        output_layout: O3IrrepLayout,
        bases: Sequence[Sequence[SymmetricContractionBasis]],
        /,
        *,
        species_count: int,
        channel_count: int,
        maximum_nodes: int = _DEFAULT_MAXIMUM_NODES,
    ) -> None:
        _validate_channel_layout(input_layout, "input_layout")
        _validate_channel_layout(output_layout, "output_layout")
        species = positive_integer(species_count, "species_count")
        channels = positive_integer(channel_count, "channel_count")
        nodes = positive_integer(maximum_nodes, "maximum_nodes")
        grouped = tuple(tuple(block) for block in bases)
        if len(grouped) != len(output_layout.blocks):
            raise ValueError("bases must provide one sequence per output block.")
        correlation = len(grouped[0]) if grouped else 0
        if correlation == 0:
            raise ValueError("Every output block needs bases for correlation 1..nu.")
        for block, block_bases in zip(output_layout.blocks, grouped):
            if len(block_bases) != correlation:
                raise ValueError("Every output block must share one correlation order.")
            for order, basis in enumerate(block_bases, start=1):
                if not isinstance(basis, SymmetricContractionBasis):
                    raise TypeError(
                        "bases must contain SymmetricContractionBasis values."
                    )
                if (
                    basis.correlation != order
                    or basis.input_layout_id != input_layout.layout_id
                    or (basis.output_degree, basis.output_parity)
                    != (block.degree, block.parity)
                ):
                    raise ValueError(
                        f"Basis for block {block.name!r}, correlation {order} does not "
                        "match the declared layouts."
                    )
        union = sorted(
            {
                term
                for block_bases in grouped
                for basis in block_bases
                for term in basis.terms
            },
            key=lambda term: (len(term), term),
        )
        graph = ProductGraphPlan(
            input_layout.packed_size,
            union,
            maximum_nodes=nodes,
            maximum_degree=correlation,
        )
        self.input_layout = input_layout
        self.output_layout = output_layout
        self.bases = grouped
        self.product_graph = graph
        self.term_maps = tuple(
            tuple(
                jnp.asarray(
                    np.asarray(
                        [graph.term_index(term) for term in basis.terms], dtype=np.int32
                    )
                )
                for basis in block_bases
            )
            for block_bases in grouped
        )
        self.correlation = correlation
        self.species_count = species
        self.channel_count = channels
        self.plan_id = canonical_fingerprint(
            {
                "kind": "symmetric-contraction-plan",
                "input_layout": input_layout.layout_id,
                "output_layout": output_layout.layout_id,
                "bases": [[basis.basis_id for basis in block] for block in grouped],
                "product_graph": graph.plan_id,
                "species_count": species,
                "channel_count": channels,
            }
        )

    @classmethod
    def native(
        cls,
        input_layout: O3IrrepLayout,
        output_layout: O3IrrepLayout,
        correlation: int,
        /,
        *,
        species_count: int,
        channel_count: int,
        maximum_terms: int = _DEFAULT_MAXIMUM_TERMS,
        maximum_nodes: int = _DEFAULT_MAXIMUM_NODES,
    ) -> SymmetricContractionPlan:
        """Prepare native coupling bases for every output block and order."""
        order = positive_integer(correlation, "correlation")
        _validate_channel_layout(output_layout, "output_layout")
        bases = tuple(
            tuple(
                SymmetricContractionBasis.native(
                    input_layout, block, nu, maximum_terms=maximum_terms
                )
                for nu in range(1, order + 1)
            )
            for block in output_layout.blocks
        )
        return cls(
            input_layout,
            output_layout,
            bases,
            species_count=species_count,
            channel_count=channel_count,
            maximum_nodes=maximum_nodes,
        )

    @property
    def path_counts(self) -> tuple[tuple[int, ...], ...]:
        return tuple(tuple(basis.path_count for basis in block) for block in self.bases)

    def weight_shapes(self) -> tuple[tuple[tuple[int, int, int], ...], ...]:
        """Shapes ``(species, paths, channels)`` of the original W per block/order."""
        return tuple(
            tuple(
                (self.species_count, basis.path_count, self.channel_count)
                for basis in block
            )
            for block in self.bases
        )

    def validate(self) -> None:
        """Re-admit this (possibly restored) plan from its layouts and bases.

        This is a host boundary over concrete arrays. Layouts and every basis
        are re-admitted by their owners; the product graph, term maps and
        ``plan_id`` are rebuilt from the validated bases and must match exactly.
        """
        input_layout = _readmitted_layout(self.input_layout, "input_layout")
        output_layout = _readmitted_layout(self.output_layout, "output_layout")
        if len(self.bases) != len(output_layout.blocks):
            raise ValueError("bases must provide one sequence per output block.")
        for block, block_bases in zip(output_layout.blocks, self.bases, strict=True):
            for basis in block_bases:
                if not isinstance(basis, SymmetricContractionBasis):
                    raise TypeError(
                        "bases must contain SymmetricContractionBasis values."
                    )
                basis.validate(input_layout, block)
        expected = SymmetricContractionPlan(
            input_layout,
            output_layout,
            self.bases,
            species_count=self.species_count,
            channel_count=self.channel_count,
            maximum_nodes=self.product_graph.node_count,
        )
        require_identical(self, expected, "Symmetric contraction plan", ValueError)

    def validate_inputs(
        self, features: ArrayLike, species: ArrayLike, /
    ) -> tuple[Array, Array]:
        scope = Scope()
        values = as_array(
            features,
            Inexact[SymmetricNodeDim, SymmetricChannelDim, SymmetricStateDim],
            "features",
            scope=scope,
        )
        indices = as_array(species, Integer[SymmetricNodeDim], "species", scope=scope)
        if values.shape[1:] != (self.channel_count, self.input_layout.packed_size):
            raise ValueError(
                "features must have shape (nodes, "
                f"{self.channel_count}, {self.input_layout.packed_size})."
            )
        return values, indices.astype(jnp.int32)


def _map_nodes(
    kernel: _NodeKernel, features: Array, species: Array, node_tile: int | None, /
) -> Array:
    if node_tile is None:
        return kernel(features, species)
    tile = positive_integer(node_tile, "node_tile")
    count = features.shape[0]
    tiles = -(-count // tile)
    padding = tiles * tile - count
    # Zero features and species zero are domain-safe for a polynomial contraction;
    # padded rows are removed before return.
    padded_features = jnp.pad(features, ((0, padding), (0, 0), (0, 0)))
    padded_species = jnp.pad(species, ((0, padding),))
    outputs = jax.lax.map(
        lambda pair: kernel(pair[0], pair[1]),
        (
            padded_features.reshape((tiles, tile, *features.shape[1:])),
            padded_species.reshape((tiles, tile)),
        ),
    )
    return outputs.reshape((tiles * tile, *outputs.shape[2:]))[:count]


@final
class SymmetricContraction(StrictModule, ParameterOwner):
    """Trainable symmetric contraction holding the original source weights W.

    ``weights[b][nu - 1]`` has shape ``(species, paths, channels)`` for output
    block ``b`` and correlation ``nu``. The plan (bases and product graph) is
    fixed data.
    """

    plan: SymmetricContractionPlan
    weights: tuple[tuple[Array, ...], ...]

    def __init__(
        self,
        plan: SymmetricContractionPlan,
        weights: Sequence[Sequence[ArrayLike]],
        /,
    ) -> None:
        if not isinstance(plan, SymmetricContractionPlan):
            raise TypeError("plan must be a SymmetricContractionPlan.")
        arrays = tuple(
            tuple(jnp.asarray(weight) for weight in block) for block in weights
        )
        expected = plan.weight_shapes()
        if tuple(tuple(weight.shape for weight in block) for block in arrays) != expected:
            raise ValueError(f"weights must have shapes {expected}.")
        dtypes = {weight.dtype for block in arrays for weight in block}
        if len(dtypes) != 1 or next(iter(dtypes)) not in (
            jnp.dtype(jnp.float32),
            jnp.dtype(jnp.float64),
        ):
            raise TypeError("weights must share one float32 or float64 dtype.")
        self.plan = plan
        self.weights = arrays

    def validate(self) -> None:
        """Re-admit the fixed plan and the original W shapes, dtype and finiteness."""
        # Bind every recorded path count to an admitted W leaf before any
        # basis replay allocates from it.
        SymmetricContraction(self.plan, self.weights)
        self.plan.validate()
        if not all(
            bool(np.all(np.isfinite(jax.device_get(weight))))
            for block in self.weights
            for weight in block
        ):
            raise ValueError("Symmetric contraction weights must be finite.")

    @classmethod
    def initialize(
        cls,
        plan: SymmetricContractionPlan,
        /,
        *,
        key: PRNGKey,
        dtype: DTypeLike = jnp.float64,
    ) -> SymmetricContraction:
        """Draw ``W ~ N(0, 1) / paths``, the original initialization."""
        resolved = np.dtype(dtype)
        if resolved not in (np.dtype(np.float32), np.dtype(np.float64)):
            raise ValueError("dtype must be float32 or float64.")
        shapes = plan.weight_shapes()
        keys = jr.split(key, sum(len(block) for block in shapes))
        flat = iter(keys)
        weights = tuple(
            tuple(
                jr.normal(next(flat), shape, dtype=resolved) / shape[1] for shape in block
            )
            for block in shapes
        )
        return cls(plan, weights)

    def __call__(
        self, features: ArrayLike, species: ArrayLike, /, *, node_tile: int | None = None
    ) -> Array:
        """Contract ``(nodes, channels, D_in)`` features to ``(nodes, channels, D_out)``."""
        values, indices = self.plan.validate_inputs(features, species)
        return _map_nodes(self._contract, values, indices, node_tile)

    def _contract(self, features: Array, species: Array, /) -> Array:
        monomials = jnp.moveaxis(self.plan.product_graph.evaluate(features), -1, 0)
        blocks = []
        for block_bases, block_maps, block_weights in zip(
            self.plan.bases, self.plan.term_maps, self.weights
        ):
            terms = [
                ein.contract(
                    "mknc,nkc->ncm",
                    basis.path_features(monomials[term_map]),
                    weight[species].astype(features.dtype),
                )
                for basis, term_map, weight in zip(block_bases, block_maps, block_weights)
            ]
            total = terms[0]
            for term in terms[1:]:
                total = total + term
            blocks.append(total)
        return jnp.concatenate(blocks, axis=-1)

    def merged(self) -> MergedSymmetricContraction:
        """Bind frozen coefficients ``C = P W`` to the current weight revision."""
        return MergedSymmetricContraction(self)


def symmetric_contraction_revision(module: SymmetricContraction, /) -> NumericRevision:
    """Host numeric revision of the original W of one contraction."""
    if not isinstance(module, SymmetricContraction):
        raise TypeError("module must be a SymmetricContraction.")
    return NumericRevision(
        SemanticProvenance(
            {"kind": "symmetric-contraction", "plan_id": module.plan.plan_id}
        ),
        {
            f"weights[{block}][{order}]": np.asarray(jax.device_get(weight))
            for block, block_weights in enumerate(module.weights)
            for order, weight in enumerate(block_weights)
        },
    )


@final
class MergedSymmetricContraction(StrictModule, NonTrainableState):
    """Frozen ``C[s, t, M, c] = sum_k P[t, M, k] W[s, k, c]`` bound to one W revision.

    Coefficients are FIXED data: optimizing them would expand the source
    parameter space, so training uses `SymmetricContraction`. Consumers check
    `require_current` at their host boundary before executing a binding;
    restoration and publication run `validate`, which recomputes every executed
    coefficient and map from the source.
    """

    plan: SymmetricContractionPlan
    coefficients: tuple[Array, ...]
    block_term_maps: tuple[Array, ...]
    source_revision_id: str = eqx.field(static=True)
    binding_id: str = eqx.field(static=True)

    def __init__(self, source: SymmetricContraction, /) -> None:
        if not isinstance(source, SymmetricContraction):
            raise TypeError("source must be a SymmetricContraction.")
        revision = symmetric_contraction_revision(source)
        plan = source.plan
        coefficients = []
        term_maps = []
        for block_bases, block_maps, block_weights in zip(
            plan.bases, plan.term_maps, source.weights
        ):
            parts = [
                ein.contract(
                    "tmk,skc->stmc", basis.dense_projection().astype(weight.dtype), weight
                )
                for basis, weight in zip(block_bases, block_weights)
            ]
            coefficients.append(jnp.concatenate(parts, axis=1))
            term_maps.append(jnp.concatenate(block_maps, axis=0))
        self.plan = plan
        self.coefficients = tuple(coefficients)
        self.block_term_maps = tuple(term_maps)
        self.source_revision_id = revision.revision_id
        self.binding_id = canonical_fingerprint(
            {
                "kind": "merged-symmetric-contraction",
                "plan_id": plan.plan_id,
                "source_revision": revision.revision_id,
            }
        )

    def require_current(self, source: SymmetricContraction, /) -> None:
        """Refuse execution when ``source`` W differ from the bound revision."""
        if not isinstance(source, SymmetricContraction):
            raise TypeError("source must be a SymmetricContraction.")
        if source.plan.plan_id != self.plan.plan_id:
            raise StaleSymmetricContractionBinding(
                "Merged contraction was prepared for another plan."
            )
        if symmetric_contraction_revision(source).revision_id != self.source_revision_id:
            raise StaleSymmetricContractionBinding(
                "Merged contraction coefficients are stale: source weights changed."
            )

    def validate(self, source: SymmetricContraction, /) -> None:
        """Refuse unless every executed field is the merge of validated ``source``.

        ``source`` must already be validated by its owner. The duplicated plan
        and term maps must equal the source exactly, the merged coefficients
        must be finite and reproduce ``C = P W`` to rounding, and the recorded
        revision and binding identities are recomputed.
        """
        self.require_current(source)
        require_identical(
            self.plan,
            source.plan,
            "Merged contraction plan",
            StaleSymmetricContractionBinding,
        )
        expected = MergedSymmetricContraction(source)
        require_identical(
            self.block_term_maps,
            expected.block_term_maps,
            "Merged contraction term maps",
            StaleSymmetricContractionBinding,
        )
        require_realized(
            self.coefficients,
            expected.coefficients,
            "Merged contraction coefficients",
            StaleSymmetricContractionBinding,
        )
        if (self.source_revision_id, self.binding_id) != (
            expected.source_revision_id,
            expected.binding_id,
        ):
            raise StaleSymmetricContractionBinding(
                "Merged contraction identity does not match its source."
            )

    def __call__(
        self, features: ArrayLike, species: ArrayLike, /, *, node_tile: int | None = None
    ) -> Array:
        values, indices = self.plan.validate_inputs(features, species)
        return _map_nodes(self._contract, values, indices, node_tile)

    def _contract(self, features: Array, species: Array, /) -> Array:
        monomials = self.plan.product_graph.evaluate(features)
        blocks = [
            ein.contract(
                "nct,ntmc->ncm",
                monomials[..., term_map],
                coefficients[species].astype(features.dtype),
            )
            for coefficients, term_map in zip(self.coefficients, self.block_term_maps)
        ]
        return jnp.concatenate(blocks, axis=-1)


for _artifact in (
    MergedSymmetricContraction,
    SymmetricContraction,
    SymmetricContractionBasis,
    SymmetricContractionPlan,
):
    register_artifact_value(f"phydrax.nn.atomistic:{_artifact.__name__}", _artifact)
del _artifact
# The product graph is registered by its first artifact consumer: the leaf
# polynomial package is imported before the model artifact registry.
register_artifact_value("phydrax.polynomial.internal:ProductGraphPlan", ProductGraphPlan)


__all__ = [
    "MergedSymmetricContraction",
    "StaleSymmetricContractionBinding",
    "SymmetricBasisOrigin",
    "SymmetricContraction",
    "SymmetricContractionBasis",
    "SymmetricContractionPlan",
    "symmetric_contraction_revision",
]
