#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Differentiable coordinate, Riemannian, and signed geometry for Phydrax."""

from . import clifford
from ._adm import (
    ADMDecomposition,
    ADMParameterization,
    ADMValidationReport,
    decompose_adm_metric,
    parameterized_adm_metric,
    validate_adm_decomposition,
)
from ._adm_geometry import (
    adm_constraint_residuals,
    adm_extrinsic_curvature,
    adm_hamiltonian_constraint,
    adm_momentum_constraint,
    adm_normal_covector,
    adm_normal_vector,
    adm_spacetime_projector,
    ADMConstraintResiduals,
)
from ._atlas import (
    AtlasValidationReport,
    ComplexAtlasStructure,
    CoordinateAtlas,
    PatchwiseScalarField,
    validate_coordinate_atlas,
)
from ._atlas_cover import AtlasCover, AtlasOverlap, ChartSupport
from ._bigraded_forms import bigraded_wedge, BigradedForm, partial, partial_bar
from ._bosonic_gaussian import (
    BosonicGaussianChannel,
    BosonicGaussianState,
    canonical_commutation_matrix,
)
from ._boundary import (
    induced_boundary_density,
    induced_boundary_metric,
    RiemannianHypersurface,
)
from ._bundle import (
    bundle_covariant_derivative,
    bundle_curvature,
    gauge_curvature_residual,
    gauge_transform_connection,
    VectorBundleConnection,
)
from ._chart import ChartTransition, CoordinateChart
from ._chern import ChernConnection, HolomorphicBundleFrame, HolomorphicBundleTransition
from ._classical_manifold import (
    HyperboloidManifold,
    PoincareBallManifold,
    ProbabilitySimplexManifold,
)
from ._compact_spectrum import SphereLaplacianLevels
from ._complex import (
    AlmostComplexStructure,
    AlmostComplexValidationReport,
    ComplexCoordinateConvention,
    holomorphicity_residual,
    nijenhuis_tensor,
    standard_complex_structure,
    validate_almost_complex_structure,
    wirtinger_derivatives,
)
from ._complex_matrix_manifold import (
    AffineInvariantHPDManifold,
    ComplexStiefelManifold,
    SpecialUnitaryGroup,
    SpecialUnitaryManifold,
    UnitaryGroup,
    UnitaryManifold,
)
from ._complex_projective import ComplexProjectiveManifold
from ._connection import (
    AbstractAffineConnection,
    CallableAffineConnection,
    christoffel_from_metric_jet,
    connection_geodesic_acceleration,
    connection_geodesic_rhs,
    connection_parallel_transport_rhs,
    connection_transformation_residual,
    geodesic_acceleration,
    geodesic_rhs,
    LeviCivitaConnection,
    nonmetricity_tensor,
    parallel_transport_rhs,
    pullback_affine_connection,
    torsion_tensor,
)
from ._curvature import (
    connection_ricci_tensor,
    connection_riemann_tensor,
    einstein_tensor,
    ricci_tensor,
    riemann_tensor,
    scalar_curvature,
    sectional_curvature,
)
from ._density import (
    metric_volume_density,
    pullback_density,
    validate_volume_density,
    VolumeDensity,
    VolumeDensityValidationReport,
)
from ._embedded import EmbeddedChart, tangent_projector_from_normal
from ._fermionic_gaussian import FermionicGaussianState
from ._forms import (
    codifferential,
    DifferentialForm,
    exterior_derivative,
    hodge_laplacian,
    hodge_star,
    interior_product,
    lie_derivative,
    pullback_form,
    wedge,
)
from ._geodesic_problem import integrate_metric_geodesic, MetricGeodesicResult
from ._hessian_geometry import HessianGeometry, validate_hessian_geometry
from ._information_operator import (
    InformationMetricOperator,
    pulled_back_information_operator,
)
from ._jet import metric_jet, MetricJet
from ._kahler import (
    HermitianStructure,
    HermitianValidationReport,
    KahlerStructure,
    KahlerValidationReport,
    validate_hermitian_structure,
    validate_kahler_structure,
)
from ._kahler_potential import KahlerPotentialGeometry
from ._legendre_geometry import (
    LegendreGeometry,
    LegendreValidationReport,
    validate_legendre_geometry,
)
from ._lie_group import (
    AbstractLieGroup,
    LieGroupStateGeometry,
    RightLieGroupStateGeometry,
    SpecialEuclideanGroup,
    SpecialOrthogonalGroup,
)
from ._lorentzian import adm_metric, flrw_metric, minkowski_metric, schwarzschild_metric
from ._manifold import (
    AbstractGeodesicManifold,
    AbstractRiemannianManifold,
    EuclideanManifold,
    SphereManifold,
)
from ._manifold_state_geometry import GeodesicManifoldStateGeometry
from ._manifold_validation import (
    ManifoldValidationReport,
    StateGeometryValidationReport,
    validate_manifold,
    validate_state_geometry,
)
from ._map import (
    DifferentiableMap,
    Immersion,
    ImmersionValidationReport,
    validate_immersion,
)
from ._map_geometry import RiemannianMapGeometry
from ._matrix_manifold import (
    AffineInvariantSPDManifold,
    FixedRankManifold,
    GrassmannManifold,
    ObliqueManifold,
    SpecialOrthogonalManifold,
    StiefelManifold,
)
from ._metric import (
    AbstractSemiRiemannianMetric,
    cholesky_metric,
    diagonal_metric,
    diagonal_semi_riemannian_metric,
    euclidean_metric,
    LorentzianConvention,
    LorentzianMetric,
    MetricSignature,
    pullback_lorentzian_metric,
    pullback_metric,
    pullback_semi_riemannian_metric,
    RiemannianMetric,
    SemiRiemannianMetric,
)
from ._metric_measure import WeightedRiemannianMeasure
from ._operator_kernels import (
    apply_cotangent_map,
    covariant_symbol_contraction,
    density_divergence,
)
from ._operators import (
    affine_covariant_derivative,
    connection_covariant_hessian,
    connection_divergence,
    covariant_derivative,
    covariant_hessian,
    divergence,
    gradient,
    laplace_beltrami,
)
from ._patchwise import (
    PatchwiseDensity,
    PatchwiseDifferentialForm,
    PatchwiseMetric,
    PatchwiseTensorField,
)
from ._precision import GeometryPrecisionPolicy
from ._product_spectrum import product_laplacian_eigenbasis
from ._quantum_density import (
    bures_squared_distance,
    BuresDensityManifold,
    density_fidelity,
    faithful_density_from_cholesky,
    faithful_density_from_generator,
    FaithfulDensityReport,
    FixedRankDensityStratum,
    principal_purification,
    SLDQuantumFisherGeometry,
    uhlmann_alignment,
    UhlmannAlignment,
)
from ._semi_riemannian import (
    causal_character,
    CausalCharacter,
    dalembertian,
    proper_time_rate,
    semi_riemannian_gradient,
    TimeOrientation,
)
from ._signed_validation import (
    SignedMetricValidationReport,
    validate_lorentzian_metric,
    validate_semi_riemannian_metric,
)
from ._special_holonomy import (
    LocalSUNStructure,
    LocalSUNValidationReport,
    validate_local_su_structure,
)
from ._state_geometry import (
    AbstractStateGeometry,
    EmbeddedStateGeometry,
    EuclideanStateGeometry,
    LocalRetraction,
    PointwiseStateGeometry,
    SpecialOrthogonalStateGeometry,
    SymmetricPositiveDefiniteStateGeometry,
)
from ._statistics import frechet_mean, frechet_objective, FrechetMeanResult
from ._stochastic import (
    brownian_generator,
    coordinate_stratonovich_to_ito_drift,
    coordinate_to_covariant_drift,
    covariant_fokker_planck_operator,
    covariant_kolmogorov_generator,
)
from ._sub_riemannian import (
    horizontal_gradient,
    horizontal_hamiltonian,
    HorizontalCometric,
    HorizontalValidationReport,
    step_two_horizontal_rank,
    sub_laplacian,
    sub_riemannian_hamiltonian_rhs,
    validate_horizontal_cometric,
)
from ._symplectic import (
    canonical_symplectic_form,
    casimir_residual,
    hamiltonian_vector_field,
    liouville_volume_form,
    poisson_bracket,
    poisson_jacobi_tensor,
    PoissonStructure,
    PoissonValidationReport,
    symplectic_to_poisson,
    SymplecticForm,
    symplecticity_residual,
    SymplecticValidationReport,
    validate_poisson_structure,
    validate_symplectic_form,
)
from ._tensor import (
    contract_indices,
    COVECTOR_TENSOR,
    DENSITY_TENSOR,
    inner_product,
    lower_index,
    pullback_covector,
    pushforward_vector,
    raise_index,
    reexpress_tensor,
    SCALAR_TENSOR,
    tensor_norm_squared,
    TensorType,
    TensorVariance,
    VECTOR_TENSOR,
)
from ._validation import MetricValidationReport, validate_metric


__all__ = [
    "ADMConstraintResiduals",
    "ADMDecomposition",
    "ADMParameterization",
    "ADMValidationReport",
    "AbstractAffineConnection",
    "AbstractGeodesicManifold",
    "AbstractRiemannianManifold",
    "AbstractSemiRiemannianMetric",
    "AlmostComplexStructure",
    "AlmostComplexValidationReport",
    "AtlasValidationReport",
    "AbstractStateGeometry",
    "AffineInvariantHPDManifold",
    "ComplexStiefelManifold",
    "AffineInvariantSPDManifold",
    "CallableAffineConnection",
    "CausalCharacter",
    "ChartTransition",
    "ComplexProjectiveManifold",
    "ComplexAtlasStructure",
    "CoordinateAtlas",
    "ComplexCoordinateConvention",
    "clifford",
    "SpecialUnitaryGroup",
    "SpecialUnitaryManifold",
    "CoordinateChart",
    "COVECTOR_TENSOR",
    "DENSITY_TENSOR",
    "DifferentiableMap",
    "Immersion",
    "ImmersionValidationReport",
    "EmbeddedChart",
    "EmbeddedStateGeometry",
    "EuclideanManifold",
    "EuclideanStateGeometry",
    "FixedRankManifold",
    "FrechetMeanResult",
    "GeometryPrecisionPolicy",
    "GrassmannManifold",
    "ObliqueManifold",
    "HyperboloidManifold",
    "HermitianStructure",
    "HermitianValidationReport",
    "HessianGeometry",
    "LegendreGeometry",
    "LegendreValidationReport",
    "LeviCivitaConnection",
    "LocalRetraction",
    "LorentzianConvention",
    "LorentzianMetric",
    "KahlerStructure",
    "KahlerValidationReport",
    "LocalSUNStructure",
    "LocalSUNValidationReport",
    "ManifoldValidationReport",
    "MetricGeodesicResult",
    "MetricJet",
    "MetricSignature",
    "MetricValidationReport",
    "PoincareBallManifold",
    "PointwiseStateGeometry",
    "ProbabilitySimplexManifold",
    "RiemannianMetric",
    "SCALAR_TENSOR",
    "SemiRiemannianMetric",
    "RiemannianMapGeometry",
    "SignedMetricValidationReport",
    "PatchwiseScalarField",
    "RiemannianHypersurface",
    "SpecialOrthogonalManifold",
    "SpecialOrthogonalStateGeometry",
    "SphereLaplacianLevels",
    "SphereManifold",
    "StateGeometryValidationReport",
    "StiefelManifold",
    "SymmetricPositiveDefiniteStateGeometry",
    "UnitaryGroup",
    "UnitaryManifold",
    "TensorType",
    "TensorVariance",
    "TimeOrientation",
    "VECTOR_TENSOR",
    "VolumeDensity",
    "VolumeDensityValidationReport",
    "WeightedRiemannianMeasure",
    "adm_metric",
    "adm_constraint_residuals",
    "VectorBundleConnection",
    "adm_extrinsic_curvature",
    "adm_hamiltonian_constraint",
    "adm_momentum_constraint",
    "adm_normal_covector",
    "adm_normal_vector",
    "adm_spacetime_projector",
    "apply_cotangent_map",
    "brownian_generator",
    "bundle_covariant_derivative",
    "bundle_curvature",
    "causal_character",
    "cholesky_metric",
    "christoffel_from_metric_jet",
    "connection_geodesic_acceleration",
    "connection_geodesic_rhs",
    "connection_parallel_transport_rhs",
    "connection_ricci_tensor",
    "connection_riemann_tensor",
    "contract_indices",
    "decompose_adm_metric",
    "coordinate_stratonovich_to_ito_drift",
    "coordinate_to_covariant_drift",
    "covariant_derivative",
    "covariant_fokker_planck_operator",
    "covariant_hessian",
    "covariant_kolmogorov_generator",
    "covariant_symbol_contraction",
    "dalembertian",
    "density_divergence",
    "diagonal_metric",
    "diagonal_semi_riemannian_metric",
    "divergence",
    "einstein_tensor",
    "euclidean_metric",
    "flrw_metric",
    "holomorphicity_residual",
    "nijenhuis_tensor",
    "geodesic_acceleration",
    "geodesic_rhs",
    "integrate_metric_geodesic",
    "gauge_curvature_residual",
    "gauge_transform_connection",
    "gradient",
    "induced_boundary_density",
    "frechet_mean",
    "frechet_objective",
    "induced_boundary_metric",
    "inner_product",
    "laplace_beltrami",
    "lower_index",
    "metric_jet",
    "metric_volume_density",
    "minkowski_metric",
    "parallel_transport_rhs",
    "proper_time_rate",
    "pullback_covector",
    "pullback_density",
    "pullback_lorentzian_metric",
    "parameterized_adm_metric",
    "product_laplacian_eigenbasis",
    "pullback_metric",
    "pullback_semi_riemannian_metric",
    "pushforward_vector",
    "raise_index",
    "reexpress_tensor",
    "ricci_tensor",
    "riemann_tensor",
    "scalar_curvature",
    "schwarzschild_metric",
    "sectional_curvature",
    "semi_riemannian_gradient",
    "standard_complex_structure",
    "tangent_projector_from_normal",
    "tensor_norm_squared",
    "validate_adm_decomposition",
    "validate_almost_complex_structure",
    "validate_coordinate_atlas",
    "validate_hermitian_structure",
    "validate_kahler_structure",
    "validate_local_su_structure",
    "validate_hessian_geometry",
    "validate_legendre_geometry",
    "validate_immersion",
    "validate_lorentzian_metric",
    "validate_manifold",
    "validate_metric",
    "validate_semi_riemannian_metric",
    "validate_state_geometry",
    "validate_volume_density",
    "wirtinger_derivatives",
    "DifferentialForm",
    "codifferential",
    "exterior_derivative",
    "hodge_laplacian",
    "hodge_star",
    "interior_product",
    "lie_derivative",
    "pullback_form",
    "wedge",
    "AbstractLieGroup",
    "LieGroupStateGeometry",
    "SpecialEuclideanGroup",
    "SpecialOrthogonalGroup",
    "PoissonStructure",
    "PoissonValidationReport",
    "SymplecticForm",
    "SymplecticValidationReport",
    "canonical_symplectic_form",
    "casimir_residual",
    "hamiltonian_vector_field",
    "liouville_volume_form",
    "poisson_bracket",
    "poisson_jacobi_tensor",
    "symplectic_to_poisson",
    "symplecticity_residual",
    "validate_poisson_structure",
    "validate_symplectic_form",
    "HorizontalCometric",
    "HorizontalValidationReport",
    "horizontal_gradient",
    "horizontal_hamiltonian",
    "sub_riemannian_hamiltonian_rhs",
    "step_two_horizontal_rank",
    "sub_laplacian",
    "validate_horizontal_cometric",
    "affine_covariant_derivative",
    "connection_covariant_hessian",
    "connection_divergence",
    "connection_transformation_residual",
    "nonmetricity_tensor",
    "pullback_affine_connection",
    "torsion_tensor",
    "AtlasCover",
    "AtlasOverlap",
    "ChartSupport",
    "BigradedForm",
    "bigraded_wedge",
    "partial",
    "partial_bar",
    "ChernConnection",
    "HolomorphicBundleFrame",
    "HolomorphicBundleTransition",
    "InformationMetricOperator",
    "pulled_back_information_operator",
    "KahlerPotentialGeometry",
    "RightLieGroupStateGeometry",
    "GeodesicManifoldStateGeometry",
    "PatchwiseDensity",
    "PatchwiseDifferentialForm",
    "PatchwiseMetric",
    "BuresDensityManifold",
    "FaithfulDensityReport",
    "FixedRankDensityStratum",
    "SLDQuantumFisherGeometry",
    "UhlmannAlignment",
    "bures_squared_distance",
    "density_fidelity",
    "faithful_density_from_cholesky",
    "faithful_density_from_generator",
    "principal_purification",
    "uhlmann_alignment",
    "BosonicGaussianChannel",
    "BosonicGaussianState",
    "canonical_commutation_matrix",
    "PatchwiseTensorField",
    "FermionicGaussianState",
]
