#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from collections.abc import Callable

import jax
import jax.numpy as jnp
from jaxtyping import Array, ArrayLike

from .._strict import StrictModule
from ._chart import CoordinateChart
from ._metric import RiemannianMetric
from ._utils import _pointwise_array
from ._validation import MetricValidationReport, validate_metric


class _HessianMetricMap(StrictModule):
    geometry: HessianGeometry

    def __init__(self, geometry: HessianGeometry, /):
        self.geometry = geometry

    def __call__(self, coordinates: Array, /) -> Array:
        return jax.hessian(self.geometry._potential_point)(coordinates)


class HessianGeometry(StrictModule):
    """A dually-flat metric candidate generated by a convex potential."""

    potential_function: Callable[[Array], Array]
    chart: CoordinateChart

    def __init__(
        self,
        potential: Callable[[Array], Array],
        /,
        *,
        chart: CoordinateChart,
    ):
        if not callable(potential):
            raise TypeError("Hessian potential must be callable.")
        if not isinstance(chart, CoordinateChart):
            raise TypeError("Hessian geometry requires a CoordinateChart.")
        self.potential_function = potential
        self.chart = chart

    def _potential_point(self, coordinates: Array, /) -> Array:
        value = jnp.asarray(self.potential_function(coordinates))
        if value.shape != ():
            raise ValueError("Pointwise Hessian potential must be scalar-valued.")
        return value

    def potential(self, coordinates: ArrayLike, /) -> Array:
        return _pointwise_array(
            self._potential_point,
            coordinates,
            self.chart.dimension,
        )

    def dual_coordinates(self, coordinates: ArrayLike, /) -> Array:
        return _pointwise_array(
            jax.grad(self._potential_point),
            coordinates,
            self.chart.dimension,
        )

    def metric(self) -> RiemannianMetric:
        return RiemannianMetric(_HessianMetricMap(self), chart=self.chart)

    def bregman_divergence(
        self,
        left: ArrayLike,
        right: ArrayLike,
        /,
    ) -> Array:
        left_array = jnp.asarray(left)
        right_array = jnp.asarray(right)
        if left_array.shape != right_array.shape or left_array.shape[-1:] != (
            self.chart.dimension,
        ):
            raise ValueError("Bregman points must share the Hessian chart shape.")
        return (
            self.potential(left_array)
            - self.potential(right_array)
            - jnp.sum(
                self.dual_coordinates(right_array) * (left_array - right_array),
                axis=-1,
            )
        )


def validate_hessian_geometry(
    geometry: HessianGeometry,
    points: ArrayLike,
    /,
    *,
    eigenvalue_floor: float = 0.0,
    maximum_condition_number: float | None = None,
    raise_on_error: bool = True,
) -> MetricValidationReport:
    if not isinstance(geometry, HessianGeometry):
        raise TypeError("geometry must be a HessianGeometry.")
    return validate_metric(
        geometry.metric(),
        points,
        eigenvalue_floor=eigenvalue_floor,
        maximum_condition_number=maximum_condition_number,
        raise_on_error=raise_on_error,
    )


__all__ = ["HessianGeometry", "validate_hessian_geometry"]
