#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

from collections.abc import Callable
from math import isfinite

import equinox as eqx
import jax
import jax.numpy as jnp
import opt_einsum as oe
from jaxtyping import Array, ArrayLike

from .._geometry_precision import GeometryPrecisionPolicy
from .._precision import PrecisionEvidenceEnvelope
from .._strict import StrictModule
from ._atlas_cover import ChartSupport
from ._chart import ChartTransition
from ._hessian_geometry import HessianGeometry
from ._information_operator import InformationMetricOperator
from ._metric import RiemannianMetric
from ._utils import _coordinates
from ._validation import MetricValidationReport, validate_metric


def _real_coordinates(value: ArrayLike, dimension: int, name: str, /) -> Array:
    coordinates = _coordinates(value, dimension)
    if not jnp.issubdtype(coordinates.dtype, jnp.floating):
        raise TypeError(f"{name} must use real floating-point coordinates.")
    return coordinates


def _maximum_point_norm(value: Array, precision: GeometryPrecisionPolicy, /) -> Array:
    norms = precision.norm(value, axis=-1)
    return precision.decision(jnp.max(norms, initial=0.0))


class LegendreGeometry(StrictModule):
    """Domain-aware Legendre duality generated by one Hessian potential."""

    hessian_geometry: HessianGeometry
    inverse_dual_function: Callable[[Array], Array]
    primal_support: ChartSupport
    dual_support: ChartSupport
    geometry_id: str = eqx.field(static=True)

    def __init__(
        self,
        hessian_geometry: HessianGeometry,
        inverse_dual_coordinates: Callable[[Array], Array],
        /,
        *,
        primal_support: ChartSupport,
        dual_support: ChartSupport,
        geometry_id: str,
    ):
        if not isinstance(hessian_geometry, HessianGeometry):
            raise TypeError("hessian_geometry must be a HessianGeometry.")
        if not callable(inverse_dual_coordinates):
            raise TypeError("inverse_dual_coordinates must be callable.")
        if not isinstance(primal_support, ChartSupport):
            raise TypeError("primal_support must be a ChartSupport.")
        if not isinstance(dual_support, ChartSupport):
            raise TypeError("dual_support must be a ChartSupport.")
        if not primal_support.chart.compatible_with(hessian_geometry.chart):
            raise ValueError(
                "Legendre primal support must use the Hessian geometry chart."
            )
        if dual_support.chart.dimension != hessian_geometry.chart.dimension:
            raise ValueError("Legendre primal and dual chart dimensions must match.")
        identifier = str(geometry_id)
        if not identifier:
            raise ValueError("geometry_id must be non-empty.")
        self.hessian_geometry = hessian_geometry
        self.inverse_dual_function = inverse_dual_coordinates
        self.primal_support = primal_support
        self.dual_support = dual_support
        self.geometry_id = identifier

    @property
    def primal_chart(self):
        return self.hessian_geometry.chart

    @property
    def dual_chart(self):
        return self.dual_support.chart

    @property
    def dimension(self) -> int:
        return self.primal_chart.dimension

    @property
    def dual_transition(self) -> ChartTransition:
        """Return the declared primal-to-dual chart transition."""
        return ChartTransition(
            self.primal_chart,
            self.dual_chart,
            self.hessian_geometry.dual_coordinates,
            inverse=self.inverse_dual_function,
        )

    def _primal(self, value: ArrayLike, name: str, /) -> Array:
        coordinates = _real_coordinates(value, self.dimension, name)
        valid = self.primal_contains(coordinates)
        return eqx.error_if(
            coordinates,
            jnp.any(~valid),
            f"{name} is outside Legendre primal support {self.primal_support.support_id!r}.",
        )

    def _dual(self, value: ArrayLike, name: str, /) -> Array:
        coordinates = _real_coordinates(value, self.dimension, name)
        valid = self.dual_contains(coordinates)
        return eqx.error_if(
            coordinates,
            jnp.any(~valid),
            f"{name} is outside Legendre dual support {self.dual_support.support_id!r}.",
        )

    def primal_contains(self, coordinates: ArrayLike, /) -> Array:
        values = _real_coordinates(coordinates, self.dimension, "Primal coordinates")
        return self.primal_support.contains(values) & jnp.all(
            jnp.isfinite(values), axis=-1
        )

    def dual_contains(self, coordinates: ArrayLike, /) -> Array:
        values = _real_coordinates(coordinates, self.dimension, "Dual coordinates")
        return self.dual_support.contains(values) & jnp.all(
            jnp.isfinite(values), axis=-1
        )

    def potential(self, coordinates: ArrayLike, /) -> Array:
        primal = self._primal(coordinates, "Potential coordinates")
        return self.hessian_geometry.potential(primal)

    def dual_coordinates(self, coordinates: ArrayLike, /) -> Array:
        primal = self._primal(coordinates, "Primal coordinates")
        dual = self.hessian_geometry.dual_coordinates(primal)
        return self._dual(dual, "Mapped dual coordinates")

    def inverse_dual_coordinates(self, coordinates: ArrayLike, /) -> Array:
        dual = self._dual(coordinates, "Dual coordinates")
        primal = self.dual_transition.inverse(dual)
        return self._primal(primal, "Mapped primal coordinates")

    def metric(self) -> RiemannianMetric:
        return self.hessian_geometry.metric()

    def information_operator(
        self,
        coordinates: ArrayLike,
        /,
        *,
        damping: ArrayLike = 0.0,
        precision: GeometryPrecisionPolicy | None = None,
    ) -> InformationMetricOperator:
        primal = self._primal(coordinates, "Information coordinates")
        return self.hessian_geometry.information_operator(
            primal,
            damping=damping,
            precision=precision,
        )

    def bregman_divergence(
        self,
        left: ArrayLike,
        right: ArrayLike,
        /,
    ) -> Array:
        left_primal = self._primal(left, "Left Bregman point")
        right_primal = self._primal(right, "Right Bregman point")
        return self.hessian_geometry.bregman_divergence(left_primal, right_primal)

    def dual_potential(self, coordinates: ArrayLike, /) -> Array:
        dual = self._dual(coordinates, "Dual-potential coordinates")
        primal = self.inverse_dual_coordinates(dual)
        return jnp.sum(primal * dual, axis=-1) - self.potential(primal)

    def dual_bregman_divergence(
        self,
        left: ArrayLike,
        right: ArrayLike,
        /,
    ) -> Array:
        left_dual = self._dual(left, "Left dual Bregman point")
        right_dual = self._dual(right, "Right dual Bregman point")
        if left_dual.shape != right_dual.shape:
            raise ValueError("Dual Bregman points must have equal shapes.")
        left_primal = self.inverse_dual_coordinates(left_dual)
        right_primal = self.inverse_dual_coordinates(right_dual)
        return self.bregman_divergence(right_primal, left_primal)

    def fenchel_young_gap(
        self,
        primal: ArrayLike,
        dual: ArrayLike,
        /,
    ) -> Array:
        primal_coordinates = self._primal(primal, "Fenchel--Young primal point")
        dual_coordinates = self._dual(dual, "Fenchel--Young dual point")
        if primal_coordinates.shape != dual_coordinates.shape:
            raise ValueError("Fenchel--Young primal and dual points must have equal shapes.")
        return (
            self.potential(primal_coordinates)
            + self.dual_potential(dual_coordinates)
            - jnp.sum(primal_coordinates * dual_coordinates, axis=-1)
        )

    def dual_translate(
        self,
        primal: ArrayLike,
        dual_displacement: ArrayLike,
        /,
    ) -> Array:
        primal_coordinates = self._primal(primal, "Mirror primal point")
        displacement = _real_coordinates(
            dual_displacement,
            self.dimension,
            "Dual displacement",
        )
        if displacement.shape != primal_coordinates.shape:
            raise ValueError("Dual displacement must match the primal point shape.")
        if displacement.dtype != primal_coordinates.dtype:
            raise TypeError("Dual displacement must match the primal point dtype.")
        translated = self.dual_coordinates(primal_coordinates) + displacement
        translated = self._dual(translated, "Translated dual coordinates")
        return self.inverse_dual_coordinates(translated)


class LegendreValidationReport(StrictModule):
    """Representative-point diagnostics for a declared Legendre geometry."""

    valid: Array
    finite: Array
    metric_validation: MetricValidationReport
    primal_support_valid: Array
    dual_support_valid: Array
    maximum_primal_roundtrip_error: Array
    maximum_dual_roundtrip_error: Array
    maximum_jacobian_inverse_error: Array
    maximum_fenchel_young_diagonal_gap: Array
    maximum_bregman_diagonal_error: Array
    precision_evidence: PrecisionEvidenceEnvelope

    def __init__(
        self,
        *,
        valid: ArrayLike,
        finite: ArrayLike,
        metric_validation: MetricValidationReport,
        primal_support_valid: ArrayLike,
        dual_support_valid: ArrayLike,
        maximum_primal_roundtrip_error: ArrayLike,
        maximum_dual_roundtrip_error: ArrayLike,
        maximum_jacobian_inverse_error: ArrayLike,
        maximum_fenchel_young_diagonal_gap: ArrayLike,
        maximum_bregman_diagonal_error: ArrayLike,
        precision_evidence: PrecisionEvidenceEnvelope,
    ):
        if not isinstance(metric_validation, MetricValidationReport):
            raise TypeError("metric_validation must be a MetricValidationReport.")
        if not isinstance(precision_evidence, PrecisionEvidenceEnvelope):
            raise TypeError("precision_evidence must be a PrecisionEvidenceEnvelope.")
        self.valid = jnp.asarray(valid, dtype=bool)
        self.finite = jnp.asarray(finite, dtype=bool)
        self.metric_validation = metric_validation
        self.primal_support_valid = jnp.asarray(primal_support_valid, dtype=bool)
        self.dual_support_valid = jnp.asarray(dual_support_valid, dtype=bool)
        self.maximum_primal_roundtrip_error = jnp.asarray(
            maximum_primal_roundtrip_error
        )
        self.maximum_dual_roundtrip_error = jnp.asarray(maximum_dual_roundtrip_error)
        self.maximum_jacobian_inverse_error = jnp.asarray(
            maximum_jacobian_inverse_error
        )
        self.maximum_fenchel_young_diagonal_gap = jnp.asarray(
            maximum_fenchel_young_diagonal_gap
        )
        self.maximum_bregman_diagonal_error = jnp.asarray(
            maximum_bregman_diagonal_error
        )
        self.precision_evidence = precision_evidence


def validate_legendre_geometry(
    geometry: LegendreGeometry,
    primal_points: ArrayLike,
    /,
    *,
    dual_points: ArrayLike | None = None,
    roundtrip_tolerance: float = 1e-8,
    jacobian_tolerance: float = 1e-8,
    conjugacy_tolerance: float = 1e-8,
    symmetry_tolerance: float = 1e-8,
    eigenvalue_floor: float = 0.0,
    maximum_condition_number: float | None = None,
    raise_on_error: bool = True,
    precision: GeometryPrecisionPolicy | None = None,
) -> LegendreValidationReport:
    """Validate declared Legendre identities at representative coordinates."""
    if not isinstance(geometry, LegendreGeometry):
        raise TypeError("geometry must be a LegendreGeometry.")
    tolerances = (
        roundtrip_tolerance,
        jacobian_tolerance,
        conjugacy_tolerance,
        symmetry_tolerance,
    )
    if any(not isfinite(float(value)) or float(value) < 0.0 for value in tolerances):
        raise ValueError("Legendre validation tolerances must be finite and non-negative.")
    precision_ = GeometryPrecisionPolicy() if precision is None else precision
    if not isinstance(precision_, GeometryPrecisionPolicy):
        raise TypeError("precision must be a GeometryPrecisionPolicy or None.")

    primal = _real_coordinates(primal_points, geometry.dimension, "Primal points")
    precision_.validate_coordinates(primal)
    primal_compute = precision_.compute(primal)
    input_primal_support = geometry.primal_contains(primal_compute)

    transition = geometry.dual_transition
    mapped_dual = precision_.compute(transition(primal_compute))
    mapped_dual_support = geometry.dual_contains(mapped_dual)
    primal_roundtrip = precision_.compute(transition.inverse(mapped_dual))
    maximum_primal_roundtrip_error = _maximum_point_norm(
        primal_roundtrip - primal_compute,
        precision_,
    )

    if dual_points is None:
        dual = mapped_dual
    else:
        dual = _real_coordinates(dual_points, geometry.dimension, "Dual points")
        precision_.validate_coordinates(dual)
        dual = precision_.compute(dual)
    supplied_dual_support = geometry.dual_contains(dual)
    dual_primal = precision_.compute(transition.inverse(dual))
    dual_roundtrip = precision_.compute(transition(dual_primal))
    maximum_dual_roundtrip_error = _maximum_point_norm(
        dual_roundtrip - dual,
        precision_,
    )
    primal_support_valid = (
        jnp.all(input_primal_support)
        & jnp.all(geometry.primal_contains(primal_roundtrip))
        & jnp.all(geometry.primal_contains(dual_primal))
    )
    dual_support_valid = jnp.all(mapped_dual_support) & jnp.all(supplied_dual_support)

    forward_jacobian = precision_.compute(transition.jacobian(primal_compute))
    inverse_jacobian = precision_.compute(transition.inverse_jacobian(mapped_dual))
    jacobian_product = oe.contract(
        "...ij,...jk->...ik",
        forward_jacobian,
        inverse_jacobian,
    )
    identity = jnp.eye(geometry.dimension, dtype=jacobian_product.dtype)
    maximum_jacobian_inverse_error = precision_.decision(
        jnp.max(jnp.abs(jacobian_product - identity), initial=0.0)
    )

    primal_potential = precision_.compute(
        geometry.hessian_geometry.potential(primal_compute)
    )
    roundtrip_potential = precision_.compute(
        geometry.hessian_geometry.potential(primal_roundtrip)
    )
    dual_potential = (
        precision_.sum(primal_roundtrip * mapped_dual, axis=-1)
        - roundtrip_potential
    )
    fenchel_young = (
        primal_potential
        + dual_potential
        - precision_.sum(primal_compute * mapped_dual, axis=-1)
    )
    maximum_fenchel_young_diagonal_gap = precision_.decision(
        jnp.max(jnp.abs(fenchel_young), initial=0.0)
    )
    bregman_diagonal = precision_.compute(
        geometry.hessian_geometry.bregman_divergence(primal_compute, primal_compute)
    )
    maximum_bregman_diagonal_error = precision_.decision(
        jnp.max(jnp.abs(bregman_diagonal), initial=0.0)
    )

    metric_validation = validate_metric(
        geometry.metric(),
        primal,
        symmetry_tolerance=symmetry_tolerance,
        eigenvalue_floor=eigenvalue_floor,
        maximum_condition_number=maximum_condition_number,
        raise_on_error=False,
        precision=precision_,
    )
    finite = jnp.all(
        jnp.stack(
            (
                jnp.all(jnp.isfinite(primal_compute)),
                jnp.all(jnp.isfinite(mapped_dual)),
                jnp.all(jnp.isfinite(primal_roundtrip)),
                jnp.all(jnp.isfinite(dual_primal)),
                jnp.all(jnp.isfinite(dual_roundtrip)),
                jnp.all(jnp.isfinite(forward_jacobian)),
                jnp.all(jnp.isfinite(inverse_jacobian)),
                jnp.isfinite(maximum_fenchel_young_diagonal_gap),
                jnp.isfinite(maximum_bregman_diagonal_error),
            )
        )
    )
    valid = (
        finite
        & primal_support_valid
        & dual_support_valid
        & metric_validation.valid
        & (
            maximum_primal_roundtrip_error
            <= jnp.asarray(
                roundtrip_tolerance,
                dtype=maximum_primal_roundtrip_error.dtype,
            )
        )
        & (
            maximum_dual_roundtrip_error
            <= jnp.asarray(
                roundtrip_tolerance,
                dtype=maximum_dual_roundtrip_error.dtype,
            )
        )
        & (
            maximum_jacobian_inverse_error
            <= jnp.asarray(
                jacobian_tolerance,
                dtype=maximum_jacobian_inverse_error.dtype,
            )
        )
        & (
            maximum_fenchel_young_diagonal_gap
            <= jnp.asarray(
                conjugacy_tolerance,
                dtype=maximum_fenchel_young_diagonal_gap.dtype,
            )
        )
        & (
            maximum_bregman_diagonal_error
            <= jnp.asarray(
                conjugacy_tolerance,
                dtype=maximum_bregman_diagonal_error.dtype,
            )
        )
    )
    report = LegendreValidationReport(
        valid=valid,
        finite=finite,
        metric_validation=metric_validation,
        primal_support_valid=primal_support_valid,
        dual_support_valid=dual_support_valid,
        maximum_primal_roundtrip_error=maximum_primal_roundtrip_error,
        maximum_dual_roundtrip_error=maximum_dual_roundtrip_error,
        maximum_jacobian_inverse_error=maximum_jacobian_inverse_error,
        maximum_fenchel_young_diagonal_gap=maximum_fenchel_young_diagonal_gap,
        maximum_bregman_diagonal_error=maximum_bregman_diagonal_error,
        precision_evidence=precision_.evidence_for(
            primal,
            children={"metric": metric_validation.precision_evidence},
        ),
    )
    if raise_on_error and not bool(jax.device_get(valid)):
        raise ValueError(
            "Legendre geometry validation failed: "
            f"finite={bool(jax.device_get(finite))}, "
            f"primal_support_valid={bool(jax.device_get(primal_support_valid))}, "
            f"dual_support_valid={bool(jax.device_get(dual_support_valid))}, "
            "maximum_primal_roundtrip_error="
            f"{float(jax.device_get(maximum_primal_roundtrip_error))}, "
            "maximum_dual_roundtrip_error="
            f"{float(jax.device_get(maximum_dual_roundtrip_error))}, "
            "maximum_jacobian_inverse_error="
            f"{float(jax.device_get(maximum_jacobian_inverse_error))}, "
            "maximum_fenchel_young_diagonal_gap="
            f"{float(jax.device_get(maximum_fenchel_young_diagonal_gap))}, "
            "maximum_bregman_diagonal_error="
            f"{float(jax.device_get(maximum_bregman_diagonal_error))}."
        )
    return report


__all__ = [
    "LegendreGeometry",
    "LegendreValidationReport",
    "validate_legendre_geometry",
]
