#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Finite-discrete factor graphs, exact inference, belief propagation, and Gibbs sampling."""

from ._belief_propagation import (
    BeliefPropagationMethod,
    BeliefPropagationResult,
    BeliefPropagationState,
    initialize_belief_propagation,
    MaxProductBeliefPropagation,
    MaxProductBeliefPropagationResult,
    prepare_belief_propagation,
    PreparedBeliefPropagation,
    refresh_belief_propagation,
    run_belief_propagation,
    SumProductBeliefPropagation,
    SumProductBeliefPropagationResult,
)
from ._exact import enumerate_assignments, enumerate_factor_graph
from ._gibbs import (
    ChromaticGibbs,
    gibbs_sweep,
    GibbsSampleResult,
    GibbsSchedule,
    GibbsState,
    GibbsTransitionInfo,
    initialize_gibbs,
    prepare_chromatic_gibbs,
    PreparedChromaticGibbs,
    refresh_chromatic_gibbs,
    sample_gibbs,
)
from ._model import (
    BinaryCardinalityFactorGroup,
    DenseTableFactorGroup,
    DiscreteFactorGraph,
    DiscreteVariableGroup,
    EnumeratedFactorGroup,
    factor_graph_contains,
    factor_graph_log_score,
    IsingFactorGroup,
    LogicalFactorGroup,
    pack_assignments,
    pack_evidence,
    PottsFactorGroup,
    unpack_assignments,
    VariableSelection,
    VariableStateValues,
)
from ._structured import ising_factor_graph, potts_factor_graph
from ._training import (
    contrastive_divergence_loss,
    exact_factor_graph_negative_log_likelihood,
    ExactNormalizerResult,
    factor_graph_moments,
    FactorGraphTrainingDiagnostics,
)
from ._types import (
    BeliefPropagationDiagnostics,
    BeliefPropagationStatus,
    ExactFactorGraphResult,
    ExactFactorGraphStatus,
    FactorGraphProvenance,
    GibbsDiagnostics,
    GibbsTransitionStatus,
)


__all__ = [
    "BeliefPropagationDiagnostics",
    "BeliefPropagationMethod",
    "BeliefPropagationResult",
    "BeliefPropagationState",
    "BeliefPropagationStatus",
    "BinaryCardinalityFactorGroup",
    "ChromaticGibbs",
    "DenseTableFactorGroup",
    "DiscreteFactorGraph",
    "DiscreteVariableGroup",
    "EnumeratedFactorGroup",
    "ExactFactorGraphResult",
    "ExactFactorGraphStatus",
    "ExactNormalizerResult",
    "FactorGraphProvenance",
    "FactorGraphTrainingDiagnostics",
    "GibbsDiagnostics",
    "GibbsSampleResult",
    "GibbsSchedule",
    "GibbsState",
    "GibbsTransitionInfo",
    "GibbsTransitionStatus",
    "IsingFactorGroup",
    "LogicalFactorGroup",
    "MaxProductBeliefPropagation",
    "MaxProductBeliefPropagationResult",
    "PottsFactorGroup",
    "PreparedBeliefPropagation",
    "PreparedChromaticGibbs",
    "SumProductBeliefPropagation",
    "SumProductBeliefPropagationResult",
    "VariableSelection",
    "VariableStateValues",
    "contrastive_divergence_loss",
    "enumerate_assignments",
    "enumerate_factor_graph",
    "exact_factor_graph_negative_log_likelihood",
    "factor_graph_contains",
    "factor_graph_log_score",
    "factor_graph_moments",
    "gibbs_sweep",
    "initialize_belief_propagation",
    "initialize_gibbs",
    "ising_factor_graph",
    "pack_assignments",
    "pack_evidence",
    "potts_factor_graph",
    "prepare_belief_propagation",
    "prepare_chromatic_gibbs",
    "refresh_belief_propagation",
    "refresh_chromatic_gibbs",
    "run_belief_propagation",
    "sample_gibbs",
    "unpack_assignments",
]
