#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from importlib import import_module
from typing import Any

from ._boolean import (
    boolean_brep,
    BRepBooleanFailure,
    BRepBooleanOperation,
    BRepBooleanPolicy,
    BRepBooleanResult,
)
from ._constructors import (
    assemble_brep_model,
    brep_box,
    brep_cone,
    brep_cylinder,
    brep_extrusion,
    brep_offset,
    brep_planar_face,
    brep_revolution,
    brep_sphere,
    brep_torus,
    BRepTessellationPolicy,
    PlanarProfile,
    ProfileArc,
    ProfileLine,
    ProfileLoop,
    ProfilePlane,
)
from ._differentiable import (
    BRepParameterLink,
    evaluate_fixed_topology_mesh,
    FixedTopologyBRepRealization,
    FixedTopologyBRepSource,
)
from ._intersection import (
    CoincidentParameterRegion,
    CurveIntersectionResult,
    CurveSurfaceIntersectionRoot,
    intersect_curve_ranges,
    intersect_curve_region,
    intersect_surface_regions,
    NativePeriodEndpoint,
    ParametricIntersectionCertificate,
    ParametricIntersectionKind,
    ParametricIntersectionPoint,
    ParametricIntersectionPolicy,
    ParametricIntersectionWork,
    SurfaceIntersectionResult,
    TrimRootEndpoint,
    UnresolvedIntersectionReason,
    UnresolvedParameterRegion,
)
from ._intersection_curve import (
    AffinePCurve,
    CurveRange,
    CurveTrimSegment,
    IntersectionCurve,
    IntersectionCurvePoint,
    IntersectionCurveSide,
    IntersectionEndpointKind,
    IntersectionPCurve,
    PeriodicPCurve,
    SurfaceRegion,
)
from ._model import (
    BRepAssemblyContainer,
    BRepBoundaryMap,
    BRepEntityId,
    BRepGeometry,
    BRepImportReport,
    BRepModel,
    BRepOccurrence,
    BRepQualifiedIncidence,
    BRepTopology,
)
from ._partition import (
    all_brep_faces,
    all_brep_solids,
    BRepPartitionHistoryError,
    BRepPartitionOperand,
    BRepPartitionPatch,
    BRepPartitionPlan,
    BRepPartitionPolicy,
    BRepPartitionRegion,
    BRepPartitionReport,
    BRepPartitionResult,
    BRepPartitionRole,
    cad_revision_from_brep_model,
    partition_brep,
)
from ._patches import (
    AbstractCurve,
    AbstractSurfacePatch,
    BSplineCurve,
    BSplineSurfacePatch,
    CircleCurve,
    ConePatch,
    Curve,
    CylinderPatch,
    EllipseCurve,
    ExtrusionSurface,
    HyperbolaCurve,
    LineCurve,
    OffsetCurve,
    OffsetSurface,
    ParabolaCurve,
    PlanePatch,
    RationalBezierPiece,
    RevolutionSurface,
    RuledSurface,
    SpherePatch,
    surface_differential,
    surface_jacobian,
    surface_normal,
    SurfacePatch,
    TorusPatch,
)
from ._projection import prepare_brep_projection
from ._projection_contracts import (
    AbstractBRepProjection,
    brep_entity_id,
    BRepEntityDimension,
    BRepProjectionPolicy,
    BRepProjectionResult,
    BRepProjectionStatus,
)
from ._query import (
    BRepContainmentResult,
    BRepMeasureResult,
    BRepQueryBudget,
    BRepQueryPolicy,
    BRepQueryResourceError,
    BRepSurfaceQueryResult,
    NativeBRepProjection,
    prepare_brep_query,
    PreparedBRepQuery,
)
from ._sewing import (
    BRepSewingContact,
    BRepSewingContactRelation,
    BRepSewingEdgeImage,
    BRepSewingFailure,
    BRepSewingLineage,
    BRepSewingPolicy,
    BRepSewingResult,
    sew_brep,
)
from ._source import BRep, BRepSource


_PLANAR_EXPORTS = frozenset(
    ("PlanarPartitionOperand", "PlanarPartitionPlan", "partition_planar")
)


def __getattr__(name: str) -> Any:
    if name in _PLANAR_EXPORTS:
        module = import_module("._planar", __package__)
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "BRepAssemblyContainer",
    "BRepQualifiedIncidence",
    "boolean_brep",
    "BRepBooleanFailure",
    "BRepBooleanOperation",
    "BRepBooleanPolicy",
    "BRepBooleanResult",
    "BRepSewingContact",
    "BRepSewingContactRelation",
    "BRepSewingEdgeImage",
    "BRepSewingFailure",
    "BRepSewingLineage",
    "BRepSewingPolicy",
    "BRepSewingResult",
    "sew_brep",
    "AffinePCurve",
    "CoincidentParameterRegion",
    "CurveIntersectionResult",
    "CurveSurfaceIntersectionRoot",
    "CurveRange",
    "CurveTrimSegment",
    "IntersectionCurve",
    "IntersectionCurvePoint",
    "IntersectionCurveSide",
    "IntersectionEndpointKind",
    "IntersectionPCurve",
    "ParametricIntersectionCertificate",
    "ParametricIntersectionKind",
    "ParametricIntersectionPoint",
    "ParametricIntersectionPolicy",
    "ParametricIntersectionWork",
    "PeriodicPCurve",
    "SurfaceIntersectionResult",
    "SurfaceRegion",
    "UnresolvedIntersectionReason",
    "UnresolvedParameterRegion",
    "NativePeriodEndpoint",
    "TrimRootEndpoint",
    "intersect_curve_ranges",
    "intersect_curve_region",
    "intersect_surface_regions",
    "AbstractBRepProjection",
    "AbstractSurfacePatch",
    "BRep",
    "BRepBoundaryMap",
    "BRepEntityDimension",
    "BRepEntityId",
    "BRepImportReport",
    "BRepModel",
    "BRepParameterLink",
    "BRepPartitionHistoryError",
    "BRepPartitionOperand",
    "BRepPartitionPatch",
    "BRepPartitionPlan",
    "BRepPartitionPolicy",
    "BRepPartitionRegion",
    "BRepPartitionReport",
    "BRepPartitionResult",
    "BRepPartitionRole",
    "BRepProjectionPolicy",
    "BRepProjectionResult",
    "BRepProjectionStatus",
    "BRepSource",
    "BRepTopology",
    "BSplineCurve",
    "BSplineSurfacePatch",
    "ConePatch",
    "CylinderPatch",
    "FixedTopologyBRepRealization",
    "FixedTopologyBRepSource",
    "OffsetSurface",
    "PlanarPartitionOperand",
    "PlanarPartitionPlan",
    "PlanePatch",
    "SpherePatch",
    "SurfacePatch",
    "TorusPatch",
    "all_brep_faces",
    "all_brep_solids",
    "brep_entity_id",
    "cad_revision_from_brep_model",
    "evaluate_fixed_topology_mesh",
    "partition_brep",
    "partition_planar",
    "prepare_brep_projection",
    "surface_differential",
    "surface_jacobian",
    "surface_normal",
    "AbstractCurve",
    "BRepContainmentResult",
    "BRepGeometry",
    "BRepMeasureResult",
    "BRepOccurrence",
    "BRepQueryBudget",
    "BRepQueryPolicy",
    "BRepQueryResourceError",
    "BRepSurfaceQueryResult",
    "BRepTessellationPolicy",
    "CircleCurve",
    "Curve",
    "EllipseCurve",
    "ExtrusionSurface",
    "HyperbolaCurve",
    "LineCurve",
    "OffsetCurve",
    "ParabolaCurve",
    "NativeBRepProjection",
    "PreparedBRepQuery",
    "RationalBezierPiece",
    "RevolutionSurface",
    "RuledSurface",
    "PlanarProfile",
    "ProfileArc",
    "ProfileLine",
    "ProfileLoop",
    "ProfilePlane",
    "assemble_brep_model",
    "brep_box",
    "brep_cone",
    "brep_cylinder",
    "brep_extrusion",
    "brep_offset",
    "brep_planar_face",
    "brep_revolution",
    "brep_sphere",
    "brep_torus",
    "prepare_brep_query",
]
