# Copyright © 2026 PHYDRA, Inc. All rights reserved.
"""Prepared meshfree approximation, conservative metrics, and surface transport."""

from importlib import import_module
from typing import Any, TYPE_CHECKING


_FACADE_EXPORT_MODULES: dict[str, str] = {
    "MeshfreeApproximation": "._types",
    "MeshfreeRowStatus": "._types",
    "StencilAcceptance": "._types",
    "StencilWeightKernel": "._types",
    "MeshfreeNeighborhoodPlan": "._neighbors",
    "PreparedMeshfreeNeighborhood": "._neighbors",
    "MeshfreeEdgeRelationPlan": "._neighbors",
    "PreparedMeshfreeEdgeRelation": "._neighbors",
    "SmoothSupportEnvelope": "._neighbors",
    "LocalStencilPolicy": "._stencils",
    "MeshfreeFunctional": "._stencils",
    "LocalStencilEvidence": "._stencils",
    "LocalStencilReport": "._stencils",
    "PreparedLocalStencils": "._stencils",
    "prepare_local_stencils": "._stencils",
    "prepare_chart_stencils": "._stencils",
    "fit_chart_stencils": "._stencils",
    "LocalStencilRefresh": "._stencils",
    "LocalStencilRefreshStatus": "._stencils",
    "refresh_local_stencils": "._stencils",
    "refresh_chart_stencils": "._stencils",
    "MeshfreeOperator": "._operators",
    "DistributedMeshfreeEvidence": "._distributed",
    "DistributedMeshfreeOperator": "._distributed",
    "distributed_inner": "._distributed",
    "distributed_norm": "._distributed",
    "distributed_sum": "._distributed",
    "MeshfreePrecisionDType": "._precision",
    "MeshfreePrecisionPolicy": "._precision",
    "MeshfreePrecisionRole": "._precision",
    "HyperviscosityPlan": "._stabilization",
    "PreparedHyperviscosity": "._stabilization",
    "HyperviscosityEvidence": "._stabilization",
    "MeshfreeCoarseningPolicy": "._multilevel",
    "MeshfreeHierarchyPlan": "._multilevel",
    "PreparedMeshfreeHierarchy": "._multilevel",
    "MeshfreeHierarchyEvidence": "._multilevel",
    "meshfree_multigrid_builder": "._multilevel",
    "MeshfreeComponentLayout": "._multilevel",
    "MeshfreeComponentSpace": "._multilevel",
    "MeshfreeHierarchyStop": "._multilevel",
    "MeshfreeNearNullspace": "._multilevel",
    "MeshfreeNearNullspaceKind": "._multilevel",
    "MeshfreePartitionOfUnity": "._schwarz",
    "MeshfreeSchwarzEvidence": "._schwarz",
    "MeshfreeSchwarzPlan": "._schwarz",
    "MeshfreeSchwarzPolicy": "._schwarz",
    "MeshfreeSchwarzProlongation": "._schwarz",
    "PreparedMeshfreeSchwarz": "._schwarz",
    "meshfree_coarse_correction_term": "._schwarz",
    "ChartSurfaceGeometry": "._surface_geometry",
    "ImplicitSurfaceGeometry": "._surface_geometry",
    "SampledSurfaceGeometry": "._surface_geometry",
    "SurfaceAmbientDim": "._surface_geometry",
    "SurfaceBoundary": "._surface_geometry",
    "SurfaceBoundaryNodeDim": "._surface_geometry",
    "SurfaceBoundarySource": "._surface_geometry",
    "SurfaceCodimensionDim": "._surface_geometry",
    "SurfaceGeometry": "._surface_geometry",
    "SurfaceGeometrySource": "._surface_geometry",
    "SurfaceGeometryStatus": "._surface_geometry",
    "SurfaceGeometryEvidence": "._surface_geometry",
    "SurfaceGeometryEvaluation": "._surface_geometry",
    "SurfaceIntrinsicDim": "._surface_geometry",
    "SurfaceNodeDim": "._surface_geometry",
    "SurfaceQuadratureKind": "._surface_quadrature",
    "SurfaceQuadratureEvidence": "._surface_quadrature",
    "SurfaceQuadraturePolicy": "._surface_quadrature",
    "chart_box_atlas": "._surface_quadrature",
    "SurfacePointCloudPlan": "._surface",
    "PreparedSurfacePointCloud": "._surface",
    "SurfaceRefreshResult": "._surface",
    "SurfaceFieldReconstructionKernel": "._surface",
    "SurfaceBoundaryKind": "._surface",
    "SurfaceChartDerivatives": "._surface",
    "SurfaceEllipticSystem": "._surface",
    "SurfacePatchInterface": "._surface",
    "SurfaceRowKind": "._surface",
    "SurfaceTangentCalculus": "._surface_pde",
    "SurfaceVectorLaplacianKind": "._surface_pde",
    "MeshfreeExteriorCalculusPlan": "._exterior",
    "PreparedMeshfreeExteriorCalculus": "._exterior",
    "MeshfreeDiffusionOperator": "._exterior",
    "MeshfreeStiffnessEvidence": "._exterior",
    "MeshfreeBoundaryQuadrature": "._exterior",
    "EdgeCoefficientAverage": "._exterior",
    "CoercivityAssessment": "._exterior",
    "MeshfreeCoercivityPolicy": "._exterior",
    "MeshfreeExteriorRefreshResult": "._exterior",
    "MeshfreeExteriorRefreshStatus": "._exterior",
    "MeshfreeMetricPolicy": "._exterior_metric",
    "MeshfreeMetricResult": "._exterior_metric",
    "MeshfreeMetricStatus": "._exterior_metric",
    "MeshfreeMomentRowStatus": "._exterior_metric",
    "PreparedMeshfreeMetric": "._exterior_metric",
    "MetricSign": "._exterior_metric",
    "MetricAcceptance": "._exterior_metric",
    "MetricSolver": "._exterior_metric",
    "BoundaryClosure": "._exterior_metric",
    "MeshfreeMetricGeometry": "._exterior_metric",
    "MeshfreeAdvection": "._exterior_transport",
    "MeshfreeAdvectionResult": "._exterior_transport",
    "MeshfreeAdvectionStatus": "._exterior_transport",
    "MeshfreeAdvectionRate": "._exterior_transport",
    "edge_upwind_content": "._exterior_transport",
    "MovingSurfaceStatus": "._moving",
    "MovingGeometryRefresh": "._motion",
    "MovingSurfaceState": "._moving",
    "MovingSurfaceEvidence": "._moving",
    "MovingSurfaceStepResult": "._moving",
    "MovingSurfaceCheckpoint": "._moving",
    "MovingSurfaceEpochResult": "._moving",
    "MovingSurfacePlan": "._moving",
    "MovingArchiveMode": "._moving",
    "MovingGCLAdmission": "._moving",
    "MovingGCLPolicy": "._moving",
    "MovingMeasureLaw": "._moving",
    "MovingStageAdmission": "._moving",
    "AbstractSurfaceMotionLaw": "._motion",
    "BulkDrivenMotion": "._motion",
    "ChartMotion": "._motion",
    "LevelSetMotion": "._motion",
    "MeanCurvatureMotion": "._motion",
    "PrescribedVelocityMotion": "._motion",
    "SurfaceGeometryProvider": "._motion",
    "SurfaceMotion": "._motion",
    "SurfaceRefreshMode": "._motion",
    "SurfaceTangentialMode": "._motion",
    "MeshfreeCapacityMap": "._capacity",
    "MeshfreeCapacityPolicy": "._capacity",
    "SurfaceMeshShift": "._shifting",
    "SurfaceShiftPolicy": "._shifting",
    "SurfaceQualityEvidence": "._resampling",
    "SurfaceResamplingPolicy": "._resampling",
    "SurfaceResamplingResult": "._resampling",
    "SurfaceTransferPlan": "._surface_transfer",
    "PointTransferEvidence": "._transfer",
    "PointTransferObjective": "._transfer",
    "PointTransferPlan": "._transfer",
    "PointTransferProvider": "._transfer",
    "PointTransferRequest": "._transfer",
    "PointTransferRoute": "._transfer",
    "PointTransferStatus": "._transfer",
    "PointTransferWitness": "._transfer",
    "PreparedPointTransfer": "._transfer",
    "MeshfreeEpochCandidate": "._epochs",
    "MeshfreeEpochCause": "._epochs",
    "MeshfreeEpochChange": "._epochs",
    "MeshfreeEpochReceipt": "._epochs",
    "MeshfreeEventLineage": "._epochs",
    "MeshfreeHistoryRemap": "._epochs",
    "MeshfreeSheetSupport": "._epochs",
    "MeshfreeSurfaceEventEpoch": "._epochs",
    "commit_meshfree_epoch": "._epochs",
    "remap_live_histories": "._epochs",
    "stage_meshfree_epoch": "._epochs",
    "surface_event_epoch": "._epochs",
    "MeshfreeAdaptationAcceptance": "._adaptivity",
    "MeshfreeAdaptationChange": "._adaptivity",
    "MeshfreeAdaptationPolicy": "._adaptivity",
    "MeshfreeAdaptationProposal": "._adaptivity",
    "MeshfreeAdaptationRefusal": "._adaptivity",
    "MeshfreeAdaptationStatus": "._adaptivity",
    "MeshfreeAdaptiveSupport": "._adaptivity",
    "MeshfreeContainment": "._adaptivity",
    "MeshfreeErrorIndicator": "._adaptivity",
    "MeshfreeIndicatorKind": "._adaptivity",
    "MeshfreeMarking": "._adaptivity",
    "MeshfreeMarkingPolicy": "._adaptivity",
    "MeshfreeMarkingStrategy": "._adaptivity",
    "MeshfreeProbeJet": "._adaptivity",
    "MeshfreeProjection": "._adaptivity",
    "MeshfreeStrongResidual": "._adaptivity",
    "MeshfreeSupportKind": "._adaptivity",
    "MeshfreeSupportQuality": "._adaptivity",
    "adaptation_acceptance": "._adaptivity",
    "degree_difference_indicator": "._adaptivity",
    "flux_jump_indicator": "._adaptivity",
    "mark_points": "._adaptivity",
    "meshfree_fill_measures": "._adaptivity",
    "prepare_adaptation_transfer": "._adaptivity",
    "probe_residual_indicator": "._adaptivity",
    "propose_adaptation": "._adaptivity",
    "support_quality": "._adaptivity",
    "MeshfreeCorrectionDerivative": "._corrections",
    "MeshfreeCorrectionProvider": "._corrections",
    "MeshfreeCorrectionRoute": "._corrections",
    "MeshfreeCorrectionSignPolicy": "._corrections",
    "MeshfreeCorrectionStatus": "._corrections",
    "MeshfreeCorrectionSubject": "._corrections",
    "MeshfreeCorrectionWitness": "._corrections",
    "MeshfreeEdgeFluxCandidate": "._corrections",
    "MeshfreeEdgeFluxCorrection": "._corrections",
    "MeshfreeEdgeFluxCorrectionEvidence": "._corrections",
    "MeshfreeEdgeFluxCorrectionPlan": "._corrections",
    "MeshfreeEdgeFluxProjection": "._corrections",
    "MeshfreeMetricCorrection": "._corrections",
    "MeshfreeMetricCorrectionEvidence": "._corrections",
    "MeshfreeMetricCorrectionPlan": "._corrections",
    "MeshfreeMetricCorrectionPolicy": "._corrections",
    "MeshfreeMetricProjection": "._corrections",
    "AbstractEdgeConstitutiveLaw": "._constitutive",
    "EdgeFeatureField": "._constitutive",
    "EdgeFeatureKind": "._constitutive",
    "EdgeFrameFeatures": "._constitutive",
    "EdgeModelLipschitzCertificate": "._constitutive",
    "LipschitzEdgeFlux": "._constitutive",
    "MonotoneEdgeConductance": "._constitutive",
    "AbstractCoupledEdgeConstitutiveLaw": "._constitutive",
    "InvariantConvexEdgeCertificate": "._constitutive",
    "LipschitzCoupledEdgeFlux": "._constitutive",
    "MonotoneCoupledEdgeFlux": "._constitutive",
    "O3EdgeInvariants": "._constitutive",
    "O3EdgeNetwork": "._constitutive",
    "EdgeCoverageAssessment": "._coverage",
    "EdgeCoveragePolicy": "._coverage",
    "EdgeCoverageStatus": "._coverage",
    "EdgeFeatureCoverage": "._coverage",
    "MeshfreeConservationAdjoint": "._conservation_solve",
    "MeshfreeConservationLedger": "._conservation_solve",
    "MeshfreeConservationProblem": "._conservation_solve",
    "MeshfreeConservationResult": "._conservation_solve",
    "MeshfreeConstitutiveEvidence": "._conservation_solve",
    "MeshfreeContractionStatus": "._conservation_solve",
    "PreparedMeshfreeConservationSolve": "._conservation_solve",
    "prepare_meshfree_conservation_solve": "._conservation_solve",
    "MeshfreeComponentConservationLedger": "._conservation_solve",
    "MeshfreeCoupledConservationAdjoint": "._conservation_solve",
    "MeshfreeCoupledConservationProblem": "._conservation_solve",
    "MeshfreeCoupledConservationResult": "._conservation_solve",
    "PreparedMeshfreeCoupledConservationSolve": "._conservation_solve",
    "prepare_meshfree_coupled_conservation_solve": "._conservation_solve",
    "meshfree_candidate_profiles": "._profiles",
    "meshfree_support": "._profiles",
    "ComplexDomainIdentity": "._complex",
    "ComplexFidelity": "._complex",
    "ComplexGeometryAuthority": "._complex",
    "ComplexGeometryRole": "._complex",
    "MeshfreeCellComplexPlan": "._complex",
    "MeshfreeComplexAdmissionError": "._complex",
    "MeshfreeComplexDegreeEvidence": "._complex",
    "MeshfreeComplexEvidence": "._complex",
    "MeshfreeComplexPolicy": "._complex",
    "PreparedMeshfreeCellComplex": "._complex",
    "RadiusCliqueComplex": "._complex",
    "RadiusCliquePolicy": "._complex",
    "radius_clique_complex": "._complex",
    "PointBoundaryCharts": "._boundary",
    "PointBoundarySamples": "._boundary",
    "PointDerivativeFamily": "._boundary",
    "PointGhostLayerEvidence": "._boundary",
    "PointGhostLayerPlan": "._boundary",
    "PointInterfaceCondition": "._boundary",
    "PointSBPDerivatives": "._boundary",
    "PointSideAdmissionEvidence": "._boundary",
    "PointSideSupportPlan": "._boundary",
    "PreparedPointGhostLayer": "._boundary",
    "PreparedPointSideSupport": "._boundary",
    "prepare_point_sbp_derivatives": "._boundary",
    "prepare_tensor_point_sbp": "._boundary",
    "sample_boundary_atlas": "._boundary",
    "sample_cubature_atlas": "._boundary",
    "PointBlockNonlinearResult": "._systems",
    "PointBlockSystemPlan": "._systems",
    "PointBlockSystemResult": "._systems",
    "PointCouplingEvidence": "._systems",
    "PreparedPointBlockSystem": "._systems",
    "isotropic_elasticity_coefficients": "._systems",
    "MechanicsStatus": "._mechanics",
    "MeshfreeElasticityPlan": "._mechanics",
    "MeshfreeElasticityPreconditioner": "._mechanics",
    "MeshfreeTractionRoute": "._mechanics",
    "MeshfreeAuxiliaryStiffness": "._auxiliary",
    "meshfree_auxiliary_builder": "._auxiliary",
    "meshfree_auxiliary_stiffness": "._auxiliary",
    "MeshfreeElasticityResult": "._mechanics",
    "MeshfreeGeneralizedStokesPlan": "._mechanics",
    "MeshfreeHyperelasticPlan": "._mechanics",
    "MeshfreeHyperelasticResult": "._mechanics",
    "MeshfreeMixedResult": "._mechanics",
    "PreparedMeshfreeElasticity": "._mechanics",
    "PreparedMeshfreeGeneralizedStokes": "._mechanics",
    "PreparedMeshfreeHyperelastic": "._mechanics",
    "displacement_gradient": "._mechanics",
    "ConservativeTransport": "._transport",
    "TransportCFL": "._transport",
    "TransportRate": "._transport",
    "TransportRefresh": "._transport",
    "TransportRefreshStatus": "._transport",
    "TransportScheme": "._transport",
    "TransportStatus": "._transport",
    "TransportVolumeFlux": "._transport",
    "minimum_image_edge_charts": "._transport",
    "EvolutionLayout": "._evolution",
    "EvolutionMeasure": "._evolution",
    "EvolutionSSPMethod": "._evolution",
    "MaterialParticleMeasure": "._evolution",
    "MeshfreeDiffusionLaw": "._evolution",
    "MeshfreeDirichletRows": "._evolution",
    "MeshfreeEvolutionAdmission": "._evolution",
    "MeshfreeEvolutionCapacity": "._evolution",
    "MeshfreeEvolutionFields": "._evolution",
    "MeshfreeEvolutionPlan": "._evolution",
    "MeshfreeEvolutionSSPMethod": "._evolution",
    "MeshfreeEvolutionStatus": "._evolution",
    "MeshfreeEvolutionStepEvidence": "._evolution",
    "MeshfreeMotion": "._evolution",
    "MeshfreeReactionLaw": "._evolution",
    "MeshfreeSpectralEstimate": "._evolution",
    "MotionKind": "._evolution",
    "PreparedMeshfreeEvolution": "._evolution",
    "ReactionTreatment": "._evolution",
    "InflowTreatment": "._evolution",
    "MovingSurfaceFixedStepMethod": "._runtime",
    "meshfree_runtime_inventory": "._runtime",
    "moving_archive_policy": "._runtime",
    "ownership_migration_relation": "._runtime",
    "support_epoch_relation": "._runtime",
    "SupportEpochChain": "._runtime",
    "resume_support_epochs": "._runtime",
}

__all__ = list(_FACADE_EXPORT_MODULES)

if TYPE_CHECKING:
    from ._adaptivity import (
        adaptation_acceptance as adaptation_acceptance,
        degree_difference_indicator as degree_difference_indicator,
        flux_jump_indicator as flux_jump_indicator,
        mark_points as mark_points,
        meshfree_fill_measures as meshfree_fill_measures,
        MeshfreeAdaptationAcceptance as MeshfreeAdaptationAcceptance,
        MeshfreeAdaptationChange as MeshfreeAdaptationChange,
        MeshfreeAdaptationPolicy as MeshfreeAdaptationPolicy,
        MeshfreeAdaptationProposal as MeshfreeAdaptationProposal,
        MeshfreeAdaptationRefusal as MeshfreeAdaptationRefusal,
        MeshfreeAdaptationStatus as MeshfreeAdaptationStatus,
        MeshfreeAdaptiveSupport as MeshfreeAdaptiveSupport,
        MeshfreeContainment as MeshfreeContainment,
        MeshfreeErrorIndicator as MeshfreeErrorIndicator,
        MeshfreeIndicatorKind as MeshfreeIndicatorKind,
        MeshfreeMarking as MeshfreeMarking,
        MeshfreeMarkingPolicy as MeshfreeMarkingPolicy,
        MeshfreeMarkingStrategy as MeshfreeMarkingStrategy,
        MeshfreeProbeJet as MeshfreeProbeJet,
        MeshfreeProjection as MeshfreeProjection,
        MeshfreeStrongResidual as MeshfreeStrongResidual,
        MeshfreeSupportKind as MeshfreeSupportKind,
        MeshfreeSupportQuality as MeshfreeSupportQuality,
        prepare_adaptation_transfer as prepare_adaptation_transfer,
        probe_residual_indicator as probe_residual_indicator,
        propose_adaptation as propose_adaptation,
        support_quality as support_quality,
    )
    from ._auxiliary import (
        meshfree_auxiliary_builder as meshfree_auxiliary_builder,
        meshfree_auxiliary_stiffness as meshfree_auxiliary_stiffness,
        MeshfreeAuxiliaryStiffness as MeshfreeAuxiliaryStiffness,
    )
    from ._boundary import (
        PointBoundaryCharts as PointBoundaryCharts,
        PointBoundarySamples as PointBoundarySamples,
        PointDerivativeFamily as PointDerivativeFamily,
        PointGhostLayerEvidence as PointGhostLayerEvidence,
        PointGhostLayerPlan as PointGhostLayerPlan,
        PointInterfaceCondition as PointInterfaceCondition,
        PointSBPDerivatives as PointSBPDerivatives,
        PointSideAdmissionEvidence as PointSideAdmissionEvidence,
        PointSideSupportPlan as PointSideSupportPlan,
        prepare_point_sbp_derivatives as prepare_point_sbp_derivatives,
        prepare_tensor_point_sbp as prepare_tensor_point_sbp,
        PreparedPointGhostLayer as PreparedPointGhostLayer,
        PreparedPointSideSupport as PreparedPointSideSupport,
        sample_boundary_atlas as sample_boundary_atlas,
        sample_cubature_atlas as sample_cubature_atlas,
    )
    from ._capacity import (
        MeshfreeCapacityMap as MeshfreeCapacityMap,
        MeshfreeCapacityPolicy as MeshfreeCapacityPolicy,
    )
    from ._complex import (
        ComplexDomainIdentity as ComplexDomainIdentity,
        ComplexFidelity as ComplexFidelity,
        ComplexGeometryAuthority as ComplexGeometryAuthority,
        ComplexGeometryRole as ComplexGeometryRole,
        MeshfreeCellComplexPlan as MeshfreeCellComplexPlan,
        MeshfreeComplexAdmissionError as MeshfreeComplexAdmissionError,
        MeshfreeComplexDegreeEvidence as MeshfreeComplexDegreeEvidence,
        MeshfreeComplexEvidence as MeshfreeComplexEvidence,
        MeshfreeComplexPolicy as MeshfreeComplexPolicy,
        PreparedMeshfreeCellComplex as PreparedMeshfreeCellComplex,
        radius_clique_complex as radius_clique_complex,
        RadiusCliqueComplex as RadiusCliqueComplex,
        RadiusCliquePolicy as RadiusCliquePolicy,
    )
    from ._conservation_solve import (
        MeshfreeComponentConservationLedger as MeshfreeComponentConservationLedger,
        MeshfreeConservationAdjoint as MeshfreeConservationAdjoint,
        MeshfreeConservationLedger as MeshfreeConservationLedger,
        MeshfreeConservationProblem as MeshfreeConservationProblem,
        MeshfreeConservationResult as MeshfreeConservationResult,
        MeshfreeConstitutiveEvidence as MeshfreeConstitutiveEvidence,
        MeshfreeContractionStatus as MeshfreeContractionStatus,
        MeshfreeCoupledConservationAdjoint as MeshfreeCoupledConservationAdjoint,
        MeshfreeCoupledConservationProblem as MeshfreeCoupledConservationProblem,
        MeshfreeCoupledConservationResult as MeshfreeCoupledConservationResult,
        prepare_meshfree_conservation_solve as prepare_meshfree_conservation_solve,
        prepare_meshfree_coupled_conservation_solve as prepare_meshfree_coupled_conservation_solve,
        PreparedMeshfreeConservationSolve as PreparedMeshfreeConservationSolve,
        PreparedMeshfreeCoupledConservationSolve as PreparedMeshfreeCoupledConservationSolve,
    )
    from ._constitutive import (
        AbstractCoupledEdgeConstitutiveLaw as AbstractCoupledEdgeConstitutiveLaw,
        AbstractEdgeConstitutiveLaw as AbstractEdgeConstitutiveLaw,
        EdgeFeatureField as EdgeFeatureField,
        EdgeFeatureKind as EdgeFeatureKind,
        EdgeFrameFeatures as EdgeFrameFeatures,
        EdgeModelLipschitzCertificate as EdgeModelLipschitzCertificate,
        InvariantConvexEdgeCertificate as InvariantConvexEdgeCertificate,
        LipschitzCoupledEdgeFlux as LipschitzCoupledEdgeFlux,
        LipschitzEdgeFlux as LipschitzEdgeFlux,
        MonotoneCoupledEdgeFlux as MonotoneCoupledEdgeFlux,
        MonotoneEdgeConductance as MonotoneEdgeConductance,
        O3EdgeInvariants as O3EdgeInvariants,
        O3EdgeNetwork as O3EdgeNetwork,
    )
    from ._corrections import (
        MeshfreeCorrectionDerivative as MeshfreeCorrectionDerivative,
        MeshfreeCorrectionProvider as MeshfreeCorrectionProvider,
        MeshfreeCorrectionRoute as MeshfreeCorrectionRoute,
        MeshfreeCorrectionSignPolicy as MeshfreeCorrectionSignPolicy,
        MeshfreeCorrectionStatus as MeshfreeCorrectionStatus,
        MeshfreeCorrectionSubject as MeshfreeCorrectionSubject,
        MeshfreeCorrectionWitness as MeshfreeCorrectionWitness,
        MeshfreeEdgeFluxCandidate as MeshfreeEdgeFluxCandidate,
        MeshfreeEdgeFluxCorrection as MeshfreeEdgeFluxCorrection,
        MeshfreeEdgeFluxCorrectionEvidence as MeshfreeEdgeFluxCorrectionEvidence,
        MeshfreeEdgeFluxCorrectionPlan as MeshfreeEdgeFluxCorrectionPlan,
        MeshfreeEdgeFluxProjection as MeshfreeEdgeFluxProjection,
        MeshfreeMetricCorrection as MeshfreeMetricCorrection,
        MeshfreeMetricCorrectionEvidence as MeshfreeMetricCorrectionEvidence,
        MeshfreeMetricCorrectionPlan as MeshfreeMetricCorrectionPlan,
        MeshfreeMetricCorrectionPolicy as MeshfreeMetricCorrectionPolicy,
        MeshfreeMetricProjection as MeshfreeMetricProjection,
    )
    from ._coverage import (
        EdgeCoverageAssessment as EdgeCoverageAssessment,
        EdgeCoveragePolicy as EdgeCoveragePolicy,
        EdgeCoverageStatus as EdgeCoverageStatus,
        EdgeFeatureCoverage as EdgeFeatureCoverage,
    )
    from ._distributed import (
        distributed_inner as distributed_inner,
        distributed_norm as distributed_norm,
        distributed_sum as distributed_sum,
        DistributedMeshfreeEvidence as DistributedMeshfreeEvidence,
        DistributedMeshfreeOperator as DistributedMeshfreeOperator,
    )
    from ._epochs import (
        commit_meshfree_epoch as commit_meshfree_epoch,
        MeshfreeEpochCandidate as MeshfreeEpochCandidate,
        MeshfreeEpochCause as MeshfreeEpochCause,
        MeshfreeEpochChange as MeshfreeEpochChange,
        MeshfreeEpochReceipt as MeshfreeEpochReceipt,
        MeshfreeEventLineage as MeshfreeEventLineage,
        MeshfreeHistoryRemap as MeshfreeHistoryRemap,
        MeshfreeSheetSupport as MeshfreeSheetSupport,
        MeshfreeSurfaceEventEpoch as MeshfreeSurfaceEventEpoch,
        remap_live_histories as remap_live_histories,
        stage_meshfree_epoch as stage_meshfree_epoch,
        surface_event_epoch as surface_event_epoch,
    )
    from ._evolution import (
        EvolutionLayout as EvolutionLayout,
        EvolutionMeasure as EvolutionMeasure,
        EvolutionSSPMethod as EvolutionSSPMethod,
        InflowTreatment as InflowTreatment,
        MaterialParticleMeasure as MaterialParticleMeasure,
        MeshfreeDiffusionLaw as MeshfreeDiffusionLaw,
        MeshfreeDirichletRows as MeshfreeDirichletRows,
        MeshfreeEvolutionAdmission as MeshfreeEvolutionAdmission,
        MeshfreeEvolutionCapacity as MeshfreeEvolutionCapacity,
        MeshfreeEvolutionFields as MeshfreeEvolutionFields,
        MeshfreeEvolutionPlan as MeshfreeEvolutionPlan,
        MeshfreeEvolutionSSPMethod as MeshfreeEvolutionSSPMethod,
        MeshfreeEvolutionStatus as MeshfreeEvolutionStatus,
        MeshfreeEvolutionStepEvidence as MeshfreeEvolutionStepEvidence,
        MeshfreeMotion as MeshfreeMotion,
        MeshfreeReactionLaw as MeshfreeReactionLaw,
        MeshfreeSpectralEstimate as MeshfreeSpectralEstimate,
        MotionKind as MotionKind,
        PreparedMeshfreeEvolution as PreparedMeshfreeEvolution,
        ReactionTreatment as ReactionTreatment,
    )
    from ._exterior import (
        CoercivityAssessment as CoercivityAssessment,
        EdgeCoefficientAverage as EdgeCoefficientAverage,
        MeshfreeBoundaryQuadrature as MeshfreeBoundaryQuadrature,
        MeshfreeCoercivityPolicy as MeshfreeCoercivityPolicy,
        MeshfreeDiffusionOperator as MeshfreeDiffusionOperator,
        MeshfreeExteriorCalculusPlan as MeshfreeExteriorCalculusPlan,
        MeshfreeExteriorRefreshResult as MeshfreeExteriorRefreshResult,
        MeshfreeExteriorRefreshStatus as MeshfreeExteriorRefreshStatus,
        MeshfreeStiffnessEvidence as MeshfreeStiffnessEvidence,
        PreparedMeshfreeExteriorCalculus as PreparedMeshfreeExteriorCalculus,
    )
    from ._exterior_metric import (
        BoundaryClosure as BoundaryClosure,
        MeshfreeMetricGeometry as MeshfreeMetricGeometry,
        MeshfreeMetricPolicy as MeshfreeMetricPolicy,
        MeshfreeMetricResult as MeshfreeMetricResult,
        MeshfreeMetricStatus as MeshfreeMetricStatus,
        MeshfreeMomentRowStatus as MeshfreeMomentRowStatus,
        MetricAcceptance as MetricAcceptance,
        MetricSign as MetricSign,
        MetricSolver as MetricSolver,
        PreparedMeshfreeMetric as PreparedMeshfreeMetric,
    )
    from ._exterior_transport import (
        edge_upwind_content as edge_upwind_content,
        MeshfreeAdvection as MeshfreeAdvection,
        MeshfreeAdvectionRate as MeshfreeAdvectionRate,
        MeshfreeAdvectionResult as MeshfreeAdvectionResult,
        MeshfreeAdvectionStatus as MeshfreeAdvectionStatus,
    )
    from ._mechanics import (
        displacement_gradient as displacement_gradient,
        MechanicsStatus as MechanicsStatus,
        MeshfreeElasticityPlan as MeshfreeElasticityPlan,
        MeshfreeElasticityPreconditioner as MeshfreeElasticityPreconditioner,
        MeshfreeElasticityResult as MeshfreeElasticityResult,
        MeshfreeGeneralizedStokesPlan as MeshfreeGeneralizedStokesPlan,
        MeshfreeHyperelasticPlan as MeshfreeHyperelasticPlan,
        MeshfreeHyperelasticResult as MeshfreeHyperelasticResult,
        MeshfreeMixedResult as MeshfreeMixedResult,
        MeshfreeTractionRoute as MeshfreeTractionRoute,
        PreparedMeshfreeElasticity as PreparedMeshfreeElasticity,
        PreparedMeshfreeGeneralizedStokes as PreparedMeshfreeGeneralizedStokes,
        PreparedMeshfreeHyperelastic as PreparedMeshfreeHyperelastic,
    )
    from ._motion import (
        AbstractSurfaceMotionLaw as AbstractSurfaceMotionLaw,
        BulkDrivenMotion as BulkDrivenMotion,
        ChartMotion as ChartMotion,
        LevelSetMotion as LevelSetMotion,
        MeanCurvatureMotion as MeanCurvatureMotion,
        MovingGeometryRefresh as MovingGeometryRefresh,
        PrescribedVelocityMotion as PrescribedVelocityMotion,
        SurfaceGeometryProvider as SurfaceGeometryProvider,
        SurfaceMotion as SurfaceMotion,
        SurfaceRefreshMode as SurfaceRefreshMode,
        SurfaceTangentialMode as SurfaceTangentialMode,
    )
    from ._moving import (
        MovingArchiveMode as MovingArchiveMode,
        MovingGCLAdmission as MovingGCLAdmission,
        MovingGCLPolicy as MovingGCLPolicy,
        MovingMeasureLaw as MovingMeasureLaw,
        MovingStageAdmission as MovingStageAdmission,
        MovingSurfaceCheckpoint as MovingSurfaceCheckpoint,
        MovingSurfaceEpochResult as MovingSurfaceEpochResult,
        MovingSurfaceEvidence as MovingSurfaceEvidence,
        MovingSurfacePlan as MovingSurfacePlan,
        MovingSurfaceState as MovingSurfaceState,
        MovingSurfaceStatus as MovingSurfaceStatus,
        MovingSurfaceStepResult as MovingSurfaceStepResult,
    )
    from ._multilevel import (
        meshfree_multigrid_builder as meshfree_multigrid_builder,
        MeshfreeCoarseningPolicy as MeshfreeCoarseningPolicy,
        MeshfreeComponentLayout as MeshfreeComponentLayout,
        MeshfreeComponentSpace as MeshfreeComponentSpace,
        MeshfreeHierarchyEvidence as MeshfreeHierarchyEvidence,
        MeshfreeHierarchyPlan as MeshfreeHierarchyPlan,
        MeshfreeHierarchyStop as MeshfreeHierarchyStop,
        MeshfreeNearNullspace as MeshfreeNearNullspace,
        MeshfreeNearNullspaceKind as MeshfreeNearNullspaceKind,
        PreparedMeshfreeHierarchy as PreparedMeshfreeHierarchy,
    )
    from ._neighbors import (
        MeshfreeEdgeRelationPlan as MeshfreeEdgeRelationPlan,
        MeshfreeNeighborhoodPlan as MeshfreeNeighborhoodPlan,
        PreparedMeshfreeEdgeRelation as PreparedMeshfreeEdgeRelation,
        PreparedMeshfreeNeighborhood as PreparedMeshfreeNeighborhood,
        SmoothSupportEnvelope as SmoothSupportEnvelope,
    )
    from ._operators import MeshfreeOperator as MeshfreeOperator
    from ._precision import (
        MeshfreePrecisionDType as MeshfreePrecisionDType,
        MeshfreePrecisionPolicy as MeshfreePrecisionPolicy,
        MeshfreePrecisionRole as MeshfreePrecisionRole,
    )
    from ._profiles import (
        meshfree_candidate_profiles as meshfree_candidate_profiles,
        meshfree_support as meshfree_support,
    )
    from ._resampling import (
        SurfaceQualityEvidence as SurfaceQualityEvidence,
        SurfaceResamplingPolicy as SurfaceResamplingPolicy,
        SurfaceResamplingResult as SurfaceResamplingResult,
    )
    from ._runtime import (
        meshfree_runtime_inventory as meshfree_runtime_inventory,
        moving_archive_policy as moving_archive_policy,
        MovingSurfaceFixedStepMethod as MovingSurfaceFixedStepMethod,
        ownership_migration_relation as ownership_migration_relation,
        resume_support_epochs as resume_support_epochs,
        support_epoch_relation as support_epoch_relation,
        SupportEpochChain as SupportEpochChain,
    )
    from ._schwarz import (
        meshfree_coarse_correction_term as meshfree_coarse_correction_term,
        MeshfreePartitionOfUnity as MeshfreePartitionOfUnity,
        MeshfreeSchwarzEvidence as MeshfreeSchwarzEvidence,
        MeshfreeSchwarzPlan as MeshfreeSchwarzPlan,
        MeshfreeSchwarzPolicy as MeshfreeSchwarzPolicy,
        MeshfreeSchwarzProlongation as MeshfreeSchwarzProlongation,
        PreparedMeshfreeSchwarz as PreparedMeshfreeSchwarz,
    )
    from ._shifting import (
        SurfaceMeshShift as SurfaceMeshShift,
        SurfaceShiftPolicy as SurfaceShiftPolicy,
    )
    from ._stabilization import (
        HyperviscosityEvidence as HyperviscosityEvidence,
        HyperviscosityPlan as HyperviscosityPlan,
        PreparedHyperviscosity as PreparedHyperviscosity,
    )
    from ._stencils import (
        fit_chart_stencils as fit_chart_stencils,
        LocalStencilEvidence as LocalStencilEvidence,
        LocalStencilPolicy as LocalStencilPolicy,
        LocalStencilRefresh as LocalStencilRefresh,
        LocalStencilRefreshStatus as LocalStencilRefreshStatus,
        LocalStencilReport as LocalStencilReport,
        MeshfreeFunctional as MeshfreeFunctional,
        prepare_chart_stencils as prepare_chart_stencils,
        prepare_local_stencils as prepare_local_stencils,
        PreparedLocalStencils as PreparedLocalStencils,
        refresh_chart_stencils as refresh_chart_stencils,
        refresh_local_stencils as refresh_local_stencils,
    )
    from ._surface import (
        PreparedSurfacePointCloud as PreparedSurfacePointCloud,
        SurfaceBoundaryKind as SurfaceBoundaryKind,
        SurfaceChartDerivatives as SurfaceChartDerivatives,
        SurfaceEllipticSystem as SurfaceEllipticSystem,
        SurfaceFieldReconstructionKernel as SurfaceFieldReconstructionKernel,
        SurfacePatchInterface as SurfacePatchInterface,
        SurfacePointCloudPlan as SurfacePointCloudPlan,
        SurfaceRefreshResult as SurfaceRefreshResult,
        SurfaceRowKind as SurfaceRowKind,
    )
    from ._surface_geometry import (
        ChartSurfaceGeometry as ChartSurfaceGeometry,
        ImplicitSurfaceGeometry as ImplicitSurfaceGeometry,
        SampledSurfaceGeometry as SampledSurfaceGeometry,
        SurfaceAmbientDim as SurfaceAmbientDim,
        SurfaceBoundary as SurfaceBoundary,
        SurfaceBoundaryNodeDim as SurfaceBoundaryNodeDim,
        SurfaceBoundarySource as SurfaceBoundarySource,
        SurfaceCodimensionDim as SurfaceCodimensionDim,
        SurfaceGeometry as SurfaceGeometry,
        SurfaceGeometryEvaluation as SurfaceGeometryEvaluation,
        SurfaceGeometryEvidence as SurfaceGeometryEvidence,
        SurfaceGeometrySource as SurfaceGeometrySource,
        SurfaceGeometryStatus as SurfaceGeometryStatus,
        SurfaceIntrinsicDim as SurfaceIntrinsicDim,
        SurfaceNodeDim as SurfaceNodeDim,
    )
    from ._surface_pde import (
        SurfaceTangentCalculus as SurfaceTangentCalculus,
        SurfaceVectorLaplacianKind as SurfaceVectorLaplacianKind,
    )
    from ._surface_quadrature import (
        chart_box_atlas as chart_box_atlas,
        SurfaceQuadratureEvidence as SurfaceQuadratureEvidence,
        SurfaceQuadratureKind as SurfaceQuadratureKind,
        SurfaceQuadraturePolicy as SurfaceQuadraturePolicy,
    )
    from ._surface_transfer import SurfaceTransferPlan as SurfaceTransferPlan
    from ._systems import (
        isotropic_elasticity_coefficients as isotropic_elasticity_coefficients,
        PointBlockNonlinearResult as PointBlockNonlinearResult,
        PointBlockSystemPlan as PointBlockSystemPlan,
        PointBlockSystemResult as PointBlockSystemResult,
        PointCouplingEvidence as PointCouplingEvidence,
        PreparedPointBlockSystem as PreparedPointBlockSystem,
    )
    from ._transfer import (
        PointTransferEvidence as PointTransferEvidence,
        PointTransferObjective as PointTransferObjective,
        PointTransferPlan as PointTransferPlan,
        PointTransferProvider as PointTransferProvider,
        PointTransferRequest as PointTransferRequest,
        PointTransferRoute as PointTransferRoute,
        PointTransferStatus as PointTransferStatus,
        PointTransferWitness as PointTransferWitness,
        PreparedPointTransfer as PreparedPointTransfer,
    )
    from ._transport import (
        ConservativeTransport as ConservativeTransport,
        minimum_image_edge_charts as minimum_image_edge_charts,
        TransportCFL as TransportCFL,
        TransportRate as TransportRate,
        TransportRefresh as TransportRefresh,
        TransportRefreshStatus as TransportRefreshStatus,
        TransportScheme as TransportScheme,
        TransportStatus as TransportStatus,
        TransportVolumeFlux as TransportVolumeFlux,
    )
    from ._types import (
        MeshfreeApproximation as MeshfreeApproximation,
        MeshfreeRowStatus as MeshfreeRowStatus,
        StencilAcceptance as StencilAcceptance,
        StencilWeightKernel as StencilWeightKernel,
    )


def __getattr__(name: str) -> Any:
    module = _FACADE_EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
