#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Dynamical-system, pathwise-evolution, analysis, and identification contracts."""

from .._array_tree import ArrayLeafSchema, ArrayPyTreeSchema
from .._identity import (
    callable_payload,
    ExecutableSignature,
    NumericRevision,
    SemanticProvenance,
    strict_module_payload,
)
from . import analysis, identification
from ._affine import affine_exponential_step, AffineExponentialResult
from ._cell_enclosure import CellMapEnclosure
from ._conley import (
    compute_conley_homology_index,
    compute_conley_index,
    ConleyHomologyIndex,
    ConleyIndexResult,
)
from ._dae_structural import (
    AcausalDAESource,
    analyze_dae_structure,
    compile_acausal_dae,
    DAEComponent,
    DAEConnection,
    DAEDerivativeIncidence,
    DAEEquationBlock,
    DAEJet,
    DAEPort,
    DAEStructuralAnalysis,
    DAEStructuralPolicy,
    DAEVariableBlock,
    ReducedDAECompilation,
)
from ._differential_algebraic import (
    AutonomousDifferentialAlgebraicResidual,
    DAERole,
    DAEStructure,
    DifferentialAlgebraicResidual,
    DifferentialAlgebraicSystem,
    InputDifferentialAlgebraicResidual,
)
from ._evolution import (
    AbstractDifferentiableEvolution,
    AbstractEvolution,
    DiscreteEvolution,
    EVOLUTION_BACKEND_FAILED,
    EVOLUTION_NONFINITE,
    EVOLUTION_OUTSIDE_GEOMETRY,
    EVOLUTION_SUCCESS,
    EvolutionStep,
    EvolutionTangentStep,
    EvolutionTrajectory,
    evolve,
)
from ._grid import EvolutionGrid, IterationGrid, TimeGrid
from ._layout import InputLayout, InputRole, StateLayout
from ._linear_descriptor import DescriptorSystemEvidence, LinearDescriptorSystem
from ._linearization import EvolutionJacobianAction
from ._model_system import (
    continuous_model_system,
    ContinuousModelVectorField,
    discrete_model_system,
    DiscreteModelTransition,
)
from ._plant import (
    AbstractDiscretePlant,
    ArrayDiscreteSystemPlant,
    PlantCheckpoint,
    PlantParameters,
    PlantProposal,
    PlantReplayResult,
    PlantResetResult,
    PlantRuntimeState,
    PlantStepContext,
    PlantStepResult,
)
from ._plant_codec import (
    ControlVectorCodec,
    EncodedControl,
    EncodedPlantState,
    EncodedPlantVector,
    PlantPowerEvidence,
    PlantStateVectorCodec,
    PlantVectorRole,
)
from ._second_order import (
    SecondOrderDifferentialProblem,
    SecondOrderDifferentialSystem,
    SecondOrderResidual,
)
from ._system import (
    AbstractInputPolicy,
    AutonomousContinuousVectorField,
    AutonomousDiscreteTransition,
    CallableInputPolicy,
    ContinuousSystem,
    DiscreteStepContext,
    DiscreteSystem,
    DiscreteTransitionEvidence,
    DiscreteTransitionResult,
    HeldInputPolicy,
    InputContinuousVectorField,
    InputDiscreteTransition,
    SystemTransition,
    SystemVectorField,
)
from ._trajectory import (
    CaseAxisRole,
    InputAlignment,
    TrajectoryData,
    TrajectoryTransitions,
)
from .identification import (
    LearnedMarginalTransition,
    LearnedPathwiseTransition,
    TargetDiscreteModelObjective,
)


__all__ = [
    "AbstractDiscretePlant",
    "ArrayDiscreteSystemPlant",
    "ArrayLeafSchema",
    "ArrayPyTreeSchema",
    "ControlVectorCodec",
    "EncodedControl",
    "EncodedPlantState",
    "EncodedPlantVector",
    "ExecutableSignature",
    "NumericRevision",
    "PlantCheckpoint",
    "PlantParameters",
    "PlantPowerEvidence",
    "PlantProposal",
    "PlantReplayResult",
    "PlantResetResult",
    "PlantRuntimeState",
    "PlantStateVectorCodec",
    "PlantStepContext",
    "PlantStepResult",
    "PlantVectorRole",
    "SemanticProvenance",
    "callable_payload",
    "strict_module_payload",
    "analysis",
    "identification",
    "AffineExponentialResult",
    "affine_exponential_step",
    "CellMapEnclosure",
    "ConleyHomologyIndex",
    "compute_conley_homology_index",
    "ConleyIndexResult",
    "compute_conley_index",
    "AbstractDifferentiableEvolution",
    "AbstractEvolution",
    "AbstractInputPolicy",
    "AutonomousContinuousVectorField",
    "AutonomousDiscreteTransition",
    "AutonomousDifferentialAlgebraicResidual",
    "CallableInputPolicy",
    "HeldInputPolicy",
    "CaseAxisRole",
    "ContinuousModelVectorField",
    "ContinuousSystem",
    "DAERole",
    "DAEStructure",
    "DifferentialAlgebraicResidual",
    "DifferentialAlgebraicSystem",
    "DescriptorSystemEvidence",
    "DiscreteEvolution",
    "DiscreteModelTransition",
    "DiscreteSystem",
    "DiscreteTransitionEvidence",
    "DiscreteTransitionResult",
    "EVOLUTION_BACKEND_FAILED",
    "EVOLUTION_NONFINITE",
    "EVOLUTION_OUTSIDE_GEOMETRY",
    "EVOLUTION_SUCCESS",
    "EvolutionGrid",
    "EvolutionJacobianAction",
    "EvolutionStep",
    "EvolutionTangentStep",
    "EvolutionTrajectory",
    "InputDifferentialAlgebraicResidual",
    "InputContinuousVectorField",
    "InputDiscreteTransition",
    "InputLayout",
    "LinearDescriptorSystem",
    "InputAlignment",
    "InputRole",
    "IterationGrid",
    "SecondOrderDifferentialProblem",
    "SecondOrderDifferentialSystem",
    "SecondOrderResidual",
    "StateLayout",
    "SystemTransition",
    "SystemVectorField",
    "TimeGrid",
    "TrajectoryData",
    "TrajectoryTransitions",
    "continuous_model_system",
    "discrete_model_system",
    "evolve",
    "AcausalDAESource",
    "analyze_dae_structure",
    "compile_acausal_dae",
    "DAEComponent",
    "DAEConnection",
    "DAEDerivativeIncidence",
    "DAEEquationBlock",
    "DAEJet",
    "DAEPort",
    "DAEStructuralAnalysis",
    "DAEStructuralPolicy",
    "DAEVariableBlock",
    "ReducedDAECompilation",
    "DiscreteStepContext",
    "LearnedMarginalTransition",
    "LearnedPathwiseTransition",
    "TargetDiscreteModelObjective",
]
