#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Scientific conditions independent of soft or hard numerical treatment."""

from . import (
    cfd,
    conservation,
    electromagnetics,
    free_boundary,
    solids,
    stochastic,
    thermal,
)
from ._base import (
    AbstractCondition,
    AbstractMomentCondition,
    AbstractResidualCondition,
    ConditionSupport,
    Moment,
    Observation,
    Residual,
)
from ._evidence import (
    AffineProjectionCertificate,
    ConditionCertificate,
    ConditionEvidence,
    ConditionRealizationStamp,
    FeasibilityCertificate,
    NonlinearRetractionCertificate,
    ProbabilisticConditioningEvidence,
)
from ._functional import (
    EventLinearMap,
    linear_functional_condition,
    LinearFunctional,
    LinearReductionAction,
    MatrixLinearFunctional,
    PointJetAction,
)
from ._ir import (
    AbstractConditionOperator,
    ArrayCodomain,
    CallableConditionOperator,
    Condition,
    ConditionCodomain,
    ConditionQuantifier,
    FieldCodomain,
    FieldSpec,
    OperatorCapabilities,
    OperatorLinearization,
    ProductCodomain,
    ProductFieldSpec,
    ValueAxis,
)
from ._lowering import bind_condition, BoundCondition, lower_condition
from ._relations import (
    AbstractConditionRelation,
    Complementarity,
    ConditionRelation,
    ConeKind,
    ConeMembership,
    Equality,
    Inequality,
    NoisyObservation,
)
from ._trace import (
    AbstractJetDeclaration,
    equal,
    field_jet,
    FieldJet,
    JetDeclaration,
    LinearTraceEquation,
    LinearTraceExpression,
    point_jet,
    PointJet,
    trace_jet,
    TraceJet,
)
from .boundary import Absorbing, ConditionValue, Dirichlet, Neumann, Robin
from .initial import Initial
from .stochastic import StochasticBoundaryResidual


__all__ = [
    "AbstractCondition",
    "AbstractConditionOperator",
    "AbstractConditionRelation",
    "AbstractJetDeclaration",
    "AbstractMomentCondition",
    "AbstractResidualCondition",
    "Absorbing",
    "AffineProjectionCertificate",
    "ArrayCodomain",
    "bind_condition",
    "BoundCondition",
    "CallableConditionOperator",
    "cfd",
    "Complementarity",
    "Condition",
    "ConditionCertificate",
    "ConditionCodomain",
    "ConditionEvidence",
    "ConditionQuantifier",
    "ConditionRealizationStamp",
    "ConditionRelation",
    "ConditionSupport",
    "ConditionValue",
    "ConeKind",
    "ConeMembership",
    "conservation",
    "Dirichlet",
    "electromagnetics",
    "Equality",
    "equal",
    "FeasibilityCertificate",
    "FieldCodomain",
    "FieldJet",
    "field_jet",
    "FieldSpec",
    "free_boundary",
    "Inequality",
    "Initial",
    "JetDeclaration",
    "LinearTraceEquation",
    "LinearTraceExpression",
    "lower_condition",
    "Moment",
    "Neumann",
    "NoisyObservation",
    "NonlinearRetractionCertificate",
    "Observation",
    "OperatorCapabilities",
    "OperatorLinearization",
    "PointJet",
    "point_jet",
    "ProbabilisticConditioningEvidence",
    "ProductCodomain",
    "ProductFieldSpec",
    "Residual",
    "Robin",
    "solids",
    "StochasticBoundaryResidual",
    "stochastic",
    "thermal",
    "TraceJet",
    "trace_jet",
    "ValueAxis",
    "EventLinearMap",
    "LinearFunctional",
    "LinearReductionAction",
    "MatrixLinearFunctional",
    "PointJetAction",
    "linear_functional_condition",
]
