"""Production data, normalization, checkpoint, and rollout utilities for operators."""
from ._artifact import (
    load_external_trained_operator,
    load_operator_artifact_manifest,
    load_operator_training_state,
    load_trained_operator,
    OperatorArtifactManifest,
    OperatorArtifactTrainingState,
    save_operator_artifact,
)
from ._checkpoint import (
    load_operator_training_checkpoint,
    operator_batch_schema,
    OperatorTrainingCheckpoint,
    save_operator_training_checkpoint,
)
from ._dataset import (
    operator_dataset_from_arrays,
    operator_dataset_from_cases,
    OperatorCaseProvenance,
    OperatorDataset,
    OperatorDatasetSplit,
    OperatorSplitPolicy,
    split_operator_dataset,
)
from ._dtype import DTypeName, OperatorDTypePolicy
from ._fit import (
    fit_operator,
    OperatorFitHistory,
    OperatorFitResult,
    OperatorMixedPrecisionPolicy,
    OperatorValidationPolicy,
)
from ._linearization import linearize_operator, OperatorLinearization
from ._loader import OperatorBatchLoader, OperatorTrainingBatch
from ._losses import (
    AbstractOperatorLossTerm,
    CochainResidualInput,
    CochainResidualLoss,
    OperatorLossContext,
    OperatorLossTerm,
    SupervisedOperatorLoss,
)
from ._normalization import (
    AffineNormalizer,
    fit_operator_normalization,
    load_operator_normalization,
    OperatorNormalizationPolicy,
    save_operator_normalization,
)
from ._physics import (
    AbstractOperatorOutputTransform,
    ConservationProjection,
    HardConstraintTransform,
    operator_hilbert_inner_product,
    operator_hilbert_norm,
    operator_hilbert_relative_error,
    operator_integral,
    operator_weak_form_loss,
    OperatorOutputPipeline,
    project_operator_conservation,
    WeakOperatorLoss,
)
from ._rollout import (
    autoregressive_operator_loss,
    autoregressive_operator_rollout,
    OperatorRollout,
    RolloutHorizonSchedule,
    TeacherForcingSchedule,
)
from ._sampling import (
    AnchorQuerySamplingPolicy,
    CallbackOperatorCaseSource,
    InMemoryOperatorCaseSource,
    OperatorCase,
    OperatorCaseMetadata,
    OperatorCaseReadRequest,
    OperatorCaseSource,
    read_operator_case_batch,
    SampleSelection,
    select_function_samples,
    take_function_samples,
    take_query_targets,
)
from ._semigroup import (
    conditioned_semigroup_consistency_loss,
    ConditionedSemigroupObjective,
    SemigroupKeyMode,
    SemigroupReduction,
)
from ._streaming import (
    ArrayOperatorQuerySource,
    ArrayPredictionSink,
    CallbackOperatorQuerySource,
    decode_query_chunks,
    NpyPredictionSink,
    OperatorPredictionMetadata,
    OperatorPredictionSink,
    OperatorQueryChunk,
    OperatorQuerySchema,
    OperatorQuerySource,
)
from ._trained_operator import (
    operator_contract_fingerprint,
    operator_normalization_fingerprint,
    PreparedOperatorInput,
    TrainedOperator,
)


__all__ = [
    "OperatorArtifactManifest",
    "OperatorArtifactTrainingState",
    "AffineNormalizer",
    "AbstractOperatorLossTerm",
    "CochainResidualInput",
    "CochainResidualLoss",
    "AbstractOperatorOutputTransform",
    "ConservationProjection",
    "HardConstraintTransform",
    "operator_hilbert_inner_product",
    "operator_hilbert_norm",
    "operator_hilbert_relative_error",
    "linearize_operator",
    "OperatorLinearization",
    "operator_integral",
    "OperatorOutputPipeline",
    "operator_weak_form_loss",
    "project_operator_conservation",
    "WeakOperatorLoss",
    "DTypeName",
    "fit_operator_normalization",
    "fit_operator",
    "OperatorBatchLoader",
    "OperatorCaseProvenance",
    "OperatorDataset",
    "OperatorDatasetSplit",
    "OperatorDTypePolicy",
    "OperatorFitHistory",
    "OperatorFitResult",
    "OperatorLossContext",
    "OperatorLossTerm",
    "OperatorMixedPrecisionPolicy",
    "OperatorRollout",
    "OperatorSplitPolicy",
    "OperatorTrainingBatch",
    "OperatorTrainingCheckpoint",
    "RolloutHorizonSchedule",
    "TeacherForcingSchedule",
    "autoregressive_operator_loss",
    "autoregressive_operator_rollout",
    "conditioned_semigroup_consistency_loss",
    "ConditionedSemigroupObjective",
    "SemigroupKeyMode",
    "SemigroupReduction",
    "PreparedOperatorInput",
    "TrainedOperator",
    "load_external_trained_operator",
    "load_operator_artifact_manifest",
    "load_operator_training_state",
    "load_trained_operator",
    "operator_contract_fingerprint",
    "operator_normalization_fingerprint",
    "save_operator_artifact",
    "load_operator_normalization",
    "load_operator_training_checkpoint",
    "OperatorNormalizationPolicy",
    "save_operator_normalization",
    "OperatorValidationPolicy",
    "operator_batch_schema",
    "operator_dataset_from_arrays",
    "operator_dataset_from_cases",
    "save_operator_training_checkpoint",
    "SupervisedOperatorLoss",
    "split_operator_dataset",
    "AnchorQuerySamplingPolicy",
    "CallbackOperatorCaseSource",
    "InMemoryOperatorCaseSource",
    "OperatorCase",
    "OperatorCaseMetadata",
    "OperatorCaseReadRequest",
    "OperatorCaseSource",
    "read_operator_case_batch",
    "SampleSelection",
    "select_function_samples",
    "take_function_samples",
    "take_query_targets",
    "ArrayOperatorQuerySource",
    "ArrayPredictionSink",
    "CallbackOperatorQuerySource",
    "decode_query_chunks",
    "NpyPredictionSink",
    "OperatorPredictionMetadata",
    "OperatorPredictionSink",
    "OperatorQueryChunk",
    "OperatorQuerySchema",
    "OperatorQuerySource",
]
