#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""
# Operators

Operators build PDE terms such as gradients, divergences, Laplacians, and
integrals. They are designed to work with `DomainFunction` objects and preserve
structure across dense and coord-separable batches.

## Families

- **Differential**: $\\nabla u$, $\\nabla \\cdot v$, $\\Delta u$, surface operators.
- **Integral**: $\\int_\\Omega u \\, d\\Omega$ and weighted variants.
- **Functional**: $\\|u\\|_p$, inner products, and averages.
- **Linear algebra**: determinants, traces, norms.

!!! example
    ```python
    import phydrax as phx

    geom = phx.domain.Square(center=(0.0, 0.0), side=2.0)

    @geom.Function("x")
    def u(x):
        return x[0] ** 2 + x[1] ** 2

    lap_u = phx.operators.laplacian(u, var="x")
    ```
"""

from . import (
    delay,
    differential,
    functional,
    graph,
    linalg,
    mechanics,
    path_integral,
    quantum,
)
from ._composition import pullback

# Re-export objects from submodules
from .delay import (  # noqa: F401
    delay as delay_operator,
)
from .differential import (  # noqa: F401
    ambient_surface_hessian_trace,
    bilaplacian,
    caputo_time_fractional,
    caputo_time_fractional_dw,
    cauchy_from_pk2,
    cauchy_strain,
    cauchy_stress,
    covariant_derivative,
    covariant_hessian,
    curl,
    deformation_gradient,
    deviatoric_stress,
    diffusion_covariance,
    directional_derivative,
    directional_stratonovich_correction,
    div,
    div_cauchy_stress,
    div_diag_k_grad,
    div_K_grad,
    div_k_grad,
    div_tensor,
    dt,
    dt_n,
    estimate_kolmogorov_generator,
    estimate_stochastic_trace,
    factor_hvp_contraction,
    fokker_planck_operator,
    fractional_derivative_gl_mc,
    fractional_laplacian,
    GeneratorContraction,
    grad,
    green_lagrange_strain,
    hessian,
    hydrostatic_pressure,
    hydrostatic_stress,
    kolmogorov_generator,
    laplace_beltrami,
    laplacian,
    lie_bracket,
    linear_elastic_cauchy_stress_2d,
    linear_elastic_orthotropic_stress_2d,
    material_derivative,
    maxwell_stress,
    navier_stokes_divergence,
    navier_stokes_stress,
    neo_hookean_cauchy,
    neo_hookean_pk1,
    partial_n,
    partial_t,
    partial_x,
    partial_y,
    partial_z,
    pk1_from_pk2,
    probability_current,
    ProbeDistribution,
    riemannian_div,
    riemannian_div_tensor,
    riemannian_grad,
    riesz_fractional_derivative_gl_mc,
    StochasticInterpretation,
    StochasticOperatorEstimate,
    StochasticTracePolicy,
    strain_rate,
    strain_rate_magnitude,
    stratonovich_to_ito_drift,
    surface_curl_scalar,
    surface_curl_vector,
    surface_div,
    surface_grad,
    svk_pk2_stress,
    tangential_component,
    viscous_stress,
    von_mises_stress,
)
from .functional import (  # noqa: F401
    spatial_inner_product,
    spatial_l2_norm,
    spatial_lp_norm,
    spatial_mean,
)
from .graph import (  # noqa: F401
    cochain_codifferential,
    cochain_exterior_derivative,
    cochain_harmonic_projection,
    cochain_hodge_laplacian,
    degree as graph_degree,
    graph_advection_diffusion_residual,
    graph_conservation_residual,
    graph_diffusion_residual,
    graph_div,
    graph_divergence,
    graph_euler_residual,
    graph_grad,
    graph_gradient,
    graph_heat_residual,
    graph_incidence_laplacian,
    graph_laplacian,
    graph_poisson_residual,
    neighbor_aggregate,
)
from .integral import (  # noqa: F401
    adaptive_integral,
    AdaptiveIntegralResult,
    AdaptiveQuadratureConfig,
    AdaptiveQuadratureMethod,
    AdaptiveSubintervals,
    build_ball_quadrature,
    build_quadrature,
    integral,
    integrate_boundary,
    integrate_interior,
    local_integral,
    local_integral_ball,
    mean,
    nonlocal_integral,
    spatial_integral,
    time_convolution,
)
from .linalg import (  # noqa: F401
    adjoint,
    conjugate,
    det,
    einsum,
    imag_part,
    norm,
    real_part,
    trace,
)
from .mechanics import (  # noqa: F401
    canonical_hamiltonian_residual,
    canonical_hamiltonian_vector_field,
    canonical_momentum,
    euler_lagrange,
    hamilton_jacobi_residual,
    poisson_bracket,
)
from .path_integral import (  # noqa: F401
    brownian_bridge_from_noise,
    diffusion_paths_from_noise,
    discrete_euclidean_action,
    euclidean_kernel,
    euclidean_kernel_from_noise,
    euclidean_kernel_function,
    feynman_kac_expectation,
    feynman_kac_from_paths,
    first_exit_index,
    first_exit_time,
    free_euclidean_kernel,
    kinetic_action,
    PathDiscretization,
    PathIntegralEstimate,
    potential_action,
    sample_brownian_bridge,
    sample_diffusion_paths,
    survival_probability,
)
from .quantum import (  # noqa: F401
    anticommutator,
    commutator,
    density_expectation,
    density_fidelity,
    density_from_factor,
    embed_operator,
    HamiltonianAction,
    heisenberg_residual,
    hermiticity_residual,
    lindblad_dissipator,
    lindblad_residual,
    observable_variance,
    partial_trace,
    purity,
    quantum_bracket,
    schrodinger_residual,
    state_expectation,
    state_fidelity,
    state_norm_residual,
    tensor_product,
    trace_distance,
    unit_trace_residual,
    von_neumann_entropy,
    von_neumann_residual,
)


__all__ = [
    # subpackages
    "delay",
    "differential",
    "functional",
    "graph",
    "linalg",
    "mechanics",
    "quantum",
    "path_integral",
    # composition exports
    "pullback",
    # delay exports
    "delay_operator",
    # differential exports
    "cauchy_from_pk2",
    "cauchy_strain",
    "cauchy_stress",
    "curl",
    "deformation_gradient",
    "deviatoric_stress",
    "covariant_derivative",
    "covariant_hessian",
    "directional_derivative",
    "div",
    "div_cauchy_stress",
    "div_diag_k_grad",
    "div_K_grad",
    "div_k_grad",
    "directional_stratonovich_correction",
    "diffusion_covariance",
    "estimate_kolmogorov_generator",
    "estimate_stochastic_trace",
    "factor_hvp_contraction",
    "dt",
    "dt_n",
    "grad",
    "fokker_planck_operator",
    "GeneratorContraction",
    "hessian",
    "green_lagrange_strain",
    "hydrostatic_pressure",
    "hydrostatic_stress",
    "bilaplacian",
    "laplacian",
    "kolmogorov_generator",
    "probability_current",
    "ProbeDistribution",
    "lie_bracket",
    "fractional_laplacian",
    "linear_elastic_cauchy_stress_2d",
    "linear_elastic_orthotropic_stress_2d",
    "material_derivative",
    "maxwell_stress",
    "navier_stokes_stress",
    "neo_hookean_cauchy",
    "neo_hookean_pk1",
    "partial_t",
    "partial_n",
    "partial_x",
    "partial_y",
    "partial_z",
    "pk1_from_pk2",
    "svk_pk2_stress",
    "viscous_stress",
    "von_mises_stress",
    "strain_rate",
    "strain_rate_magnitude",
    "StochasticInterpretation",
    "StochasticOperatorEstimate",
    "StochasticTracePolicy",
    "stratonovich_to_ito_drift",
    "div_tensor",
    "navier_stokes_divergence",
    "ambient_surface_hessian_trace",
    "laplace_beltrami",
    "riemannian_div",
    "riemannian_div_tensor",
    "riemannian_grad",
    "surface_curl_scalar",
    "surface_curl_vector",
    "surface_div",
    "surface_grad",
    "tangential_component",
    "fractional_derivative_gl_mc",
    "riesz_fractional_derivative_gl_mc",
    "caputo_time_fractional",
    "caputo_time_fractional_dw",
    # integral exports
    "AdaptiveIntegralResult",
    "AdaptiveQuadratureConfig",
    "AdaptiveQuadratureMethod",
    "AdaptiveSubintervals",
    "adaptive_integral",
    "build_ball_quadrature",
    "build_quadrature",
    "integrate_boundary",
    "integrate_interior",
    "integral",
    "local_integral",
    "local_integral_ball",
    "mean",
    "nonlocal_integral",
    "spatial_integral",
    "time_convolution",
    # path-integral exports
    "PathDiscretization",
    "PathIntegralEstimate",
    "brownian_bridge_from_noise",
    "diffusion_paths_from_noise",
    "discrete_euclidean_action",
    "euclidean_kernel",
    "euclidean_kernel_function",
    "euclidean_kernel_from_noise",
    "feynman_kac_expectation",
    "feynman_kac_from_paths",
    "first_exit_index",
    "first_exit_time",
    "free_euclidean_kernel",
    "kinetic_action",
    "potential_action",
    "sample_brownian_bridge",
    "sample_diffusion_paths",
    "survival_probability",
    # functional exports
    "spatial_inner_product",
    "spatial_l2_norm",
    "spatial_lp_norm",
    "spatial_mean",
    # mechanics exports
    "canonical_hamiltonian_residual",
    "canonical_hamiltonian_vector_field",
    "canonical_momentum",
    "euler_lagrange",
    "hamilton_jacobi_residual",
    "poisson_bracket",
    # quantum exports
    "HamiltonianAction",
    "anticommutator",
    "commutator",
    "density_fidelity",
    "density_expectation",
    "density_from_factor",
    "embed_operator",
    "heisenberg_residual",
    "hermiticity_residual",
    "lindblad_dissipator",
    "lindblad_residual",
    "quantum_bracket",
    "observable_variance",
    "purity",
    "partial_trace",
    "schrodinger_residual",
    "state_expectation",
    "state_fidelity",
    "state_norm_residual",
    "tensor_product",
    "trace_distance",
    "unit_trace_residual",
    "von_neumann_residual",
    "von_neumann_entropy",
    # graph exports
    "cochain_codifferential",
    "cochain_exterior_derivative",
    "cochain_harmonic_projection",
    "cochain_hodge_laplacian",
    "graph_advection_diffusion_residual",
    "graph_conservation_residual",
    "graph_degree",
    "graph_diffusion_residual",
    "graph_div",
    "graph_divergence",
    "graph_euler_residual",
    "graph_grad",
    "graph_gradient",
    "graph_heat_residual",
    "graph_incidence_laplacian",
    "graph_laplacian",
    "graph_poisson_residual",
    "neighbor_aggregate",
    # linalg exports
    "det",
    "adjoint",
    "conjugate",
    "einsum",
    "imag_part",
    "norm",
    "real_part",
    "trace",
]
