#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""
# Operators

Operators build PDE terms such as gradients, divergences, Laplacians, and
integrals. They are designed to work with `DomainFunction` objects and preserve
structure across dense and coord-separable batches.

## Families

- **Differential**: $\\nabla u$, $\\nabla \\cdot v$, $\\Delta u$, surface operators.
- **Integral**: $\\int_\\Omega u \\, d\\Omega$ and weighted variants.
- **Interpolation**: reusable sparse polynomial `DomainFunction` surrogates.
- **Functional**: $\\|u\\|_p$, inner products, and averages.
- **Linear algebra**: determinants, traces, norms.

!!! example
    ```python
    import phydrax as phx

    geom = phx.domain.GeometryDomain(
        phx.geometry.Square(center=(0.0, 0.0), side=2.0).compile()
    )

    @geom.Function("x")
    def u(x):
        return x[0] ** 2 + x[1] ** 2

    lap_u = phx.operators.laplacian(u, var="x")
    ```
"""

import sys
from importlib import import_module
from types import ModuleType
from typing import Any

from .._model import StructuredDerivativeProvider
from . import (
    delay,
    differential,
    interpolation,
    linalg,
)
from ._composition import pullback

# Re-export objects from submodules
from .delay import (
    delay as delay_operator,
)
from .differential import (
    ambient_surface_hessian_trace,
    as_lorentzian_metric_field,
    bilaplacian,
    cauchy_from_pk2,
    cauchy_strain,
    cauchy_stress,
    clifford_dirac,
    coordinate_divergence_samples,
    coordinate_second_derivative_samples,
    covariant_derivative,
    covariant_hessian,
    curl,
    deformation_gradient,
    deviatoric_stress,
    dimension_sum_samples,
    DimensionContributionEvaluation,
    DimensionOperatorEstimate,
    DimensionOperatorSamples,
    DimensionSamplingMode,
    DimensionSamplingPolicy,
    directional_derivative,
    directional_stratonovich_correction,
    div,
    div_cauchy_stress,
    div_diag_k_grad,
    div_K_grad,
    div_k_grad,
    div_tensor,
    domain_codifferential,
    domain_differential_form,
    domain_einstein_tensor,
    domain_exterior_derivative,
    domain_hodge_laplacian,
    domain_hodge_star,
    domain_interior_product,
    domain_kahler_positivity_margin,
    domain_lie_derivative,
    domain_maxwell_residuals,
    domain_monge_ampere_residual,
    domain_pullback_form,
    domain_ricci_tensor,
    domain_riemann_tensor,
    domain_scalar_curvature,
    domain_to_twisted,
    domain_to_untwisted,
    domain_wedge,
    DomainDifferentialForm,
    DomainMaxwellResiduals,
    dt,
    dt_n,
    EquivalentStressConvention,
    estimate_dimension_sum,
    estimate_kolmogorov_generator,
    estimate_stochastic_trace,
    evaluate_taylor_contractions,
    exact_state_divergence,
    factor_hvp_contraction,
    fractional_derivative_gl_mc,
    fractional_laplacian,
    grad,
    green_lagrange_strain,
    hessian,
    horizontal_grad,
    hydrostatic_pressure,
    hydrostatic_stress,
    intrinsic_dalembertian,
    laplace_beltrami,
    laplacian,
    level_set_coarea_density,
    level_set_curvature,
    level_set_gradient_norm,
    level_set_normal,
    level_set_normal_velocity,
    level_set_phase_indicator,
    lie_bracket,
    linear_elastic_cauchy_stress_2d,
    linear_elastic_orthotropic_stress_2d,
    linear_elastic_stress,
    lorentzian_metric_from_field,
    material_derivative,
    maxwell_stress,
    navier_stokes_divergence,
    navier_stokes_stress,
    neo_hookean_cauchy,
    neo_hookean_pk1,
    neo_hookean_reference_energy,
    partial_n,
    partial_t,
    partial_x,
    partial_y,
    partial_z,
    pk1_from_pk2,
    plan_taylor_contractions,
    ProbeDistribution,
    regularized_delta,
    regularized_heaviside,
    riemannian_div,
    riemannian_div_tensor,
    riemannian_grad,
    riemannian_map_conformality_residual,
    riemannian_map_energy,
    riemannian_map_isometry_residual,
    riemannian_map_tension,
    riesz_fractional_derivative_gl_mc,
    scalar_curl_2d,
    semi_riemannian_grad,
    stochastic_bilaplacian_samples,
    stochastic_divergence_samples,
    stochastic_trace_samples,
    StochasticOperatorEstimate,
    StochasticOperatorSamples,
    StochasticTracePolicy,
    strain_rate,
    strain_rate_magnitude,
    sub_laplacian,
    surface_curl_scalar,
    surface_curl_vector,
    surface_div,
    surface_grad,
    svk_pk2_stress,
    tangential_component,
    TaylorContractionPlan,
    TaylorContractionPolicy,
    TaylorContractionRequest,
    TaylorContractionResources,
    TaylorContractionResult,
    TaylorContractionStrategy,
    vector_curl_2d,
    viscous_stress,
    von_mises_stress,
    weighted_fokker_planck_operator,
    weighted_kolmogorov_generator,
    weighted_laplacian,
    weighted_probability_current,
    weighted_riemannian_div,
    weighted_riemannian_grad,
)
from .interpolation import (
    AdaptiveSmolyakInterpolationDiagnostics,
    AdaptiveSmolyakInterpolationPlan,
    AdaptiveSmolyakInterpolationResult,
    BSplineBoundaryConstraint,
    BSplineBoundaryMode,
    BSplineFitDiagnostics,
    BSplineFitMode,
    BSplineInterpolant,
    BSplineInterpolationPlan,
    fit_bspline,
    fit_fourier_scattered,
    fit_mixed_tensor,
    fourier_type1,
    fourier_type2,
    FourierFitDiagnostics,
    FourierInterpolant,
    FourierScatteredFitPlan,
    FourierWeightPolicy,
    interpolate_adaptive_smolyak,
    interpolate_bspline,
    interpolate_mixed_tensor,
    interpolate_smolyak,
    MixedBoundsPolicy,
    MixedTensorInterpolant,
    MixedTensorReconstructionPlan,
    SmolyakInterpolant,
    SmolyakInterpolationPlan,
    SmolyakInterpolationRule,
)
from .linalg import (
    adjoint,
    conjugate,
    det,
    einsum,
    imag_part,
    norm,
    real_part,
    trace,
)


_FACADE_EXPORT_MODULES = (
    ".differential",
    ".functional",
    ".graph",
    ".integral",
    ".integral.vortex",
    ".mechanics",
    ".path_integral",
    ".quantum",
)


def __getattr__(name: str) -> Any:
    if name in {
        "functional",
        "graph",
        "mechanics",
        "path_integral",
        "periodic",
        "quantum",
    }:
        value = import_module(f".{name}", __package__)
        globals()[name] = value
        return value
    if name == "integral":
        # The public operator, not the same-named subpackage (see below).
        value = import_module(".integral", __package__).integral
        globals()[name] = value
        return value
    if name == "graph_degree":
        value = import_module(".graph", __package__).degree
        globals()[name] = value
        return value
    for module_name in reversed(_FACADE_EXPORT_MODULES):
        module = import_module(module_name, __package__)
        if name in module.__all__:
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


class _OperatorsModule(ModuleType):
    """This package with its public ``integral`` operator protected.

    ``integral`` names both a subpackage and the public integration operator.
    Loading the subpackage makes the import system bind it on this package,
    which would shadow the operator for every later attribute access. That
    convenience binding is declined; the subpackage stays importable by its
    dotted name through ``sys.modules``.
    """

    def __setattr__(self, name: str, value: object) -> None:
        if name == "integral" and isinstance(value, ModuleType):
            return
        super().__setattr__(name, value)


sys.modules[__name__].__class__ = _OperatorsModule

__all__ = [
    # subpackages
    "delay",
    "differential",
    "functional",
    "graph",
    "interpolation",
    "linalg",
    "mechanics",
    "quantum",
    "periodic",
    "path_integral",
    # composition exports
    "pullback",
    "as_lorentzian_metric_field",
    "StructuredDerivativeProvider",
    # delay exports
    "delay_operator",
    # differential exports
    "coordinate_divergence_samples",
    "coordinate_second_derivative_samples",
    "DimensionContributionEvaluation",
    "DimensionOperatorEstimate",
    "DimensionOperatorSamples",
    "DimensionSamplingMode",
    "DimensionSamplingPolicy",
    "dimension_sum_samples",
    "estimate_dimension_sum",
    "cauchy_from_pk2",
    "cauchy_strain",
    "cauchy_stress",
    "clifford_dirac",
    "curl",
    "EquivalentStressConvention",
    "deformation_gradient",
    "deviatoric_stress",
    "covariant_derivative",
    "covariant_hessian",
    "directional_derivative",
    "directional_stratonovich_correction",
    "div",
    "div_cauchy_stress",
    "div_diag_k_grad",
    "div_K_grad",
    "div_k_grad",
    "diffusion_covariance",
    "dt",
    "dt_n",
    "grad",
    "estimate_kolmogorov_generator",
    "exact_state_divergence",
    "estimate_stochastic_trace",
    "factor_hvp_contraction",
    "GeneratorContraction",
    "fokker_planck_operator",
    "hessian",
    "horizontal_grad",
    "intrinsic_dalembertian",
    "green_lagrange_strain",
    "hydrostatic_pressure",
    "hydrostatic_stress",
    "bilaplacian",
    "laplacian",
    "kolmogorov_generator",
    "lie_bracket",
    "level_set_coarea_density",
    "level_set_curvature",
    "level_set_gradient_norm",
    "level_set_normal",
    "level_set_normal_velocity",
    "level_set_phase_indicator",
    "linear_elastic_stress",
    "regularized_delta",
    "regularized_heaviside",
    "fractional_laplacian",
    "linear_elastic_cauchy_stress_2d",
    "linear_elastic_orthotropic_stress_2d",
    "material_derivative",
    "maxwell_stress",
    "navier_stokes_stress",
    "neo_hookean_cauchy",
    "neo_hookean_reference_energy",
    "neo_hookean_pk1",
    "partial_t",
    "partial_n",
    "partial_x",
    "partial_y",
    "partial_z",
    "pk1_from_pk2",
    "probability_current",
    "ProbeDistribution",
    "svk_pk2_stress",
    "scalar_curl_2d",
    "vector_curl_2d",
    "viscous_stress",
    "von_mises_stress",
    "strain_rate",
    "strain_rate_magnitude",
    "StochasticInterpretation",
    "StochasticOperatorEstimate",
    "stochastic_divergence_samples",
    "StochasticOperatorSamples",
    "stochastic_trace_samples",
    "StochasticTracePolicy",
    "stochastic_bilaplacian_samples",
    "TaylorContractionPolicy",
    "TaylorContractionRequest",
    "TaylorContractionResources",
    "TaylorContractionStrategy",
    "TaylorContractionPlan",
    "TaylorContractionResult",
    "plan_taylor_contractions",
    "evaluate_taylor_contractions",
    "stratonovich_to_ito_drift",
    "div_tensor",
    "navier_stokes_divergence",
    "ambient_surface_hessian_trace",
    "laplace_beltrami",
    "riemannian_div",
    "riemannian_div_tensor",
    "riemannian_grad",
    "riemannian_map_conformality_residual",
    "riemannian_map_energy",
    "riemannian_map_isometry_residual",
    "riemannian_map_tension",
    "domain_kahler_positivity_margin",
    "domain_monge_ampere_residual",
    "weighted_fokker_planck_operator",
    "weighted_kolmogorov_generator",
    "weighted_laplacian",
    "weighted_probability_current",
    "weighted_riemannian_div",
    "weighted_riemannian_grad",
    "semi_riemannian_grad",
    "surface_curl_scalar",
    "surface_curl_vector",
    "surface_div",
    "surface_grad",
    "sub_laplacian",
    "tangential_component",
    "fractional_derivative_gl_mc",
    "riesz_fractional_derivative_gl_mc",
    "caputo_time_fractional",
    "caputo_time_fractional_dw",
    # integral exports
    # interpolation exports
    "BSplineBoundaryConstraint",
    "BSplineBoundaryMode",
    "BSplineFitDiagnostics",
    "BSplineFitMode",
    "BSplineInterpolant",
    "BSplineInterpolationPlan",
    "fit_bspline",
    "interpolate_bspline",
    "SmolyakInterpolant",
    "SmolyakInterpolationPlan",
    "SmolyakInterpolationRule",
    "interpolate_smolyak",
    "AbstractLayerKernel",
    "BoundaryPanelization2D",
    "double_layer_principal_value_matrix",
    "evaluate_layer_potential",
    "integrate_boundary",
    "integrate_interior",
    "integral",
    "KernelActionSide",
    "LaplaceLayerKernel2D",
    "LaplaceLayerPotential2D",
    "LayerDiscretizationReport",
    "LayerEvaluationPlan2D",
    "LayerEvaluationReport",
    "LayerEvaluationResult",
    "LayerPotentialTargetReport",
    "LaplaceSingleLayerDP0AssemblyReport3D",
    "LaplaceSingleLayerDP0Galerkin3D",
    "LaplaceSingleLayerDP0GalerkinPolicy3D",
    "prepare_laplace_single_layer_dp0_3d",
    "ClosedPolygonalCurve2D",
    "CurveTraversal2D",
    "ScalarTraceConvention2D",
    "ScalarTraceSide2D",
    "BoundaryTraceRepresentation2D",
    "BoundaryTraceSpace2D",
    "ScalarBoundarySpaces2D",
    "ScalarLaplaceGalerkinPolicy2D",
    "ScalarLaplaceGalerkinReport2D",
    "ScalarLaplaceGalerkin2D",
    "ScalarLaplaceFieldEvaluation2D",
    "prepare_scalar_laplace_galerkin_2d",
    "ExteriorFarField2D",
    "PreparedExteriorLaplaceDirichlet2D",
    "ExteriorLaplaceDirichletResult2D",
    "prepare_exterior_laplace_dirichlet_2d",
    "solve_exterior_laplace_dirichlet_2d",
    "BoundaryTraceProjection2D",
    "TraceProjectionResult2D",
    "prepare_boundary_trace_projection_2d",
    "local_integral",
    "local_integral_ball",
    "mean",
    "nonlocal_integral",
    "spatial_integral",
    "time_convolution",
    "AdaptiveLayerEvaluation2D",
    "PanelInteractionReport2D",
    "classify_panel_interactions_2d",
    "BoundaryCornerTopology2D",
    "BoundaryPanelPartition2D",
    # path-integral exports
    "HelmholtzCombinedField2D",
    "HelmholtzLayerKernel2D",
    "HelmholtzLayerPotential2D",
    "LaplaceLayerKernel3D",
    "LaplaceLayerPotential3D",
    "SurfacePanelization3D",
    "SurfaceTargetReport3D",
    "evaluate_laplace_layer_3d",
    "evaluate_single_layer_self_triangle_3d",
    "evaluate_double_layer_self_triangle_3d",
    "QBXEvaluation3D",
    "evaluate_qbx_3d",
    "DirectNearFarReferenceBackend2D",
    "AbstractLayerBackend",
    "LayerBackendEvaluation2D",
    "HelmholtzCombinedField3D",
    "HelmholtzLayerKernel3D",
    "HelmholtzLayerPotential3D",
    "BoundaryOperatorAssemblyReport",
    "QBXEvaluation2D",
    "evaluate_qbx_2d",
    "RCIPPreconditioner2D",
    "LaplaceTreecodeBackend2D",
    "LaplaceTreecodeEvaluation2D",
    "LaplaceFMMBackend2D",
    "LaplaceFMMEvaluation2D",
    "AbstractIncrementalLatticeAction",
    "AbstractLatticeEuclideanAction",
    "CompactU1GaugeMeasure",
    "LatticeObservablePlan",
    "LocalPhi4LatticeAction",
    "Phi4LatticeAction",
    "WilsonGaugeAction",
    "PathIntegralEstimate",
    "brownian_bridge_from_noise",
    "diffusion_paths_from_noise",
    "discrete_euclidean_action",
    "GlobalQBXFMMEvaluation2D",
    "evaluate_global_qbx_fmm_2d",
    "compact_geometric_target_from_lattice_action",
    "euclidean_kernel",
    "euclidean_kernel_function",
    "euclidean_kernel_from_noise",
    "evaluate_lattice_observable",
    "feynman_kac_expectation",
    "feynman_kac_from_paths",
    "first_exit_index",
    "first_exit_time",
    "free_euclidean_kernel",
    "full_target_from_lattice_action",
    "incremental_target_from_lattice_action",
    "kinetic_action",
    "potential_action",
    "prepare_local_phi4_action",
    "sample_brownian_bridge",
    "sample_diffusion_paths",
    "survival_probability",
    # functional exports
    "spatial_inner_product",
    "spatial_l2_norm",
    "spatial_lp_norm",
    "spatial_mean",
    # differential-form exports
    "DomainDifferentialForm",
    "DomainMaxwellResiduals",
    "domain_einstein_tensor",
    "domain_codifferential",
    "domain_differential_form",
    "domain_exterior_derivative",
    "domain_hodge_laplacian",
    "domain_hodge_star",
    "domain_interior_product",
    "domain_lie_derivative",
    "domain_pullback_form",
    "domain_to_twisted",
    "domain_to_untwisted",
    "domain_wedge",
    "domain_ricci_tensor",
    "domain_maxwell_residuals",
    "domain_riemann_tensor",
    "domain_scalar_curvature",
    "lorentzian_metric_from_field",
    # mechanics exports
    "FiniteStrainKinematics",
    "HyperelasticLaw",
    "HyperelasticResponse",
    "NansonResponse",
    "NeoHookeanLaw",
    "LinearElasticityTensor",
    "NeoHookeanParameters",
    "VolumetricConstraint",
    "VolumetricConstraintKind",
    "canonical_hamiltonian_residual",
    "canonical_hamiltonian_vector_field",
    "canonical_momentum",
    "canonical_poisson_bracket",
    "cauchy_to_first_piola",
    "euler_lagrange",
    "finite_strain_kinematics",
    "first_piola_to_cauchy",
    "hamilton_jacobi_residual",
    "hamiltonian_vector_field",
    "inverse_nanson_transform",
    "logarithmic_volumetric_constraint",
    "nanson_response",
    "nanson_transform",
    "neo_hookean_first_piola",
    "neo_hookean_response",
    "neo_hookean_tangent",
    "plane_strain_embedding",
    "poisson_bracket",
    "volumetric_constraint",
    # quantum exports
    "AbstractLocalQuantumOperator",
    "AbstractDiscreteQuantumOperator",
    "AmplitudeRatio",
    "amplitude_ratio",
    "BasisStateSubspace",
    "CoherentPauliExpansion",
    "DenseQuantumSubspace",
    "GateQualityDiagnostics",
    "GateQualityResult",
    "ModeReductionCostEstimate",
    "ModeReductionDiagnostics",
    "ModeReductionPlan",
    "ModeReductionPolicy",
    "ModeReductionProblem",
    "ModeResolutionPolicy",
    "ModeResolutionReport",
    "NamedModeOperator",
    "PreparedModeReduction",
    "QuantumSubspace",
    "QuantumSubspaceEvidence",
    "basis_state_subspace",
    "coherent_pauli_expansion",
    "finite_channel_gate_quality",
    "plan_mode_reduction",
    "prepare_mode_reduction",
    "project_quantum_operator",
    "refresh_mode_reduction",
    "restrict_quantum_subspace",
    "unitary_gate_quality",
    "HamiltonianAction",
    "anticommutator",
    "CallableDiscreteQuantumOperator",
    "ComplexParameterMode",
    "ConnectedConfigurations",
    "commutator",
    "density_fidelity",
    "density_expectation",
    "density_from_factor",
    "ElectronicCoulombHamiltonian",
    "ElectronicKineticPolicy",
    "ElectronicTraceMethod",
    "electronic_initial_walkers",
    "evaluate_local_operator",
    "embed_operator",
    "FiniteSignedPermutationSymmetry",
    "heisenberg_residual",
    "hermiticity_residual",
    "lindblad_dissipator",
    "lindblad_residual",
    "harmonic_mean_electron_proposal",
    "LocalOperatorEstimate",
    "LocalOperatorStatus",
    "LogAmplitude",
    "quantum_bracket",
    "observable_variance",
    "purity",
    "partial_trace",
    "schrodinger_residual",
    "sampling_log_weight",
    "state_expectation",
    "state_fidelity",
    "state_norm_residual",
    "SymmetryProjectedAmplitude",
    "tensor_product",
    "trace_distance",
    "unit_trace_residual",
    "von_neumann_residual",
    "von_neumann_entropy",
    # graph exports
    "cochain_codifferential",
    "cochain_exterior_derivative",
    "cochain_harmonic_projection",
    "cochain_hodge_laplacian",
    "graph_advection_diffusion_residual",
    "graph_conservation_residual",
    "graph_degree",
    "graph_diffusion_residual",
    "graph_div",
    "graph_divergence",
    "graph_euler_residual",
    "graph_grad",
    "graph_gradient",
    "graph_heat_residual",
    "graph_incidence_laplacian",
    "graph_laplacian",
    "graph_poisson_residual",
    "neighbor_aggregate",
    # linalg exports
    "det",
    "adjoint",
    "conjugate",
    "einsum",
    "imag_part",
    "norm",
    "real_part",
    "trace",
    "ClosedScalarCalderon3D",
    "DiffraxCollocationIntegralOperator",
    "DisplacementDiscontinuityEvidence3D",
    "DisplacementDiscontinuitySpace3D",
    "ModifiedHelmholtzLayerPotential3D",
    "PeriodicFreeSurfaceGreen3D",
    "PeriodicFreeSurfaceGreenEvidence3D",
    "PeriodicMaxwellBoundaryEvidence3D",
    "PeriodicMaxwellBoundaryPolicy3D",
    "prepare_closed_scalar_calderon_3d",
    "prepare_displacement_discontinuity_3d",
    "prepare_modified_helmholtz_reconstruction_3d",
    "prepare_periodic_free_surface_green_3d",
    "prepare_periodic_maxwell_boundary_3d",
    "prepare_scalar_calderon_3d",
    "prepare_scalar_fmm_provider_3d",
    "prepare_scalar_h_matrix_provider_3d",
    "prepare_scalar_h2_matrix_provider_3d",
    "prepare_scalar_hypersingular_p1_3d",
    "PreparedDisplacementDiscontinuity3D",
    "PreparedPeriodicMaxwellBoundary3D",
    "PreparedScalarFastProvider3D",
    "ScalarBoundarySpaces3D",
    "ScalarCalderonGalerkin3D",
    "ScalarConformingAssemblyEvidence3D",
    "ScalarFastAlgorithm3D",
    "ScalarFastEvidence3D",
    "ScalarFastPolicy3D",
    "AdaptiveSmolyakInterpolationDiagnostics",
    "AdaptiveSmolyakInterpolationPlan",
    "AdaptiveSmolyakInterpolationResult",
    "fit_fourier_scattered",
    "fit_mixed_tensor",
    "FourierFitDiagnostics",
    "FourierInterpolant",
    "FourierScatteredFitPlan",
    "FourierWeightPolicy",
    "fourier_type1",
    "fourier_type2",
    "interpolate_adaptive_smolyak",
    "interpolate_mixed_tensor",
    "MixedBoundsPolicy",
    "MixedTensorInterpolant",
    "MixedTensorReconstructionPlan",
    "apply_finite_cptp",
    "compose_finite_cptp",
    "ElectronicConnections",
    "ElectronicIntegralHamiltonian",
    "ElectronicVMCResourcePlan",
    "factor_finite_cptp",
    "finite_cptp_from_choi",
    "finite_cptp_from_kraus",
    "finite_cptp_from_local_kraus_operation",
    "finite_cptp_from_prepared_local_kraus_channel",
    "finite_cptp_from_superoperator",
    "finite_cptp_from_unitary",
    "finite_cptp_to_local_kraus_operation",
    "FiniteChannelFactorizationPolicy",
    "FiniteChannelPhysicalityEvidence",
    "FiniteCPTPMap",
    "FiniteKrausFactorization",
    "periodic_coulomb_energy",
    "PeriodicElectronicEvidence",
    "StochasticElectronicKineticPolicy",
    "StochasticKineticEstimate",
    "tensor_finite_cptp",
    "layer_potential",
    "FixedClusterDiagnostics2D",
    "FixedClusterVortexPlan2D",
    "DirectVortexResourceEvidence",
    "DirectVortexResourceEvidence3D",
    "FilamentVelocityDiagnostics",
    "FilamentVelocityEvaluation",
    "FlowPanelGeometry2D",
    "GaussianDirectDiagnostics2D",
    "GaussianDirectVortexPlan2D",
    "GaussianErfDirectVortexPlan3D",
    "GaussianErfKernelEvaluation3D",
    "GaussianErfVortexKernel3D",
    "GaussianParticleStrengthExchangePlan",
    "GaussianVortexKernelEvaluation2D",
    "ParticleStrengthExchangeEvidence",
    "PeriodicVortexInCellDiagnostics",
    "PeriodicVortexInCellPlan",
    "PreparedFilamentVelocity3D",
    "PreparedGaussianDirectVortex2D",
    "PreparedGaussianErfDirectVortex3D",
    "PreparedGaussianParticleStrengthExchange",
    "PreparedPeriodicVortexInCell",
    "RosenheadVortexKernel2D",
    "RosenheadVortexKernel3D",
    "RigidPanelMotion2D",
    "SingularVortexKernel2D",
    "SingularVortexKernel3D",
    "VortexCoreEvaluation",
    "constant_panel_velocity_2d",
    "gaussian_vortex_kernel_2d",
    "gaussian_vortex_velocity_2d",
    "gaussian_vortex_velocity_gradient_2d",
    "gaussian_vortex_vorticity_2d",
    "panel_influence_matrix_2d",
    "regularized_filament_velocity_3d",
]
