import phydrax as phx


def test_special_namespace_is_public():
    expected = [
        "airy",
        "airye",
        "dawsn",
        "ellipam",
        "ellipe",
        "ellipeinc",
        "ellipj",
        "ellipk",
        "ellipkinc",
        "ellipkm1",
        "ellippi",
        "ellippiinc",
        "elliprc",
        "elliprd",
        "elliprf",
        "elliprg",
        "elliprj",
        "hankel1",
        "hankel2",
        "iv",
        "iv_order_derivative",
        "ive",
        "ive_order_derivative",
        "jv",
        "jv_order_derivative",
        "kv",
        "kv_order_derivative",
        "kve",
        "kve_order_derivative",
        "normal_cdf",
        "normal_logcdf",
        "normal_logpdf",
        "normal_logsurvival",
        "normal_pdf",
        "normal_quantile",
        "normal_survival",
        "principal_log",
        "principal_sqrt",
        "sph_harm_y",
        "sph_harm_y_cart",
        "sph_legendre_p",
        "voigt_profile",
        "wofz",
        "yv",
        "yv_order_derivative",
    ]

    assert "special" in phx.__all__
    assert phx.special.__all__ == expected
    assert all(callable(getattr(phx.special, name)) for name in expected)
