#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Physically typed reduced-model preparation, execution, and evidence."""

from ._affine import (
    AbstractAffineCoefficientMap,
    AffineCoefficientEvaluation,
    AffineCoefficientStatus,
    AffineLinearROMEvaluation,
    AffineLinearROMPlan,
    AffineLinearROMProblem,
    AffineLinearROMStatus,
    ArrayAffineCoefficientMap,
    NamedROMObservation,
    prepare_affine_linear_rom,
    PreparedAffineLinearROM,
    PreparedAffineObservation,
)
from ._archive import (
    read_affine_linear_rom,
    read_empirical_interpolation_artifact,
    read_reduced_basis_artifact,
    write_affine_linear_rom,
    write_empirical_interpolation_artifact,
    write_reduced_basis_artifact,
)
from ._basis import BasisRole, reduced_basis_from_subspace_model, ReducedBasisArtifact
from ._certification import (
    AbstractStabilityBoundEvaluator,
    AffineROMCertification,
    ArrayAffineStabilityBound,
    CertificationStatus,
    CertifiedAffineROMEvaluation,
    certify_affine_rom_evaluation,
    prepare_residual_dual_norm,
    ResidualDualNormArtifact,
    StabilityBoundEvaluation,
)
from ._empirical_interpolation import (
    EmpiricalInterpolationArtifact,
    EmpiricalInterpolationPlan,
    prepare_empirical_interpolation,
    PreparedEmpiricalInterpolation,
)
from ._evaluation import AffineLinearROMAudit, audit_affine_linear_rom
from ._fidelity import AffineLinearROMFidelityEvaluator
from ._identified import IdentifiedReducedDynamics, project_trajectory_data
from ._nonlinear import (
    AbstractElementResidualProvider,
    AbstractResidualProvider,
    AbstractSampledNonlinearProvider,
    AbstractSampledStageResidualProvider,
    AbstractStageResidualProvider,
    DEIMArtifact,
    ECSWArtifact,
    ECSWPlan,
    evaluate_ecsw,
    FullResidualGalerkin,
    GNATArtifact,
    GNATLSPGProblem,
    LSPGStepContext,
    prepare_deim,
    prepare_ecsw,
    prepare_gnat,
    ReducedLSPGProblem,
)
from ._reduction import trial_test_reduction_from_bases, TrialTestReduction


__all__ = [
    "AbstractElementResidualProvider",
    "AbstractResidualProvider",
    "AbstractSampledNonlinearProvider",
    "AbstractSampledStageResidualProvider",
    "AbstractStageResidualProvider",
    "DEIMArtifact",
    "ECSWArtifact",
    "ECSWPlan",
    "FullResidualGalerkin",
    "GNATArtifact",
    "GNATLSPGProblem",
    "LSPGStepContext",
    "ReducedLSPGProblem",
    "evaluate_ecsw",
    "prepare_deim",
    "prepare_ecsw",
    "prepare_gnat",
    "AbstractStabilityBoundEvaluator",
    "AffineROMCertification",
    "ArrayAffineStabilityBound",
    "CertificationStatus",
    "CertifiedAffineROMEvaluation",
    "ResidualDualNormArtifact",
    "StabilityBoundEvaluation",
    "certify_affine_rom_evaluation",
    "prepare_residual_dual_norm",
    "AbstractAffineCoefficientMap",
    "AffineCoefficientEvaluation",
    "AffineCoefficientStatus",
    "AffineLinearROMAudit",
    "AffineLinearROMEvaluation",
    "AffineLinearROMFidelityEvaluator",
    "AffineLinearROMPlan",
    "AffineLinearROMProblem",
    "AffineLinearROMStatus",
    "ArrayAffineCoefficientMap",
    "BasisRole",
    "EmpiricalInterpolationArtifact",
    "EmpiricalInterpolationPlan",
    "IdentifiedReducedDynamics",
    "NamedROMObservation",
    "PreparedAffineLinearROM",
    "PreparedAffineObservation",
    "PreparedEmpiricalInterpolation",
    "ReducedBasisArtifact",
    "TrialTestReduction",
    "audit_affine_linear_rom",
    "prepare_affine_linear_rom",
    "project_trajectory_data",
    "prepare_empirical_interpolation",
    "read_affine_linear_rom",
    "read_empirical_interpolation_artifact",
    "read_reduced_basis_artifact",
    "reduced_basis_from_subspace_model",
    "trial_test_reduction_from_bases",
    "write_affine_linear_rom",
    "write_empirical_interpolation_artifact",
    "write_reduced_basis_artifact",
]
