#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Free-boundary PINN, operator, probabilistic, and benchmark workflows."""

from ._benchmarks import (
    ExactStefanBenchmark,
    ExactStefanFields,
    FreeBoundaryDatasetSplit,
    FSIReport,
    hysing_bubble_benchmark,
    HysingBubbleReport,
    mullins_sekerka_benchmark,
    MullinsSekerkaReport,
    obstacle_complementarity_benchmark,
    ObstacleComplementarityReport,
    phase_field_fracture_benchmark,
    PhaseFieldFractureReport,
    topology_event_benchmark,
    TopologyEventReport,
    trajectory_disjoint_ood_split,
    turek_hron_fsi_benchmark,
)
from ._probabilistic import (
    fit_probabilistic_level_set_stefan,
    ParticlePhase,
    probabilistic_stefan_moment_loss,
    ProbabilisticLevelSetStefan,
    ProbabilisticStefanBatch,
    ProbabilisticStefanFitResult,
    ProbabilisticStefanLoss,
    ProbabilisticStefanParameters,
    relaxed_first_passage_weights,
    RelaxedStoppingResult,
)
from ._stefan import (
    compare_stefan_representations,
    explicit_front_stefan_loss,
    ExplicitFrontStefanPINN,
    fit_stefan_pinn,
    fit_stefan_time_slabs,
    implicit_level_set_stefan_loss,
    ImplicitLevelSetStefanPINN,
    OnePhaseStefanParameters,
    reference_map_stefan_loss,
    ReferenceMapStefanPINN,
    stefan_collocation_batch,
    StefanBoundaryData,
    StefanCollocationBatch,
    StefanFitResult,
    StefanLoss,
    StefanRepresentation,
    StefanRepresentationComparison,
)


__all__ = [
    "ExactStefanBenchmark",
    "ExactStefanFields",
    "FSIReport",
    "FreeBoundaryDatasetSplit",
    "HysingBubbleReport",
    "MullinsSekerkaReport",
    "ObstacleComplementarityReport",
    "PhaseFieldFractureReport",
    "TopologyEventReport",
    "hysing_bubble_benchmark",
    "mullins_sekerka_benchmark",
    "obstacle_complementarity_benchmark",
    "phase_field_fracture_benchmark",
    "topology_event_benchmark",
    "trajectory_disjoint_ood_split",
    "turek_hron_fsi_benchmark",
    "ParticlePhase",
    "ProbabilisticLevelSetStefan",
    "ProbabilisticStefanBatch",
    "ProbabilisticStefanFitResult",
    "ProbabilisticStefanLoss",
    "ProbabilisticStefanParameters",
    "RelaxedStoppingResult",
    "fit_probabilistic_level_set_stefan",
    "probabilistic_stefan_moment_loss",
    "relaxed_first_passage_weights",
    "ExplicitFrontStefanPINN",
    "ImplicitLevelSetStefanPINN",
    "OnePhaseStefanParameters",
    "ReferenceMapStefanPINN",
    "StefanBoundaryData",
    "StefanCollocationBatch",
    "StefanFitResult",
    "StefanLoss",
    "StefanRepresentation",
    "StefanRepresentationComparison",
    "compare_stefan_representations",
    "explicit_front_stefan_loss",
    "fit_stefan_pinn",
    "fit_stefan_time_slabs",
    "implicit_level_set_stefan_loss",
    "reference_map_stefan_loss",
    "stefan_collocation_batch",
]
