#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Exact bounded finite-spin magnetic-resonance experiments."""

from ._conventions import (
    angular_rate_to_hz,
    chemical_shift_angular_rate,
    HBAR_J_S,
    hz_to_angular_rate,
    MagneticResonanceConvention,
    MagneticResonanceResourcePolicy,
    MU0_OVER_4PI_N_A2,
    TWO_PI,
)
from ._experiment import (
    acquire_fid,
    AcquisitionPlan,
    apply_instrument,
    evolve_density_exact,
    ExactDensityEvolutionResult,
    ExactEvolutionEvidence,
    fid_spectrum,
    FIDResult,
    FixedPulseSequence,
    InstrumentPlan,
    InstrumentResult,
    prepare_pulse_sequence,
    PreparedPulseSequence,
    receiver_operator,
    SpectrumResult,
)
from ._orientation import SingleCrystalOrientation
from ._profiles import (
    ExactSingleCrystalEPRProfile,
    ExactSingleCrystalNMRProfile,
    ExactStaticSiteMuonSpinRotationProfile,
)
from ._qualification import (
    magnetic_resonance_candidate_campaigns,
    magnetic_resonance_candidate_profiles,
    magnetic_resonance_support_tuples,
)
from ._spin_system import (
    CARBON_13,
    DipolarCoupling,
    ELECTRON,
    HYDROGEN_1,
    HyperfineCoupling,
    MagneticResonanceSpinSystem,
    NITROGEN_14,
    ParticleKind,
    POSITIVE_MUON,
    prepare_spin_system,
    PreparedMagneticResonanceSystem,
    QuadrupolarInteraction,
    ResonanceIsotope,
    ScalarJCoupling,
    spin_operators,
    SpinAssemblyEvidence,
    SpinInteraction,
    SpinOperators,
    SpinSite,
)


__all__ = [
    "CARBON_13",
    "ELECTRON",
    "HBAR_J_S",
    "HYDROGEN_1",
    "MU0_OVER_4PI_N_A2",
    "NITROGEN_14",
    "POSITIVE_MUON",
    "TWO_PI",
    "AcquisitionPlan",
    "DipolarCoupling",
    "ExactDensityEvolutionResult",
    "ExactEvolutionEvidence",
    "ExactSingleCrystalEPRProfile",
    "ExactSingleCrystalNMRProfile",
    "ExactStaticSiteMuonSpinRotationProfile",
    "FIDResult",
    "FixedPulseSequence",
    "HyperfineCoupling",
    "InstrumentPlan",
    "InstrumentResult",
    "MagneticResonanceConvention",
    "magnetic_resonance_candidate_campaigns",
    "magnetic_resonance_candidate_profiles",
    "magnetic_resonance_support_tuples",
    "MagneticResonanceResourcePolicy",
    "MagneticResonanceSpinSystem",
    "ParticleKind",
    "PreparedMagneticResonanceSystem",
    "PreparedPulseSequence",
    "QuadrupolarInteraction",
    "ResonanceIsotope",
    "ScalarJCoupling",
    "SingleCrystalOrientation",
    "SpectrumResult",
    "SpinAssemblyEvidence",
    "SpinInteraction",
    "SpinOperators",
    "SpinSite",
    "acquire_fid",
    "angular_rate_to_hz",
    "apply_instrument",
    "chemical_shift_angular_rate",
    "evolve_density_exact",
    "fid_spectrum",
    "hz_to_angular_rate",
    "prepare_pulse_sequence",
    "prepare_spin_system",
    "receiver_operator",
    "spin_operators",
]
