"""Scientific image supports, camera models, and audited medical preparation."""

from . import camera
from ._asset import ImageAsset, ImageFieldSpec
from ._core import (
    DeidentificationEvidence,
    DiffusionTensorImage,
    HostMetadataValue,
    ImageAxisConvention,
    ImageIndexAffine,
    LabelDefinition,
    LabelOntology,
    LabelVolume,
    MedicalImageAsset,
    MedicalImageSupport,
    VoxelReference,
)
from ._nibabel import NibabelImageProvider
from ._plane import ImagePlaneSupport
from ._providers import (
    ANTsRegistrationProvider,
    Dcm2NiixProvider,
    FastSurferProvider,
    FreeSurferProvider,
    GreedyRegistrationProvider,
    MedicalToolProvider,
    MedicalToolResult,
    SynthSegProvider,
)
from ._registration import (
    PreparedRegistrationEvaluation,
    RegistrationCandidate,
    RegistrationCheckpoint,
    RegistrationDirection,
    RegistrationEvaluationPlan,
    RegistrationEvidence,
)
from ._sampling import backward_warp, bilinear_sample, image_coordinates, ImageSample2D
from ._segmentation import (
    build_compartment_complex,
    CompartmentSurface,
    CompartmentSurfaceResult,
    extract_compartment_surfaces,
    SegmentationOperation,
    SegmentationOperationKind,
    SegmentationOperationReport,
    SegmentationProcessingPlan,
    SegmentationTransition,
)
from ._transfer import (
    ConservativeVoxelCellTransfer,
    CoveragePolicy,
    ImageToP1ProjectionPlan,
    ImageTransferResult,
    LabelImageTransferPlan,
    PreparedImageToP1Projection,
    ProbabilityImageTransferPlan,
    TensorImageTransferPlan,
    TensorInterpolationPolicy,
    TransferEvidence,
)
from .schlieren import (
    BackgroundOrientedSchlierenPlan,
    GladstoneDaleRelation,
    KnifeEdgeSchlierenPlan,
    SchlierenDeflectionPlan,
    SchlierenDeflectionResult,
    SchlierenImageFormationResult,
    SchlierenImagePair,
    SchlierenMethod,
)


__all__ = [
    "ANTsRegistrationProvider",
    "camera",
    "backward_warp",
    "BackgroundOrientedSchlierenPlan",
    "bilinear_sample",
    "build_compartment_complex",
    "CompartmentSurface",
    "CompartmentSurfaceResult",
    "ConservativeVoxelCellTransfer",
    "Dcm2NiixProvider",
    "CoveragePolicy",
    "DeidentificationEvidence",
    "DiffusionTensorImage",
    "HostMetadataValue",
    "ImageToP1ProjectionPlan",
    "ImageTransferResult",
    "LabelImageTransferPlan",
    "FastSurferProvider",
    "FreeSurferProvider",
    "GladstoneDaleRelation",
    "GreedyRegistrationProvider",
    "ImageAsset",
    "ImageFieldSpec",
    "ImageAxisConvention",
    "image_coordinates",
    "ImageSample2D",
    "ImageIndexAffine",
    "ImagePlaneSupport",
    "KnifeEdgeSchlierenPlan",
    "LabelDefinition",
    "LabelOntology",
    "LabelVolume",
    "extract_compartment_surfaces",
    "MedicalImageAsset",
    "MedicalImageSupport",
    "MedicalToolProvider",
    "MedicalToolResult",
    "NibabelImageProvider",
    "ProbabilityImageTransferPlan",
    "PreparedRegistrationEvaluation",
    "RegistrationCandidate",
    "RegistrationCheckpoint",
    "RegistrationDirection",
    "RegistrationEvaluationPlan",
    "RegistrationEvidence",
    "PreparedImageToP1Projection",
    "TensorImageTransferPlan",
    "SchlierenDeflectionPlan",
    "SchlierenDeflectionResult",
    "SchlierenImageFormationResult",
    "SchlierenImagePair",
    "SchlierenMethod",
    "TensorInterpolationPolicy",
    "TransferEvidence",
    "SegmentationOperation",
    "SegmentationOperationKind",
    "SegmentationOperationReport",
    "SegmentationProcessingPlan",
    "SegmentationTransition",
    "SynthSegProvider",
    "VoxelReference",
]
