"""Typed bounded semantics shared by HEP production applications."""

from . import statistics
from ._associations import AssociationTable
from ._capabilities import HEPProviderBinding
from ._events import (
    ParticleEventBatch,
    ParticleEventPlan,
    ParticleEventStatus,
    PreparedParticleEvents,
)
from ._host_events import (
    EventPackingReport,
    EventPackingStatus,
    HostAttribute,
    HostEventPackingResult,
    HostEventRecord,
    HostEventWeight,
    HostParticleRecord,
    HostVertexRecord,
    pack_host_events,
    unpack_particle_events,
)
from ._identity import (
    ParticleCatalogReference,
    ParticleRole,
    ReproducibilityGrade,
)
from ._native_spectrum import (
    assess_native_vacuum_stability,
    compute_native_mssm_pole_masses,
    cross_qualify_spectra,
    ElectroweakSymmetryBreakingEvidence,
    integrate_native_rge,
    native_beta_function,
    NativePoleMassEvidence,
    NativeRGEHistory,
    NativeSpectrumBVPPlan,
    NativeSpectrumBVPRoots,
    NativeSpectrumModel,
    NativeSpectrumModelPlan,
    NativeSpectrumStatus,
    propagate_spectrum_uncertainty,
    scan_native_spectrum,
    solve_mssm_electroweak_breaking,
    solve_native_spectrum_bvp,
    SpectrumCalculatorAdapter,
    SpectrumCrossQualificationEvidence,
    SpectrumScanResult,
    SpectrumThreshold,
    SpectrumUncertaintyEvidence,
    VacuumStabilityEvidence,
)
from ._operations import (
    BeamConditionSnapshot,
    HEPRunContext,
    merge_process_normalizations,
    ProcessNormalization,
)
from ._qualification import (
    build_hep_qualification_bundle,
    HEP_RELEASE_GATES,
    HEPQualificationBundle,
)
from ._scale_bvp import (
    evaluate_scale_bvp,
    ScaleBVPEvaluation,
    ScaleBVPPlan,
    ScaleBVPResult,
    ScaleBVPStatus,
    solve_scale_bvp,
)
from ._species import lookup_particle_species, ParticleSpeciesLookup, ParticleSpeciesTable
from ._spectrum import (
    SpectrumApproximationProfile,
    SpectrumCalculationResult,
    SpectrumDiagnostics,
    SpectrumObservableTable,
    SpectrumStatus,
)
from ._spectrum_provider import (
    execute_spectrum_provider,
    ExternalSpectrumProvider,
    spectrum_result_from_provider,
    SpectrumProviderExecution,
    SpectrumProviderPlan,
    SpectrumProviderStatus,
)
from ._spectrum_qualification import (
    particle_spectrum_candidate_profiles,
    particle_spectrum_candidate_support_tuples,
)
from ._systematics import SystematicConfiguration, SystematicKind, SystematicSource
from ._weights import (
    CrossSectionLedger,
    EventAccountingStatus,
    EventWeightSet,
    summarize_event_weights,
    WeightVariationKind,
)


__all__ = [
    "AssociationTable",
    "BeamConditionSnapshot",
    "CrossSectionLedger",
    "EventAccountingStatus",
    "EventWeightSet",
    "EventPackingReport",
    "ElectroweakSymmetryBreakingEvidence",
    "EventPackingStatus",
    "ExternalSpectrumProvider",
    "HEPProviderBinding",
    "HEPRunContext",
    "HEPQualificationBundle",
    "HEP_RELEASE_GATES",
    "HostAttribute",
    "HostEventPackingResult",
    "HostEventRecord",
    "HostEventWeight",
    "HostParticleRecord",
    "HostVertexRecord",
    "NativePoleMassEvidence",
    "NativeRGEHistory",
    "NativeSpectrumBVPPlan",
    "NativeSpectrumBVPRoots",
    "NativeSpectrumModel",
    "NativeSpectrumModelPlan",
    "NativeSpectrumStatus",
    "ParticleCatalogReference",
    "ParticleEventBatch",
    "ParticleEventPlan",
    "ParticleEventStatus",
    "ParticleRole",
    "ParticleSpeciesLookup",
    "ParticleSpeciesTable",
    "ProcessNormalization",
    "PreparedParticleEvents",
    "particle_spectrum_candidate_profiles",
    "particle_spectrum_candidate_support_tuples",
    "ReproducibilityGrade",
    "ScaleBVPEvaluation",
    "ScaleBVPPlan",
    "ScaleBVPResult",
    "ScaleBVPStatus",
    "SpectrumCalculatorAdapter",
    "SpectrumCrossQualificationEvidence",
    "SpectrumScanResult",
    "SpectrumThreshold",
    "SpectrumUncertaintyEvidence",
    "SpectrumApproximationProfile",
    "SpectrumCalculationResult",
    "SpectrumDiagnostics",
    "SpectrumObservableTable",
    "SpectrumProviderExecution",
    "SpectrumProviderPlan",
    "SpectrumProviderStatus",
    "SpectrumStatus",
    "WeightVariationKind",
    "SystematicConfiguration",
    "statistics",
    "SystematicKind",
    "SystematicSource",
    "VacuumStabilityEvidence",
    "assess_native_vacuum_stability",
    "compute_native_mssm_pole_masses",
    "cross_qualify_spectra",
    "lookup_particle_species",
    "evaluate_scale_bvp",
    "integrate_native_rge",
    "native_beta_function",
    "propagate_spectrum_uncertainty",
    "scan_native_spectrum",
    "execute_spectrum_provider",
    "build_hep_qualification_bundle",
    "pack_host_events",
    "summarize_event_weights",
    "merge_process_normalizations",
    "solve_scale_bvp",
    "solve_mssm_electroweak_breaking",
    "solve_native_spectrum_bvp",
    "spectrum_result_from_provider",
    "unpack_particle_events",
]
