#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Financial risk measures, attribution, stress, and backtesting."""

from ._attribution import (
    AttributionResult,
    brinson_attribution,
    explain_pnl,
    PnLExplanation,
    stress_test,
    StressTestResult,
)
from ._backtest import (
    BacktestDecisions,
    evaluate_nested_backtest,
    evaluate_walk_forward,
    nested_backtest_splits,
    NestedBacktestDecisions,
    NestedBacktestPlan,
    NestedBacktestResult,
    NestedBacktestSplits,
    validate_no_lookahead,
    walk_forward_splits,
    WalkForwardPlan,
    WalkForwardResult,
    WalkForwardSplit,
)
from ._market import (
    explain_factor_pnl,
    FactorPnL,
    FactorRiskModel,
    market_factor_risk,
    MarketRiskReport,
)
from ._measures import (
    cvar_atoms,
    CVaRAtoms,
    drawdown_risk,
    DrawdownRisk,
    entropic_value_at_risk,
    EntropicRiskEstimate,
    expected_shortfall,
    gaussian_var_es,
    historical_var_es,
    kelly_risk,
    KellyRisk,
    spectral_risk,
    TailRiskEstimate,
    value_at_risk,
)
from ._scenarios import (
    entropy_tilt_scenarios,
    evaluate_scenarios,
    reduce_scenarios,
    reweight_scenarios,
    ScenarioEvaluation,
    ScenarioEvaluationAdapter,
    ScenarioReductionResult,
    ScenarioReweightingResult,
)


__all__ = [
    "AttributionResult",
    "BacktestDecisions",
    "CVaRAtoms",
    "DrawdownRisk",
    "EntropicRiskEstimate",
    "FactorPnL",
    "FactorRiskModel",
    "KellyRisk",
    "MarketRiskReport",
    "NestedBacktestDecisions",
    "NestedBacktestPlan",
    "NestedBacktestResult",
    "NestedBacktestSplits",
    "PnLExplanation",
    "ScenarioEvaluation",
    "ScenarioEvaluationAdapter",
    "ScenarioReductionResult",
    "ScenarioReweightingResult",
    "StressTestResult",
    "TailRiskEstimate",
    "WalkForwardPlan",
    "WalkForwardResult",
    "WalkForwardSplit",
    "brinson_attribution",
    "cvar_atoms",
    "drawdown_risk",
    "entropic_value_at_risk",
    "entropy_tilt_scenarios",
    "evaluate_nested_backtest",
    "evaluate_scenarios",
    "evaluate_walk_forward",
    "expected_shortfall",
    "explain_factor_pnl",
    "explain_pnl",
    "gaussian_var_es",
    "historical_var_es",
    "kelly_risk",
    "market_factor_risk",
    "nested_backtest_splits",
    "reduce_scenarios",
    "reweight_scenarios",
    "spectral_risk",
    "stress_test",
    "validate_no_lookahead",
    "value_at_risk",
    "walk_forward_splits",
]
