#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Quantum operator algebra and closed/open-system evolution residuals."""

from ._algebra import (
    anticommutator,
    commutator,
    hermiticity_residual,
    quantum_bracket,
    unit_trace_residual,
)
from ._amplitude import (
    amplitude_ratio,
    AmplitudeRatio,
    ComplexParameterMode,
    LogAmplitude,
    sampling_log_weight,
)
from ._bath_decomposition import (
    drude_lorentz_matsubara,
    drude_lorentz_pade,
    drude_lorentz_pade_from_poles,
    fit_bath_exponentials,
    underdamped_brownian_two_pole,
)
from ._berry import (
    berry_link,
    berry_loop_phase,
    quantum_geometric_tensor,
    QuantumGeometricTensorResult,
)
from ._channels import (
    apply_finite_cptp,
    compose_finite_cptp,
    factor_finite_cptp,
    finite_cptp_from_choi,
    finite_cptp_from_kraus,
    finite_cptp_from_local_kraus_operation,
    finite_cptp_from_prepared_local_kraus_channel,
    finite_cptp_from_superoperator,
    finite_cptp_from_unitary,
    finite_cptp_to_local_kraus_operation,
    FiniteChannelFactorizationPolicy,
    FiniteChannelPhysicalityEvidence,
    FiniteCPTPMap,
    FiniteKrausFactorization,
    tensor_finite_cptp,
)
from ._composite import embed_operator, partial_trace, tensor_product
from ._discrete import (
    AbstractDiscreteQuantumOperator,
    CallableDiscreteQuantumOperator,
    ConnectedConfigurations,
)
from ._dynamics import (
    HamiltonianAction,
    heisenberg_residual,
    schrodinger_residual,
    von_neumann_residual,
)
from ._electronic import (
    electronic_initial_walkers,
    ElectronicCoulombHamiltonian,
    ElectronicKineticPolicy,
    ElectronicTraceMethod,
    ElectronicVMCResourcePlan,
    harmonic_mean_electron_proposal,
)
from ._electronic_advanced import (
    ElectronicConnections,
    ElectronicIntegralHamiltonian,
    periodic_coulomb_energy,
    PeriodicElectronicEvidence,
    StochasticElectronicKineticPolicy,
    StochasticKineticEstimate,
)
from ._fock import (
    BosonicFockSpace,
    FockCutoffEvidence,
    jaynes_cummings_hamiltonian,
    kerr_hamiltonian,
)
from ._information import (
    density_fidelity,
    purity,
    state_fidelity,
    trace_distance,
    von_neumann_entropy,
)
from ._local import (
    AbstractLocalQuantumOperator,
    evaluate_local_operator,
    LocalOperatorEstimate,
    LocalOperatorStatus,
)
from ._nonmarkovianity import (
    analyze_dynamical_map_series,
    blp_information_backflow,
    DynamicalMapSeriesPhysicality,
)
from ._open_contracts import (
    ApproximationAxis,
    ApproximationQuantity,
    evaluate_open_system_promotion,
    OpenSystemApproximationEvidence,
    OpenSystemPhysicalityEvidence,
    OpenSystemPromotionDecision,
    OpenSystemPromotionPolicy,
    OpenSystemRefinement,
    PhysicalityStatus,
    QuantumGeneratorAction,
    QuantumObservablePlan,
)
from ._open_system import lindblad_dissipator, lindblad_residual
from ._operations import (
    LocalKrausChannelOperation,
    LocalUnitaryOperation,
    QuantumOperation,
    QuantumProgram,
    QuantumStateKind,
)
from ._propagation import (
    apply_local_kraus_to_density,
    apply_local_unitary_to_state,
    apply_unitary_to_state,
    conjugate_density,
    conjugate_local_density,
    density_invariant_residuals,
    kraus_trace_preservation_residual,
    unitarity_residual,
)
from ._pseudomode import (
    BathCorrelationExpansion,
    lorentzian_pseudomode,
    Pseudomode,
    ReactionCoordinateMapping,
)
from ._register import HilbertRegisterLayout
from ._states import (
    density_expectation,
    density_from_factor,
    observable_variance,
    state_expectation,
    state_norm_residual,
)
from ._symmetry import FiniteSignedPermutationSymmetry, SymmetryProjectedAmplitude


__all__ = [
    "AbstractLocalQuantumOperator",
    "AbstractDiscreteQuantumOperator",
    "AmplitudeRatio",
    "HamiltonianAction",
    "HilbertRegisterLayout",
    "anticommutator",
    "CallableDiscreteQuantumOperator",
    "ComplexParameterMode",
    "ConnectedConfigurations",
    "commutator",
    "density_expectation",
    "density_fidelity",
    "density_from_factor",
    "ElectronicCoulombHamiltonian",
    "ElectronicKineticPolicy",
    "ElectronicTraceMethod",
    "electronic_initial_walkers",
    "evaluate_local_operator",
    "ElectronicConnections",
    "ElectronicIntegralHamiltonian",
    "ElectronicVMCResourcePlan",
    "PeriodicElectronicEvidence",
    "StochasticElectronicKineticPolicy",
    "StochasticKineticEstimate",
    "FiniteSignedPermutationSymmetry",
    "FiniteCPTPMap",
    "FiniteChannelFactorizationPolicy",
    "FiniteChannelPhysicalityEvidence",
    "FiniteKrausFactorization",
    "embed_operator",
    "heisenberg_residual",
    "hermiticity_residual",
    "lindblad_dissipator",
    "LocalOperatorEstimate",
    "LocalOperatorStatus",
    "LocalKrausChannelOperation",
    "LocalUnitaryOperation",
    "LogAmplitude",
    "lindblad_residual",
    "amplitude_ratio",
    "harmonic_mean_electron_proposal",
    "quantum_bracket",
    "observable_variance",
    "purity",
    "partial_trace",
    "schrodinger_residual",
    "state_expectation",
    "state_fidelity",
    "state_norm_residual",
    "sampling_log_weight",
    "SymmetryProjectedAmplitude",
    "tensor_product",
    "trace_distance",
    "unit_trace_residual",
    "von_neumann_residual",
    "von_neumann_entropy",
    "QuantumGeometricTensorResult",
    "QuantumOperation",
    "QuantumProgram",
    "QuantumStateKind",
    "apply_finite_cptp",
    "apply_local_kraus_to_density",
    "apply_local_unitary_to_state",
    "apply_unitary_to_state",
    "berry_link",
    "berry_loop_phase",
    "conjugate_density",
    "conjugate_local_density",
    "density_invariant_residuals",
    "compose_finite_cptp",
    "factor_finite_cptp",
    "finite_cptp_from_choi",
    "finite_cptp_from_kraus",
    "finite_cptp_from_local_kraus_operation",
    "finite_cptp_from_prepared_local_kraus_channel",
    "finite_cptp_from_superoperator",
    "finite_cptp_from_unitary",
    "finite_cptp_to_local_kraus_operation",
    "quantum_geometric_tensor",
    "kraus_trace_preservation_residual",
    "unitarity_residual",
    "ApproximationAxis",
    "ApproximationQuantity",
    "BathCorrelationExpansion",
    "BosonicFockSpace",
    "FockCutoffEvidence",
    "OpenSystemApproximationEvidence",
    "evaluate_open_system_promotion",
    "OpenSystemPromotionDecision",
    "OpenSystemPromotionPolicy",
    "OpenSystemPhysicalityEvidence",
    "OpenSystemRefinement",
    "PhysicalityStatus",
    "Pseudomode",
    "QuantumGeneratorAction",
    "QuantumObservablePlan",
    "ReactionCoordinateMapping",
    "jaynes_cummings_hamiltonian",
    "periodic_coulomb_energy",
    "drude_lorentz_pade",
    "kerr_hamiltonian",
    "lorentzian_pseudomode",
    "DynamicalMapSeriesPhysicality",
    "analyze_dynamical_map_series",
    "blp_information_backflow",
    "drude_lorentz_matsubara",
    "drude_lorentz_pade_from_poles",
    "fit_bath_exponentials",
    "underdamped_brownian_two_pole",
    "tensor_finite_cptp",
]
