#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#
# The asymptotic regime structure is adapted from SciPy XSF, licensed under
# BSD-3-Clause. See NOTICE and LICENSES/SCIPY-XSF-BSD-3-CLAUSE.txt.
#

"""Real Airy functions and their exponentially scaled variants."""

from __future__ import annotations

import math

import jax
import jax.numpy as jnp
from jax import Array
from jax.typing import ArrayLike

from .._numerics._compensated import two_sum as _two_sum
from ._dtype import promote_real


_AI_ZERO = 0.3550280538878172392600631860041831764
_AIP_ZERO = -0.2588194037928067984051835601892039635
_SQRT_THREE = math.sqrt(3.0)
_INV_SQRT_PI = 1.0 / math.sqrt(math.pi)
_INV_SQRT_TWO = 1.0 / math.sqrt(2.0)
_DEKKER_SPLITTER = 134217729.0

# Generated by tools/generate_airy_coefficients.py at 120 decimal digits.
_AI_SCALED_COEFFICIENTS = (
    9.909253278629120976e-01,
    -8.787979198916313558e-03,
    2.708640061605207161e-04,
    -1.463172473533969967e-05,
    1.085226020835939303e-06,
    -9.972552056312785359e-08,
    1.073909038644727774e-08,
    -1.309259653125608007e-09,
    1.765607635969083061e-10,
    -2.590435120353513756e-11,
    4.084102938847912634e-12,
    -6.853850259533147775e-13,
    1.215122462293806486e-13,
    -2.262114113790132588e-14,
    4.399957412572511979e-15,
    -8.904529694172307430e-16,
    1.868404039422277974e-16,
    -4.052458927104195282e-17,
    9.061998422410240565e-18,
)
_AIP_SCALED_COEFFICIENTS = (
    1.012899767562267517e00,
    1.255553934189892161e-02,
    -3.262574142189338285e-04,
    1.664941035906724868e-05,
    -1.199896184476621699e-06,
    1.083548973675652922e-07,
    -1.153159593859687821e-08,
    1.393933937918404888e-09,
    -1.867649440675132093e-10,
    2.726191943112684631e-11,
    -4.280401427005199938e-12,
    7.158721135902916655e-13,
    -1.265515085860670637e-13,
    2.350115193018197456e-14,
    -4.561353105568536875e-15,
    9.213872744138308567e-16,
    -1.930111915502533654e-16,
    4.180123816750690854e-17,
    -9.335102671548374936e-18,
)
_BI_SCALED_COEFFICIENTS = (
    1.011705612872281668e00,
    1.238473011641420818e-02,
    7.628741147304859364e-04,
    9.107663285679636631e-05,
    4.281877536933720278e-06,
    -4.657906784913201419e-06,
    -1.692569312732888442e-06,
    1.076038624694475144e-07,
    2.100999230839613143e-07,
    5.822319108198393777e-09,
    -2.897983225574107258e-08,
    -7.036715053437099795e-10,
    4.673978480064377270e-09,
    -2.964109892309229611e-10,
    -7.968695529593932424e-10,
    1.831144111562689661e-10,
    1.199919410750880632e-10,
    -6.374437635469040383e-11,
    -9.144654832582357319e-12,
    1.632204188292197826e-11,
    -2.903612767404594941e-12,
    -2.788596631694760562e-12,
    1.655875877184256690e-12,
    5.693005407394627497e-14,
    -4.297336437001631867e-13,
    1.622798162309349774e-13,
    4.046477204199079249e-14,
    -6.051818827524907108e-14,
    1.736343522670837656e-14,
    8.020101740695070850e-15,
    -8.763039184861865574e-15,
    2.250261885050406300e-15,
    1.297965039252921086e-15,
    -1.349584833517050212e-15,
    3.707490547979441576e-16,
    1.877755473397385233e-16,
    -2.199224724940607457e-16,
    7.368340990485698856e-17,
    2.270101146843565312e-17,
    -3.680560272817145055e-17,
    1.602044330176704860e-17,
)
_BIP_SCALED_COEFFICIENTS = (
    9.840221658969121599e-01,
    -1.675579207611572682e-02,
    -8.696742843350897291e-04,
    -9.996048012504573060e-05,
    -5.184441820113159736e-06,
    4.750790974249758655e-06,
    1.780056703370739198e-06,
    -9.508554437456613071e-08,
    -2.163909214648003035e-07,
    -7.874651545509200031e-09,
    2.962195219753769190e-08,
    9.822871013854136153e-10,
    -4.774727983788960570e-09,
    2.611253667733887805e-10,
    8.170586800390778550e-10,
    -1.799905608198128926e-10,
    -1.241596484988710680e-10,
    6.402068286342658954e-11,
    9.890457453333371450e-12,
    -1.657306350891632045e-11,
    2.820258506550939138e-12,
    2.868511508175111943e-12,
    -1.664149670735272187e-12,
    -7.213886480084640205e-14,
    4.373907449004289448e-13,
    -1.616900053155382365e-13,
    -4.257631290044546470e-14,
    6.128704049878498652e-14,
    -1.717421606099661133e-14,
    -8.307451841564252199e-15,
    8.852239658000875510e-15,
    -2.217856979293037710e-15,
    -1.338895097285605571e-15,
    1.362260920975586455e-15,
    -3.661467218871145786e-16,
    -1.939377279085418349e-16,
    2.220998891476702257e-16,
    -7.314947962440896119e-17,
    -2.366153968674659373e-17,
    3.722697854823737109e-17,
    -1.598943848142446684e-17,
)

_NEGATIVE_U_COEFFICIENTS = (
    9.997541229881232727e-01,
    -3.265982675007251222e-04,
    -7.981413648152953374e-05,
    1.017222243442064043e-06,
    1.039955324403524810e-07,
    -6.345336539621232160e-09,
    -1.837288638990609191e-10,
    5.207689903987740414e-11,
    -2.371394869982986858e-12,
    -3.405603804778931704e-13,
    6.671006052435994809e-14,
    -2.873816733231941457e-15,
    -7.836814938587172338e-16,
    1.749262979117004575e-16,
    -1.119064984780331203e-17,
    -2.335113969176455460e-18,
    7.491549246224319496e-19,
)
_NEGATIVE_V_COEFFICIENTS = (
    4.630924989192123850e-03,
    4.617328112299689917e-03,
    -1.615725921537187568e-05,
    -2.489909747011090595e-06,
    7.585259784665230347e-08,
    4.813097702445520134e-09,
    -5.685833379370604643e-10,
    3.352233490193613234e-12,
    4.580593032743580322e-12,
    -4.513051502103502019e-13,
    -1.142248592042053455e-14,
    8.258110254044059490e-15,
    -9.189414960121667456e-16,
    -2.698357373533989555e-17,
    2.495633811749466595e-17,
    -3.768359311670794560e-18,
)
_NEGATIVE_UD_COEFFICIENTS = (
    1.000291025499718600e00,
    3.866851943849145250e-04,
    9.467056937517908473e-05,
    -1.109750895031631610e-06,
    -1.141341862395834358e-07,
    6.748797811310412563e-09,
    2.005623361276590242e-10,
    -5.481085257762291977e-11,
    2.436609303204319630e-12,
    3.586802098889393831e-13,
    -6.910038965191637146e-14,
    2.901602763241571801e-15,
    8.162044873946142086e-16,
    -1.798872720573694296e-16,
    1.130548647953865843e-17,
    2.425000027673378259e-18,
    -7.680345268763324270e-19,
)
_NEGATIVE_VD_COEFFICIENTS = (
    -6.491021348490458309e-03,
    -6.475790462409087081e-03,
    1.810656748589998616e-05,
    2.800031218638056616e-06,
    -8.147421096436958880e-08,
    -5.225417011507327444e-09,
    6.008508482621213577e-10,
    -3.014831595370847788e-12,
    -4.812771779736099857e-12,
    4.667343273510874620e-13,
    1.243918985682680476e-14,
    -8.565936222686459110e-15,
    9.416070365826256380e-16,
    2.919449100180917807e-17,
    -2.573705347999425820e-17,
    3.849128325177776618e-18,
)


def _chebyshev(coordinate: Array, coefficients: tuple[float, ...]) -> Array:
    first = jnp.zeros_like(coordinate)
    second = jnp.zeros_like(coordinate)
    for coefficient in reversed(coefficients[1:]):
        current = 2.0 * coordinate * first - second + coefficient
        second = first
        first = current
    return coordinate * first - second + coefficients[0]


def _central(x: Array) -> tuple[Array, Array, Array, Array]:
    x3 = x * x * x

    def body(
        k: int, state: tuple[Array, Array, Array, Array, Array, Array, Array, Array]
    ) -> tuple[Array, Array, Array, Array, Array, Array, Array, Array]:
        f, f_term, g, g_term, df, df_term, dg, dg_term = state
        three_k = 3.0 * jnp.asarray(k, dtype=x.dtype)
        f_term = f_term * x3 / (three_k * (three_k - 1.0))
        g_term = g_term * x3 / (three_k * (three_k + 1.0))
        df_term = df_term * x3 / (three_k * (three_k + 2.0))
        dg_term = dg_term * x3 / (three_k * (three_k - 2.0))
        return (
            f + f_term,
            f_term,
            g + g_term,
            g_term,
            df + df_term,
            df_term,
            dg + dg_term,
            dg_term,
        )

    initial = (
        jnp.ones_like(x),
        jnp.ones_like(x),
        x,
        x,
        0.5 * x * x,
        0.5 * x * x,
        jnp.ones_like(x),
        jnp.ones_like(x),
    )
    f, _, g, _, df, _, dg, _ = jax.lax.fori_loop(1, 41, body, initial)
    ai = _AI_ZERO * f + _AIP_ZERO * g
    bi = _SQRT_THREE * (_AI_ZERO * f - _AIP_ZERO * g)
    aip = _AI_ZERO * df + _AIP_ZERO * dg
    bip = _SQRT_THREE * (_AI_ZERO * df - _AIP_ZERO * dg)
    return ai, aip, bi, bip


def _positive_scaled(x: Array) -> tuple[Array, Array, Array, Array]:
    sqrt_x = jnp.sqrt(x)
    fourth_root = jnp.sqrt(sqrt_x)
    coordinate = 2.0 * jnp.power(3.0 / x, 1.5) - 1.0
    ai = (
        0.5 * _INV_SQRT_PI * _chebyshev(coordinate, _AI_SCALED_COEFFICIENTS) / fourth_root
    )
    aip = (
        -0.5
        * _INV_SQRT_PI
        * fourth_root
        * _chebyshev(coordinate, _AIP_SCALED_COEFFICIENTS)
    )
    bi = _INV_SQRT_PI * _chebyshev(coordinate, _BI_SCALED_COEFFICIENTS) / fourth_root
    bip = _INV_SQRT_PI * fourth_root * _chebyshev(coordinate, _BIP_SCALED_COEFFICIENTS)
    return ai, aip, bi, bip


def _split(value: Array) -> tuple[Array, Array]:
    split_limit = jnp.finfo(value.dtype).max / _DEKKER_SPLITTER
    can_split = jnp.abs(value) <= split_limit
    safe_value = jnp.where(can_split, value, jnp.zeros_like(value))
    product = _DEKKER_SPLITTER * safe_value
    high = product - (product - safe_value)
    low = safe_value - high
    return (
        jnp.where(can_split, high, value),
        jnp.where(can_split, low, jnp.zeros_like(value)),
    )


def _two_product(left: Array, right: Array) -> tuple[Array, Array]:
    product = left * right
    finite = jnp.isfinite(product)
    safe_left = jnp.where(finite, left, jnp.zeros_like(left))
    safe_right = jnp.where(finite, right, jnp.zeros_like(right))
    left_high, left_low = _split(safe_left)
    right_high, right_low = _split(safe_right)
    error = (
        (left_high * right_high - product)
        + left_high * right_low
        + left_low * right_high
        + left_low * right_low
    )
    return product, jnp.where(finite, error, jnp.zeros_like(product))


def _negative_phase(absolute_x: Array, sqrt_x: Array) -> tuple[Array, Array]:
    square_high, square_low = _two_product(sqrt_x, sqrt_x)
    sqrt_low = ((absolute_x - square_high) - square_low) / (2.0 * sqrt_x)

    product_high, product_low = _two_product(absolute_x, sqrt_x)
    product_high, product_low = _two_sum(
        product_high, product_low + absolute_x * sqrt_low
    )
    numerator_high = 2.0 * product_high
    numerator_low = 2.0 * product_low

    zeta_high = numerator_high / 3.0
    divisor_high, divisor_low = _two_product(zeta_high, jnp.asarray(3.0))
    zeta_low = ((numerator_high - divisor_high) + (numerator_low - divisor_low)) / 3.0
    zeta_high, zeta_low = _two_sum(zeta_high, zeta_low)

    sine_high = jnp.sin(zeta_high)
    cosine_high = jnp.cos(zeta_high)
    sine_low = jnp.sin(zeta_low)
    cosine_low = jnp.cos(zeta_low)
    sine_zeta = sine_high * cosine_low + cosine_high * sine_low
    cosine_zeta = cosine_high * cosine_low - sine_high * sine_low
    return (
        _INV_SQRT_TWO * (sine_zeta + cosine_zeta),
        _INV_SQRT_TWO * (cosine_zeta - sine_zeta),
    )


def _negative_asymptotic(x: Array) -> tuple[Array, Array, Array, Array]:
    evaluation_x = x.astype(jnp.float64) if x.dtype == jnp.float32 else x
    absolute_x = -evaluation_x
    sqrt_x = jnp.sqrt(absolute_x)
    fourth_root = jnp.sqrt(sqrt_x)
    sine, cosine = _negative_phase(absolute_x, sqrt_x)
    coordinate = 2.0 * jnp.power(5.0 / absolute_x, 1.5) - 1.0
    u = _chebyshev(coordinate, _NEGATIVE_U_COEFFICIENTS)
    v = _chebyshev(coordinate, _NEGATIVE_V_COEFFICIENTS)
    ud = _chebyshev(coordinate, _NEGATIVE_UD_COEFFICIENTS)
    vd = _chebyshev(coordinate, _NEGATIVE_VD_COEFFICIENTS)
    ai = _INV_SQRT_PI * (sine * u - cosine * v) / fourth_root
    bi = _INV_SQRT_PI * (cosine * u + sine * v) / fourth_root
    aip = -_INV_SQRT_PI * fourth_root * (cosine * ud + sine * vd)
    bip = _INV_SQRT_PI * fourth_root * (sine * ud - cosine * vd)
    return (
        ai.astype(x.dtype),
        aip.astype(x.dtype),
        bi.astype(x.dtype),
        bip.astype(x.dtype),
    )


def _airy_primal(x: Array, *, scaled: bool) -> tuple[Array, Array, Array, Array]:
    positive_region = x > 3.0
    negative_region = x < -5.0
    central_region = ~(positive_region | negative_region)

    central_x = jnp.where(central_region, x, jnp.zeros_like(x))
    central = _central(central_x)
    positive_x = jnp.where(positive_region, x, jnp.full_like(x, 3.0))
    positive = _positive_scaled(positive_x)
    negative_x = jnp.where(negative_region, x, jnp.full_like(x, -5.0))
    negative = _negative_asymptotic(negative_x)

    positive_zeta = 2.0 * positive_x * jnp.sqrt(positive_x) / 3.0
    central_zeta = 2.0 * jnp.maximum(x, 0.0) ** 1.5 / 3.0
    if scaled:
        central_factors = (
            jnp.exp(central_zeta),
            jnp.exp(central_zeta),
            jnp.exp(-central_zeta),
            jnp.exp(-central_zeta),
        )
        positive_factors = (1.0, 1.0, 1.0, 1.0)
    else:
        central_factors = (1.0, 1.0, 1.0, 1.0)
        positive_factors = (
            jnp.exp(-positive_zeta),
            jnp.exp(-positive_zeta),
            jnp.exp(positive_zeta),
            jnp.exp(positive_zeta),
        )

    values = []
    for (
        central_value,
        central_factor,
        positive_value,
        positive_factor,
        negative_value,
    ) in zip(central, central_factors, positive, positive_factors, negative):
        value = central_value * central_factor
        value = jnp.where(positive_region, positive_value * positive_factor, value)
        value = jnp.where(negative_region, negative_value, value)
        values.append(value)

    positive_infinity = jnp.isposinf(x)
    negative_infinity = jnp.isneginf(x)
    if scaled:
        infinity_values = (0.0, -jnp.inf, 0.0, jnp.inf)
    else:
        infinity_values = (0.0, 0.0, jnp.inf, jnp.inf)
    for index, infinity_value in enumerate(infinity_values):
        values[index] = jnp.where(positive_infinity, infinity_value, values[index])
        values[index] = jnp.where(
            negative_infinity, jnp.full_like(x, jnp.nan), values[index]
        )
    return values[0], values[1], values[2], values[3]


@jax.custom_jvp
def _airy_array(x: Array) -> tuple[Array, Array, Array, Array]:
    return _airy_primal(x, scaled=False)


@_airy_array.defjvp
def _airy_jvp(
    primals: tuple[Array], tangents: tuple[Array]
) -> tuple[tuple[Array, Array, Array, Array], tuple[Array, Array, Array, Array]]:
    (x,) = primals
    (x_dot,) = tangents
    ai, aip, bi, bip = _airy_array(x)
    derivatives = (aip, x * ai, bip, x * bi)
    infinity_derivatives = (0.0, 0.0, jnp.inf, jnp.inf)
    derivatives = tuple(
        jnp.where(jnp.isposinf(x), boundary, derivative)
        for derivative, boundary in zip(derivatives, infinity_derivatives)
    )
    return (ai, aip, bi, bip), (
        derivatives[0] * x_dot,
        derivatives[1] * x_dot,
        derivatives[2] * x_dot,
        derivatives[3] * x_dot,
    )


@jax.custom_jvp
def _airye_array(x: Array) -> tuple[Array, Array, Array, Array]:
    return _airy_primal(x, scaled=True)


@_airye_array.defjvp
def _airye_jvp(
    primals: tuple[Array], tangents: tuple[Array]
) -> tuple[tuple[Array, Array, Array, Array], tuple[Array, Array, Array, Array]]:
    (x,) = primals
    (x_dot,) = tangents
    ai, aip, bi, bip = _airye_array(x)
    sqrt_x = jnp.sqrt(jnp.maximum(x, 0.0))
    positive = x > 0.0
    derivatives = (
        jnp.where(positive, aip + sqrt_x * ai, aip),
        jnp.where(positive, x * ai + sqrt_x * aip, x * ai),
        jnp.where(positive, bip - sqrt_x * bi, bip),
        jnp.where(positive, x * bi - sqrt_x * bip, x * bi),
    )

    asymptotic = (x > 3.0) & jnp.isfinite(x)
    asymptotic_x = jnp.where(asymptotic, x, jnp.full_like(x, 4.0))
    _, asymptotic_derivatives = jax.jvp(
        _positive_scaled,
        (asymptotic_x,),
        (jnp.ones_like(asymptotic_x),),
    )
    derivatives = tuple(
        jnp.where(asymptotic, stable, derivative)
        for stable, derivative in zip(asymptotic_derivatives, derivatives)
    )
    derivatives = tuple(
        jnp.where(jnp.isposinf(x), jnp.zeros_like(derivative), derivative)
        for derivative in derivatives
    )
    return (ai, aip, bi, bip), (
        derivatives[0] * x_dot,
        derivatives[1] * x_dot,
        derivatives[2] * x_dot,
        derivatives[3] * x_dot,
    )


def airy(x: ArrayLike) -> tuple[Array, Array, Array, Array]:
    """Return principal-continuation Airy functions and derivatives."""
    if jnp.issubdtype(jnp.asarray(x).dtype, jnp.complexfloating):
        from ._continuation import complex_airy

        return complex_airy(x)
    (promoted_x,) = promote_real("airy", x)
    return _airy_array(promoted_x)


def airye(x: ArrayLike) -> tuple[Array, Array, Array, Array]:
    """Return exponentially scaled principal-continuation Airy functions."""
    if jnp.issubdtype(jnp.asarray(x).dtype, jnp.complexfloating):
        from ._continuation import complex_airy, promote_principal

        (z,) = promote_principal(x)
        ai, aip, bi, bip = complex_airy(z)
        zeta = (2.0 / 3.0) * z * jnp.sqrt(z)
        ai_scale = jnp.exp(zeta)
        bi_scale = jnp.exp(-jnp.abs(jnp.real(zeta)))
        return ai * ai_scale, aip * ai_scale, bi * bi_scale, bip * bi_scale
    (promoted_x,) = promote_real("airye", x)
    return _airye_array(promoted_x)


__all__ = ["airy", "airye"]
