#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Self-adjoint eigenproblems and general dense complex Schur decompositions."""

from ._observables import (
    schur_spectral_observables,
    SchurSpectralObservables,
    SpectralObservableProvenance,
    SpectralObservableStatus,
    SpectralStabilityStatus,
)
from ._plans import EigenCostEstimate, EigenSolvePlan
from ._policies import (
    AutoEigenMethod,
    DenseEigh,
    EigenDifferentiationMode,
    EigenResourcePolicy,
    EigenSolvePolicy,
    EigenTarget,
    EigenTolerancePolicy,
    LOBPCG,
    RestartedLanczos,
)
from ._prepared import DenseEigenState, PreparedEigenSolve
from ._problems import Eigenproblem, EigenproblemKind, GeneralizedEigenproblem
from ._results import (
    EigenSolveDiagnostics,
    EigenSolveProvenance,
    EigenSolveResult,
    EigenSolveStatus,
)
from ._runtime import (
    eigensolve,
    plan_eigensolve,
    prepare_eigensolve,
    refresh_eigensolve,
)
from ._schur import (
    plan_schur_eigensolve,
    prepare_schur_eigensolve,
    PreparedSchurSolve,
    refresh_schur_eigensolve,
    schur_eigensolve,
    SchurBackend,
    SchurCostEstimate,
    SchurEigenproblem,
    SchurResourcePolicy,
    SchurSolveDiagnostics,
    SchurSolvePlan,
    SchurSolvePolicy,
    SchurSolveProvenance,
    SchurSolveResult,
    SchurSolveStatus,
    SchurTolerancePolicy,
)
from ._subspaces import (
    plan_spectral_subspace,
    prepare_spectral_subspace,
    PreparedSpectralSubspace,
    refresh_spectral_subspace,
    spectral_projector_derivative,
    spectral_subspace,
    SpectralProjectorDerivativeDiagnostics,
    SpectralProjectorDerivativeProvenance,
    SpectralProjectorDerivativeResult,
    SpectralProjectorDerivativeStatus,
    SpectralSelection,
    SpectralSelectionKind,
    SpectralSubspace,
    SpectralSubspaceCostEstimate,
    SpectralSubspaceDiagnostics,
    SpectralSubspacePlan,
    SpectralSubspacePolicy,
    SpectralSubspaceProvenance,
    SpectralSubspaceResourcePolicy,
    SpectralSubspaceStatus,
)


__all__ = [
    "AutoEigenMethod",
    "DenseEigh",
    "EigenCostEstimate",
    "EigenDifferentiationMode",
    "Eigenproblem",
    "EigenproblemKind",
    "EigenResourcePolicy",
    "EigenSolveDiagnostics",
    "EigenSolvePlan",
    "EigenSolvePolicy",
    "EigenSolveProvenance",
    "EigenSolveResult",
    "EigenSolveStatus",
    "EigenTarget",
    "EigenTolerancePolicy",
    "GeneralizedEigenproblem",
    "LOBPCG",
    "DenseEigenState",
    "PreparedEigenSolve",
    "RestartedLanczos",
    "PreparedSchurSolve",
    "PreparedSpectralSubspace",
    "SchurBackend",
    "SchurCostEstimate",
    "SchurEigenproblem",
    "SchurResourcePolicy",
    "SchurSolveDiagnostics",
    "SchurSolvePlan",
    "SchurSolvePolicy",
    "SchurSolveProvenance",
    "SchurSolveResult",
    "SchurSolveStatus",
    "SchurTolerancePolicy",
    "SchurSpectralObservables",
    "SpectralObservableProvenance",
    "SpectralObservableStatus",
    "SpectralStabilityStatus",
    "SpectralProjectorDerivativeDiagnostics",
    "SpectralProjectorDerivativeProvenance",
    "SpectralProjectorDerivativeResult",
    "SpectralProjectorDerivativeStatus",
    "SpectralSelection",
    "SpectralSelectionKind",
    "SpectralSubspace",
    "SpectralSubspaceCostEstimate",
    "SpectralSubspaceDiagnostics",
    "SpectralSubspacePlan",
    "SpectralSubspacePolicy",
    "SpectralSubspaceProvenance",
    "SpectralSubspaceResourcePolicy",
    "SpectralSubspaceStatus",
    "eigensolve",
    "plan_eigensolve",
    "plan_schur_eigensolve",
    "plan_spectral_subspace",
    "prepare_eigensolve",
    "prepare_schur_eigensolve",
    "prepare_spectral_subspace",
    "refresh_eigensolve",
    "refresh_schur_eigensolve",
    "refresh_spectral_subspace",
    "schur_eigensolve",
    "schur_spectral_observables",
    "spectral_projector_derivative",
    "spectral_subspace",
]
