#
#  Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Sparse graph execution utilities for Phydrax.

This package provides the low-level graph substrate used by graph domains,
operators, and graph neural network modules. The canonical representation is
`GraphIR`: a counts-first sparse graph batch with optional node, edge, and
global features.
"""

from . import compat, nn
from ._abelian_gauge import (
    abelian_current_continuity,
    abelian_curvature,
    abelian_gauge_transform,
    abelian_maxwell_action,
    abelian_maxwell_residual,
    AbelianBridgeReport,
    AbelianGaugeDiagnostics,
    AbelianMaxwellOperator,
    project_abelian_gauge_field,
    validate_abelian_gauge_system,
)
from ._architectures import MeshGraphNet, MeshGraphNetBlock, RowMLP
from ._cochain import (
    cochain_complex_from_incidences,
    cochain_complex_from_simplicial,
    CochainComplexIR,
    CochainIncidence,
    graph_to_cochain_complex,
    GraphEdgeSemantics,
    HarmonicSubspace,
    reorient_cochain,
    reorient_cochain_complex,
    triangle_mesh_to_cochain_complex,
)
from ._cochain_field import CochainField
from ._cochain_metric import cochain_metric_reduce, CochainMetricReduction
from ._cochain_ops import (
    cochain_codifferential,
    cochain_exterior_derivative,
    cochain_harmonic_projection,
    cochain_hodge_laplacian,
    CochainCodifferential,
    CochainExteriorDerivative,
    CochainHarmonicProjection,
    CochainHodgeLaplacian,
    HodgeLaplacianComponent,
)
from ._cochain_residual import CochainResidualProgram
from ._cochain_spectrum import (
    cochain_hodge_sector_spectra,
    cochain_laplacian_eigenbasis,
    CochainHodgeSectorSpectra,
    CochainLaplacianComponent,
    compute_harmonic_subspace,
)
from ._continuous_bridge import (
    ContinuousCochainBridge,
    ContinuousCochainProjection,
    integrate_form_to_cochain,
    OrientedCellParameterization,
    StokesValidationReport,
    validate_stokes_bridge,
)
from ._data import Batch, Data
from ._derived import (
    line_graph,
    LineGraph,
    LineGraphConnectivity,
    mesh_to_dual_graph,
    MeshDualGraph,
)
from ._equivariant import (
    EquivariantGraphConvolution,
    euclidean_edge_features,
    gaussian_radial_basis,
)
from ._generators import (
    get_fully_connected_graph,
    sparse_matrix_to_graph,
    sparse_matrix_to_graphs_tuple,
)
from ._geometry import (
    GeometryGraph,
    knn_graph,
    knn_query_graph,
    mesh_to_geometry_graph,
    mesh_to_graph,
    mollified_kernel_weight,
    point_cloud_to_graph,
    query_graph_from_edges,
    QueryGraph,
    radius_graph,
    radius_query_graph,
)
from ._graph import ensure_graph, Graph, graph_counts, is_graph_like
from ._hypergraph import (
    hypergraph_to_bipartite_graph,
    HypergraphBipartiteGraph,
    HypergraphConvolution,
    incidence_to_bipartite_graph,
)
from ._index import (
    add_remaining_self_loops,
    add_self_loops,
    coalesce,
    degree,
    in_degree,
    maybe_num_nodes,
    out_degree,
    remove_self_loops,
    to_dense_adj,
    to_edge_index,
    to_undirected,
)
from ._ir import (
    batch,
    batch_graphs,
    batch_np,
    GraphIR,
    unbatch,
    unbatch_graph,
    unbatch_np,
)
from ._kernels import (
    scatter_add,
    scatter_max,
    scatter_mean,
    scatter_min,
    segment_max,
    segment_max_or_constant,
    segment_mean,
    segment_min,
    segment_min_or_constant,
    segment_normalize,
    segment_softmax,
    segment_sum,
    segment_variance,
)
from ._layout import LayoutPlan, pack_graphs
from ._mesh import (
    mesh_cotangent_weights,
    mesh_face_areas,
    mesh_face_normals,
    mesh_lumped_vertex_areas,
    mesh_to_cotangent_graph,
    mesh_vertex_normals,
    MeshCotangentLaplacian,
    MeshLaplacianSign,
)
from ._metric_assembly import (
    assemble_metric_cochain_complex,
    MetricCochainAssembly,
)
from ._models import (
    DeepSets,
    GAT,
    graph_map_features,
    GraphConvolution,
    GraphMapFeatures,
    GraphNetGAT,
    GraphNetwork,
    InteractionNetwork,
    RelationNetwork,
)
from ._mp import MessagePassing
from ._multigraph import (
    gaot_operator,
    gino_operator,
    GraphEncodeProcessDecode,
    GraphFieldProcessor,
    query_encode_process_decode,
    query_graph_with_source_features,
    query_target_features,
    QueryGraphOperator,
    RegionalGraphProcessor,
    rigno_operator,
    transolver_operator,
)
from ._multiscale import (
    GraphClusterPool,
    GraphMultiscaleBlock,
    GraphPoolReduce,
    pool_graph_by_cluster,
    unpool_nodes_by_cluster,
)
from ._neural_operators import (
    GraphAttentionOperator,
    GraphDiffusion,
    GraphFiniteVolumeDiffusion,
    GraphFiniteVolumeDivergence,
    GraphKernelIntegral,
    GraphNeuralOperator,
    GraphProcessor,
    RepeatedGraphProcessor,
)
from ._operator_topology import (
    broadcast_operator_topology,
    operator_graph_fingerprint,
    operator_topology_fingerprint,
    OperatorTopology,
    OperatorTopologyEntity,
    OperatorTopologyKind,
    OperatorTopologySite,
    pad_operator_topology,
    slice_operator_topology,
    stack_operator_topologies,
    take_operator_topology,
)
from ._ops import concatenated_args, partition_softmax
from ._padding import (
    dynamically_batch,
    get_edge_padding_mask,
    get_graph_padding_mask,
    get_node_padding_mask,
    get_number_of_padding_with_graphs_edges,
    get_number_of_padding_with_graphs_graphs,
    get_number_of_padding_with_graphs_nodes,
    pad_with_graphs,
    unpad_with_graphs,
    with_zero_out_padding_outputs,
    zero_out_padding,
)
from ._process import (
    AutoregressiveGraphRollout,
    euler_step,
    EulerGraphStepper,
    GraphFeatureName,
    GraphRolloutReduction,
    rk4_step,
    RK4GraphStepper,
    rollout,
    rollout_feature_loss,
    rollout_features,
)
from ._query_batch import (
    batched_knn_graph,
    batched_knn_query_graph,
    query_neighbors,
    QueryNeighborhood,
)
from ._simplicial import (
    FormDegree,
    SimplicialComplexGraph,
    SimplicialHodgeLaplacian,
    triangle_mesh_to_simplicial_graph,
)
from ._spectral import (
    graph_adjacency_apply,
    graph_laplacian_apply,
    GraphChebyshevFilter,
    GraphFilterOperator,
    GraphFlow,
    GraphLaplacianNormalization,
    GraphLaplacianOperator,
    GraphPolynomialFilter,
    spectral_discretization_from_graph,
    spectral_discretization_from_triangle_mesh,
)
from ._typed import (
    edge_type_ids,
    edge_type_indices,
    node_type_ids,
    node_type_indices,
    RelationalGraphConvolution,
    typed_edges_component,
    typed_nodes_component,
)
from .nn import GCNConv, GINConv, SAGEConv


__all__ = [
    "compat",
    "nn",
    "Graph",
    "GraphIR",
    "OperatorTopology",
    "OperatorTopologyEntity",
    "OperatorTopologyKind",
    "OperatorTopologySite",
    "broadcast_operator_topology",
    "operator_graph_fingerprint",
    "operator_topology_fingerprint",
    "pad_operator_topology",
    "slice_operator_topology",
    "stack_operator_topologies",
    "take_operator_topology",
    "ensure_graph",
    "is_graph_like",
    "graph_counts",
    "HypergraphBipartiteGraph",
    "HypergraphConvolution",
    "hypergraph_to_bipartite_graph",
    "incidence_to_bipartite_graph",
    "Data",
    "Batch",
    "LineGraph",
    "LineGraphConnectivity",
    "MeshDualGraph",
    "line_graph",
    "mesh_to_dual_graph",
    "EquivariantGraphConvolution",
    "euclidean_edge_features",
    "gaussian_radial_basis",
    "batch",
    "batch_np",
    "batch_graphs",
    "unbatch",
    "unbatch_np",
    "unbatch_graph",
    "LayoutPlan",
    "pack_graphs",
    "coalesce",
    "to_undirected",
    "add_self_loops",
    "add_remaining_self_loops",
    "remove_self_loops",
    "degree",
    "in_degree",
    "out_degree",
    "maybe_num_nodes",
    "to_dense_adj",
    "to_edge_index",
    "segment_sum",
    "segment_mean",
    "segment_variance",
    "segment_normalize",
    "segment_max",
    "segment_max_or_constant",
    "segment_min",
    "segment_min_or_constant",
    "segment_softmax",
    "scatter_add",
    "scatter_mean",
    "scatter_max",
    "scatter_min",
    "partition_softmax",
    "concatenated_args",
    "MessagePassing",
    "GraphNetwork",
    "InteractionNetwork",
    "RelationNetwork",
    "DeepSets",
    "GraphNetGAT",
    "GAT",
    "GraphConvolution",
    "GraphMapFeatures",
    "graph_map_features",
    "RowMLP",
    "MeshGraphNetBlock",
    "MeshGraphNet",
    "MeshCotangentLaplacian",
    "MeshLaplacianSign",
    "GraphDiffusion",
    "GraphAttentionOperator",
    "GraphFiniteVolumeDiffusion",
    "GraphFiniteVolumeDivergence",
    "GraphKernelIntegral",
    "GraphNeuralOperator",
    "GraphProcessor",
    "RepeatedGraphProcessor",
    "GraphLaplacianOperator",
    "GraphPolynomialFilter",
    "GraphChebyshevFilter",
    "GraphFilterOperator",
    "GraphFlow",
    "GraphLaplacianNormalization",
    "graph_adjacency_apply",
    "graph_laplacian_apply",
    "spectral_discretization_from_graph",
    "spectral_discretization_from_triangle_mesh",
    "GraphEdgeSemantics",
    "CochainMetricReduction",
    "CochainResidualProgram",
    "CochainHodgeSectorSpectra",
    "CochainLaplacianComponent",
    "CochainComplexIR",
    "CochainIncidence",
    "HarmonicSubspace",
    "cochain_complex_from_incidences",
    "cochain_complex_from_simplicial",
    "compute_harmonic_subspace",
    "graph_to_cochain_complex",
    "reorient_cochain",
    "reorient_cochain_complex",
    "triangle_mesh_to_cochain_complex",
    "CochainCodifferential",
    "CochainExteriorDerivative",
    "CochainHarmonicProjection",
    "CochainHodgeLaplacian",
    "cochain_hodge_sector_spectra",
    "cochain_laplacian_eigenbasis",
    "HodgeLaplacianComponent",
    "cochain_codifferential",
    "cochain_metric_reduce",
    "cochain_exterior_derivative",
    "cochain_harmonic_projection",
    "cochain_hodge_laplacian",
    "FormDegree",
    "SimplicialComplexGraph",
    "SimplicialHodgeLaplacian",
    "triangle_mesh_to_simplicial_graph",
    "RelationalGraphConvolution",
    "node_type_ids",
    "edge_type_ids",
    "node_type_indices",
    "edge_type_indices",
    "typed_nodes_component",
    "typed_edges_component",
    "GCNConv",
    "SAGEConv",
    "GINConv",
    "pad_with_graphs",
    "get_number_of_padding_with_graphs_graphs",
    "get_number_of_padding_with_graphs_nodes",
    "get_number_of_padding_with_graphs_edges",
    "unpad_with_graphs",
    "get_node_padding_mask",
    "get_edge_padding_mask",
    "get_graph_padding_mask",
    "dynamically_batch",
    "zero_out_padding",
    "with_zero_out_padding_outputs",
    "AutoregressiveGraphRollout",
    "EulerGraphStepper",
    "GraphFeatureName",
    "GraphRolloutReduction",
    "RK4GraphStepper",
    "euler_step",
    "rk4_step",
    "rollout",
    "rollout_feature_loss",
    "rollout_features",
    "GraphClusterPool",
    "GraphMultiscaleBlock",
    "GraphPoolReduce",
    "QueryNeighborhood",
    "batched_knn_graph",
    "batched_knn_query_graph",
    "query_neighbors",
    "GraphEncodeProcessDecode",
    "GraphFieldProcessor",
    "RegionalGraphProcessor",
    "QueryGraphOperator",
    "query_encode_process_decode",
    "gaot_operator",
    "gino_operator",
    "rigno_operator",
    "transolver_operator",
    "query_graph_with_source_features",
    "query_target_features",
    "pool_graph_by_cluster",
    "unpool_nodes_by_cluster",
    "get_fully_connected_graph",
    "sparse_matrix_to_graph",
    "sparse_matrix_to_graphs_tuple",
    "GeometryGraph",
    "QueryGraph",
    "knn_graph",
    "knn_query_graph",
    "mesh_to_graph",
    "mesh_to_geometry_graph",
    "mesh_to_cotangent_graph",
    "mesh_cotangent_weights",
    "mesh_face_areas",
    "mesh_face_normals",
    "mesh_lumped_vertex_areas",
    "mesh_vertex_normals",
    "mollified_kernel_weight",
    "point_cloud_to_graph",
    "query_graph_from_edges",
    "radius_graph",
    "radius_query_graph",
    "assemble_metric_cochain_complex",
    "MetricCochainAssembly",
    "ContinuousCochainBridge",
    "ContinuousCochainProjection",
    "OrientedCellParameterization",
    "StokesValidationReport",
    "integrate_form_to_cochain",
    "validate_stokes_bridge",
    "AbelianBridgeReport",
    "AbelianGaugeDiagnostics",
    "AbelianMaxwellOperator",
    "CochainField",
    "abelian_current_continuity",
    "abelian_curvature",
    "abelian_gauge_transform",
    "abelian_maxwell_action",
    "abelian_maxwell_residual",
    "project_abelian_gauge_field",
    "validate_abelian_gauge_system",
]
