#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import sys
from pathlib import Path

import numpy as np


_TRIANGLE_DEGREES = tuple(range(1, 31))
_TETRAHEDRON_DEGREES = tuple(range(1, 16))
_LEBEDEV_ORDERS = (3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31)


def _digest(path: Path, /) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _array_literal(values: np.ndarray, /, *, indent: int) -> str:
    prefix = " " * indent
    rows = []
    for row in values:
        if np.ndim(row) == 0:
            rows.append(f"{prefix}{float(row)!r},")
        else:
            entries = ", ".join(repr(float(value)) for value in row)
            rows.append(f"{prefix}({entries}),")
    return "\n".join(rows)


def _rules_literal(rules: dict[int, tuple[np.ndarray, np.ndarray]], /) -> str:
    blocks = []
    for degree, (points, weights) in rules.items():
        blocks.append(
            f"    {degree}: (\n"
            "        (\n"
            f"{_array_literal(points, indent=12)}\n"
            "        ),\n"
            "        (\n"
            f"{_array_literal(weights, indent=12)}\n"
            "        ),\n"
            "    ),"
        )
    return "\n".join(blocks)


def _simplex_rules(modepy_root: Path, /):
    sys.path.insert(0, str(modepy_root))
    from modepy.quadrature.xiao_gimbutas import XiaoGimbutasSimplexQuadrature

    def family(dimension: int, degrees: tuple[int, ...]):
        scale = 2.0**dimension
        rules = {}
        for degree in degrees:
            source = XiaoGimbutasSimplexQuadrature(degree, dimension)
            points = 0.5 * (np.asarray(source.nodes, dtype=float).T + 1.0)
            weights = np.asarray(source.weights, dtype=float) / scale
            rules[degree] = (points, weights)
        return rules

    data_path = modepy_root / "modepy" / "quadrature" / "xg_quad_data.py"
    return (
        family(2, _TRIANGLE_DEGREES),
        family(3, _TETRAHEDRON_DEGREES),
        _digest(data_path),
    )


def _lebedev_rules():
    from scipy.integrate._lebedev import lebedev_rule

    rules = {}
    for order in _LEBEDEV_ORDERS:
        points, weights = lebedev_rule(order)
        points_ = np.asarray(points, dtype=float).T
        weights_ = np.asarray(weights, dtype=float)
        if np.all(weights_ > 0.0):
            rules[order] = (points_, weights_)
    import scipy.integrate._lebedev as module

    source = Path(module.__file__)
    return rules, _digest(source), importlib.metadata.version("scipy")


def _write_simplex(
    output: Path,
    triangle: dict[int, tuple[np.ndarray, np.ndarray]],
    tetrahedron: dict[int, tuple[np.ndarray, np.ndarray]],
    source_digest: str,
) -> None:
    content = f"""#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#
# Generated by tools/generate_cubature_data.py from ModePy 2026.1
# modepy/quadrature/xg_quad_data.py SHA-256: {source_digest}
# ModePy is distributed under the MIT License.
#

from __future__ import annotations


TRIANGLE_RULES = {{
{_rules_literal(triangle)}
}}

TETRAHEDRON_RULES = {{
{_rules_literal(tetrahedron)}
}}


__all__ = ["TETRAHEDRON_RULES", "TRIANGLE_RULES"]
"""
    output.write_text(content)


def _write_lebedev(
    output: Path,
    rules: dict[int, tuple[np.ndarray, np.ndarray]],
    source_digest: str,
    scipy_version: str,
) -> None:
    content = f"""#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#
# Generated by tools/generate_cubature_data.py from SciPy {scipy_version}
# scipy/integrate/_lebedev.py SHA-256: {source_digest}
# SciPy is distributed under the BSD 3-Clause License.
# Only strictly positive-weight rules are retained.
#

from __future__ import annotations


LEBEDEV_RULES = {{
{_rules_literal(rules)}
}}


__all__ = ["LEBEDEV_RULES"]
"""
    output.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate deterministic private cubature data modules."
    )
    parser.add_argument(
        "--modepy-root",
        type=Path,
        required=True,
        help="Directory containing the pinned ModePy installation.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("phydrax/_polynomial"),
    )
    arguments = parser.parse_args()
    output = arguments.output_dir
    output.mkdir(parents=True, exist_ok=True)
    triangle, tetrahedron, modepy_digest = _simplex_rules(arguments.modepy_root)
    lebedev, scipy_digest, scipy_version = _lebedev_rules()
    _write_simplex(
        output / "_simplex_cubature_data.py",
        triangle,
        tetrahedron,
        modepy_digest,
    )
    _write_lebedev(
        output / "_lebedev_cubature_data.py",
        lebedev,
        scipy_digest,
        scipy_version,
    )


if __name__ == "__main__":
    main()
