#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Measure-aware deterministic, adaptive, and stochastic integration."""

from ._api import from_samples, integrate, IntegrationRealization, materialize, reduce
from ._batches import (
    IntegrationBatch,
    MappedIntegrationBatch,
    PointIntegrationBatch,
    SeparableIntegrationBatch,
    WeightedSampleBatch,
)
from ._estimates import (
    AdaptivePartition,
    AdaptiveQuadratureDiagnostics,
    AntitheticDiagnostics,
    FixedQuadratureDiagnostics,
    IntegrationEstimate,
    IntegrationProvenance,
    MappedIntegrationDiagnostics,
    MonteCarloDiagnostics,
    ProductIntegrationDiagnostics,
    RandomizedQMCDiagnostics,
    SparseGridDiagnostics,
    StratifiedDiagnostics,
    WeightedSampleDiagnostics,
)
from ._plans import (
    AdaptiveQuadraturePlan,
    AntitheticDesign,
    CellQuadraturePlan,
    ControlVariateEstimator,
    FixedQuadraturePlan,
    IIDDesign,
    ImportanceSamplingPlan,
    IntegrationPlan,
    LatinHypercubeDesign,
    MonteCarloPlan,
    ProductIntegrationPlan,
    QuasiMonteCarloPlan,
    RandomizedQMCDesign,
    SampleMeanEstimator,
    SelfNormalizedEstimator,
    SparseGridPlan,
    StratifiedDesign,
    StratifiedMonteCarloPlan,
)
from ._product import ProductIntegrationRealization
from ._rules import (
    ClenshawCurtisRule,
    GaussKronrodRule,
    GaussLegendreRule,
    interval_rule_data,
    IntervalRule,
    reference_rule_data,
    ReferenceCellData,
    ReferenceHexahedronRule,
    ReferenceIntervalRule,
    ReferenceQuadrilateralRule,
    ReferenceRule,
    ReferenceTetrahedronRule,
    ReferenceTriangleRule,
    TanhSinhRule,
)
from ._sparse_grid import SparseGridRealization
from ._status import IntegrationStatus, status_message
from ._targets import (
    ComponentTarget,
    density,
    DensityTarget,
    discrete,
    DiscreteMeasureTarget,
    expectation,
    IntegrationTarget,
    mapped,
    MappedTarget,
    mean_over,
    normalized_density,
    over,
    ProbabilityTarget,
    weighted,
    WeightedSampleTarget,
)


__all__ = [
    "AdaptivePartition",
    "AdaptiveQuadratureDiagnostics",
    "AdaptiveQuadraturePlan",
    "AntitheticDesign",
    "AntitheticDiagnostics",
    "CellQuadraturePlan",
    "ClenshawCurtisRule",
    "ComponentTarget",
    "ControlVariateEstimator",
    "DensityTarget",
    "DiscreteMeasureTarget",
    "FixedQuadratureDiagnostics",
    "FixedQuadraturePlan",
    "GaussKronrodRule",
    "GaussLegendreRule",
    "IIDDesign",
    "LatinHypercubeDesign",
    "WeightedSampleDiagnostics",
    "ImportanceSamplingPlan",
    "IntegrationBatch",
    "IntegrationEstimate",
    "IntegrationPlan",
    "IntegrationProvenance",
    "IntegrationStatus",
    "IntegrationRealization",
    "IntegrationTarget",
    "IntervalRule",
    "MappedIntegrationBatch",
    "MappedIntegrationDiagnostics",
    "MappedTarget",
    "ReferenceCellData",
    "ReferenceHexahedronRule",
    "ReferenceIntervalRule",
    "ReferenceQuadrilateralRule",
    "MonteCarloDiagnostics",
    "MonteCarloPlan",
    "PointIntegrationBatch",
    "ProbabilityTarget",
    "ProductIntegrationDiagnostics",
    "ProductIntegrationPlan",
    "ProductIntegrationRealization",
    "QuasiMonteCarloPlan",
    "RandomizedQMCDesign",
    "RandomizedQMCDiagnostics",
    "ReferenceRule",
    "ReferenceTetrahedronRule",
    "ReferenceTriangleRule",
    "SampleMeanEstimator",
    "SelfNormalizedEstimator",
    "SeparableIntegrationBatch",
    "SparseGridDiagnostics",
    "SparseGridPlan",
    "SparseGridRealization",
    "StratifiedDesign",
    "StratifiedDiagnostics",
    "StratifiedMonteCarloPlan",
    "TanhSinhRule",
    "WeightedSampleBatch",
    "WeightedSampleTarget",
    "discrete",
    "density",
    "from_samples",
    "expectation",
    "integrate",
    "interval_rule_data",
    "mapped",
    "materialize",
    "mean_over",
    "normalized_density",
    "over",
    "reduce",
    "reference_rule_data",
    "status_message",
    "weighted",
]
