#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Serializable, validated equation representations for physics-aware models."""

from ._compile import (
    compile_pde_expression,
    compile_pde_problem,
    compile_pde_residual_term,
    CompiledPDECondition,
    CompiledPDEEquation,
    CompiledPDEProblem,
    DifferentialBackend,
    IntegralCompiler,
    make_pde_operator,
)
from ._ir import (
    as_expression,
    PDECondition,
    PDEConditionKind,
    PDECoordinate,
    PDECoordinateKind,
    PDEEquation,
    PDEExpression,
    PDEExpressionOp,
    PDEField,
    PDEParameter,
    PDEProblemIR,
    PDERegion,
    PDERegionKind,
    PDERepresentation,
)
from ._randomized_compile import (
    analyze_randomized_compilation,
    compile_pde_randomized_term,
    CompiledRandomizedPDETerm,
    RandomizedCompilationReport,
    RandomizedDifferentialMethod,
    RandomizedDifferentialPlan,
    RandomizedNodeCoupling,
)
from ._semidiscrete import (
    BoundaryLift,
    compile_semidiscrete_dae,
    compile_semidiscrete_pde,
    CompiledSpatialDynamics,
    CompiledSpatialResidual,
    ResolvedSemidiscreteMethod,
    SemidiscreteCompilationMethod,
    SemidiscreteDAEStructuralReport,
    SemidiscreteFieldLayout,
)
from ._serialize import (
    pde_ir_from_dict,
    pde_ir_from_json,
    pde_ir_hash,
    pde_ir_to_dict,
    pde_ir_to_json,
)
from ._tokens import (
    pad_pde_tokens,
    PDE_OPERATOR_VOCABULARY,
    PDE_TOKEN_ATTRIBUTES,
    PDE_TOKEN_KINDS,
    PDETokenBatch,
    stack_pde_tokens,
    tokenize_pde_ir,
)
from ._validate import infer_expression_type, PDEValueType, validate_pde_ir


__all__ = [
    "analyze_randomized_compilation",
    "BoundaryLift",
    "CompiledPDECondition",
    "CompiledPDEEquation",
    "CompiledPDEProblem",
    "CompiledSpatialDynamics",
    "CompiledSpatialResidual",
    "CompiledRandomizedPDETerm",
    "DifferentialBackend",
    "ResolvedSemidiscreteMethod",
    "SemidiscreteCompilationMethod",
    "SemidiscreteDAEStructuralReport",
    "SemidiscreteFieldLayout",
    "IntegralCompiler",
    "PDECondition",
    "PDEConditionKind",
    "PDECoordinate",
    "PDECoordinateKind",
    "PDEEquation",
    "PDEExpression",
    "PDEExpressionOp",
    "PDEField",
    "PDEParameter",
    "PDEProblemIR",
    "PDERegion",
    "PDERegionKind",
    "PDERepresentation",
    "PDEValueType",
    "PDE_OPERATOR_VOCABULARY",
    "PDE_TOKEN_ATTRIBUTES",
    "PDE_TOKEN_KINDS",
    "PDETokenBatch",
    "as_expression",
    "compile_pde_expression",
    "compile_pde_residual_term",
    "compile_pde_randomized_term",
    "compile_pde_problem",
    "compile_semidiscrete_dae",
    "compile_semidiscrete_pde",
    "infer_expression_type",
    "make_pde_operator",
    "pad_pde_tokens",
    "pde_ir_from_dict",
    "pde_ir_from_json",
    "pde_ir_hash",
    "pde_ir_to_dict",
    "pde_ir_to_json",
    "stack_pde_tokens",
    "tokenize_pde_ir",
    "RandomizedCompilationReport",
    "RandomizedDifferentialMethod",
    "RandomizedDifferentialPlan",
    "RandomizedNodeCoupling",
    "validate_pde_ir",
]
