#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Serializable, validated equation representations for physics-aware models."""

from ._compile import (
    compile_pde_expression,
    compile_pde_problem,
    compile_pde_residual_term,
    CompiledPDECondition,
    CompiledPDEEquation,
    CompiledPDEProblem,
    DifferentialBackend,
    IntegralCompiler,
    make_pde_operator,
)
from ._conservation import (
    compile_conservation_problem,
    CompiledConservationProblem,
    ConservationProblemIR,
)
from ._fd_boundary_lowering import (
    BoundaryTarget,
    FDBoundaryBinding,
    FDInterfaceBinding,
    FDInterfaceConditionKind,
    lower_fd_boundaries,
    lower_fd_interfaces,
    prepare_fd_boundary_program,
    prepare_fd_boundary_runtime,
    prepare_fd_interfaces,
    PreparedFDBoundaryPair,
    PreparedFDBoundaryProgram,
    PreparedFDInterface,
)
from ._fd_compile import (
    compile_finite_difference_pde,
    CompiledFiniteDifferenceDynamics,
    FiniteDifferenceCompilationPolicy,
)
from ._ir import (
    as_expression,
    PDECondition,
    PDEConditionKind,
    PDECoordinate,
    PDECoordinateKind,
    PDEEquation,
    PDEExpression,
    PDEExpressionOp,
    PDEField,
    PDEParameter,
    PDEProblemIR,
    PDERegion,
    PDERegionKind,
    PDERepresentation,
)
from ._manufactured import (
    ManufacturedConvergencePlan,
    ManufacturedConvergenceResult,
    ManufacturedNorm,
    ManufacturedPDECase,
    ManufacturedSpatialOperator,
)
from ._randomized_compile import (
    analyze_randomized_compilation,
    compile_pde_randomized_term,
    CompiledRandomizedPDETerm,
    RandomizedCompilationReport,
    RandomizedDifferentialMethod,
    RandomizedDifferentialPlan,
    RandomizedNodeCoupling,
)
from ._semidiscrete import (
    BoundaryLift,
    compile_semidiscrete_dae,
    compile_semidiscrete_pde,
    CompiledDiscreteDynamics,
    CompiledDiscreteResidual,
    DiscreteStateLayout,
    ResolvedSemidiscreteMethod,
    SemidiscreteCompilationMethod,
    SemidiscreteDAEStructuralReport,
)
from ._serialize import (
    pde_ir_from_dict,
    pde_ir_from_json,
    pde_ir_hash,
    pde_ir_to_dict,
    pde_ir_to_json,
)
from ._stencil_compile import (
    compile_stencil_dynamics,
    CompiledStencilDynamics,
    StencilStateLayout,
)
from ._tokens import (
    pad_pde_tokens,
    PDE_OPERATOR_VOCABULARY,
    PDE_TOKEN_ATTRIBUTES,
    PDE_TOKEN_KINDS,
    PDETokenBatch,
    stack_pde_tokens,
    tokenize_pde_ir,
)
from ._validate import infer_expression_type, PDEValueType, validate_pde_ir
from ._variational import (
    compile_variational_problem,
    CompiledVariationalProblem,
    VariationalProblemIR,
)


__all__ = [
    "analyze_randomized_compilation",
    "BoundaryLift",
    "CompiledPDECondition",
    "BoundaryTarget",
    "CompiledPDEEquation",
    "CompiledPDEProblem",
    "CompiledDiscreteDynamics",
    "CompiledDiscreteResidual",
    "CompiledFiniteDifferenceDynamics",
    "CompiledStencilDynamics",
    "CompiledVariationalProblem",
    "CompiledConservationProblem",
    "ConservationProblemIR",
    "CompiledRandomizedPDETerm",
    "DifferentialBackend",
    "ResolvedSemidiscreteMethod",
    "SemidiscreteCompilationMethod",
    "FDBoundaryBinding",
    "FDInterfaceBinding",
    "FDInterfaceConditionKind",
    "SemidiscreteDAEStructuralReport",
    "DiscreteStateLayout",
    "FiniteDifferenceCompilationPolicy",
    "IntegralCompiler",
    "ManufacturedConvergencePlan",
    "ManufacturedConvergenceResult",
    "ManufacturedNorm",
    "ManufacturedPDECase",
    "ManufacturedSpatialOperator",
    "PDECondition",
    "PDEConditionKind",
    "PDECoordinate",
    "PDECoordinateKind",
    "PDEEquation",
    "PDEExpression",
    "PDEExpressionOp",
    "PDEField",
    "PDEParameter",
    "PDEProblemIR",
    "PDERegion",
    "PDERegionKind",
    "PDERepresentation",
    "PDEValueType",
    "PDE_OPERATOR_VOCABULARY",
    "PDE_TOKEN_ATTRIBUTES",
    "PDE_TOKEN_KINDS",
    "PDETokenBatch",
    "as_expression",
    "compile_pde_expression",
    "compile_pde_residual_term",
    "compile_pde_randomized_term",
    "compile_variational_problem",
    "lower_fd_interfaces",
    "prepare_fd_boundary_program",
    "compile_conservation_problem",
    "compile_pde_problem",
    "prepare_fd_interfaces",
    "PreparedFDBoundaryProgram",
    "PreparedFDInterface",
    "compile_semidiscrete_dae",
    "compile_finite_difference_pde",
    "lower_fd_boundaries",
    "prepare_fd_boundary_runtime",
    "PreparedFDBoundaryPair",
    "compile_semidiscrete_pde",
    "compile_stencil_dynamics",
    "infer_expression_type",
    "make_pde_operator",
    "pad_pde_tokens",
    "pde_ir_from_dict",
    "pde_ir_from_json",
    "pde_ir_hash",
    "pde_ir_to_dict",
    "pde_ir_to_json",
    "stack_pde_tokens",
    "tokenize_pde_ir",
    "RandomizedCompilationReport",
    "RandomizedDifferentialMethod",
    "RandomizedDifferentialPlan",
    "RandomizedNodeCoupling",
    "StencilStateLayout",
    "validate_pde_ir",
    "VariationalProblemIR",
]
