#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Nonlinear algebraic systems, fixed points, and implicit root calculus."""

from .._bounds import Bounds
from ._aspin import ASPIN
from ._causal import (
    CausalLevenbergMarquardt,
    CausalLinearizationMode,
    CausalLinearizationPolicy,
    CausalNewton,
    CausalProbeDistribution,
    CausalRecurrenceDiagnostics,
    CausalRecurrenceProblem,
    CausalRecurrenceResult,
    solve_causal_recurrence,
)
from ._composition import CompositeNonlinearUpdate, NonlinearCompositionKind
from ._decomposition import (
    AbstractNonlinearSchwarz,
    NonlinearAdditiveSchwarz,
    NonlinearGaussSeidel,
    NonlinearMultiplicativeSchwarz,
    NonlinearSubdomain,
)
from ._fas import (
    fas_cycle,
    FASCycleKind,
    FASCyclePolicy,
    FASDiagnostics,
    FASHierarchy,
    FASLevel,
    FASNonlinearPreconditioner,
    FASResult,
)
from ._fixed_point import (
    AndersonAcceleration,
    FixedPointIteration,
    PicardIteration,
    PicardUpdate,
)
from ._implicit import implicit_root, implicit_root_result
from ._linearization import (
    JacobianMode,
    JacobianPolicy,
    prepare_jacobian,
    PreparedJacobian,
)
from ._newton import (
    JacobianRefreshPolicy,
    JacobianRefreshStrategy,
    NewtonForcingPolicy,
    NewtonForcingStrategy,
    NewtonKrylov,
    NewtonTrustRegion,
    root,
    RootLineSearch,
    RootTrustRegion,
)
from ._ngmres import NonlinearGMRES
from ._preconditioning import (
    AbstractLeftNonlinearPreconditioner,
    AbstractNonlinearSystemTransformation,
    AbstractRightNonlinearPreconditioner,
    FunctionLeftNonlinearPreconditioner,
    FunctionRightNonlinearPreconditioner,
    left_precondition,
    LeftPreconditionedSystem,
    right_precondition,
    RightPreconditionedSystem,
)
from ._prepared import (
    prepare_nonlinear,
    PreparedNonlinearSolve,
    refresh_nonlinear,
    solve_prepared_nonlinear,
)
from ._richardson import NonlinearRichardson
from ._types import (
    AbstractNonlinearMethod,
    FixedPointProblem,
    nonlinear_status_message,
    NonlinearCapabilities,
    NonlinearDiagnostics,
    NonlinearProvenance,
    NonlinearResult,
    NonlinearStatus,
    NonlinearSystemProblem,
    NonlinearTermination,
    NonlinearTransformationEvidence,
)
from ._updates import (
    AbstractNonlinearUpdate,
    apply_prepared_nonlinear_update,
    FunctionNonlinearUpdate,
    NewtonStepUpdate,
    nonlinear_update_status_message,
    NonlinearUpdateCapabilities,
    NonlinearUpdateControl,
    NonlinearUpdateDiagnostics,
    NonlinearUpdatePlan,
    NonlinearUpdateProvenance,
    NonlinearUpdateResult,
    NonlinearUpdateStatus,
    plan_nonlinear_update,
    prepare_nonlinear_update,
    PreparedNonlinearUpdate,
    refresh_nonlinear_update,
)
from ._vi import (
    complementarity_certificate,
    ComplementarityCertificate,
    ComplementarityFormulation,
    GeneralizedDerivativePolicy,
    prepare_variational_inequality,
    PreparedVariationalInequalitySolve,
    refresh_variational_inequality,
    SemismoothNewton,
    solve_prepared_variational_inequality,
    VariationalInequalityFeasibility,
    VariationalInequalityProblem,
    VariationalInequalityResult,
)


__all__ = [
    "AbstractNonlinearMethod",
    "AbstractLeftNonlinearPreconditioner",
    "AbstractNonlinearSchwarz",
    "AbstractNonlinearSystemTransformation",
    "AbstractNonlinearUpdate",
    "ASPIN",
    "AndersonAcceleration",
    "AbstractRightNonlinearPreconditioner",
    "Bounds",
    "CausalLevenbergMarquardt",
    "CausalLinearizationMode",
    "CausalLinearizationPolicy",
    "CausalNewton",
    "CompositeNonlinearUpdate",
    "CausalProbeDistribution",
    "CausalRecurrenceDiagnostics",
    "CausalRecurrenceProblem",
    "CausalRecurrenceResult",
    "ComplementarityCertificate",
    "ComplementarityFormulation",
    "FASCycleKind",
    "FASCyclePolicy",
    "FASDiagnostics",
    "FASHierarchy",
    "FASLevel",
    "FASNonlinearPreconditioner",
    "FASResult",
    "FixedPointIteration",
    "FixedPointProblem",
    "FunctionLeftNonlinearPreconditioner",
    "FunctionRightNonlinearPreconditioner",
    "FunctionNonlinearUpdate",
    "GeneralizedDerivativePolicy",
    "JacobianRefreshPolicy",
    "JacobianRefreshStrategy",
    "JacobianMode",
    "JacobianPolicy",
    "LeftPreconditionedSystem",
    "NewtonKrylov",
    "NewtonTrustRegion",
    "NewtonForcingPolicy",
    "NewtonForcingStrategy",
    "NewtonStepUpdate",
    "NonlinearCapabilities",
    "NonlinearGMRES",
    "NonlinearDiagnostics",
    "NonlinearProvenance",
    "NonlinearTransformationEvidence",
    "NonlinearAdditiveSchwarz",
    "NonlinearGaussSeidel",
    "NonlinearMultiplicativeSchwarz",
    "NonlinearSubdomain",
    "NonlinearCompositionKind",
    "NonlinearResult",
    "NonlinearRichardson",
    "NonlinearStatus",
    "NonlinearSystemProblem",
    "NonlinearTermination",
    "NonlinearUpdateCapabilities",
    "NonlinearUpdateControl",
    "NonlinearUpdateDiagnostics",
    "NonlinearUpdatePlan",
    "NonlinearUpdateProvenance",
    "NonlinearUpdateResult",
    "NonlinearUpdateStatus",
    "PicardIteration",
    "PicardUpdate",
    "PreparedJacobian",
    "PreparedNonlinearSolve",
    "PreparedNonlinearUpdate",
    "PreparedVariationalInequalitySolve",
    "RightPreconditionedSystem",
    "RootLineSearch",
    "RootTrustRegion",
    "SemismoothNewton",
    "VariationalInequalityProblem",
    "VariationalInequalityResult",
    "VariationalInequalityFeasibility",
    "complementarity_certificate",
    "apply_prepared_nonlinear_update",
    "fas_cycle",
    "implicit_root",
    "implicit_root_result",
    "left_precondition",
    "nonlinear_status_message",
    "nonlinear_update_status_message",
    "prepare_jacobian",
    "plan_nonlinear_update",
    "prepare_nonlinear",
    "prepare_nonlinear_update",
    "prepare_variational_inequality",
    "root",
    "refresh_nonlinear",
    "refresh_nonlinear_update",
    "refresh_variational_inequality",
    "right_precondition",
    "solve_prepared_nonlinear",
    "solve_prepared_variational_inequality",
    "solve_causal_recurrence",
]
