#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Nonlinear algebraic systems, fixed points, and implicit root calculus."""

from .._bounds import Bounds
from ._architecture import (
    AbstractDirectionPolicy,
    AbstractGlobalizationPolicy,
    AbstractNonlinearCertificate,
    AbstractNonlinearModelPolicy,
    DirectionResult,
    DirectionStatus,
    GlobalizationResult,
    GlobalizationStatus,
    NewtonDirectionPolicy,
    NonlinearCertificate,
    NonlinearModel,
    ResidualArmijoPolicy,
    RootLinearModelPolicy,
    RootResidualCertificate,
)
from ._aspin import ASPIN
from ._batched import batched_small_root, BatchedRootResult, SmallRootKernel
from ._causal import (
    CausalLevenbergMarquardt,
    CausalLinearizationMode,
    CausalLinearizationPolicy,
    CausalNewton,
    CausalProbeDistribution,
    CausalRecurrenceDiagnostics,
    CausalRecurrenceProblem,
    CausalRecurrenceResult,
    solve_causal_recurrence,
)
from ._composition import CompositeNonlinearUpdate, NonlinearCompositionKind
from ._decomposition import (
    AbstractNonlinearSchwarz,
    NonlinearAdditiveSchwarz,
    NonlinearGaussSeidel,
    NonlinearMultiplicativeSchwarz,
    NonlinearSubdomain,
)
from ._execution import (
    MixedPrecisionRootExecution,
    NormReduction,
    ShardedNonlinearPolicy,
)
from ._fas import (
    fas_cycle,
    FASCycleKind,
    FASCyclePolicy,
    FASDiagnostics,
    FASHierarchy,
    FASLevel,
    FASNonlinearPreconditioner,
    FASResult,
)
from ._fixed_point import (
    AndersonAcceleration,
    FixedPointIteration,
    PicardIteration,
    PicardUpdate,
    SteffensenIteration,
)
from ._graduation import (
    evaluate_solver_graduation,
    evaluate_solver_regression,
    SolverGraduationEvidence,
    SolverGraduationLevel,
    SolverGraduationPolicy,
    SolverGraduationResult,
    SolverRegressionEvidence,
    SolverRegressionResult,
)
from ._higher_order import VectorHalley
from ._implicit import implicit_root, implicit_root_result
from ._linearization import (
    JacobianMode,
    JacobianPolicy,
    prepare_jacobian,
    PreparedJacobian,
)
from ._newton import (
    JacobianRefreshPolicy,
    JacobianRefreshStrategy,
    NewtonForcingPolicy,
    NewtonForcingStrategy,
    NewtonKrylov,
    NewtonTrustRegion,
    root,
    RootLineSearch,
    RootTrustRegion,
)
from ._ngmres import NonlinearGMRES
from ._polyalgorithm import FastRoot, RobustRoot, RootPolyalgorithm
from ._precision import NonlinearPrecisionPolicy
from ._preconditioning import (
    AbstractLeftNonlinearPreconditioner,
    AbstractNonlinearSystemTransformation,
    AbstractRightNonlinearPreconditioner,
    FunctionLeftNonlinearPreconditioner,
    FunctionRightNonlinearPreconditioner,
    left_precondition,
    LeftPreconditionedSystem,
    right_precondition,
    RightPreconditionedSystem,
)
from ._prepared import (
    prepare_nonlinear,
    PreparedNonlinearSolve,
    refresh_nonlinear,
    solve_prepared_nonlinear,
    step_prepared_nonlinear,
)
from ._pseudo_transient import PseudoTransient
from ._quasi_newton import Broyden, BroydenKind, Chord
from ._richardson import NonlinearRichardson
from ._scalar import (
    AbstractScalarRootMethod,
    Bisection,
    Brent,
    Ridder,
    SafeguardedHalley,
    SafeguardedNewton,
    scalar_root,
    ScalarRootProblem,
    ScalarRootResult,
    TOMS748,
)
from ._scaling import (
    NonlinearScaling,
    NonlinearScalingPolicy,
    prepare_scaled_root,
    PreparedScaledRoot,
    ScalingMode,
)
from ._sensitivity import (
    differentiate_iterations_jvp,
    direct_loss_minimization_gradient,
    minimizer_solution_jvp,
    root_solution_jvp,
    root_solution_second_jvp,
    root_solution_vjp,
    SensitivityEvidence,
    SensitivityMode,
    SensitivityPolicy,
    SensitivityStatus,
    SolutionMapDerivative,
)
from ._spectral import DFSANE
from ._types import (
    AbstractNonlinearMethod,
    FixedPointProblem,
    nonlinear_status_message,
    NonlinearCapabilities,
    NonlinearDiagnostics,
    NonlinearProvenance,
    NonlinearResult,
    NonlinearStatus,
    NonlinearSystemProblem,
    NonlinearTermination,
    NonlinearTransformationEvidence,
)
from ._updates import (
    AbstractNonlinearUpdate,
    apply_prepared_nonlinear_update,
    FunctionNonlinearUpdate,
    NewtonStepUpdate,
    nonlinear_update_status_message,
    NonlinearUpdateCapabilities,
    NonlinearUpdateControl,
    NonlinearUpdateDiagnostics,
    NonlinearUpdatePlan,
    NonlinearUpdateProvenance,
    NonlinearUpdateResult,
    NonlinearUpdateStatus,
    plan_nonlinear_update,
    prepare_nonlinear_update,
    PreparedNonlinearUpdate,
    refresh_nonlinear_update,
)
from ._vi import (
    complementarity_certificate,
    ComplementarityCertificate,
    ComplementarityFormulation,
    GeneralizedDerivativePolicy,
    prepare_variational_inequality,
    PreparedVariationalInequalitySolve,
    refresh_variational_inequality,
    SemismoothNewton,
    solve_prepared_variational_inequality,
    VariationalInequalityFeasibility,
    VariationalInequalityProblem,
    VariationalInequalityResult,
)
from ._work import (
    NonlinearAttemptEvidence,
    NonlinearWork,
    NonlinearWorkBudget,
)


__all__ = [
    "AbstractDirectionPolicy",
    "AbstractGlobalizationPolicy",
    "AbstractScalarRootMethod",
    "BatchedRootResult",
    "AbstractNonlinearCertificate",
    "AbstractNonlinearModelPolicy",
    "AbstractNonlinearMethod",
    "AbstractLeftNonlinearPreconditioner",
    "AbstractNonlinearSchwarz",
    "AbstractNonlinearSystemTransformation",
    "AbstractNonlinearUpdate",
    "ASPIN",
    "AndersonAcceleration",
    "AbstractRightNonlinearPreconditioner",
    "Bounds",
    "CausalLevenbergMarquardt",
    "CausalLinearizationMode",
    "CausalLinearizationPolicy",
    "CausalNewton",
    "CompositeNonlinearUpdate",
    "CausalProbeDistribution",
    "CausalRecurrenceDiagnostics",
    "Bisection",
    "Brent",
    "Broyden",
    "BroydenKind",
    "Chord",
    "CausalRecurrenceProblem",
    "CausalRecurrenceResult",
    "ComplementarityCertificate",
    "ComplementarityFormulation",
    "FASCycleKind",
    "FASCyclePolicy",
    "FASDiagnostics",
    "DFSANE",
    "DirectionResult",
    "DirectionStatus",
    "FASHierarchy",
    "FASLevel",
    "FASNonlinearPreconditioner",
    "FastRoot",
    "FASResult",
    "FixedPointIteration",
    "FixedPointProblem",
    "FunctionLeftNonlinearPreconditioner",
    "FunctionRightNonlinearPreconditioner",
    "FunctionNonlinearUpdate",
    "GeneralizedDerivativePolicy",
    "JacobianRefreshPolicy",
    "JacobianRefreshStrategy",
    "JacobianMode",
    "JacobianPolicy",
    "LeftPreconditionedSystem",
    "GlobalizationResult",
    "GlobalizationStatus",
    "NewtonKrylov",
    "NewtonTrustRegion",
    "NewtonForcingPolicy",
    "NewtonForcingStrategy",
    "NewtonStepUpdate",
    "NonlinearAttemptEvidence",
    "NonlinearCapabilities",
    "NonlinearGMRES",
    "NonlinearDiagnostics",
    "NonlinearProvenance",
    "NonlinearTransformationEvidence",
    "NonlinearAdditiveSchwarz",
    "NonlinearGaussSeidel",
    "NonlinearMultiplicativeSchwarz",
    "NonlinearSubdomain",
    "NonlinearCompositionKind",
    "NewtonDirectionPolicy",
    "NonlinearCertificate",
    "NonlinearModel",
    "NonlinearPrecisionPolicy",
    "NonlinearScaling",
    "NonlinearScalingPolicy",
    "NonlinearResult",
    "NonlinearRichardson",
    "NonlinearStatus",
    "NonlinearSystemProblem",
    "NonlinearTermination",
    "NonlinearWork",
    "MixedPrecisionRootExecution",
    "NormReduction",
    "NonlinearWorkBudget",
    "NonlinearUpdateCapabilities",
    "NonlinearUpdateControl",
    "NonlinearUpdateDiagnostics",
    "NonlinearUpdatePlan",
    "NonlinearUpdateProvenance",
    "NonlinearUpdateResult",
    "NonlinearUpdateStatus",
    "PicardIteration",
    "PseudoTransient",
    "PicardUpdate",
    "PreparedJacobian",
    "PreparedNonlinearSolve",
    "PreparedNonlinearUpdate",
    "Ridder",
    "SmallRootKernel",
    "SafeguardedHalley",
    "SafeguardedNewton",
    "PreparedVariationalInequalitySolve",
    "PreparedScaledRoot",
    "RightPreconditionedSystem",
    "RootLineSearch",
    "RootTrustRegion",
    "SemismoothNewton",
    "SensitivityEvidence",
    "SensitivityMode",
    "SensitivityPolicy",
    "SensitivityStatus",
    "SolutionMapDerivative",
    "ScalarRootProblem",
    "ScalarRootResult",
    "RobustRoot",
    "ScalingMode",
    "SolverGraduationEvidence",
    "SolverGraduationLevel",
    "SolverGraduationPolicy",
    "SolverGraduationResult",
    "SolverRegressionEvidence",
    "SolverRegressionResult",
    "VariationalInequalityProblem",
    "ShardedNonlinearPolicy",
    "VectorHalley",
    "VariationalInequalityResult",
    "VariationalInequalityFeasibility",
    "SteffensenIteration",
    "complementarity_certificate",
    "apply_prepared_nonlinear_update",
    "fas_cycle",
    "TOMS748",
    "RootPolyalgorithm",
    "implicit_root",
    "implicit_root_result",
    "batched_small_root",
    "left_precondition",
    "nonlinear_status_message",
    "nonlinear_update_status_message",
    "ResidualArmijoPolicy",
    "RootLinearModelPolicy",
    "RootResidualCertificate",
    "prepare_jacobian",
    "differentiate_iterations_jvp",
    "direct_loss_minimization_gradient",
    "minimizer_solution_jvp",
    "root_solution_second_jvp",
    "root_solution_jvp",
    "root_solution_vjp",
    "plan_nonlinear_update",
    "prepare_nonlinear",
    "evaluate_solver_graduation",
    "evaluate_solver_regression",
    "prepare_nonlinear_update",
    "prepare_scaled_root",
    "prepare_variational_inequality",
    "root",
    "refresh_nonlinear",
    "refresh_nonlinear_update",
    "refresh_variational_inequality",
    "right_precondition",
    "step_prepared_nonlinear",
    "solve_prepared_nonlinear",
    "solve_prepared_variational_inequality",
    "solve_causal_recurrence",
    "scalar_root",
]
