#
# Copyright © 2026 PHYDRA, Inc. All rights reserved.
#

"""Immutable JAX-native preprocessing recipes and fitted transforms."""

from ._categorical import (
    CategoricalDiagnostics,
    CategoricalSchema,
    FittedOneHotEncoder,
    FittedOrdinalEncoder,
    FittedSimpleImputer,
    FittedTargetEncoder,
    ImputationStrategy,
    OneHotEncoder,
    OrdinalEncoder,
    SimpleImputer,
    TargetEncoder,
    UnknownPolicy,
)
from ._common import PreprocessingDiagnostics
from ._features import (
    FeatureHasher,
    FittedFeatureHasher,
    FittedFourierFeatures,
    FittedGaussianRandomProjection,
    FittedPolynomialFeatures,
    FittedPowerTransformer,
    FittedQuantileTransformer,
    FittedRandomFourierFeatures,
    FittedSparseRandomProjection,
    FittedSplineTransformer,
    FourierFeatures,
    GaussianRandomProjection,
    PolynomialFeatures,
    PowerTransformer,
    QuantileTransformer,
    RandomFourierFeatures,
    SparseRandomProjection,
    SplineTransformer,
)
from ._scalers import (
    FittedMaxAbsScaler,
    FittedMinMaxScaler,
    FittedNormScaler,
    FittedRobustScaler,
    FittedStandardScaler,
    MaxAbsScaler,
    MinMaxScaler,
    NormScaler,
    RobustScaler,
    StandardScaler,
)


__all__ = [
    "CategoricalDiagnostics",
    "CategoricalSchema",
    "FeatureHasher",
    "FittedFeatureHasher",
    "FittedFourierFeatures",
    "FittedGaussianRandomProjection",
    "FittedMaxAbsScaler",
    "FittedMinMaxScaler",
    "FittedNormScaler",
    "FittedOneHotEncoder",
    "FittedOrdinalEncoder",
    "FittedPolynomialFeatures",
    "FittedPowerTransformer",
    "FittedQuantileTransformer",
    "FittedRandomFourierFeatures",
    "FittedRobustScaler",
    "FittedSimpleImputer",
    "FittedSparseRandomProjection",
    "FittedSplineTransformer",
    "FittedStandardScaler",
    "FittedTargetEncoder",
    "FourierFeatures",
    "GaussianRandomProjection",
    "ImputationStrategy",
    "MaxAbsScaler",
    "MinMaxScaler",
    "NormScaler",
    "OneHotEncoder",
    "OrdinalEncoder",
    "PolynomialFeatures",
    "PowerTransformer",
    "PreprocessingDiagnostics",
    "QuantileTransformer",
    "RandomFourierFeatures",
    "RobustScaler",
    "SimpleImputer",
    "SparseRandomProjection",
    "SplineTransformer",
    "StandardScaler",
    "TargetEncoder",
    "UnknownPolicy",
]
